import { CATALOG_COUNTS, QUESTION_CATALOG, SPARE_QUESTIONS } from "./seed-data";

/**
 * Catalogue self-check.
 *
 * Building the catalogue executes every problem's reference solution against
 * its own inputs, so simply importing it proves the answer key is consistent.
 * This script adds the structural assertions on top: exact counts, unique
 * slugs, a public sample per problem, and enough hidden coverage to mark with.
 *
 *   npm run db:verify
 */

const problems = [...QUESTION_CATALOG, ...SPARE_QUESTIONS];
const failures: string[] = [];

function check(condition: boolean, message: string) {
  if (!condition) failures.push(message);
}

check(CATALOG_COUNTS.EASY === 100, `Easy holds ${CATALOG_COUNTS.EASY} problems, expected 100.`);
check(CATALOG_COUNTS.MEDIUM === 100, `Medium holds ${CATALOG_COUNTS.MEDIUM} problems, expected 100.`);
check(CATALOG_COUNTS.HARD === 100, `Hard holds ${CATALOG_COUNTS.HARD} problems, expected 100.`);

const seen = new Set<string>();
for (const problem of problems) {
  if (seen.has(problem.slug)) failures.push(`Duplicate slug: ${problem.slug}`);
  seen.add(problem.slug);

  const samples = problem.testCases.filter((t) => t.kind === "SAMPLE");
  const hidden = problem.testCases.filter((t) => t.kind !== "SAMPLE");

  check(samples.length >= 1, `${problem.slug}: no public sample case.`);
  check(hidden.length >= 3, `${problem.slug}: only ${hidden.length} hidden/edge cases.`);
  check(problem.hints.length === 3, `${problem.slug}: expected 3 hints, found ${problem.hints.length}.`);
  check(problem.examples.length >= 1, `${problem.slug}: no worked examples.`);
  check(problem.topics.length >= 1, `${problem.slug}: no topic tags.`);
  check(problem.approach.trim().length > 0, `${problem.slug}: empty editorial approach.`);
  check(problem.timeComplexity.trim().length > 0, `${problem.slug}: missing time complexity.`);

  for (const [index, testCase] of problem.testCases.entries()) {
    check(
      testCase.expectedOutput !== undefined && testCase.expectedOutput !== null,
      `${problem.slug}: test case ${index + 1} has no expected output.`,
    );
  }
}

const totalCases = problems.reduce((sum, p) => sum + p.testCases.length, 0);
const withCode = problems.filter((p) => Object.keys(p.solutions).length > 0).length;
const topics = new Map<string, number>();
for (const problem of QUESTION_CATALOG) {
  for (const topic of problem.topics) topics.set(topic, (topics.get(topic) ?? 0) + 1);
}

console.log("\nDSA Forge catalogue\n");
console.log(`  Easy            ${CATALOG_COUNTS.EASY}`);
console.log(`  Medium          ${CATALOG_COUNTS.MEDIUM}`);
console.log(`  Hard            ${CATALOG_COUNTS.HARD}`);
console.log(`  Published       ${QUESTION_CATALOG.length}`);
console.log(`  Spare           ${SPARE_QUESTIONS.length}`);
console.log(`  Test cases      ${totalCases} (all generated by each problem's reference solution)`);
console.log(`  Topics covered  ${topics.size}`);
console.log(`  Reference code  ${withCode} problems carry runnable solutions in at least one language`);

console.log("\n  Topic distribution");
for (const [topic, count] of [...topics.entries()].sort((a, b) => b[1] - a[1])) {
  console.log(`    ${topic.padEnd(18)} ${count}`);
}

if (failures.length > 0) {
  console.error(`\n${failures.length} problem(s) found:\n`);
  for (const failure of failures.slice(0, 40)) console.error(`  - ${failure}`);
  process.exit(1);
}

console.log("\nCatalogue is consistent.\n");
