import { build, join, linesOut, reader, yesNo, type QuestionSpec } from "./catalog";

const A = (input: string) => {
  const r = reader(input);
  return r.ints(r.int());
};

const specs: QuestionSpec[] = [
  {
    slug: "prefix-sum-queries",
    title: "Range Sum Queries",
    difficulty: "EASY",
    topics: ["arrays"],
    d: "Answer q queries, each asking for the sum of a[l..r] inclusive with 0-indexed bounds.",
    in: "First line: n and q.\nSecond line: n integers.\nNext q lines: l and r.",
    out: "One sum per query, one per line.",
    c: "1 <= n, q <= 100000\n0 <= l <= r < n\n-10^9 <= a[i] <= 10^9",
    hints: ["Summing per query is O(nq) and too slow.", "Precompute something that answers any range in O(1).", "prefix[i] = a[0] + ... + a[i-1], then the answer is prefix[r+1] - prefix[l]."],
    ap: "Build a prefix-sum array once, then answer each query with a single subtraction.",
    it: "A range sum is the difference of two prefixes, so one linear preprocessing pass makes every query constant time.",
    st: ["Build prefix of length n+1 with prefix[0] = 0.", "Set prefix[i+1] = prefix[i] + a[i].", "For each query print prefix[r+1] - prefix[l]."],
    tc: "O(n + q)", sc: "O(n)",
    solve: (input) => { const r = reader(input); const n = r.int(), q = r.int(); const a = r.ints(n); const p = new Array(n + 1).fill(0); for (let i = 0; i < n; i += 1) p[i + 1] = p[i] + a[i]; const out: number[] = []; for (let i = 0; i < q; i += 1) { const l = r.int(), rr = r.int(); out.push(p[rr + 1] - p[l]); } return linesOut(out); },
    samples: ["5 2\n1 2 3 4 5\n0 2\n1 3", "3 1\n-1 -2 -3\n0 2"],
    why: ["1+2+3 = 6 and 2+3+4 = 9.", "The whole array sums to -6."],
    hidden: ["1 1\n5\n0 0", "4 2\n1 1 1 1\n0 3\n2 2", "6 3\n1 -1 1 -1 1 -1\n0 5\n0 0\n1 4", "2 1\n1000000000 1000000000\n0 1"],
    edge: ["1 2\n0\n0 0\n0 0"],
  },
  {
    slug: "sliding-window-max-sum-k",
    title: "Maximum Sum of a Window of Size K",
    difficulty: "EASY",
    topics: ["arrays"],
    d: "Find the largest sum of any k consecutive elements.",
    in: "First line: n and k.\nSecond line: n integers.",
    out: "The maximum window sum.",
    c: "1 <= k <= n <= 100000\n-10^9 <= a[i] <= 10^9",
    hints: ["Recomputing each window from scratch costs O(nk).", "Consecutive windows overlap in k-1 elements.", "Slide: add the entering element, subtract the leaving one."],
    ap: "Compute the first window's sum, then slide it across the array in O(1) per step.",
    it: "Adjacent windows differ by exactly two elements, so the sum can be updated instead of recomputed.",
    st: ["Sum the first k elements.", "For each later index, add a[i] and subtract a[i-k].", "Track the maximum."],
    tc: "O(n)", sc: "O(1)",
    solve: (input) => { const r = reader(input); const n = r.int(), k = r.int(); const a = r.ints(n); let sum = 0; for (let i = 0; i < k; i += 1) sum += a[i]; let best = sum; for (let i = k; i < n; i += 1) { sum += a[i] - a[i - k]; best = Math.max(best, sum); } return String(best); },
    samples: ["6 3\n2 1 5 1 3 2", "4 2\n-1 -2 -3 -4"],
    why: ["The window [5,1,3] sums to 9.", "The best pair is the first two."],
    hidden: ["1 1\n7", "5 5\n1 2 3 4 5", "6 2\n1 1 1 1 1 9", "5 3\n0 0 0 0 0"],
    edge: ["2 1\n-1000000000 1000000000"],
  },
  {
    slug: "two-pointer-pair-sum-sorted",
    title: "Pair with a Given Sum in a Sorted Array",
    difficulty: "EASY",
    topics: ["arrays", "searching"],
    d: "Given a sorted array, decide whether two distinct positions hold values summing to a target.",
    in: "First line: n and target.\nSecond line: n sorted integers.",
    out: "YES if such a pair exists, otherwise NO.",
    c: "2 <= n <= 100000\n-10^9 <= values, target <= 10^9",
    hints: ["A hash set works but ignores the sortedness.", "Start with the smallest and largest values.", "If their sum is too big, shrink from the right; if too small, grow from the left."],
    ap: "Two pointers at both ends, moving inwards based on how the current sum compares with the target.",
    it: "Sortedness makes the sum monotone in each pointer, so each move safely discards a whole set of pairs.",
    st: ["Set lo = 0 and hi = n-1.", "While lo < hi compare a[lo] + a[hi] with the target.", "Move lo up when too small, hi down when too large.", "Report YES on an exact match."],
    tc: "O(n)", sc: "O(1)",
    solve: (input) => { const r = reader(input); const n = r.int(), target = r.int(); const a = r.ints(n); let lo = 0, hi = n - 1; while (lo < hi) { const sum = a[lo] + a[hi]; if (sum === target) return "YES"; if (sum < target) lo += 1; else hi -= 1; } return "NO"; },
    samples: ["5 9\n1 2 4 5 7", "4 100\n1 2 3 4"],
    why: ["2 + 7 = 9.", "No pair reaches 100."],
    hidden: ["2 3\n1 2", "6 0\n-3 -1 0 1 2 3", "5 14\n7 7 7 7 7", "3 2\n1 1 1"],
    edge: ["2 0\n-1000000000 1000000000"],
  },
  {
    slug: "remove-element-value",
    title: "Remove All Occurrences of a Value",
    difficulty: "EASY",
    topics: ["arrays"],
    d: "Remove every occurrence of a value from an array, keeping the order of the remaining elements.",
    in: "First line: n and target.\nSecond line: n integers.",
    out: "The remaining values in order, or EMPTY.",
    c: "1 <= n <= 100000\n-10^9 <= values <= 10^9",
    hints: ["You do not need a second array.", "Use a write pointer for the kept elements.", "Copy forward only the values you keep."],
    ap: "Compaction with a write pointer: copy each surviving element to the next free slot.",
    it: "Stable filtering is a single left-to-right compaction.",
    st: ["Set write = 0.", "For each value not equal to the target, store it at index write and advance.", "Print the first `write` elements."],
    tc: "O(n)", sc: "O(1)",
    solve: (input) => { const r = reader(input); const n = r.int(), target = r.int(); const out = r.ints(n).filter((v) => v !== target); return out.length ? join(out) : "EMPTY"; },
    samples: ["6 3\n3 2 2 3 4 3", "3 1\n1 1 1"],
    why: ["Only the non-3 values remain.", "Every element is removed."],
    hidden: ["1 5\n5", "4 0\n1 2 3 4", "5 -1\n-1 0 -1 1 -1", "2 2\n2 3"],
    edge: ["1 1\n2"],
  },
  {
    slug: "check-sorted-array",
    title: "Check if an Array is Sorted",
    difficulty: "EASY",
    topics: ["arrays"],
    d: "Decide whether an array is sorted in non-decreasing order.",
    in: "First line: n.\nSecond line: n integers.",
    out: "YES if sorted, otherwise NO.",
    c: "1 <= n <= 100000\n-10^9 <= a[i] <= 10^9",
    hints: ["Sortedness is a property of neighbouring pairs.", "One violation is enough to answer NO.", "Compare each element with the next and stop early."],
    ap: "Scan adjacent pairs; the array is sorted exactly when no pair is out of order.",
    it: "The order relation is transitive, so checking neighbours checks everything.",
    st: ["Loop i from 0 to n-2.", "If a[i] > a[i+1] print NO and stop.", "Otherwise print YES."],
    tc: "O(n)", sc: "O(1)",
    solve: (i) => { const a = A(i); for (let k = 1; k < a.length; k += 1) if (a[k] < a[k - 1]) return "NO"; return "YES"; },
    samples: ["5\n1 2 2 3 4", "4\n1 3 2 4"],
    why: ["Every neighbouring pair is in order.", "3 is followed by 2."],
    hidden: ["1\n5", "3\n3 2 1", "4\n1 1 1 1", "5\n-5 -4 -3 -2 -1"],
    edge: ["2\n2 1"],
  },
  {
    slug: "min-max-array",
    title: "Minimum and Maximum",
    difficulty: "EASY",
    topics: ["arrays"],
    d: "Print the smallest and largest values of an array.",
    in: "First line: n.\nSecond line: n integers.",
    out: "The minimum and the maximum, space separated.",
    c: "1 <= n <= 100000\n-10^9 <= a[i] <= 10^9",
    hints: ["One pass can maintain both.", "Initialise both to the first element.", "Update each with a comparison per element."],
    ap: "Single pass maintaining two running extremes.",
    it: "Both extremes are folds over the same sequence, so they share one traversal.",
    st: ["Set lo = hi = a[0].", "For each later value update lo and hi.", "Print lo then hi."],
    tc: "O(n)", sc: "O(1)",
    solve: (i) => { const a = A(i); return `${Math.min(...a)} ${Math.max(...a)}`; },
    samples: ["5\n3 1 4 1 5", "1\n7"],
    why: ["1 is smallest and 5 is largest.", "One element is both."],
    hidden: ["2\n-1 1", "4\n5 5 5 5", "6\n-9 -1 -5 -3 -7 -2", "3\n0 0 1"],
    edge: ["2\n-1000000000 1000000000"],
  },
  {
    slug: "average-of-array",
    title: "Average of an Array",
    difficulty: "EASY",
    topics: ["arrays", "math"],
    d: "Print the mean of the array rounded to exactly two decimal places.",
    in: "First line: n.\nSecond line: n integers.",
    out: "The average with two decimal places.",
    c: "1 <= n <= 100000\n-10^9 <= a[i] <= 10^9",
    hints: ["Accumulate in 64-bit before dividing.", "Divide only once, at the end.", "Format the result to exactly two decimals."],
    ap: "Sum with a 64-bit accumulator, divide once, and format to two decimals.",
    it: "Dividing as you go accumulates floating-point error; a single division at the end does not.",
    st: ["Sum every element.", "Divide by n in floating point.", "Print with two decimal places."],
    tc: "O(n)", sc: "O(1)",
    solve: (i) => { const a = A(i); return (a.reduce((s, v) => s + v, 0) / a.length).toFixed(2); },
    samples: ["4\n1 2 3 4", "3\n1 1 2"],
    why: ["10 / 4 = 2.50.", "4 / 3 = 1.33 to two places."],
    hidden: ["1\n7", "5\n-1 -2 -3 -4 -5", "2\n1 2", "4\n0 0 0 1"],
    edge: ["2\n-1000000000 1000000000"],
  },
  {
    slug: "frequency-count-array",
    title: "Frequency of Each Element",
    difficulty: "EASY",
    topics: ["hashing"],
    d: "Print each distinct value and how many times it occurs, sorted by value.",
    in: "First line: n.\nSecond line: n integers.",
    out: "One line per distinct value: the value and its count.",
    c: "1 <= n <= 100000\n-10^9 <= a[i] <= 10^9",
    hints: ["A hash map counts in one pass.", "Sorting the keys gives the required output order.", "Sorting the array first also groups equal values together."],
    ap: "Count into a hash map, then emit the entries in ascending key order.",
    it: "Counting and ordering are separate concerns; the map handles the first, the sort the second.",
    st: ["Count occurrences into a map.", "Collect and sort the distinct keys.", "Print each key with its count."],
    tc: "O(n log n)", sc: "O(n)",
    solve: (i) => { const a = A(i); const m = new Map<number, number>(); for (const v of a) m.set(v, (m.get(v) ?? 0) + 1); return linesOut([...m.entries()].sort((x, y) => x[0] - y[0]).map(([v, c]) => `${v} ${c}`)); },
    samples: ["6\n1 2 2 3 3 3", "3\n5 5 5"],
    why: ["Counts in ascending value order.", "One distinct value occurring three times."],
    hidden: ["1\n0", "4\n-1 -1 1 1", "5\n4 3 2 1 0", "4\n7 7 8 8"],
    edge: ["2\n-1000000000 1000000000"],
  },
  {
    slug: "union-two-arrays",
    title: "Union of Two Arrays",
    difficulty: "EASY",
    topics: ["hashing"],
    d: "Print all distinct values that appear in either array, in increasing order.",
    in: "First line: n and m.\nSecond line: n integers.\nThird line: m integers.",
    out: "The distinct values in increasing order.",
    c: "1 <= n, m <= 100000\n-10^9 <= values <= 10^9",
    hints: ["Duplicates must collapse.", "A set removes duplicates for free.", "Insert both arrays, then sort the result."],
    ap: "Insert every value from both arrays into a set and print the sorted contents.",
    it: "A set is exactly the union operation with deduplication built in.",
    st: ["Insert all values from the first array into a set.", "Insert all values from the second.", "Sort and print the set."],
    tc: "O((n+m) log (n+m))", sc: "O(n+m)",
    solve: (input) => { const r = reader(input); const n = r.int(), m = r.int(); const s = new Set([...r.ints(n), ...r.ints(m)]); return join([...s].sort((x, y) => x - y)); },
    samples: ["3 3\n1 2 3\n2 3 4", "2 2\n1 1\n1 1"],
    why: ["The union is 1, 2, 3, 4.", "Every value collapses to a single 1."],
    hidden: ["1 1\n5\n5", "4 2\n-1 -2 -3 -4\n0 1", "3 3\n1 2 3\n4 5 6", "2 3\n9 8\n7 8 9"],
    edge: ["1 1\n1000000000\n-1000000000"],
  },
  {
    slug: "string-compression-basic",
    title: "Run-Length Encoding",
    difficulty: "EASY",
    topics: ["strings"],
    d: "Compress a string by replacing each run of identical characters with the character followed by the run length. Runs of length one keep the count 1.",
    in: "A single line containing a lowercase string.",
    out: "The run-length encoding.",
    c: "1 <= |s| <= 100000",
    hints: ["Runs are maximal blocks of equal characters.", "Compare each character with the previous one.", "Emit the character and the length when the run ends."],
    ap: "Scan once, extending the current run while characters match and emitting character plus count when it breaks.",
    it: "Run-length encoding only needs the current run, so one counter and one pass are enough.",
    st: ["Start a run at the first character.", "Extend it while the next character matches.", "When it breaks, emit the character and the length.", "Emit the final run."],
    tc: "O(n)", sc: "O(n)",
    solve: (input) => { const s = input.trim(); let out = ""; let i = 0; while (i < s.length) { let j = i; while (j < s.length && s[j] === s[i]) j += 1; out += s[i] + (j - i); i = j; } return out; },
    samples: ["aaabbc", "abcd"],
    why: ["Three a's, two b's and one c.", "Every run has length one."],
    hidden: ["a", "aaaaaaaaaa", "aabbaa", "zzzyyx"],
    edge: ["ab"],
  },
  {
    slug: "remove-spaces",
    title: "Remove All Spaces",
    difficulty: "EASY",
    topics: ["strings"],
    d: "Given a line of text, print it with every space removed.",
    in: "A single line that may contain spaces.",
    out: "The line with spaces removed.",
    c: "1 <= |s| <= 100000",
    hints: ["This is a filter, not a rearrangement.", "Copy only the characters you keep.", "A write pointer avoids allocating a second buffer."],
    ap: "Copy every non-space character forward with a write pointer.",
    it: "Filtering is a compaction, so it costs one pass and no extra memory.",
    st: ["Set write = 0.", "For each character that is not a space, store it at index write and advance.", "Print the first `write` characters."],
    tc: "O(n)", sc: "O(1)",
    solve: (input) => input.replace(/\r?\n$/, "").split(" ").join(""),
    samples: ["forge your dsa skills", "no_spaces_here"],
    why: ["All four spaces are removed.", "There was nothing to remove."],
    hidden: ["a b", "   ", "a  b  c", " leading and trailing "],
    edge: [" "],
  },
  {
    slug: "capitalize-words",
    title: "Capitalise Each Word",
    difficulty: "EASY",
    topics: ["strings"],
    d: "Given a list of lowercase words, print them space separated with the first letter of each capitalised.",
    in: "First line: n.\nSecond line: n space-separated lowercase words.",
    out: "The capitalised words, space separated.",
    c: "1 <= n <= 100000\nEach word is at most 50 characters.",
    hints: ["Only the first character of each word changes.", "Uppercasing is a fixed offset in ASCII.", "Rebuild each word from its transformed first character plus the rest."],
    ap: "For each word, uppercase the first character and append the remainder unchanged.",
    it: "Word boundaries are already given, so no parsing is needed.",
    st: ["Read the words.", "For each, uppercase the leading character.", "Join with single spaces."],
    tc: "O(total length)", sc: "O(total length)",
    solve: (input) => { const r = reader(input); const n = r.int(); return r.strs(n).map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(" "); },
    samples: ["3\nforge your skills", "1\ndsa"],
    why: ["Each word gains a capital.", "A single word is capitalised."],
    hidden: ["2\na b", "4\none two three four", "1\nz", "3\nabc def ghi"],
    edge: ["2\nx y"],
  },
  {
    slug: "count-substring-occurrences",
    title: "Count Substring Occurrences",
    difficulty: "EASY",
    topics: ["strings"],
    d: "Count how many times a pattern occurs in a text, counting overlapping occurrences.",
    in: "Line 1: the text.\nLine 2: the pattern.",
    out: "The number of occurrences.",
    c: "1 <= |text| <= 100000\n1 <= |pattern| <= |text|",
    hints: ["Overlapping matches must all be counted.", "Try every starting position.", "Compare the pattern against the window starting at each index."],
    ap: "Slide the pattern across every starting position and compare. Naive matching is fine at these limits; KMP would make it strictly linear.",
    it: "Counting overlaps means you advance the start by one after a match, not by the pattern length.",
    st: ["Loop start from 0 to |text| - |pattern|.", "Compare the substring of that length against the pattern.", "Increment the count on a match."],
    tc: "O(|text| * |pattern|)", sc: "O(1)",
    solve: (input) => { const [text = "", pattern = ""] = input.trim().split("\n").map((l) => l.trim()); let count = 0; for (let i = 0; i + pattern.length <= text.length; i += 1) if (text.startsWith(pattern, i)) count += 1; return String(count); },
    samples: ["aaaa\naa", "abcabc\nabc"],
    why: ["Three overlapping matches at positions 0, 1 and 2.", "Two non-overlapping matches."],
    hidden: ["abc\nd", "aaaaa\na", "abababa\naba", "xyz\nxyz"],
    edge: ["a\na"],
  },
  {
    slug: "longest-common-prefix",
    title: "Longest Common Prefix",
    difficulty: "EASY",
    topics: ["strings"],
    d: "Find the longest prefix shared by every string in a list. Print EMPTY when there is none.",
    in: "First line: n.\nNext n lines: one string each.",
    out: "The longest common prefix, or EMPTY.",
    c: "1 <= n <= 1000\n1 <= |s| <= 200",
    hints: ["The answer can never be longer than the shortest string.", "Compare character by character across all strings.", "Stop at the first position where any string disagrees."],
    ap: "Walk positions left to right, checking that every string agrees at that index, and stop at the first disagreement.",
    it: "A common prefix is closed under truncation, so the first disagreement fixes the answer.",
    st: ["Take the first string as a candidate.", "For each position, check every other string.", "Stop at the first mismatch or when a string ends.", "Print the accumulated prefix."],
    tc: "O(n * |shortest|)", sc: "O(1)",
    solve: (input) => { const parts = input.trim().split("\n").map((l) => l.trim()); const n = Number(parts[0]); const words = parts.slice(1, 1 + n); let prefix = ""; const first = words[0] ?? ""; for (let i = 0; i < first.length; i += 1) { const ch = first[i]; if (words.every((w) => w[i] === ch)) prefix += ch; else break; } return prefix || "EMPTY"; },
    samples: ["3\nflower\nflow\nflight", "2\ndog\ncar"],
    why: ["All three start with 'fl'.", "The words share no leading character."],
    hidden: ["1\nsolo", "3\nabc\nabc\nabc", "2\na\nab", "4\ninterview\ninternal\ninternet\ninterval"],
    edge: ["2\na\nb"],
    companies: ["amazon", "adobe"],
  },
  {
    slug: "string-rotation-check",
    title: "String Rotation",
    difficulty: "EASY",
    topics: ["strings"],
    d: "Decide whether one string is a rotation of another.",
    in: "Line 1: string s.\nLine 2: string t.",
    out: "YES if t is a rotation of s, otherwise NO.",
    c: "1 <= |s|, |t| <= 100000",
    hints: ["Different lengths can never be rotations.", "Every rotation of s appears inside s+s.", "So check whether t is a substring of s concatenated with itself."],
    ap: "If the lengths match, test whether t occurs as a substring of s+s.",
    it: "Concatenating a string with itself lays out all of its rotations as contiguous windows.",
    st: ["If the lengths differ print NO.", "Form the doubled string s+s.", "Print YES when t occurs inside it."],
    tc: "O(n) with a linear substring search", sc: "O(n)",
    solve: (input) => { const [s = "", t = ""] = input.trim().split("\n").map((l) => l.trim()); return yesNo(s.length === t.length && (s + s).includes(t)); },
    samples: ["abcde\ncdeab", "abcde\nabced"],
    why: ["Rotating left by two produces the second string.", "The characters are reordered, not rotated."],
    hidden: ["a\na", "ab\nba", "abc\nabc", "aab\naba"],
    edge: ["a\nb"],
  },
  {
    slug: "nth-root-binary-search",
    title: "Integer Square Root",
    difficulty: "EASY",
    topics: ["searching", "math"],
    d: "Print the largest integer whose square does not exceed n.",
    in: "A single integer n.",
    out: "The integer square root of n.",
    c: "0 <= n <= 10^18",
    hints: ["Linear search up to 10^9 is too slow.", "The predicate 'x*x <= n' is monotone in x.", "Binary search on the answer, and watch for overflow when squaring."],
    ap: "Binary search on the answer over [0, 10^9], keeping the largest x with x*x <= n. Compare using division to avoid overflow.",
    it: "Binary search applies to any monotone predicate, not only to sorted arrays.",
    st: ["Set lo = 0 and hi = 10^9.", "While lo <= hi, test mid*mid <= n.", "Move the bound that keeps the predicate satisfiable.", "Print the best satisfying value."],
    tc: "O(log n)", sc: "O(1)",
    solve: (input) => { const n = BigInt(input.trim()); let lo = 0n, hi = 1000000000n, best = 0n; while (lo <= hi) { const mid = (lo + hi) / 2n; if (mid * mid <= n) { best = mid; lo = mid + 1n; } else hi = mid - 1n; } return best.toString(); },
    samples: ["17", "16"],
    why: ["4*4 = 16 <= 17 but 5*5 = 25 > 17.", "16 is a perfect square."],
    hidden: ["0", "1", "999999999999999999", "1000000000000000000"],
    edge: ["2", "3"],
  },
  {
    slug: "first-last-position-sorted",
    title: "First and Last Position in a Sorted Array",
    difficulty: "EASY",
    topics: ["searching"],
    d: "In a sorted array, find the first and last positions of a target value. Print -1 -1 when it is absent.",
    in: "First line: n and target.\nSecond line: n sorted integers.",
    out: "Two indices, or -1 -1.",
    c: "1 <= n <= 200000\n-10^9 <= values <= 10^9",
    hints: ["Scanning outwards from one match is O(n) in the worst case.", "Run two different binary searches.", "One finds the leftmost match, the other the rightmost."],
    ap: "Two binary searches: a lower bound for the first index, an upper bound for the last.",
    it: "Rather than stopping at any match, keep searching the side that could still hold an earlier or later occurrence.",
    st: ["Binary search for the leftmost index with a[i] >= target.", "Binary search for the rightmost index with a[i] <= target.", "Verify the value actually matches.", "Print both indices, or -1 -1."],
    tc: "O(log n)", sc: "O(1)",
    solve: (input) => { const r = reader(input); const n = r.int(), target = r.int(); const a = r.ints(n); const first = a.indexOf(target); if (first === -1) return "-1 -1"; return `${first} ${a.lastIndexOf(target)}`; },
    samples: ["6 8\n5 7 7 8 8 10", "5 6\n5 7 7 8 8"],
    why: ["8 spans indices 3 and 4.", "6 never occurs."],
    hidden: ["1 1\n1", "5 7\n7 7 7 7 7", "6 5\n5 6 7 8 9 10", "4 10\n1 2 3 4"],
    edge: ["2 1\n1 1"],
    companies: ["amazon", "microsoft"],
  },
  {
    slug: "square-root-perfect",
    title: "Perfect Square Check",
    difficulty: "EASY",
    topics: ["math", "searching"],
    d: "Decide whether n is a perfect square.",
    in: "A single integer n.",
    out: "YES if n is a perfect square, otherwise NO.",
    c: "0 <= n <= 10^18",
    hints: ["Floating-point square roots lose precision at 10^18.", "Compute the integer square root instead.", "Then check whether squaring it returns n exactly."],
    ap: "Binary search for the integer square root, then verify that its square equals n exactly.",
    it: "Integer arithmetic avoids the rounding error that makes a floating-point check unreliable at these magnitudes.",
    st: ["Binary search for the largest x with x*x <= n.", "Compare x*x with n.", "Print YES when they are equal."],
    tc: "O(log n)", sc: "O(1)",
    solve: (input) => { const n = BigInt(input.trim()); let lo = 0n, hi = 1000000000n, best = 0n; while (lo <= hi) { const mid = (lo + hi) / 2n; if (mid * mid <= n) { best = mid; lo = mid + 1n; } else hi = mid - 1n; } return yesNo(best * best === n); },
    samples: ["49", "50"],
    why: ["7 squared is 49.", "50 lies between 49 and 64."],
    hidden: ["0", "1", "1000000000000000000", "999999999999999999"],
    edge: ["2"],
  },
  {
    slug: "queue-using-stacks",
    title: "Queue Using Two Stacks",
    difficulty: "EASY",
    topics: ["queue", "stack"],
    d: "Implement a queue using only stack operations. Operations are ENQUEUE x, DEQUEUE and FRONT; the last two print EMPTY on an empty queue.",
    in: "First line: q.\nNext q lines: one operation each.",
    out: "One line per DEQUEUE or FRONT.",
    c: "1 <= q <= 100000",
    hints: ["Reversing a stack into another stack restores FIFO order.", "Use an input stack and an output stack.", "Only refill the output stack when it is empty."],
    ap: "Two stacks: pushes go to the input stack; reads pop from the output stack, refilling it from the input stack only when it empties. Each element moves at most twice, so the amortised cost is O(1).",
    it: "Reversing once and reading many times is what makes the amortised cost constant rather than linear per read.",
    st: ["ENQUEUE pushes onto the input stack.", "For a read, if the output stack is empty pour the input stack into it.", "Then pop or peek the output stack."],
    tc: "Amortised O(1) per operation", sc: "O(q)",
    solve: (input) => { const parts = input.trim().split("\n"); const q = Number(parts[0]); const data: string[] = []; let head = 0; const out: string[] = []; for (let i = 1; i <= q; i += 1) { const [op, value] = (parts[i] ?? "").trim().split(/\s+/); if (op === "ENQUEUE") data.push(value); else if (op === "DEQUEUE") out.push(head < data.length ? data[head++] : "EMPTY"); else if (op === "FRONT") out.push(head < data.length ? data[head] : "EMPTY"); } return linesOut(out); },
    samples: ["5\nENQUEUE 1\nENQUEUE 2\nFRONT\nDEQUEUE\nFRONT", "2\nDEQUEUE\nFRONT"],
    why: ["1 entered first so it leaves first.", "Both reads hit an empty queue."],
    hidden: ["4\nENQUEUE 5\nDEQUEUE\nDEQUEUE\nFRONT", "3\nENQUEUE 1\nENQUEUE 2\nDEQUEUE", "6\nENQUEUE 1\nENQUEUE 2\nDEQUEUE\nENQUEUE 3\nDEQUEUE\nDEQUEUE", "1\nDEQUEUE"],
    edge: ["2\nENQUEUE 9\nFRONT"],
    companies: ["microsoft", "amazon"],
  },
  {
    slug: "stack-min-tracking",
    title: "Stack with Minimum",
    difficulty: "EASY",
    topics: ["stack"],
    d: "Support PUSH x, POP and MIN on a stack, where MIN reports the smallest value currently stored. MIN and POP print EMPTY when the stack is empty.",
    in: "First line: q.\nNext q lines: one operation each.",
    out: "One line per POP or MIN.",
    c: "1 <= q <= 100000\n-10^9 <= x <= 10^9",
    hints: ["Scanning the stack for the minimum is O(n) per query.", "Store the minimum alongside each element.", "A second stack of running minima also works."],
    ap: "Keep a parallel stack of prefix minima so MIN is O(1) and pops stay consistent.",
    it: "Because a stack only changes at one end, the minimum of every prefix can be cached as you push.",
    st: ["On PUSH, store min(value, current minimum) alongside the value.", "On POP, remove both entries.", "MIN reads the top of the minimum stack."],
    tc: "O(1) per operation", sc: "O(q)",
    solve: (input) => { const parts = input.trim().split("\n"); const q = Number(parts[0]); const stack: number[] = []; const mins: number[] = []; const out: string[] = []; for (let i = 1; i <= q; i += 1) { const [op, value] = (parts[i] ?? "").trim().split(/\s+/); if (op === "PUSH") { const v = Number(value); stack.push(v); mins.push(mins.length ? Math.min(v, mins[mins.length - 1]) : v); } else if (op === "POP") { if (!stack.length) out.push("EMPTY"); else { out.push(String(stack.pop())); mins.pop(); } } else if (op === "MIN") out.push(mins.length ? String(mins[mins.length - 1]) : "EMPTY"); } return linesOut(out); },
    samples: ["5\nPUSH 3\nPUSH 1\nMIN\nPOP\nMIN", "2\nMIN\nPOP"],
    why: ["1 is the minimum until it is popped, then 3 is.", "Both operations hit an empty stack."],
    hidden: ["4\nPUSH -1\nPUSH 5\nMIN\nPOP", "3\nPUSH 7\nMIN\nPOP", "6\nPUSH 2\nPUSH 2\nMIN\nPOP\nMIN\nPOP", "1\nMIN"],
    edge: ["2\nPOP\nMIN"],
    companies: ["amazon", "google"],
  },
  {
    slug: "next-greater-element-basic",
    title: "Next Greater Element",
    difficulty: "EASY",
    topics: ["stack", "arrays"],
    d: "For each element, find the first strictly greater element to its right, or -1 if there is none.",
    in: "First line: n.\nSecond line: n integers.",
    out: "n values, space separated.",
    c: "1 <= n <= 100000\n-10^9 <= a[i] <= 10^9",
    hints: ["The quadratic solution rescans the suffix for every element.", "Process the array from the right.", "A stack of candidates lets you discard values that can never be an answer."],
    ap: "Scan right to left with a monotonic decreasing stack, popping everything not greater than the current element; the remaining top is the answer.",
    it: "Once a smaller value is covered by a larger one to its right, it can never be anyone's next greater element, so it can be discarded permanently.",
    st: ["Iterate i from n-1 down to 0.", "Pop stack entries that are <= a[i].", "The answer is the top, or -1 if the stack is empty.", "Push a[i]."],
    tc: "O(n)", sc: "O(n)",
    solve: (i) => { const a = A(i); const out = new Array(a.length).fill(-1); const st: number[] = []; for (let k = a.length - 1; k >= 0; k -= 1) { while (st.length && st[st.length - 1] <= a[k]) st.pop(); out[k] = st.length ? st[st.length - 1] : -1; st.push(a[k]); } return join(out); },
    samples: ["4\n4 5 2 25", "3\n3 2 1"],
    why: ["5 follows 4; 25 follows both 5 and 2.", "The array is decreasing, so nothing has a greater element to the right."],
    hidden: ["1\n7", "5\n1 2 3 4 5", "4\n2 2 2 2", "6\n13 7 6 12 9 10"],
    edge: ["2\n1 1"],
    companies: ["amazon", "adobe", "microsoft"],
  },
  {
    slug: "balanced-brackets-depth",
    title: "Maximum Nesting Depth",
    difficulty: "EASY",
    topics: ["stack", "strings"],
    d: "Given a balanced string of round brackets, print the maximum nesting depth.",
    in: "A single line of round brackets.",
    out: "The maximum nesting depth.",
    c: "1 <= |s| <= 100000\nThe string is balanced.",
    hints: ["You do not need an actual stack, only its height.", "An opening bracket increases depth by one.", "Track the running depth and its maximum."],
    ap: "Keep a running depth counter, incrementing on '(' and decrementing on ')', and record the largest value it reaches.",
    it: "The stack height is the only thing depth depends on, so a counter replaces the stack entirely.",
    st: ["Set depth = 0 and best = 0.", "On '(' increment depth and update best.", "On ')' decrement depth.", "Print best."],
    tc: "O(n)", sc: "O(1)",
    solve: (input) => { let depth = 0, best = 0; for (const ch of input.trim()) { if (ch === "(") { depth += 1; best = Math.max(best, depth); } else if (ch === ")") depth -= 1; } return String(best); },
    samples: ["((()))", "()()"],
    why: ["Three brackets are open at once.", "Never more than one is open."],
    hidden: ["()", "(()(()))", "(((((())))))", "(())()"],
    edge: ["()"],
  },
  {
    slug: "level-order-traversal",
    title: "Level Order Traversal",
    difficulty: "EASY",
    topics: ["trees", "queue"],
    d: "Print a binary tree level by level, top to bottom and left to right within each level. The tree is given in level order with -1 for absent children.",
    in: "First line: n.\nSecond line: n level-order values, -1 for absent.",
    out: "One line per level with that level's values, or EMPTY.",
    c: "1 <= n <= 100000",
    hints: ["Depth-first traversal will not produce level order.", "Process nodes in the order you discover them.", "A queue gives exactly that order."],
    ap: "Breadth-first search with a queue, processing one full level per iteration by recording the queue size before draining it.",
    it: "A queue preserves discovery order, which for a tree is precisely level order.",
    st: ["Push the root into a queue.", "While the queue is non-empty, record its size.", "Pop that many nodes, emitting their values and pushing their children.", "Emit one line per level."],
    tc: "O(n)", sc: "O(n)",
    solve: (input) => { const r = reader(input); const n = r.int(); const a = r.ints(n); const out: string[] = []; let level = [0]; while (level.length) { const values = level.filter((i) => i < n && a[i] !== -1); if (!values.length) break; out.push(join(values.map((i) => a[i]))); const next: number[] = []; for (const i of values) { next.push(2 * i + 1, 2 * i + 2); } level = next; } return out.length ? linesOut(out) : "EMPTY"; },
    samples: ["7\n1 2 3 4 5 6 7", "3\n1 -1 2"],
    why: ["Three levels of the complete tree.", "The root has only a right child."],
    hidden: ["1\n5", "3\n1 2 -1", "7\n1 2 3 -1 -1 6 7", "5\n1 2 3 4 5"],
    edge: ["1\n-1"],
    companies: ["amazon", "microsoft", "meta"],
  },
  {
    slug: "tree-node-count",
    title: "Count Nodes in a Binary Tree",
    difficulty: "EASY",
    topics: ["trees", "recursion"],
    d: "Count the nodes of a binary tree given in level order with -1 for absent children.",
    in: "First line: n.\nSecond line: n level-order values, -1 for absent.",
    out: "The number of nodes.",
    c: "1 <= n <= 100000",
    hints: ["Every node contributes exactly one.", "count(null) = 0.", "count(node) = 1 + count(left) + count(right)."],
    ap: "Recursive post-order sum over both subtrees.",
    it: "Counting is the simplest example of a divide-and-conquer tree fold.",
    st: ["Return 0 for an absent node.", "Otherwise return 1 plus both subtree counts."],
    tc: "O(n)", sc: "O(h)",
    solve: (input) => { const r = reader(input); const n = r.int(); const a = r.ints(n); const go = (i: number): number => (i >= n || a[i] === -1 ? 0 : 1 + go(2 * i + 1) + go(2 * i + 2)); return String(go(0)); },
    samples: ["7\n1 2 3 4 5 6 7", "1\n-1"],
    why: ["The complete tree has seven nodes.", "An empty tree has none."],
    hidden: ["1\n1", "3\n1 2 -1", "5\n1 2 3 4 -1", "7\n1 2 3 -1 -1 -1 -1"],
    edge: ["3\n1 -1 -1"],
  },
  {
    slug: "bst-min-max",
    title: "Minimum and Maximum in a BST",
    difficulty: "EASY",
    topics: ["bst"],
    d: "Print the smallest and largest values in a binary search tree given in level order with -1 for absent children.",
    in: "First line: n.\nSecond line: n level-order values, -1 for absent.",
    out: "The minimum and the maximum, space separated.",
    c: "1 <= n <= 100000\nAll present values are non-negative and distinct.",
    hints: ["You do not have to inspect every node.", "The BST invariant places extremes at the ends.", "Walk left for the minimum and right for the maximum."],
    ap: "Walk to the leftmost node for the minimum and the rightmost for the maximum.",
    it: "In a BST every left step decreases and every right step increases, so the extremes sit at the ends of those chains.",
    st: ["From the root, follow left children until none remain — that is the minimum.", "From the root, follow right children until none remain — that is the maximum."],
    tc: "O(h)", sc: "O(1)",
    solve: (input) => { const r = reader(input); const n = r.int(); const a = r.ints(n); let i = 0; while (2 * i + 1 < n && a[2 * i + 1] !== -1) i = 2 * i + 1; const lo = a[i]; let j = 0; while (2 * j + 2 < n && a[2 * j + 2] !== -1) j = 2 * j + 2; return `${lo} ${a[j]}`; },
    samples: ["7\n8 3 10 1 6 -1 14", "1\n5"],
    why: ["The leftmost node is 1 and the rightmost is 14.", "A single node is both extremes."],
    hidden: ["3\n2 1 3", "7\n50 30 70 20 40 60 80", "3\n2 1 -1", "3\n2 -1 3"],
    edge: ["1\n0"],
  },
  {
    slug: "graph-bfs-order",
    title: "BFS of a Graph",
    difficulty: "EASY",
    topics: ["graphs", "queue"],
    d: "Print the breadth-first traversal of an undirected graph starting at vertex 0. Visit neighbours in increasing vertex order.",
    in: "First line: n and m.\nNext m lines: an edge u v.",
    out: "The BFS order, space separated.",
    c: "1 <= n <= 100000\n0 <= m <= 200000",
    hints: ["BFS explores by distance from the source.", "A queue produces that order naturally.", "Mark a vertex visited when you enqueue it, not when you dequeue it."],
    ap: "Standard BFS from vertex 0 using an adjacency list with sorted neighbours and a visited array.",
    it: "Marking on enqueue rather than dequeue is what prevents a vertex from entering the queue twice.",
    st: ["Build sorted adjacency lists.", "Enqueue vertex 0 and mark it visited.", "Dequeue, emit, and enqueue every unvisited neighbour.", "Repeat until the queue empties."],
    tc: "O(n + m)", sc: "O(n + m)",
    solve: (input) => { const r = reader(input); const n = r.int(), m = r.int(); const adj: number[][] = Array.from({ length: n }, () => []); for (let i = 0; i < m; i += 1) { const u = r.int(), v = r.int(); adj[u].push(v); adj[v].push(u); } adj.forEach((list) => list.sort((x, y) => x - y)); const seen = new Uint8Array(n); const out: number[] = []; const queue = [0]; seen[0] = 1; for (let head = 0; head < queue.length; head += 1) { const u = queue[head]; out.push(u); for (const v of adj[u]) if (!seen[v]) { seen[v] = 1; queue.push(v); } } return join(out); },
    samples: ["5 4\n0 1\n0 2\n1 3\n2 4", "3 0"],
    why: ["Level 0 is {0}, level 1 is {1,2}, level 2 is {3,4}.", "With no edges only vertex 0 is reachable."],
    hidden: ["1 0", "4 3\n0 1\n1 2\n2 3", "4 2\n0 1\n2 3", "6 5\n0 1\n0 2\n0 3\n1 4\n2 5"],
    edge: ["2 1\n0 1"],
    companies: ["amazon", "microsoft", "google"],
  },
  {
    slug: "graph-dfs-order",
    title: "DFS of a Graph",
    difficulty: "EASY",
    topics: ["graphs", "recursion"],
    d: "Print the depth-first traversal of an undirected graph starting at vertex 0, visiting neighbours in increasing vertex order.",
    in: "First line: n and m.\nNext m lines: an edge u v.",
    out: "The DFS order, space separated.",
    c: "1 <= n <= 100000\n0 <= m <= 200000",
    hints: ["DFS goes as deep as possible before backtracking.", "Recursion or an explicit stack both work.", "Mark a vertex visited the moment you enter it."],
    ap: "Recursive depth-first search over sorted adjacency lists, with an explicit stack if recursion depth is a concern.",
    it: "DFS follows one branch to exhaustion, which is what makes it natural for connectivity and cycle questions.",
    st: ["Build sorted adjacency lists.", "Visit vertex 0, marking it.", "For each unvisited neighbour, recurse.", "Emit vertices in entry order."],
    tc: "O(n + m)", sc: "O(n + m)",
    solve: (input) => { const r = reader(input); const n = r.int(), m = r.int(); const adj: number[][] = Array.from({ length: n }, () => []); for (let i = 0; i < m; i += 1) { const u = r.int(), v = r.int(); adj[u].push(v); adj[v].push(u); } adj.forEach((list) => list.sort((x, y) => x - y)); const seen = new Uint8Array(n); const out: number[] = []; const stack = [0]; seen[0] = 1; const visit = (u: number) => { out.push(u); for (const v of adj[u]) if (!seen[v]) { seen[v] = 1; visit(v); } }; stack.pop(); visit(0); return join(out); },
    samples: ["5 4\n0 1\n0 2\n1 3\n2 4", "3 0"],
    why: ["The walk descends 0-1-3 before backtracking to 2-4.", "Only vertex 0 is reachable."],
    hidden: ["1 0", "4 3\n0 1\n1 2\n2 3", "4 2\n0 1\n2 3", "6 5\n0 1\n0 2\n1 3\n1 4\n2 5"],
    edge: ["2 1\n0 1"],
  },
  {
    slug: "count-connected-components",
    title: "Count Connected Components",
    difficulty: "EASY",
    topics: ["graphs"],
    d: "Count the connected components of an undirected graph.",
    in: "First line: n and m.\nNext m lines: an edge u v.",
    out: "The number of connected components.",
    c: "1 <= n <= 100000\n0 <= m <= 200000",
    hints: ["Each traversal from an unvisited vertex covers one whole component.", "Loop over all vertices, not just vertex 0.", "Count how many traversals you start."],
    ap: "Run BFS or DFS from every vertex that is still unvisited, counting how many traversals begin. A disjoint-set structure works equally well.",
    it: "A traversal reaches exactly one component, so the number of traversals equals the number of components.",
    st: ["Mark all vertices unvisited.", "For each vertex, if unvisited start a traversal and increment the count.", "The traversal marks the whole component.", "Print the count."],
    tc: "O(n + m)", sc: "O(n + m)",
    solve: (input) => { const r = reader(input); const n = r.int(), m = r.int(); const adj: number[][] = Array.from({ length: n }, () => []); for (let i = 0; i < m; i += 1) { const u = r.int(), v = r.int(); adj[u].push(v); adj[v].push(u); } const seen = new Uint8Array(n); let count = 0; for (let s = 0; s < n; s += 1) { if (seen[s]) continue; count += 1; const queue = [s]; seen[s] = 1; for (let head = 0; head < queue.length; head += 1) for (const v of adj[queue[head]]) if (!seen[v]) { seen[v] = 1; queue.push(v); } } return String(count); },
    samples: ["5 3\n0 1\n1 2\n3 4", "4 0"],
    why: ["{0,1,2} and {3,4} are two components.", "Every isolated vertex is its own component."],
    hidden: ["1 0", "3 3\n0 1\n1 2\n0 2", "6 3\n0 1\n2 3\n4 5", "2 1\n0 1"],
    edge: ["1 0"],
    companies: ["amazon", "google"],
  },
  {
    slug: "min-steps-grid-bfs",
    title: "Shortest Path in a Grid",
    difficulty: "EASY",
    topics: ["graphs", "matrix"],
    d: "A grid contains 0 for open cells and 1 for walls. Find the fewest moves from the top-left to the bottom-right cell, moving only up, down, left or right through open cells. Print -1 when no path exists.",
    in: "First line: n and m.\nNext n lines: m values, each 0 or 1.",
    out: "The minimum number of moves, or -1.",
    c: "1 <= n, m <= 500",
    hints: ["Every move costs the same, so all edges have weight one.", "BFS finds shortest paths on unweighted graphs.", "Record the distance when you first enqueue a cell."],
    ap: "Breadth-first search over the grid, treating each open cell as a vertex with up to four unit-weight edges.",
    it: "With uniform edge weights, the first time BFS reaches a cell is necessarily along a shortest path.",
    st: ["Reject immediately if the start or the target is a wall.", "Enqueue the start with distance 0.", "Expand to open, unvisited neighbours with distance+1.", "Return the distance when the target is dequeued, else -1."],
    tc: "O(nm)", sc: "O(nm)",
    solve: (input) => { const r = reader(input); const n = r.int(), m = r.int(); const g: number[][] = []; for (let i = 0; i < n; i += 1) g.push(r.ints(m)); if (g[0][0] === 1 || g[n - 1][m - 1] === 1) return "-1"; const dist = Array.from({ length: n }, () => new Array(m).fill(-1)); dist[0][0] = 0; const queue: Array<[number, number]> = [[0, 0]]; const dirs = [[1, 0], [-1, 0], [0, 1], [0, -1]]; for (let head = 0; head < queue.length; head += 1) { const [x, y] = queue[head]; if (x === n - 1 && y === m - 1) return String(dist[x][y]); for (const [dx, dy] of dirs) { const nx = x + dx, ny = y + dy; if (nx >= 0 && ny >= 0 && nx < n && ny < m && g[nx][ny] === 0 && dist[nx][ny] === -1) { dist[nx][ny] = dist[x][y] + 1; queue.push([nx, ny]); } } } return "-1"; },
    samples: ["3 3\n0 0 0\n1 1 0\n0 0 0", "2 2\n0 1\n1 0"],
    why: ["The path goes right, right, down, down.", "Both routes are blocked."],
    hidden: ["1 1\n0", "2 2\n0 0\n0 0", "3 3\n0 0 0\n0 0 0\n0 0 0", "3 3\n0 1 0\n0 1 0\n0 0 0"],
    edge: ["1 1\n1"],
  },
  {
    slug: "min-jumps-simple",
    title: "Minimum Jumps to the End",
    difficulty: "EASY",
    topics: ["greedy", "arrays"],
    d: "From index i you may jump forward up to a[i] positions. Find the fewest jumps needed to reach the last index, or -1 if it is unreachable.",
    in: "First line: n.\nSecond line: n non-negative integers.",
    out: "The minimum number of jumps, or -1.",
    c: "1 <= n <= 100000\n0 <= a[i] <= 1000",
    hints: ["Think of the positions reachable with exactly k jumps as a level.", "That level is a contiguous range.", "Track the end of the current level and the farthest reachable position."],
    ap: "Greedy level expansion: sweep left to right tracking the farthest reachable index and the end of the current jump level, incrementing the jump count when the level boundary is crossed.",
    it: "This is BFS on an implicit graph where each level is a contiguous interval, so the queue collapses into two indices.",
    st: ["Set jumps = 0, currentEnd = 0, farthest = 0.", "For each index below n-1, update farthest.", "When the index reaches currentEnd, increment jumps and set currentEnd = farthest.", "Return -1 if currentEnd stalls before the end."],
    tc: "O(n)", sc: "O(1)",
    solve: (i) => { const a = A(i); const n = a.length; if (n === 1) return "0"; let jumps = 0, end = 0, far = 0; for (let k = 0; k < n - 1; k += 1) { far = Math.max(far, k + a[k]); if (k === end) { jumps += 1; end = far; if (end >= n - 1) return String(jumps); if (end <= k) return "-1"; } } return end >= n - 1 ? String(jumps) : "-1"; },
    samples: ["5\n2 3 1 1 4", "4\n1 0 0 1"],
    why: ["Jump to index 1, then straight to the end.", "Index 1 has jump length zero, so the end is unreachable."],
    hidden: ["1\n0", "3\n1 1 1", "5\n1 1 1 1 1", "6\n5 1 1 1 1 1"],
    edge: ["2\n0 0"],
    companies: ["amazon", "adobe"],
  },
];

export const EASY_C = specs.map(build);
