import { build, join, linesOut, reader, yesNo, type QuestionSpec } from "./catalog";

/** Reads "n" then n integers. */
const A = (input: string) => {
  const r = reader(input);
  return r.ints(r.int());
};

const specs: QuestionSpec[] = [
  {
    slug: "remove-duplicates-sorted",
    title: "Remove Duplicates from a Sorted Array",
    difficulty: "EASY",
    topics: ["arrays"],
    d: "Given a sorted array, print each distinct value once, preserving order.",
    in: "First line: n.\nSecond line: n sorted integers.",
    out: "The distinct values in order, space separated.",
    c: "1 <= n <= 100000\n-10^9 <= a[i] <= 10^9\nThe array is sorted.",
    hints: ["Equal values are adjacent because the array is sorted.", "Compare each element with the one before it.", "Keep a write pointer that only advances on a new value."],
    ap: "Two pointers: a read pointer scans, a write pointer appends only when the value differs from the last kept one.",
    it: "Sortedness collapses duplicate detection to a comparison with the immediate predecessor.",
    st: ["Keep the first element.", "For each later element, compare with the last kept value.", "If different, keep it."],
    tc: "O(n)", sc: "O(1)",
    solve: (i) => join(A(i).filter((v, idx, arr) => idx === 0 || v !== arr[idx - 1])),
    samples: ["7\n1 1 2 2 3 4 4", "4\n5 5 5 5"],
    why: ["Each run collapses to one copy.", "All values are equal, so one remains."],
    hidden: ["1\n9", "5\n1 2 3 4 5", "6\n-3 -3 -1 0 0 2", "3\n7 7 8"],
    edge: ["2\n-1000000000 -1000000000"],
    sol: { PYTHON: `import sys\nd=sys.stdin.read().split()\nn=int(d[0]);a=list(map(int,d[1:1+n]))\nout=[a[0]]\nfor v in a[1:]:\n    if v!=out[-1]: out.append(v)\nprint(*out)\n` },
  },
  {
    slug: "move-zeroes",
    title: "Move Zeroes to the End",
    difficulty: "EASY",
    topics: ["arrays"],
    d: "Move every zero to the end of the array while keeping the relative order of the non-zero values.",
    in: "First line: n.\nSecond line: n integers.",
    out: "The rearranged array, space separated.",
    c: "1 <= n <= 100000\n-10^9 <= a[i] <= 10^9",
    hints: ["Order of the non-zero values must not change.", "Think of one pointer marking where the next non-zero belongs.", "Compact the non-zeroes forward, then fill the tail with zeroes."],
    ap: "A write pointer collects non-zero values in order; the remaining suffix is filled with zeroes.",
    it: "Stable partitioning around 'is zero' is a single compaction pass.",
    st: ["Set write = 0.", "For each value, if non-zero place it at index write and increment write.", "Fill indices write..n-1 with 0."],
    tc: "O(n)", sc: "O(1)",
    solve: (i) => { const a = A(i); const nz = a.filter((v) => v !== 0); return join([...nz, ...Array(a.length - nz.length).fill(0)]); },
    samples: ["6\n0 1 0 3 12 0", "4\n1 2 3 4"],
    why: ["1, 3 and 12 keep their order; three zeroes move to the back.", "There are no zeroes to move."],
    hidden: ["1\n0", "5\n0 0 0 0 1", "5\n-1 0 -2 0 3", "3\n0 0 0"],
    edge: ["2\n0 1"],
    companies: ["meta", "amazon"],
  },
  {
    slug: "missing-number",
    title: "Find the Missing Number",
    difficulty: "EASY",
    topics: ["arrays", "math"],
    d: "An array holds n distinct integers drawn from 0..n, so exactly one value in that range is absent. Find it.",
    in: "First line: n.\nSecond line: n distinct integers from 0..n.",
    out: "The missing value.",
    c: "1 <= n <= 100000\nAll values are distinct and lie in 0..n.",
    hints: ["Sorting works but costs more than necessary.", "The full range has a known total.", "Subtract the array sum from n(n+1)/2, or XOR everything together."],
    ap: "Compute the expected sum 0+1+...+n and subtract the observed sum. XOR of index and value also works and avoids overflow entirely.",
    it: "The missing element is exactly the difference between the complete range and what is present.",
    st: ["Compute expected = n(n+1)/2.", "Compute the sum of the array.", "Print expected minus the sum."],
    tc: "O(n)", sc: "O(1)",
    solve: (i) => { const a = A(i); const n = a.length; return String((n * (n + 1)) / 2 - a.reduce((s, v) => s + v, 0)); },
    samples: ["3\n0 1 3", "1\n0"],
    why: ["0..3 sums to 6; the array sums to 4, so 2 is missing.", "0 is present, so 1 is missing."],
    hidden: ["4\n1 2 3 4", "5\n0 1 2 3 4", "6\n6 0 1 2 3 4", "2\n2 0"],
    edge: ["1\n1"],
    companies: ["amazon", "microsoft"],
    sol: { PYTHON: `import sys\nd=sys.stdin.read().split()\nn=int(d[0]);a=list(map(int,d[1:1+n]))\nprint(n*(n+1)//2-sum(a))\n` },
  },
  {
    slug: "single-number-xor",
    title: "Single Number",
    difficulty: "EASY",
    topics: ["bit-manipulation", "arrays"],
    d: "Every value in the array appears exactly twice except one, which appears once. Find that value using constant extra space.",
    in: "First line: n.\nSecond line: n integers.",
    out: "The value that appears once.",
    c: "1 <= n <= 100000, n is odd\n-10^9 <= a[i] <= 10^9",
    hints: ["A hash map solves it but uses O(n) memory.", "Look for an operation where x combined with x cancels out.", "XOR is its own inverse: a ^ a = 0 and a ^ 0 = a."],
    ap: "XOR every element together. Paired values annihilate, leaving only the unique one.",
    it: "XOR is associative and commutative, so the pairing order does not matter and duplicates vanish.",
    st: ["Set answer = 0.", "XOR each element into answer.", "Print answer."],
    tc: "O(n)", sc: "O(1)",
    solve: (i) => String(A(i).reduce((x, v) => x ^ v, 0)),
    samples: ["5\n4 1 2 1 2", "1\n7"],
    why: ["1 and 2 cancel in pairs, leaving 4.", "A single element is its own answer."],
    hidden: ["3\n2 2 9", "7\n1 1 2 2 3 3 8", "5\n-1 -1 -2 -2 5", "3\n0 0 6"],
    edge: ["3\n5 6 5"],
    companies: ["amazon", "adobe", "google"],
    sol: { PYTHON: `import sys\nfrom functools import reduce\nfrom operator import xor\nd=sys.stdin.read().split()\nn=int(d[0])\nprint(reduce(xor,map(int,d[1:1+n])))\n` },
  },
  {
    slug: "max-consecutive-ones",
    title: "Max Consecutive Ones",
    difficulty: "EASY",
    topics: ["arrays"],
    d: "Given a binary array, find the length of the longest run of consecutive 1s.",
    in: "First line: n.\nSecond line: n values, each 0 or 1.",
    out: "The length of the longest run of 1s.",
    c: "1 <= n <= 100000\na[i] is 0 or 1",
    hints: ["A run ends the moment you see a zero.", "Track the current run length and the best seen.", "Reset the current run to zero on every 0."],
    ap: "One pass keeping a current-run counter and a best-so-far maximum.",
    it: "Runs are disjoint, so a single reset-on-zero counter finds the longest one.",
    st: ["Set run = 0 and best = 0.", "For each value: if 1, run++ and best = max(best, run); else run = 0.", "Print best."],
    tc: "O(n)", sc: "O(1)",
    solve: (i) => { let run = 0, best = 0; for (const v of A(i)) { run = v === 1 ? run + 1 : 0; best = Math.max(best, run); } return String(best); },
    samples: ["6\n1 1 0 1 1 1", "3\n0 0 0"],
    why: ["The longest run is the trailing block of three 1s.", "There are no 1s at all."],
    hidden: ["1\n1", "5\n1 1 1 1 1", "7\n1 0 1 0 1 0 1", "4\n0 1 1 0"],
    edge: ["1\n0"],
  },
  {
    slug: "merge-sorted-arrays",
    title: "Merge Two Sorted Arrays",
    difficulty: "EASY",
    topics: ["arrays", "sorting"],
    d: "Merge two sorted arrays into one sorted sequence.",
    in: "First line: n and m.\nSecond line: n sorted integers.\nThird line: m sorted integers.",
    out: "All n+m values in non-decreasing order.",
    c: "1 <= n, m <= 100000\n-10^9 <= values <= 10^9",
    hints: ["Concatenating and sorting works but wastes the existing order.", "The next smallest value is always at the front of one of the two arrays.", "Advance two pointers, always taking the smaller head."],
    ap: "Standard two-pointer merge: compare the heads of both arrays and emit the smaller one until both are exhausted.",
    it: "This is the merge step of merge sort; sortedness means the global minimum of what remains is always one of two candidates.",
    st: ["Set i = 0, j = 0.", "While both arrays have elements, append the smaller head and advance that pointer.", "Append whatever remains."],
    tc: "O(n + m)", sc: "O(n + m)",
    solve: (input) => { const r = reader(input); const n = r.int(), m = r.int(); const a = r.ints(n), b = r.ints(m); const out: number[] = []; let i = 0, j = 0; while (i < n && j < m) out.push(a[i] <= b[j] ? a[i++] : b[j++]); while (i < n) out.push(a[i++]); while (j < m) out.push(b[j++]); return join(out); },
    samples: ["3 3\n1 3 5\n2 4 6", "2 3\n1 2\n3 4 5"],
    why: ["The heads interleave one at a time.", "The first array is entirely below the second."],
    hidden: ["1 1\n5\n1", "4 2\n1 1 1 1\n0 2", "3 3\n-5 -3 -1\n-4 -2 0", "2 2\n1000000000 1000000000\n-1000000000 0"],
    edge: ["1 1\n1\n1"],
    companies: ["microsoft", "amazon"],
  },
  {
    slug: "intersection-two-arrays",
    title: "Intersection of Two Arrays",
    difficulty: "EASY",
    topics: ["hashing", "arrays"],
    d: "Print the distinct values that appear in both arrays, in increasing order.",
    in: "First line: n and m.\nSecond line: n integers.\nThird line: m integers.",
    out: "The distinct common values in increasing order, or the word NONE if there are none.",
    c: "1 <= n, m <= 100000\n-10^9 <= values <= 10^9",
    hints: ["Checking each element of one array against all of the other is O(nm).", "Membership testing is the operation you want to be fast.", "Put one array in a hash set, then filter the other."],
    ap: "Build a hash set from the first array, collect the members of the second that are present, deduplicate, then sort.",
    it: "A hash set turns 'is x in this collection?' into an O(1) question.",
    st: ["Insert every value of the first array into a set.", "Scan the second array collecting values present in the set.", "Deduplicate and sort the result."],
    tc: "O(n + m log m)", sc: "O(n)",
    solve: (input) => { const r = reader(input); const n = r.int(), m = r.int(); const a = new Set(r.ints(n)); const out = [...new Set(r.ints(m).filter((v) => a.has(v)))].sort((x, y) => x - y); return out.length ? join(out) : "NONE"; },
    samples: ["4 3\n1 2 2 4\n2 4 6", "3 3\n1 2 3\n4 5 6"],
    why: ["2 and 4 appear in both; duplicates collapse.", "The arrays share no value."],
    hidden: ["1 1\n5\n5", "5 5\n1 1 1 1 1\n1 2 3 4 5", "4 4\n-3 -2 -1 0\n0 -1 5 6", "3 2\n7 8 9\n10 11"],
    edge: ["1 1\n1\n2"],
  },
  {
    slug: "majority-element-boyer",
    title: "Majority Element",
    difficulty: "EASY",
    topics: ["arrays"],
    d: "One value occupies strictly more than half of the array. Find it using constant extra space.",
    in: "First line: n.\nSecond line: n integers.",
    out: "The majority value.",
    c: "1 <= n <= 100000\nA majority element is guaranteed to exist.",
    hints: ["Counting with a hash map works but uses O(n) memory.", "Imagine each occurrence of the majority cancelling one occurrence of anything else.", "Boyer-Moore voting: keep a candidate and a counter."],
    ap: "Boyer-Moore majority vote. Hold a candidate and a counter; matching values increment it, differing values decrement it, and a zero counter adopts a new candidate.",
    it: "Because the majority appears more than n/2 times, it survives pairwise cancellation against everything else.",
    st: ["Set count = 0 and candidate undefined.", "For each value: if count is 0 adopt it as candidate.", "Increment count on a match, decrement otherwise.", "Print the surviving candidate."],
    tc: "O(n)", sc: "O(1)",
    solve: (i) => { let count = 0, candidate = 0; for (const v of A(i)) { if (count === 0) candidate = v; count += v === candidate ? 1 : -1; } return String(candidate); },
    samples: ["7\n2 2 1 1 2 2 2", "1\n9"],
    why: ["2 appears five times out of seven.", "A single element is trivially the majority."],
    hidden: ["3\n1 1 2", "5\n3 3 4 3 3", "9\n-1 -1 -1 -1 -1 2 3 4 5", "5\n0 0 0 1 2"],
    edge: ["3\n7 7 7"],
    companies: ["amazon", "adobe"],
  },
  {
    slug: "kadane-max-subarray",
    title: "Maximum Subarray Sum",
    difficulty: "EASY",
    topics: ["arrays", "dp"],
    d: "Find the largest sum obtainable from a non-empty contiguous subarray.",
    in: "First line: n.\nSecond line: n integers.",
    out: "The maximum subarray sum.",
    c: "1 <= n <= 100000\n-10^9 <= a[i] <= 10^9",
    hints: ["Trying every subarray is O(n^2).", "Ask what the best subarray ending exactly at position i looks like.", "It is either a[i] alone or a[i] extending the best subarray ending at i-1."],
    ap: "Kadane's algorithm. Maintain the best sum ending at the current index; the global answer is the maximum of those values.",
    it: "A prefix with negative total can only hurt, so you restart whenever the running sum drops below the current element.",
    st: ["Set current = best = a[0].", "For each later value: current = max(value, current + value).", "best = max(best, current).", "Print best."],
    tc: "O(n)", sc: "O(1)",
    solve: (i) => { const a = A(i); let cur = a[0], best = a[0]; for (let k = 1; k < a.length; k += 1) { cur = Math.max(a[k], cur + a[k]); best = Math.max(best, cur); } return String(best); },
    samples: ["9\n-2 1 -3 4 -1 2 1 -5 4", "3\n-5 -2 -9"],
    why: ["The subarray [4, -1, 2, 1] sums to 6.", "All values are negative, so the best is the single largest."],
    hidden: ["1\n5", "5\n1 2 3 4 5", "5\n-1 -2 -3 -4 -5", "6\n5 -9 6 -2 3 -1"],
    edge: ["2\n-1000000000 1000000000"],
    companies: ["amazon", "microsoft", "google", "adobe"],
    sol: { PYTHON: `import sys\nd=sys.stdin.read().split()\nn=int(d[0]);a=list(map(int,d[1:1+n]))\ncur=best=a[0]\nfor v in a[1:]:\n    cur=max(v,cur+v); best=max(best,cur)\nprint(best)\n`, CPP: `#include <bits/stdc++.h>\nusing namespace std;\nint main(){int n;cin>>n;long long cur,best,x;cin>>cur;best=cur;for(int i=1;i<n;i++){cin>>x;cur=max(x,cur+x);best=max(best,cur);}cout<<best<<"\\n";}\n` },
  },
  {
    slug: "best-time-buy-sell-stock",
    title: "Best Time to Buy and Sell Stock",
    difficulty: "EASY",
    topics: ["arrays", "greedy"],
    d: "Prices for consecutive days are given. Buy on one day and sell on a strictly later day to maximise profit. If no profit is possible, the answer is 0.",
    in: "First line: n.\nSecond line: n prices.",
    out: "The maximum achievable profit.",
    c: "1 <= n <= 100000\n0 <= price <= 10^9",
    hints: ["The sell day must come after the buy day.", "For each day, the best buy is the cheapest day so far.", "Track the running minimum price and the best profit against it."],
    ap: "Single pass keeping the minimum price seen so far and the best profit obtainable by selling today.",
    it: "The optimal buy for any sell day is simply the cheapest earlier day, which a running minimum tracks for free.",
    st: ["Set minPrice = price[0] and profit = 0.", "For each later price: profit = max(profit, price - minPrice).", "minPrice = min(minPrice, price).", "Print profit."],
    tc: "O(n)", sc: "O(1)",
    solve: (i) => { const a = A(i); let lo = a[0], best = 0; for (const p of a) { best = Math.max(best, p - lo); lo = Math.min(lo, p); } return String(best); },
    samples: ["6\n7 1 5 3 6 4", "5\n7 6 4 3 1"],
    why: ["Buy at 1 and sell at 6 for a profit of 5.", "Prices only fall, so no trade is profitable."],
    hidden: ["1\n5", "2\n1 2", "5\n2 4 1 7 3", "4\n3 3 3 3"],
    edge: ["2\n1000000000 0"],
    companies: ["amazon", "meta", "microsoft"],
  },
  {
    slug: "contains-duplicate",
    title: "Contains Duplicate",
    difficulty: "EASY",
    topics: ["hashing", "arrays"],
    d: "Decide whether any value appears more than once in the array.",
    in: "First line: n.\nSecond line: n integers.",
    out: "YES if a duplicate exists, otherwise NO.",
    c: "1 <= n <= 100000\n-10^9 <= a[i] <= 10^9",
    hints: ["Sorting makes duplicates adjacent.", "A hash set answers membership in O(1).", "Insert as you scan and stop the moment an insert finds an existing value."],
    ap: "Insert values into a hash set; if a value is already present the answer is YES.",
    it: "Duplicate detection is exactly asking whether the set of values is smaller than the array.",
    st: ["Create an empty set.", "For each value, if it is already in the set print YES.", "Otherwise insert it.", "If the scan finishes print NO."],
    tc: "O(n)", sc: "O(n)",
    solve: (i) => { const a = A(i); return yesNo(new Set(a).size !== a.length); },
    samples: ["4\n1 2 3 1", "4\n1 2 3 4"],
    why: ["1 appears twice.", "Every value is distinct."],
    hidden: ["1\n5", "5\n1 1 1 1 1", "6\n-1 -2 -3 -1 0 5", "3\n0 1 2"],
    edge: ["2\n1000000000 1000000000"],
  },
  {
    slug: "first-unique-character",
    title: "First Unique Character",
    difficulty: "EASY",
    topics: ["strings", "hashing"],
    d: "Find the index of the first character in a string that occurs exactly once. If there is none, print -1.",
    in: "A single line containing a lowercase string.",
    out: "The 0-indexed position of the first non-repeating character, or -1.",
    c: "1 <= |s| <= 100000",
    hints: ["You need counts before you can decide about the first character.", "Two passes are fine.", "Count every letter first, then rescan for the first with count one."],
    ap: "Count letter frequencies in one pass, then scan again and return the first index whose count is one.",
    it: "Uniqueness is a global property, so a full count must exist before any position can be judged.",
    st: ["Count occurrences of each character.", "Scan the string from the left.", "Return the first index whose count is 1, else -1."],
    tc: "O(n)", sc: "O(1)",
    solve: (input) => { const s = input.trim(); const count = new Map<string, number>(); for (const ch of s) count.set(ch, (count.get(ch) ?? 0) + 1); for (let i = 0; i < s.length; i += 1) if (count.get(s[i]) === 1) return String(i); return "-1"; },
    samples: ["leetcode", "aabb"],
    why: ["'l' is the first character that occurs once.", "Every character repeats."],
    hidden: ["a", "loveleetcode", "zzzza", "abcabcd"],
    edge: ["aa"],
    companies: ["amazon", "microsoft"],
  },
  {
    slug: "valid-parentheses",
    title: "Valid Parentheses",
    difficulty: "EASY",
    topics: ["stack", "strings"],
    d: "Decide whether a string of brackets is balanced. The brackets are (), [] and {}. A string is balanced when every opening bracket is closed by the matching type in the correct order.",
    in: "A single line containing bracket characters.",
    out: "YES if the string is balanced, otherwise NO.",
    c: "1 <= |s| <= 100000",
    hints: ["The most recently opened bracket must be the first one closed.", "That last-in-first-out behaviour has a name.", "Push opening brackets onto a stack and pop on a closing bracket."],
    ap: "Push every opening bracket; on a closing bracket, the stack top must be its match. The string is valid when the stack ends empty.",
    it: "Nesting is inherently LIFO, which is exactly what a stack models.",
    st: ["Create an empty stack.", "Push opening brackets.", "On a closing bracket, fail if the stack is empty or the top does not match; otherwise pop.", "Succeed only if the stack is empty at the end."],
    tc: "O(n)", sc: "O(n)",
    solve: (input) => { const s = input.trim(); const pairs: Record<string, string> = { ")": "(", "]": "[", "}": "{" }; const stack: string[] = []; for (const ch of s) { if (ch === "(" || ch === "[" || ch === "{") stack.push(ch); else if (pairs[ch]) { if (stack.pop() !== pairs[ch]) return "NO"; } } return yesNo(stack.length === 0); },
    samples: ["()[]{}", "(]"],
    why: ["Every bracket closes in the right order.", "'(' is closed by ']'."],
    hidden: ["()", "([{}])", "(((", "){"],
    edge: ["]"],
    companies: ["amazon", "google", "microsoft", "meta"],
    sol: { PYTHON: `import sys\ns=sys.stdin.readline().strip()\npairs={')':'(',']':'[','}':'{'}\nst=[]\nok=True\nfor ch in s:\n    if ch in '([{': st.append(ch)\n    elif ch in pairs:\n        if not st or st.pop()!=pairs[ch]: ok=False; break\nprint("YES" if ok and not st else "NO")\n` },
  },
  {
    slug: "implement-stack-array",
    title: "Implement a Stack",
    difficulty: "EASY",
    topics: ["stack"],
    d: "Simulate a stack. Operations are PUSH x, POP and TOP. POP and TOP on an empty stack print EMPTY; POP otherwise prints the removed value.",
    in: "First line: q.\nNext q lines: one operation each.",
    out: "One line per POP or TOP operation.",
    c: "1 <= q <= 100000\n-10^9 <= x <= 10^9",
    hints: ["A dynamic array supports both ends cheaply at the back.", "Track the top index rather than shifting elements.", "PUSH appends, POP removes from the same end."],
    ap: "Back an array with a top index. Push appends, pop removes from the tail, and both are O(1).",
    it: "A stack only ever touches one end, so an array's tail is the natural storage.",
    st: ["Keep an array and a size counter.", "PUSH appends the value.", "POP removes and prints the last value, or EMPTY.", "TOP prints the last value without removing it."],
    tc: "O(1) per operation", sc: "O(q)",
    solve: (input) => { const parts = input.trim().split("\n"); const q = Number(parts[0]); const stack: string[] = []; const out: string[] = []; for (let i = 1; i <= q; i += 1) { const [op, value] = (parts[i] ?? "").trim().split(/\s+/); if (op === "PUSH") stack.push(value); else if (op === "POP") out.push(stack.length ? stack.pop()! : "EMPTY"); else if (op === "TOP") out.push(stack.length ? stack[stack.length - 1] : "EMPTY"); } return linesOut(out); },
    samples: ["5\nPUSH 3\nPUSH 7\nTOP\nPOP\nTOP", "3\nPOP\nTOP\nPUSH 1"],
    why: ["7 is on top, is popped, and 3 is revealed.", "Both reads happen on an empty stack."],
    hidden: ["4\nPUSH 1\nPUSH 2\nPOP\nPOP", "2\nPUSH -5\nTOP", "6\nPUSH 1\nPOP\nPOP\nPUSH 2\nTOP\nPOP", "1\nTOP"],
    edge: ["2\nPOP\nPOP"],
  },
  {
    slug: "implement-queue",
    title: "Implement a Queue",
    difficulty: "EASY",
    topics: ["queue"],
    d: "Simulate a queue. Operations are ENQUEUE x, DEQUEUE and FRONT. DEQUEUE and FRONT on an empty queue print EMPTY.",
    in: "First line: q.\nNext q lines: one operation each.",
    out: "One line per DEQUEUE or FRONT operation.",
    c: "1 <= q <= 100000\n-10^9 <= x <= 10^9",
    hints: ["Removing from the front of an array shifts everything.", "Keep a head index instead of shifting.", "Advance the head pointer on dequeue and never move the stored values."],
    ap: "Store values in an array with a head index. Enqueue appends, dequeue advances the head, both O(1).",
    it: "A queue touches two ends, so one pointer per end avoids the cost of shifting.",
    st: ["Keep an array plus a head index.", "ENQUEUE appends.", "DEQUEUE prints the value at head and advances it, or EMPTY.", "FRONT prints the value at head without advancing."],
    tc: "O(1) per operation", sc: "O(q)",
    solve: (input) => { const parts = input.trim().split("\n"); const q = Number(parts[0]); const data: string[] = []; let head = 0; const out: string[] = []; for (let i = 1; i <= q; i += 1) { const [op, value] = (parts[i] ?? "").trim().split(/\s+/); if (op === "ENQUEUE") data.push(value); else if (op === "DEQUEUE") out.push(head < data.length ? data[head++] : "EMPTY"); else if (op === "FRONT") out.push(head < data.length ? data[head] : "EMPTY"); } return linesOut(out); },
    samples: ["5\nENQUEUE 3\nENQUEUE 7\nFRONT\nDEQUEUE\nFRONT", "2\nDEQUEUE\nFRONT"],
    why: ["3 entered first, so it is at the front and leaves first.", "Both reads happen on an empty queue."],
    hidden: ["4\nENQUEUE 1\nENQUEUE 2\nDEQUEUE\nDEQUEUE", "3\nENQUEUE -4\nFRONT\nDEQUEUE", "5\nENQUEUE 1\nDEQUEUE\nDEQUEUE\nENQUEUE 9\nFRONT", "1\nFRONT"],
    edge: ["2\nDEQUEUE\nDEQUEUE"],
  },
  {
    slug: "bubble-sort-impl",
    title: "Bubble Sort",
    difficulty: "EASY",
    topics: ["sorting"],
    d: "Sort an array in non-decreasing order using bubble sort and print the result. The constraints are small so the quadratic cost is acceptable.",
    in: "First line: n.\nSecond line: n integers.",
    out: "The sorted array, space separated.",
    c: "1 <= n <= 2000\n-10^9 <= a[i] <= 10^9",
    hints: ["Each pass pushes the largest remaining value to the end.", "After k passes, the last k positions are final.", "Stop early if a pass performs no swap."],
    ap: "Repeatedly sweep the array swapping out-of-order neighbours; after each sweep the largest unsorted value settles at the end. An early exit when a sweep makes no swap makes the best case linear.",
    it: "Adjacent swaps can only fix one inversion at a time, which is why the worst case is quadratic.",
    st: ["Repeat n-1 times.", "Sweep the unsorted prefix swapping a[j] and a[j+1] when out of order.", "If a sweep makes no swaps, stop.", "Print the array."],
    tc: "O(n^2) worst case, O(n) best case", sc: "O(1)",
    solve: (i) => join(A(i).sort((x, y) => x - y)),
    samples: ["5\n5 1 4 2 8", "3\n1 2 3"],
    why: ["Repeated neighbour swaps order the array.", "Already sorted, so the first sweep makes no swaps."],
    hidden: ["1\n7", "4\n4 3 2 1", "6\n2 2 1 1 3 3", "5\n-1 -5 0 3 -2"],
    edge: ["2\n2 1"],
  },
  {
    slug: "selection-sort-impl",
    title: "Selection Sort",
    difficulty: "EASY",
    topics: ["sorting"],
    d: "Sort an array using selection sort and print the result.",
    in: "First line: n.\nSecond line: n integers.",
    out: "The sorted array, space separated.",
    c: "1 <= n <= 2000\n-10^9 <= a[i] <= 10^9",
    hints: ["Find where the smallest remaining value should go.", "Each round places exactly one element permanently.", "Scan the unsorted suffix for its minimum and swap it into position."],
    ap: "For each position i, find the minimum of a[i..n-1] and swap it into index i. Exactly n-1 swaps are performed regardless of the input.",
    it: "Selection sort minimises writes: it does the fewest swaps of the simple quadratic sorts.",
    st: ["For i from 0 to n-2, find the index of the minimum in a[i..n-1].", "Swap that element with a[i].", "Print the array."],
    tc: "O(n^2)", sc: "O(1)",
    solve: (i) => join(A(i).sort((x, y) => x - y)),
    samples: ["5\n64 25 12 22 11", "2\n2 1"],
    why: ["Each round moves the smallest remaining value forward.", "One swap sorts the pair."],
    hidden: ["1\n3", "4\n1 2 3 4", "5\n5 4 3 2 1", "6\n0 -1 0 -1 0 -1"],
    edge: ["3\n7 7 7"],
  },
  {
    slug: "insertion-sort-impl",
    title: "Insertion Sort",
    difficulty: "EASY",
    topics: ["sorting"],
    d: "Sort an array using insertion sort and print the result.",
    in: "First line: n.\nSecond line: n integers.",
    out: "The sorted array, space separated.",
    c: "1 <= n <= 2000\n-10^9 <= a[i] <= 10^9",
    hints: ["Treat the prefix as already sorted.", "Insert the next element into its correct place in that prefix.", "Shift larger elements right until the slot appears."],
    ap: "Grow a sorted prefix one element at a time, shifting larger values right to open the correct slot for the incoming element.",
    it: "Insertion sort is near-linear on nearly sorted input, which is why it is used as the base case inside faster sorts.",
    st: ["For i from 1 to n-1, hold key = a[i].", "Shift elements of the sorted prefix that exceed key one place right.", "Place key in the opened slot.", "Print the array."],
    tc: "O(n^2) worst case, O(n) on nearly sorted input", sc: "O(1)",
    solve: (i) => join(A(i).sort((x, y) => x - y)),
    samples: ["5\n12 11 13 5 6", "4\n1 2 4 3"],
    why: ["Each element is inserted into the growing sorted prefix.", "Only the last element needs to move."],
    hidden: ["1\n1", "5\n5 4 3 2 1", "6\n3 3 2 2 1 1", "4\n-2 -3 -1 0"],
    edge: ["2\n1 1"],
  },
  {
    slug: "sort-colors-01",
    title: "Sort an Array of 0s, 1s and 2s",
    difficulty: "EASY",
    topics: ["arrays", "sorting"],
    d: "The array contains only the values 0, 1 and 2. Sort it in one pass using constant extra space.",
    in: "First line: n.\nSecond line: n values from {0, 1, 2}.",
    out: "The sorted array, space separated.",
    c: "1 <= n <= 100000\na[i] is 0, 1 or 2",
    hints: ["Counting the three values and rewriting works, but needs two passes.", "Think of three regions: zeroes, ones, and twos.", "Use three pointers (low, mid, high) and classify a[mid] each step."],
    ap: "The Dutch national flag partition: low marks the end of the zero block, high marks the start of the two block, and mid scans between them.",
    it: "Three-way partitioning is the same trick quicksort uses to handle many equal keys efficiently.",
    st: ["Set low = 0, mid = 0, high = n-1.", "If a[mid] is 0 swap with low and advance both.", "If it is 1 just advance mid.", "If it is 2 swap with high and decrement high."],
    tc: "O(n)", sc: "O(1)",
    solve: (i) => join(A(i).sort((x, y) => x - y)),
    samples: ["6\n2 0 2 1 1 0", "3\n2 1 0"],
    why: ["Zeroes first, then ones, then twos.", "Reversed input becomes ordered."],
    hidden: ["1\n1", "5\n0 0 0 0 0", "5\n2 2 2 2 2", "7\n1 0 2 1 0 2 1"],
    edge: ["2\n2 0"],
    companies: ["microsoft", "amazon", "adobe"],
  },
  {
    slug: "power-of-two",
    title: "Power of Two",
    difficulty: "EASY",
    topics: ["bit-manipulation", "math"],
    d: "Decide whether a positive integer is an exact power of two.",
    in: "A single integer n.",
    out: "YES if n is a power of two, otherwise NO.",
    c: "1 <= n <= 10^18",
    hints: ["Repeated division by 2 works but is not the neat answer.", "Write a power of two in binary and look at the bit pattern.", "n & (n-1) clears the lowest set bit."],
    ap: "A power of two has exactly one set bit, so n & (n-1) is zero exactly when n is a power of two (for n >= 1).",
    it: "Subtracting one from a power of two flips its single bit off and every lower bit on, so the AND is zero.",
    st: ["Reject n <= 0.", "Compute n & (n-1).", "Print YES when the result is zero."],
    tc: "O(1)", sc: "O(1)",
    solve: (input) => { const n = BigInt(input.trim()); return yesNo(n > 0n && (n & (n - 1n)) === 0n); },
    samples: ["16", "18"],
    why: ["16 is 2^4.", "18 has more than one set bit."],
    hidden: ["1", "1024", "1000000000000000000", "576460752303423488"],
    edge: ["2", "3"],
  },
  {
    slug: "count-set-bits",
    title: "Count Set Bits",
    difficulty: "EASY",
    topics: ["bit-manipulation"],
    d: "Count how many bits are set to 1 in the binary representation of a non-negative integer.",
    in: "A single integer n.",
    out: "The number of set bits.",
    c: "0 <= n <= 10^18",
    hints: ["Checking all 64 bits works and is perfectly fine.", "There is a trick that loops once per set bit instead.", "n & (n-1) removes the lowest set bit."],
    ap: "Brian Kernighan's method: repeatedly clear the lowest set bit with n &= n-1 and count the iterations.",
    it: "Each clear removes exactly one set bit, so the loop runs popcount(n) times rather than 64.",
    st: ["Set count = 0.", "While n is non-zero: n &= n-1 and increment count.", "Print count."],
    tc: "O(popcount n)", sc: "O(1)",
    solve: (input) => { let n = BigInt(input.trim()); let count = 0; while (n > 0n) { n &= n - 1n; count += 1; } return String(count); },
    samples: ["13", "0"],
    why: ["13 is 1101 in binary, which has three set bits.", "Zero has no set bits."],
    hidden: ["1", "255", "1024", "1000000000000000000"],
    edge: ["2"],
  },
  {
    slug: "reverse-integer-digits",
    title: "Reverse the Digits of a Number",
    difficulty: "EASY",
    topics: ["math"],
    d: "Reverse the decimal digits of an integer. The sign is preserved and leading zeroes disappear.",
    in: "A single integer n.",
    out: "The integer with its digits reversed.",
    c: "-10^18 <= n <= 10^18",
    hints: ["Handle the sign separately from the digits.", "Peel digits off with mod 10 and rebuild with multiply-by-10.", "Leading zeroes vanish automatically when you rebuild numerically."],
    ap: "Strip the sign, repeatedly take n mod 10 to build the reversed value, then reapply the sign.",
    it: "Building a number digit by digit is the inverse of peeling digits off, so one loop does both.",
    st: ["Record whether n is negative and take its absolute value.", "While n > 0: result = result*10 + n mod 10; n /= 10.", "Reapply the sign and print."],
    tc: "O(log n)", sc: "O(1)",
    solve: (input) => { const s = input.trim(); const neg = s.startsWith("-"); const digits = s.replace("-", "").split("").reverse().join("").replace(/^0+(?=\d)/, ""); return (neg && digits !== "0" ? "-" : "") + digits; },
    samples: ["12345", "-4700"],
    why: ["The digits are read back to front.", "The sign stays and the trailing zeroes disappear."],
    hidden: ["0", "7", "1000000", "-1"],
    edge: ["10"],
  },
  {
    slug: "armstrong-number",
    title: "Armstrong Number",
    difficulty: "EASY",
    topics: ["math"],
    d: "An Armstrong number equals the sum of its own digits each raised to the power of the digit count. Decide whether n is one.",
    in: "A single integer n.",
    out: "YES if n is an Armstrong number, otherwise NO.",
    c: "1 <= n <= 10^9",
    hints: ["First you need the number of digits.", "Then raise each digit to that power.", "Compare the total with the original number."],
    ap: "Count the digits, sum each digit raised to that power, and compare against n.",
    it: "The definition is self-referential in the digit count, so that count must be computed before the sum.",
    st: ["Count the digits of n.", "Sum digit^count over all digits.", "Print YES when the sum equals n."],
    tc: "O(log n)", sc: "O(1)",
    solve: (input) => { const s = input.trim(); const k = s.length; const total = s.split("").reduce((sum, ch) => sum + Number(ch) ** k, 0); return yesNo(total === Number(s)); },
    samples: ["153", "154"],
    why: ["1^3 + 5^3 + 3^3 = 153.", "1^3 + 5^3 + 4^3 = 190, not 154."],
    hidden: ["1", "9474", "9475", "370"],
    edge: ["10"],
  },
  {
    slug: "perfect-number",
    title: "Perfect Number",
    difficulty: "EASY",
    topics: ["math"],
    d: "A perfect number equals the sum of its positive divisors excluding itself. Decide whether n is perfect.",
    in: "A single integer n.",
    out: "YES if n is perfect, otherwise NO.",
    c: "1 <= n <= 10^9",
    hints: ["Enumerating every divisor up to n is too slow.", "Divisors pair up around the square root.", "For each d up to sqrt(n) that divides n, add both d and n/d."],
    ap: "Enumerate divisors up to sqrt(n), adding both members of each pair while avoiding double counting the square root and n itself.",
    it: "Divisors are symmetric around sqrt(n), so half the range determines all of them.",
    st: ["Set total = 1 for n > 1.", "For d from 2 while d*d <= n, if d divides n add d and n/d (once if equal).", "Print YES when total equals n."],
    tc: "O(sqrt n)", sc: "O(1)",
    solve: (input) => { const n = Number(input.trim()); if (n <= 1) return "NO"; let total = 1; for (let d = 2; d * d <= n; d += 1) { if (n % d === 0) { total += d; if (d !== n / d) total += n / d; } } return yesNo(total === n); },
    samples: ["28", "12"],
    why: ["1+2+4+7+14 = 28.", "1+2+3+4+6 = 16, not 12."],
    hidden: ["6", "496", "8128", "97"],
    edge: ["1"],
  },
  {
    slug: "sieve-primes",
    title: "Primes up to N",
    difficulty: "EASY",
    topics: ["math"],
    d: "Print all prime numbers up to and including n, in increasing order. If there are none, print NONE.",
    in: "A single integer n.",
    out: "The primes up to n, space separated, or NONE.",
    c: "1 <= n <= 1000000",
    hints: ["Testing each number separately costs n sqrt(n).", "Composites are exactly the multiples of smaller primes.", "Use a sieve: mark multiples of each prime starting from its square."],
    ap: "The sieve of Eratosthenes. Mark multiples of every prime, starting at p*p because smaller multiples were already marked.",
    it: "Each composite is crossed off by its smallest prime factor, so the total work is n log log n.",
    st: ["Create a boolean array of size n+1 initialised to prime.", "Mark 0 and 1 as not prime.", "For each p with p*p <= n that is still prime, mark p*p, p*p+p, ... as composite.", "Print every index still marked prime."],
    tc: "O(n log log n)", sc: "O(n)",
    solve: (input) => { const n = Number(input.trim()); if (n < 2) return "NONE"; const sieve = new Uint8Array(n + 1); const out: number[] = []; for (let p = 2; p <= n; p += 1) { if (sieve[p]) continue; out.push(p); for (let q = p * p; q <= n; q += p) sieve[q] = 1; } return out.length ? join(out) : "NONE"; },
    samples: ["20", "1"],
    why: ["These are the primes at most 20.", "There are no primes below 2."],
    hidden: ["2", "10", "50", "100"],
    edge: ["3"],
  },
  {
    slug: "linked-list-traverse",
    title: "Traverse a Linked List",
    difficulty: "EASY",
    topics: ["linked-lists"],
    d: "A singly linked list is described by its node values in order. Print the values from head to tail, then the length on the next line.",
    in: "First line: n.\nSecond line: n node values in list order.",
    out: "Line 1: the values, space separated (or the word EMPTY).\nLine 2: the length.",
    c: "0 <= n <= 100000\n-10^9 <= value <= 10^9",
    hints: ["Walking a list means following next pointers until null.", "Count as you walk.", "Handle the empty list before you dereference anything."],
    ap: "Follow next pointers from the head, emitting each value and incrementing a counter until the pointer becomes null.",
    it: "Traversal is the single primitive every linked-list algorithm is built from.",
    st: ["Start at the head.", "While the node is not null, record its value and move to next.", "Print the values, then the count."],
    tc: "O(n)", sc: "O(1)",
    solve: (input) => { const r = reader(input); const n = r.int(); const a = r.ints(n); return `${a.length ? join(a) : "EMPTY"}\n${n}`; },
    samples: ["4\n1 2 3 4", "0"],
    why: ["Four nodes are visited in order.", "An empty list has no values and length zero."],
    hidden: ["1\n7", "3\n-1 0 1", "5\n5 5 5 5 5", "2\n1000000000 -1000000000"],
    edge: ["1\n0"],
  },
  {
    slug: "linked-list-reverse",
    title: "Reverse a Linked List",
    difficulty: "EASY",
    topics: ["linked-lists"],
    d: "Reverse a singly linked list and print the resulting order.",
    in: "First line: n.\nSecond line: n node values in list order.",
    out: "The reversed list, space separated, or EMPTY.",
    c: "0 <= n <= 100000\n-10^9 <= value <= 10^9",
    hints: ["You cannot walk backwards, so you must rewire as you go.", "Keep track of the node you just came from.", "Three pointers: previous, current, next."],
    ap: "Iterative pointer reversal: remember the next node, point current at previous, then shift all three pointers forward.",
    it: "Reversal is local: each step only needs the node before and after the current one.",
    st: ["Set prev = null, curr = head.", "While curr is not null: save next = curr.next.", "Set curr.next = prev, then prev = curr and curr = next.", "The new head is prev."],
    tc: "O(n)", sc: "O(1)",
    solve: (input) => { const r = reader(input); const n = r.int(); const a = r.ints(n); return a.length ? join(a.reverse()) : "EMPTY"; },
    samples: ["5\n1 2 3 4 5", "1\n9"],
    why: ["The links are flipped end to end.", "A single node reverses to itself."],
    hidden: ["0", "2\n1 2", "4\n-1 -2 -3 -4", "3\n7 7 7"],
    edge: ["2\n0 0"],
    companies: ["amazon", "microsoft", "google", "meta"],
  },
  {
    slug: "linked-list-middle",
    title: "Middle of a Linked List",
    difficulty: "EASY",
    topics: ["linked-lists"],
    d: "Print the value at the middle node of a singly linked list. With an even number of nodes, print the second of the two middle nodes.",
    in: "First line: n.\nSecond line: n node values in list order.",
    out: "The middle node's value.",
    c: "1 <= n <= 100000\n-10^9 <= value <= 10^9",
    hints: ["Counting first and walking again works, but takes two passes.", "Imagine two walkers moving at different speeds.", "Move one pointer one step and the other two steps per iteration."],
    ap: "Slow and fast pointers. When the fast pointer runs off the end, the slow pointer sits on the middle node.",
    it: "Moving at twice the speed means the fast pointer covers the whole list while the slow one covers exactly half.",
    st: ["Set slow = fast = head.", "While fast and fast.next exist, advance slow once and fast twice.", "Print slow's value."],
    tc: "O(n)", sc: "O(1)",
    solve: (input) => { const r = reader(input); const n = r.int(); const a = r.ints(n); return String(a[Math.floor(n / 2)]); },
    samples: ["5\n1 2 3 4 5", "6\n1 2 3 4 5 6"],
    why: ["The third of five nodes is the middle.", "With six nodes the second middle is the fourth node."],
    hidden: ["1\n5", "2\n1 2", "7\n1 2 3 4 5 6 7", "4\n-1 -2 -3 -4"],
    edge: ["3\n0 0 0"],
  },
  {
    slug: "linked-list-cycle",
    title: "Detect a Cycle in a Linked List",
    difficulty: "EASY",
    topics: ["linked-lists"],
    d: "A list is described by n node values followed by an index pos. If pos is -1 the list ends normally; otherwise the tail links back to the node at index pos. Decide whether the list contains a cycle.",
    in: "First line: n and pos.\nSecond line: n node values.",
    out: "YES if a cycle exists, otherwise NO.",
    c: "1 <= n <= 100000\n-1 <= pos < n",
    hints: ["Marking visited nodes in a hash set works but uses O(n) memory.", "Two runners on a circular track eventually meet.", "Advance one pointer by one and another by two; a meeting means a cycle."],
    ap: "Floyd's cycle detection. If a cycle exists, the fast pointer laps the slow one and they meet; otherwise the fast pointer reaches the end.",
    it: "Inside a cycle the gap between the two pointers shrinks by one each step, so they must eventually coincide.",
    st: ["Set slow = fast = head.", "Advance slow by one and fast by two.", "If they ever meet, print YES.", "If fast reaches null, print NO."],
    tc: "O(n)", sc: "O(1)",
    solve: (input) => { const r = reader(input); r.int(); const pos = r.int(); return yesNo(pos !== -1); },
    samples: ["4 1\n3 2 0 -4", "2 -1\n1 2"],
    why: ["The tail links back to index 1, forming a cycle.", "pos is -1, so the list terminates."],
    hidden: ["1 0\n1", "1 -1\n1", "5 4\n1 2 3 4 5", "3 -1\n1 2 3"],
    edge: ["2 0\n1 2"],
    companies: ["amazon", "microsoft", "meta"],
  },
  {
    slug: "tree-inorder",
    title: "Inorder Traversal of a Binary Tree",
    difficulty: "EASY",
    topics: ["trees"],
    d: "A binary tree is given in level order with -1 marking an absent child. Print its inorder traversal.",
    in: "First line: n, the number of level-order entries.\nSecond line: n values, where -1 marks a missing node.",
    out: "The inorder traversal, space separated, or EMPTY.",
    c: "1 <= n <= 100000\nValues are non-negative or -1.",
    hints: ["Inorder means left subtree, node, right subtree.", "In a level-order array the children of index i are at 2i+1 and 2i+2.", "Recurse, skipping indices that are out of range or hold -1."],
    ap: "Treat the level-order array as an implicit tree: index i has children 2i+1 and 2i+2. Recurse left, emit, recurse right.",
    it: "For a binary search tree inorder yields sorted output, which is why this traversal is the default one.",
    st: ["Start at index 0.", "If the index is out of range or holds -1, return.", "Recurse into 2i+1, emit a[i], recurse into 2i+2."],
    tc: "O(n)", sc: "O(h)",
    solve: (input) => { const r = reader(input); const n = r.int(); const a = r.ints(n); const out: number[] = []; const go = (i: number) => { if (i >= n || a[i] === -1) return; go(2 * i + 1); out.push(a[i]); go(2 * i + 2); }; go(0); return out.length ? join(out) : "EMPTY"; },
    samples: ["7\n1 2 3 4 5 6 7", "3\n1 -1 2"],
    why: ["Left subtree, then root, then right subtree.", "The root has no left child."],
    hidden: ["1\n5", "5\n1 2 3 -1 -1", "7\n10 5 15 3 7 -1 18", "3\n1 2 -1"],
    edge: ["1\n-1"],
    companies: ["amazon", "microsoft"],
  },
  {
    slug: "tree-height",
    title: "Height of a Binary Tree",
    difficulty: "EASY",
    topics: ["trees", "recursion"],
    d: "Given a binary tree in level order with -1 for absent children, print its height measured in nodes. An empty tree has height 0.",
    in: "First line: n.\nSecond line: n level-order values, -1 for absent.",
    out: "The height of the tree.",
    c: "1 <= n <= 100000",
    hints: ["The height of a node depends only on its children.", "Define height(null) = 0.", "height(node) = 1 + max(height(left), height(right))."],
    ap: "Recursive post-order evaluation: compute both subtree heights, then combine.",
    it: "Height is a classic post-order property — a node cannot be answered before its children are.",
    st: ["If the index is out of range or holds -1, return 0.", "Compute the left and right heights recursively.", "Return 1 plus their maximum."],
    tc: "O(n)", sc: "O(h)",
    solve: (input) => { const r = reader(input); const n = r.int(); const a = r.ints(n); const go = (i: number): number => (i >= n || a[i] === -1 ? 0 : 1 + Math.max(go(2 * i + 1), go(2 * i + 2))); return String(go(0)); },
    samples: ["7\n1 2 3 4 5 6 7", "1\n-1"],
    why: ["Three complete levels.", "An empty tree has height 0."],
    hidden: ["1\n1", "3\n1 2 -1", "7\n1 2 -1 3 -1 -1 -1", "5\n1 2 3 4 5"],
    edge: ["3\n1 -1 -1"],
  },
  {
    slug: "bst-search",
    title: "Search in a Binary Search Tree",
    difficulty: "EASY",
    topics: ["bst", "searching"],
    d: "A binary search tree is given in level order with -1 for absent children. Decide whether a target value is present.",
    in: "First line: n and target.\nSecond line: n level-order values, -1 for absent.",
    out: "YES if the target is present, otherwise NO.",
    c: "1 <= n <= 100000\nAll present values are distinct and non-negative.",
    hints: ["Do not traverse the whole tree.", "The BST ordering tells you which side to take.", "Go left when the target is smaller, right when it is larger."],
    ap: "Walk down from the root, choosing the subtree the ordering permits, until the value is found or the walk falls off the tree.",
    it: "The BST invariant makes every comparison discard an entire subtree.",
    st: ["Start at the root.", "If the value equals the target, answer YES.", "If the target is smaller go left, otherwise go right.", "If you run off the tree, answer NO."],
    tc: "O(h)", sc: "O(1)",
    solve: (input) => { const r = reader(input); const n = r.int(); const target = r.int(); const a = r.ints(n); let i = 0; while (i < n && a[i] !== -1) { if (a[i] === target) return "YES"; i = target < a[i] ? 2 * i + 1 : 2 * i + 2; } return "NO"; },
    samples: ["7 7\n8 3 10 1 6 -1 14", "7 5\n8 3 10 1 6 -1 14"],
    why: ["7 is absent from that tree... check the path 8 -> 3 -> 6 -> right child.", "5 is not present either."],
    hidden: ["1 1\n1", "3 3\n2 1 3", "7 14\n8 3 10 1 6 -1 14", "3 9\n2 1 3"],
    edge: ["1 0\n-1"],
  },
  {
    slug: "min-max-heap-top",
    title: "K Smallest Elements",
    difficulty: "EASY",
    topics: ["heap", "sorting"],
    d: "Print the k smallest values of an array in increasing order.",
    in: "First line: n and k.\nSecond line: n integers.",
    out: "The k smallest values in increasing order.",
    c: "1 <= k <= n <= 100000\n-10^9 <= a[i] <= 10^9",
    hints: ["Sorting the whole array works and is simple.", "A heap can do better when k is much smaller than n.", "Keep a max-heap of size k while scanning."],
    ap: "Sorting gives O(n log n). A size-k max-heap gives O(n log k) by evicting the largest whenever the heap exceeds k.",
    it: "You never need the ordering of the elements you are going to discard.",
    st: ["Push elements into a max-heap.", "Whenever its size exceeds k, pop the maximum.", "Drain the heap and sort the survivors ascending."],
    tc: "O(n log k)", sc: "O(k)",
    solve: (input) => { const r = reader(input); const n = r.int(), k = r.int(); return join(r.ints(n).sort((x, y) => x - y).slice(0, k)); },
    samples: ["6 3\n7 10 4 3 20 15", "4 1\n5 2 9 1"],
    why: ["The three smallest values in order.", "The single smallest value."],
    hidden: ["1 1\n5", "5 5\n5 4 3 2 1", "6 2\n-1 -2 -3 0 1 2", "5 3\n2 2 2 2 2"],
    edge: ["2 2\n1000000000 -1000000000"],
  },
  {
    slug: "matrix-transpose",
    title: "Transpose a Matrix",
    difficulty: "EASY",
    topics: ["matrix"],
    d: "Print the transpose of an n by m matrix, where the element at row i, column j moves to row j, column i.",
    in: "First line: n and m.\nNext n lines: m integers each.",
    out: "m lines of n integers each.",
    c: "1 <= n, m <= 500\n-10^9 <= values <= 10^9",
    hints: ["The output has m rows and n columns.", "Element (i, j) becomes element (j, i).", "For a square matrix you can swap in place across the diagonal."],
    ap: "Emit the input read column-wise. For a square matrix, swapping a[i][j] with a[j][i] for i < j does it in place.",
    it: "Transposition is a reflection across the main diagonal.",
    st: ["Read the matrix.", "For each column j, emit a[0][j], a[1][j], ... a[n-1][j] as a row.", "Print the m rows."],
    tc: "O(nm)", sc: "O(nm)",
    solve: (input) => { const r = reader(input); const n = r.int(), m = r.int(); const g: number[][] = []; for (let i = 0; i < n; i += 1) g.push(r.ints(m)); const out: string[] = []; for (let j = 0; j < m; j += 1) out.push(join(g.map((row) => row[j]))); return linesOut(out); },
    samples: ["2 3\n1 2 3\n4 5 6", "1 1\n7"],
    why: ["Rows become columns.", "A single cell is its own transpose."],
    hidden: ["3 3\n1 2 3\n4 5 6\n7 8 9", "1 4\n1 2 3 4", "4 1\n1\n2\n3\n4", "2 2\n-1 -2\n-3 -4"],
    edge: ["2 2\n0 0\n0 0"],
  },
  {
    slug: "matrix-row-sums",
    title: "Row and Column Sums",
    difficulty: "EASY",
    topics: ["matrix"],
    d: "Print the sum of each row on one line, then the sum of each column on the next.",
    in: "First line: n and m.\nNext n lines: m integers each.",
    out: "Line 1: n row sums.\nLine 2: m column sums.",
    c: "1 <= n, m <= 500\n-10^9 <= values <= 10^9",
    hints: ["Both answers can be built in the same pass.", "Keep one accumulator per row and one per column.", "Use 64-bit accumulators."],
    ap: "Single traversal accumulating into a row-sum array and a column-sum array simultaneously.",
    it: "Every cell contributes to exactly one row total and one column total, so one visit each suffices.",
    st: ["Allocate row and column accumulators.", "For each cell add its value to both accumulators.", "Print both arrays."],
    tc: "O(nm)", sc: "O(n + m)",
    solve: (input) => { const r = reader(input); const n = r.int(), m = r.int(); const rows: number[] = [], cols = new Array(m).fill(0); for (let i = 0; i < n; i += 1) { const row = r.ints(m); rows.push(row.reduce((s, v) => s + v, 0)); row.forEach((v, j) => (cols[j] += v)); } return `${join(rows)}\n${join(cols)}`; },
    samples: ["2 3\n1 2 3\n4 5 6", "1 1\n5"],
    why: ["Rows sum to 6 and 15; columns to 5, 7 and 9.", "A single cell is both totals."],
    hidden: ["3 3\n1 1 1\n1 1 1\n1 1 1", "2 2\n-1 -2\n-3 -4", "1 3\n1000000000 1000000000 1000000000", "3 1\n1\n2\n3"],
    edge: ["2 2\n0 0\n0 0"],
  },
  {
    slug: "matrix-diagonal-sum",
    title: "Diagonal Sum of a Square Matrix",
    difficulty: "EASY",
    topics: ["matrix"],
    d: "Sum the primary and secondary diagonals of an n by n matrix. When n is odd the centre cell belongs to both and is counted once.",
    in: "First line: n.\nNext n lines: n integers each.",
    out: "The diagonal sum.",
    c: "1 <= n <= 500\n-10^9 <= values <= 10^9",
    hints: ["The primary diagonal is where i equals j.", "The secondary diagonal is where i + j equals n-1.", "Do not count the centre cell twice when n is odd."],
    ap: "Walk i from 0 to n-1, adding a[i][i] and a[i][n-1-i], subtracting the centre once when n is odd.",
    it: "Both diagonals are one-dimensional slices, so a single loop covers them.",
    st: ["Set total = 0.", "For each i add a[i][i] and a[i][n-1-i].", "If n is odd subtract the centre cell once.", "Print total."],
    tc: "O(n^2) to read, O(n) to sum", sc: "O(1)",
    solve: (input) => { const r = reader(input); const n = r.int(); const g: number[][] = []; for (let i = 0; i < n; i += 1) g.push(r.ints(n)); let total = 0; for (let i = 0; i < n; i += 1) { total += g[i][i] + g[i][n - 1 - i]; } if (n % 2 === 1) total -= g[(n - 1) / 2][(n - 1) / 2]; return String(total); },
    samples: ["3\n1 2 3\n4 5 6\n7 8 9", "2\n1 2\n3 4"],
    why: ["1+5+9 plus 3+5+7 minus the doubled centre 5 gives 25.", "1+4 plus 2+3 equals 10."],
    hidden: ["1\n7", "4\n1 1 1 1\n1 1 1 1\n1 1 1 1\n1 1 1 1", "3\n-1 -2 -3\n-4 -5 -6\n-7 -8 -9", "2\n0 0\n0 0"],
    edge: ["1\n0"],
  },
  {
    slug: "spiral-matrix-print",
    title: "Spiral Order of a Matrix",
    difficulty: "EASY",
    topics: ["matrix"],
    d: "Print all elements of an n by m matrix in spiral order, starting at the top-left corner and moving clockwise.",
    in: "First line: n and m.\nNext n lines: m integers each.",
    out: "All n*m values in spiral order, space separated.",
    c: "1 <= n, m <= 500\n-10^9 <= values <= 10^9",
    hints: ["Track the current boundary of the unvisited region.", "After walking a side, shrink that boundary.", "Guard against re-walking a row or column when only one remains."],
    ap: "Maintain top, bottom, left and right boundaries. Walk right, down, left and up in turn, shrinking the corresponding boundary after each side.",
    it: "A spiral is four directed sweeps repeated over a shrinking rectangle.",
    st: ["Set top=0, bottom=n-1, left=0, right=m-1.", "Walk the top row left to right, then top++.", "Walk the right column, then right--.", "Walk the bottom row and left column if they still exist, shrinking each time."],
    tc: "O(nm)", sc: "O(1)",
    solve: (input) => { const r = reader(input); const n = r.int(), m = r.int(); const g: number[][] = []; for (let i = 0; i < n; i += 1) g.push(r.ints(m)); const out: number[] = []; let top = 0, bottom = n - 1, left = 0, right = m - 1; while (top <= bottom && left <= right) { for (let j = left; j <= right; j += 1) out.push(g[top][j]); top += 1; for (let i = top; i <= bottom; i += 1) out.push(g[i][right]); right -= 1; if (top <= bottom) { for (let j = right; j >= left; j -= 1) out.push(g[bottom][j]); bottom -= 1; } if (left <= right) { for (let i = bottom; i >= top; i -= 1) out.push(g[i][left]); left += 1; } } return join(out); },
    samples: ["3 3\n1 2 3\n4 5 6\n7 8 9", "1 4\n1 2 3 4"],
    why: ["The walk goes around the border and then into the centre.", "A single row is walked left to right."],
    hidden: ["1 1\n5", "4 1\n1\n2\n3\n4", "2 3\n1 2 3\n4 5 6", "3 2\n1 2\n3 4\n5 6"],
    edge: ["2 2\n1 2\n3 4"],
    companies: ["amazon", "microsoft", "adobe"],
  },
  {
    slug: "string-uppercase-toggle",
    title: "Toggle Case",
    difficulty: "EASY",
    topics: ["strings"],
    d: "Swap the case of every alphabetic character in a string, leaving other characters untouched.",
    in: "A single line containing visible ASCII characters without spaces.",
    out: "The string with its case toggled.",
    c: "1 <= |s| <= 100000",
    hints: ["Case is a single bit in ASCII.", "Test whether each character is a letter first.", "Uppercase and lowercase differ by 32, or by the 0x20 bit."],
    ap: "Map each character: uppercase letters become lowercase and vice versa; everything else passes through unchanged.",
    it: "In ASCII, toggling case is flipping bit 5, which is why the transform is O(1) per character.",
    st: ["For each character decide whether it is a letter.", "If uppercase, add 32; if lowercase, subtract 32.", "Otherwise leave it alone."],
    tc: "O(n)", sc: "O(n)",
    solve: (input) => input.trim().split("").map((ch) => (ch === ch.toUpperCase() ? ch.toLowerCase() : ch.toUpperCase())).join(""),
    samples: ["DsaForge", "abc123XYZ"],
    why: ["Each letter flips case.", "Digits are untouched."],
    hidden: ["a", "Z", "HELLO", "hello"],
    edge: ["123"],
  },
  {
    slug: "longest-word",
    title: "Longest Word in a Sentence",
    difficulty: "EASY",
    topics: ["strings"],
    d: "Given a sentence of space-separated words, print the longest word. If several tie, print the one that appears first.",
    in: "First line: n, the number of words.\nSecond line: n space-separated words.",
    out: "The longest word.",
    c: "1 <= n <= 100000\nEach word is at most 100 characters.",
    hints: ["Scan the words once.", "Keep the best word seen so far.", "Only replace it on a strictly greater length so ties keep the earlier word."],
    ap: "One pass tracking the longest word, replacing only on a strictly longer candidate so the earliest of any tie survives.",
    it: "Using a strict comparison is what encodes the tie-breaking rule.",
    st: ["Set best to the first word.", "For each later word, replace best when it is strictly longer.", "Print best."],
    tc: "O(total length)", sc: "O(1)",
    solve: (input) => { const r = reader(input); const n = r.int(); const words = r.strs(n); let best = words[0]; for (const w of words) if (w.length > best.length) best = w; return best; },
    samples: ["4\nforge your dsa skills", "3\nabc de fgh"],
    why: ["'skills' has six characters.", "'abc' and 'fgh' tie, so the earlier one wins."],
    hidden: ["1\nhello", "5\na bb ccc dd e", "3\nsame same same", "4\nx yy zzz wwww"],
    edge: ["2\na b"],
  },
  {
    slug: "word-frequency",
    title: "Most Frequent Word",
    difficulty: "EASY",
    topics: ["hashing", "strings"],
    d: "Given a list of words, print the word that occurs most often. If several tie, print the lexicographically smallest of them.",
    in: "First line: n.\nSecond line: n space-separated lowercase words.",
    out: "The most frequent word.",
    c: "1 <= n <= 100000\nEach word is at most 30 characters.",
    hints: ["You need counts before you can compare.", "A hash map from word to count does the counting.", "Break ties by comparing the words themselves."],
    ap: "Count with a hash map, then pick the entry with the highest count, breaking ties lexicographically.",
    it: "Counting and selection are separate phases; conflating them is what makes tie handling error prone.",
    st: ["Count every word into a map.", "Scan the map tracking the best (count, word) pair.", "Prefer the higher count, then the smaller word.", "Print the winner."],
    tc: "O(n)", sc: "O(distinct words)",
    solve: (input) => { const r = reader(input); const n = r.int(); const words = r.strs(n); const count = new Map<string, number>(); for (const w of words) count.set(w, (count.get(w) ?? 0) + 1); let best = ""; let bestCount = -1; for (const [w, c] of count) { if (c > bestCount || (c === bestCount && w < best)) { best = w; bestCount = c; } } return best; },
    samples: ["6\napple banana apple cherry banana apple", "4\nb a b a"],
    why: ["'apple' occurs three times.", "Both occur twice, so the smaller word wins."],
    hidden: ["1\nsolo", "5\nx x y y z", "3\ndsa forge dsa", "4\nz z a a"],
    edge: ["2\nb a"],
  },
  {
    slug: "fizzbuzz",
    title: "FizzBuzz",
    difficulty: "EASY",
    topics: ["math"],
    d: "For each integer from 1 to n print Fizz when it is divisible by 3, Buzz when divisible by 5, FizzBuzz when divisible by both, and otherwise the number itself.",
    in: "A single integer n.",
    out: "n lines, one per value.",
    c: "1 <= n <= 100000",
    hints: ["Check the both-case before the single cases.", "Divisibility by 15 is the same as by 3 and 5.", "Build the output as one string to avoid slow per-line printing."],
    ap: "Iterate 1..n testing divisibility, checking the combined case first so it is not shadowed by the single cases.",
    it: "Order of the conditions is the whole exercise: the most specific rule must be tested first.",
    st: ["Loop i from 1 to n.", "If i mod 15 is 0 print FizzBuzz.", "Else if i mod 3 is 0 print Fizz, else if i mod 5 is 0 print Buzz.", "Otherwise print i."],
    tc: "O(n)", sc: "O(1)",
    solve: (input) => { const n = Number(input.trim()); const out: string[] = []; for (let i = 1; i <= n; i += 1) out.push(i % 15 === 0 ? "FizzBuzz" : i % 3 === 0 ? "Fizz" : i % 5 === 0 ? "Buzz" : String(i)); return linesOut(out); },
    samples: ["5", "15"],
    why: ["3 is Fizz and 5 is Buzz.", "15 is divisible by both."],
    hidden: ["1", "3", "10", "20"],
    edge: ["2"],
    companies: ["tcs", "infosys", "accenture"],
  },
  {
    slug: "leap-year",
    title: "Leap Year",
    difficulty: "EASY",
    topics: ["math"],
    d: "Decide whether a year is a leap year. A year is a leap year if it is divisible by 4, except centuries, which must be divisible by 400.",
    in: "A single integer y.",
    out: "YES if y is a leap year, otherwise NO.",
    c: "1 <= y <= 10^9",
    hints: ["Three rules interact, so the order of the tests matters.", "Divisible by 400 always wins.", "Divisible by 100 but not 400 is never a leap year."],
    ap: "Test divisibility by 400 first, then by 100, then by 4.",
    it: "The century exception is a correction to the simple rule, so it must be applied before it.",
    st: ["If y mod 400 is 0 print YES.", "Else if y mod 100 is 0 print NO.", "Else print YES when y mod 4 is 0."],
    tc: "O(1)", sc: "O(1)",
    solve: (input) => { const y = Number(input.trim()); return yesNo(y % 400 === 0 || (y % 100 !== 0 && y % 4 === 0)); },
    samples: ["2000", "1900"],
    why: ["2000 is divisible by 400.", "1900 is a century not divisible by 400."],
    hidden: ["2024", "2023", "4", "100"],
    edge: ["1"],
  },
  {
    slug: "min-coins-greedy",
    title: "Minimum Coins with Canonical Denominations",
    difficulty: "EASY",
    topics: ["greedy"],
    d: "Using coins of denominations 1, 2, 5, 10, 20, 50, 100, 500 and 2000, make an exact amount with as few coins as possible. Print the number of coins.",
    in: "A single integer amount.",
    out: "The minimum number of coins.",
    c: "1 <= amount <= 10^9",
    hints: ["This denomination set is canonical, so greedy is optimal.", "Always take the largest coin that still fits.", "Use integer division rather than repeated subtraction."],
    ap: "Greedy from the largest denomination down, taking amount / coin of each and reducing the remainder.",
    it: "Greedy is only correct because these denominations are canonical; for arbitrary sets you need dynamic programming.",
    st: ["List the denominations in descending order.", "For each, take as many as fit.", "Reduce the amount by that value.", "Print the total coin count."],
    tc: "O(number of denominations)", sc: "O(1)",
    solve: (input) => { let amount = Number(input.trim()); let count = 0; for (const coin of [2000, 500, 100, 50, 20, 10, 5, 2, 1]) { count += Math.floor(amount / coin); amount %= coin; } return String(count); },
    samples: ["70", "3"],
    why: ["50 + 20 uses two coins.", "2 + 1 uses two coins."],
    hidden: ["1", "2000", "2673", "999999999"],
    edge: ["4"],
  },
  {
    slug: "activity-selection-count",
    title: "Maximum Non-Overlapping Activities",
    difficulty: "EASY",
    topics: ["greedy"],
    d: "Given start and finish times of activities, select as many mutually non-overlapping activities as possible. An activity may start exactly when another finishes.",
    in: "First line: n.\nNext n lines: start and finish for one activity.",
    out: "The maximum number of activities.",
    c: "1 <= n <= 100000\n0 <= start < finish <= 10^9",
    hints: ["Sorting by start time is not the right order.", "Finishing early leaves the most room for what follows.", "Sort by finish time and take greedily."],
    ap: "Sort by finishing time and take each activity whose start is at least the last taken finish.",
    it: "Choosing the earliest finisher never rules out a better schedule, which is the exchange argument that proves greedy optimal here.",
    st: ["Sort activities by finish time.", "Track the last selected finish, initially -infinity.", "Take an activity when its start is not before that finish.", "Count the selections."],
    tc: "O(n log n)", sc: "O(n)",
    solve: (input) => { const r = reader(input); const n = r.int(); const acts: Array<[number, number]> = []; for (let i = 0; i < n; i += 1) acts.push([r.int(), r.int()]); acts.sort((a, b) => a[1] - b[1]); let count = 0, last = -Infinity; for (const [s, f] of acts) { if (s >= last) { count += 1; last = f; } } return String(count); },
    samples: ["4\n1 3\n2 5\n4 7\n6 8", "3\n1 2\n2 3\n3 4"],
    why: ["Selecting [1,3], [4,7] gives two activities.", "All three chain end to end."],
    hidden: ["1\n0 1", "3\n1 10\n2 3\n4 5", "4\n1 2\n1 2\n1 2\n1 2", "5\n0 1\n1 2\n2 3\n3 4\n4 5"],
    edge: ["2\n0 1000000000\n0 1"],
  },
  {
    slug: "climbing-stairs",
    title: "Climbing Stairs",
    difficulty: "EASY",
    topics: ["dp", "recursion"],
    d: "You can climb one or two steps at a time. Count the distinct ways to reach step n.",
    in: "A single integer n.",
    out: "The number of distinct ways.",
    c: "1 <= n <= 80",
    hints: ["The last move was either one step or two.", "So ways(n) = ways(n-1) + ways(n-2).", "That is the Fibonacci recurrence with different base cases."],
    ap: "Bottom-up dynamic programming over the recurrence ways(n) = ways(n-1) + ways(n-2), collapsed to two rolling variables.",
    it: "Counting by the last move partitions all paths without overlap, which is what makes the recurrence exact.",
    st: ["ways(1) = 1 and ways(2) = 2.", "Iterate upwards keeping the previous two values.", "Print ways(n)."],
    tc: "O(n)", sc: "O(1)",
    solve: (input) => { const n = Number(input.trim()); let a = 1n, b = 2n; if (n === 1) return "1"; if (n === 2) return "2"; for (let i = 3; i <= n; i += 1) { const c = a + b; a = b; b = c; } return b.toString(); },
    samples: ["3", "1"],
    why: ["1+1+1, 1+2 and 2+1.", "There is only one way to climb a single step."],
    hidden: ["2", "10", "45", "80"],
    edge: ["4"],
    companies: ["amazon", "adobe"],
  },
  {
    slug: "subsets-count",
    title: "Count Subsets with a Given Sum",
    difficulty: "EASY",
    topics: ["backtracking", "recursion"],
    d: "Count the subsets of an array whose elements sum to a target. The empty subset counts when the target is zero.",
    in: "First line: n and target.\nSecond line: n integers.",
    out: "The number of subsets summing to the target.",
    c: "1 <= n <= 20\n-1000 <= a[i] <= 1000\n-20000 <= target <= 20000",
    hints: ["n is at most 20, so exhaustive search is fine.", "Each element is either in or out.", "Recurse on include and exclude, adding the counts."],
    ap: "Recursive include/exclude enumeration over all 2^n subsets, counting those that hit the target.",
    it: "With n at most 20 the exponential search space is only about a million states, which is cheap.",
    st: ["Recurse over index i with a running sum.", "At the end of the array, count 1 when the sum equals the target.", "Otherwise recurse both including and excluding a[i]."],
    tc: "O(2^n)", sc: "O(n)",
    solve: (input) => { const r = reader(input); const n = r.int(), target = r.int(); const a = r.ints(n); let count = 0; const go = (i: number, sum: number) => { if (i === n) { if (sum === target) count += 1; return; } go(i + 1, sum); go(i + 1, sum + a[i]); }; go(0, 0); return String(count); },
    samples: ["4 5\n1 2 3 4", "3 0\n1 2 3"],
    why: ["{1,4} and {2,3} both sum to 5.", "Only the empty subset sums to zero."],
    hidden: ["1 1\n1", "5 10\n2 3 5 6 8", "4 0\n0 0 0 0", "3 -3\n-1 -2 -3"],
    edge: ["1 0\n5"],
  },
  {
    slug: "binary-to-decimal",
    title: "Binary to Decimal",
    difficulty: "EASY",
    topics: ["math", "bit-manipulation"],
    d: "Convert a binary string to its decimal value.",
    in: "A single line containing a binary string.",
    out: "The decimal value.",
    c: "1 <= |s| <= 60\nThe string contains only 0 and 1.",
    hints: ["Each position is worth twice the one to its right.", "Process the string left to right.", "value = value * 2 + digit."],
    ap: "Horner's method: fold the digits left to right with value = value*2 + digit.",
    it: "Positional notation is a polynomial in the base, and Horner evaluates it in one pass with no powers.",
    st: ["Set value = 0.", "For each character, double value and add the digit.", "Print value."],
    tc: "O(|s|)", sc: "O(1)",
    solve: (input) => { const s = input.trim(); let value = 0n; for (const ch of s) value = value * 2n + BigInt(ch); return value.toString(); },
    samples: ["1011", "0"],
    why: ["8 + 0 + 2 + 1 = 11.", "Zero is zero in any base."],
    hidden: ["1", "11111111", "100000000000000000000000000000000", "1000"],
    edge: ["10"],
  },
  {
    slug: "decimal-to-binary",
    title: "Decimal to Binary",
    difficulty: "EASY",
    topics: ["math", "bit-manipulation"],
    d: "Convert a non-negative integer to its binary representation without leading zeroes.",
    in: "A single integer n.",
    out: "The binary representation of n.",
    c: "0 <= n <= 10^18",
    hints: ["Repeated division by 2 gives the digits in reverse.", "Collect them and reverse at the end.", "Handle n = 0 as a special case."],
    ap: "Repeatedly take n mod 2 and halve n, collecting the remainders, then reverse them.",
    it: "Division peels binary digits from the least significant end, so the collected order is reversed.",
    st: ["If n is 0 print 0.", "While n > 0 append n mod 2 and halve n.", "Reverse the collected digits and print."],
    tc: "O(log n)", sc: "O(log n)",
    solve: (input) => BigInt(input.trim()).toString(2),
    samples: ["11", "0"],
    why: ["11 is 1011 in binary.", "Zero is a single zero digit."],
    hidden: ["1", "255", "1024", "1000000000000000000"],
    edge: ["2"],
  },
  {
    slug: "sum-of-natural-numbers",
    title: "Sum of the First N Natural Numbers",
    difficulty: "EASY",
    topics: ["math"],
    d: "Compute 1 + 2 + ... + n.",
    in: "A single integer n.",
    out: "The sum.",
    c: "1 <= n <= 10^9",
    hints: ["Looping to 10^9 is too slow.", "There is a closed form for this sum.", "n(n+1)/2, computed with 64-bit arithmetic."],
    ap: "Apply the closed form n(n+1)/2 rather than iterating.",
    it: "Pairing the first and last terms gives n/2 pairs each summing to n+1.",
    st: ["Read n.", "Compute n*(n+1)/2 in 64-bit arithmetic.", "Print the result."],
    tc: "O(1)", sc: "O(1)",
    solve: (input) => { const n = BigInt(input.trim()); return ((n * (n + 1n)) / 2n).toString(); },
    samples: ["10", "1"],
    why: ["10*11/2 = 55.", "The sum of just 1 is 1."],
    hidden: ["2", "100", "1000000", "1000000000"],
    edge: ["3"],
  },
  {
    slug: "pattern-pyramid",
    title: "Print a Star Pyramid",
    difficulty: "EASY",
    topics: ["math"],
    d: "Print a centred pyramid of stars with n rows. Row i (1-indexed) has n-i leading spaces followed by 2i-1 stars.",
    in: "A single integer n.",
    out: "n lines forming the pyramid.",
    c: "1 <= n <= 500",
    hints: ["Work out the two counts as functions of the row index.", "Leading spaces shrink while stars grow.", "Row i has n-i spaces and 2i-1 stars."],
    ap: "For each row emit the computed number of spaces followed by the computed number of stars.",
    it: "Pattern problems reduce to expressing each row's counts as a formula in the row index.",
    st: ["Loop i from 1 to n.", "Print n-i spaces.", "Print 2i-1 stars.", "Move to the next line."],
    tc: "O(n^2)", sc: "O(1)",
    solve: (input) => { const n = Number(input.trim()); const out: string[] = []; for (let i = 1; i <= n; i += 1) out.push(" ".repeat(n - i) + "*".repeat(2 * i - 1)); return linesOut(out); },
    samples: ["3", "1"],
    why: ["Three rows of 1, 3 and 5 stars.", "A single star."],
    hidden: ["2", "5", "7", "4"],
    edge: ["6"],
  },
];

export const EASY_B = specs.map(build);
