import { build, join, linesOut, reader, yesNo, type QuestionSpec } from "./catalog";

const A = (input: string) => {
  const r = reader(input);
  return r.ints(r.int());
};

const MOD = 1000000007n;

const specs: QuestionSpec[] = [
  {
    slug: "median-two-sorted-arrays",
    title: "Median of Two Sorted Arrays",
    difficulty: "HARD",
    topics: ["searching", "arrays"],
    d: "Find the median of two sorted arrays combined. Print it with one decimal place.",
    in: "First line: n and m.\nSecond line: n sorted integers.\nThird line: m sorted integers.",
    out: "The median with one decimal place.",
    c: "1 <= n + m <= 200000\n-10^9 <= values <= 10^9",
    hints: ["Merging is O(n+m); the intended bound is logarithmic.", "Think of partitioning both arrays so the left halves together hold exactly half the elements.", "Binary search the split point in the shorter array."],
    ap: "Binary search the partition of the shorter array. A partition is correct when every element left of the cut is at most every element right of it in both arrays; the median then comes from the boundary values.",
    it: "The median is defined entirely by a balanced partition, so you never need to merge anything.",
    st: ["Binary search the cut in the shorter array.", "Derive the matching cut in the other array.", "Check the four boundary values for the cross condition.", "Combine the boundary values into the median."],
    tc: "O(log min(n, m))", sc: "O(1)",
    solve: (input) => { const r = reader(input); const n = r.int(), m = r.int(); const all = [...r.ints(n), ...r.ints(m)].sort((x, y) => x - y); const k = all.length; const median = k % 2 === 1 ? all[(k - 1) / 2] : (all[k / 2 - 1] + all[k / 2]) / 2; return median.toFixed(1); },
    samples: ["2 1\n1 3\n2", "2 2\n1 2\n3 4"],
    why: ["The merged array is 1 2 3 with median 2.", "The merged array is 1 2 3 4 with median 2.5."],
    hidden: ["1 1\n1\n2", "3 3\n1 2 3\n4 5 6", "1 5\n5\n1 2 3 4 6", "4 4\n1 1 1 1\n1 1 1 1"],
    edge: ["1 1\n-1000000000\n1000000000"],
    companies: ["google", "amazon", "microsoft", "adobe"],
  },
  {
    slug: "merge-k-sorted-lists",
    title: "Merge K Sorted Lists",
    difficulty: "HARD",
    topics: ["heap", "linked-lists"],
    d: "Merge k sorted lists into one sorted sequence.",
    in: "First line: k.\nNext k lines: a list, given as its length followed by that many sorted values.",
    out: "All values in non-decreasing order, or EMPTY.",
    c: "1 <= k <= 10000\nTotal values <= 200000",
    hints: ["Merging pairwise one at a time is O(kN).", "You always need the smallest current head across k lists.", "A min-heap of size k answers that in log k."],
    ap: "Min-heap keyed by the current head of each list. Pop the smallest, emit it, and push that list's next value.",
    it: "The heap replaces a linear scan across k heads with a logarithmic one.",
    st: ["Push the head of every non-empty list into a min-heap.", "Pop the smallest and emit it.", "Push the successor from the same list.", "Repeat until the heap empties."],
    tc: "O(N log k)", sc: "O(k)",
    solve: (input) => { const r = reader(input); const k = r.int(); const all: number[] = []; for (let i = 0; i < k; i += 1) { const len = r.int(); all.push(...r.ints(len)); } all.sort((x, y) => x - y); return all.length ? join(all) : "EMPTY"; },
    samples: ["3\n3 1 4 5\n3 1 3 4\n2 2 6", "2\n0\n0"],
    why: ["All values merged into one sorted run.", "Every list is empty."],
    hidden: ["1\n1 5", "2\n2 1 2\n2 3 4", "3\n1 1\n1 2\n1 3", "2\n3 -1 0 1\n2 -2 5"],
    edge: ["1\n0"],
    companies: ["amazon", "google", "meta", "microsoft"],
  },
  {
    slug: "sliding-window-median",
    title: "Sliding Window Median",
    difficulty: "HARD",
    topics: ["heap", "arrays"],
    d: "For every window of size k, print the median with one decimal place.",
    in: "First line: n and k.\nSecond line: n integers.",
    out: "The n-k+1 medians, space separated, each with one decimal place.",
    c: "1 <= k <= n <= 20000\n-10^9 <= a[i] <= 10^9",
    hints: ["Re-sorting each window is O(nk log k).", "Maintain the window as two halves.", "A max-heap for the lower half and a min-heap for the upper half keep the median at the tops."],
    ap: "Two balanced heaps (a max-heap of the smaller half and a min-heap of the larger half) with lazy deletion for elements leaving the window.",
    it: "Keeping the halves balanced means the median is always at one or both heap roots, never requiring a scan.",
    st: ["Insert into the appropriate heap and rebalance.", "When the window slides, mark the leaving element deleted.", "Purge deleted roots lazily.", "Read the median from the roots."],
    tc: "O(n log k)", sc: "O(k)",
    solve: (input) => { const r = reader(input); const n = r.int(), k = r.int(); const a = r.ints(n); const out: string[] = []; for (let i = 0; i + k <= n; i += 1) { const w = a.slice(i, i + k).sort((x, y) => x - y); const median = k % 2 === 1 ? w[(k - 1) / 2] : (w[k / 2 - 1] + w[k / 2]) / 2; out.push(median.toFixed(1)); } return out.join(" "); },
    samples: ["8 3\n1 3 -1 -3 5 3 6 7", "4 2\n1 2 3 4"],
    why: ["Each window's middle value.", "Even windows average the two middle values."],
    hidden: ["1 1\n5", "5 5\n1 2 3 4 5", "4 1\n4 3 2 1", "6 3\n1 1 1 1 1 1"],
    edge: ["2 2\n-1000000000 1000000000"],
    companies: ["google", "amazon"],
  },
  {
    slug: "find-median-stream",
    title: "Median from a Data Stream",
    difficulty: "HARD",
    topics: ["heap"],
    d: "Process a stream of operations: ADD x inserts a value, MEDIAN prints the current median with one decimal place. MEDIAN on an empty stream prints EMPTY.",
    in: "First line: q.\nNext q lines: one operation each.",
    out: "One line per MEDIAN.",
    c: "1 <= q <= 200000\n-10^9 <= x <= 10^9",
    hints: ["Sorting on every query is far too slow.", "Split the data into a lower and an upper half.", "Keep the halves within one element of each other in size."],
    ap: "Two heaps: a max-heap for the lower half and a min-heap for the upper half, rebalanced after every insertion so the median sits at the roots.",
    it: "You never need the full ordering, only the boundary between the halves.",
    st: ["Insert into the lower heap, then move its root to the upper heap.", "If the upper heap grows larger, move its root back.", "The median is the lower root, or the average of both roots."],
    tc: "O(log n) per operation", sc: "O(n)",
    solve: (input) => { const parts = input.trim().split("\n"); const q = Number(parts[0]); const data: number[] = []; const out: string[] = []; for (let i = 1; i <= q; i += 1) { const [op, value] = (parts[i] ?? "").trim().split(/\s+/); if (op === "ADD") { const v = Number(value); let lo = 0, hi = data.length; while (lo < hi) { const mid = (lo + hi) >> 1; if (data[mid] < v) lo = mid + 1; else hi = mid; } data.splice(lo, 0, v); } else if (op === "MEDIAN") { if (!data.length) out.push("EMPTY"); else { const k = data.length; const median = k % 2 === 1 ? data[(k - 1) / 2] : (data[k / 2 - 1] + data[k / 2]) / 2; out.push(median.toFixed(1)); } } } return linesOut(out); },
    samples: ["5\nADD 1\nADD 2\nMEDIAN\nADD 3\nMEDIAN", "2\nMEDIAN\nADD 1"],
    why: ["Median of {1,2} is 1.5, of {1,2,3} is 2.0.", "The stream is empty at the first query."],
    hidden: ["3\nADD 5\nMEDIAN\nADD 5", "4\nADD -1\nADD 1\nADD 0\nMEDIAN", "2\nADD 7\nMEDIAN", "1\nMEDIAN"],
    edge: ["3\nADD 0\nADD 0\nMEDIAN"],
    companies: ["amazon", "google", "microsoft"],
  },
  {
    slug: "trapping-rain-water-2d",
    title: "Trapping Rain Water in 2D",
    difficulty: "HARD",
    topics: ["heap", "matrix", "graphs"],
    d: "Given a 2D height map, compute how much water it can trap after rain. Water escapes over the border.",
    in: "First line: n and m.\nNext n lines: m non-negative heights.",
    out: "The total trapped water.",
    c: "1 <= n, m <= 200\n0 <= height <= 20000",
    hints: ["The 1D two-pointer trick does not generalise directly.", "Water level at a cell is set by the lowest boundary on any escape path.", "Process cells from the lowest boundary inward with a min-heap."],
    ap: "Priority-queue flood from the border inwards. The current lowest boundary determines the water level; interior cells below it hold water and then join the boundary at that level.",
    it: "Water escapes over the lowest point of the enclosing wall, so processing walls in increasing height order settles each cell exactly once.",
    st: ["Push every border cell into a min-heap and mark it visited.", "Pop the lowest boundary cell.", "For each unvisited neighbour, add max(0, level - height) and push it at max(level, height).", "Repeat until the heap empties."],
    tc: "O(nm log(nm))", sc: "O(nm)",
    solve: (input) => { const r = reader(input); const n = r.int(), m = r.int(); const g: number[][] = []; for (let i = 0; i < n; i += 1) g.push(r.ints(m)); if (n < 3 || m < 3) return "0"; const seen = Array.from({ length: n }, () => new Array(m).fill(false)); const heap: Array<[number, number, number]> = []; const push = (h: number, x: number, y: number) => { heap.push([h, x, y]); heap.sort((a, b) => a[0] - b[0]); }; for (let i = 0; i < n; i += 1) for (let j = 0; j < m; j += 1) if (i === 0 || j === 0 || i === n - 1 || j === m - 1) { seen[i][j] = true; push(g[i][j], i, j); } let total = 0; const dirs = [[1, 0], [-1, 0], [0, 1], [0, -1]]; while (heap.length) { const [h, x, y] = heap.shift()!; for (const [dx, dy] of dirs) { const nx = x + dx, ny = y + dy; if (nx < 0 || ny < 0 || nx >= n || ny >= m || seen[nx][ny]) continue; seen[nx][ny] = true; total += Math.max(0, h - g[nx][ny]); push(Math.max(h, g[nx][ny]), nx, ny); } } return String(total); },
    samples: ["3 6\n1 4 3 1 3 2\n3 2 1 3 2 4\n2 3 3 2 3 1", "3 3\n1 1 1\n1 0 1\n1 1 1"],
    why: ["Four units settle in the interior basin.", "The single low cell holds one unit."],
    hidden: ["1 1\n5", "3 3\n5 5 5\n5 1 5\n5 5 5", "4 4\n9 9 9 9\n9 0 0 9\n9 0 0 9\n9 9 9 9", "2 5\n1 2 3 4 5"],
    edge: ["3 3\n0 0 0\n0 0 0\n0 0 0"],
    companies: ["google", "amazon"],
  },
  {
    slug: "largest-rectangle-binary-matrix",
    title: "Maximal Rectangle in a Binary Matrix",
    difficulty: "HARD",
    topics: ["stack", "matrix", "dp"],
    d: "Find the area of the largest rectangle containing only 1s in a binary matrix.",
    in: "First line: n and m.\nNext n lines: m values, each 0 or 1.",
    out: "The largest rectangle area.",
    c: "1 <= n, m <= 500",
    hints: ["Consider each row as the base of the rectangle.", "The column heights above that row form a histogram.", "Reuse the largest-rectangle-in-a-histogram algorithm per row."],
    ap: "For each row, maintain a histogram of consecutive 1s ending at that row, then apply the monotonic-stack largest-rectangle algorithm.",
    it: "Every maximal rectangle has a bottom row, so scanning rows as bases covers all of them.",
    st: ["Maintain per-column heights, reset to 0 on a 0.", "After each row, run the histogram algorithm.", "Track the global maximum area."],
    tc: "O(nm)", sc: "O(m)",
    solve: (input) => { const r = reader(input); const n = r.int(), m = r.int(); const heights = new Array(m).fill(0); let best = 0; const histogram = (h: number[]) => { const a = [...h, 0]; const stack: number[] = []; let area = 0; for (let i = 0; i < a.length; i += 1) { while (stack.length && a[stack[stack.length - 1]] >= a[i]) { const height = a[stack.pop()!]; const left = stack.length ? stack[stack.length - 1] : -1; area = Math.max(area, height * (i - left - 1)); } stack.push(i); } return area; }; for (let i = 0; i < n; i += 1) { const row = r.ints(m); for (let j = 0; j < m; j += 1) heights[j] = row[j] === 1 ? heights[j] + 1 : 0; best = Math.max(best, histogram(heights)); } return String(best); },
    samples: ["4 5\n1 0 1 0 0\n1 0 1 1 1\n1 1 1 1 1\n1 0 0 1 0", "1 1\n0"],
    why: ["A 2 by 3 block of 1s gives area 6.", "There is no rectangle of 1s."],
    hidden: ["1 1\n1", "2 2\n1 1\n1 1", "3 3\n0 0 0\n0 0 0\n0 0 0", "2 3\n1 1 1\n1 1 1"],
    edge: ["1 3\n1 0 1"],
    companies: ["google", "amazon", "microsoft"],
  },
  {
    slug: "edit-distance-hard-ops",
    title: "Minimum Operations to Convert Strings",
    difficulty: "HARD",
    topics: ["dp", "strings"],
    d: "Given per-operation costs for insertion, deletion and substitution, find the minimum total cost to convert one string into another.",
    in: "Line 1: string a.\nLine 2: string b.\nLine 3: insertCost, deleteCost, replaceCost.",
    out: "The minimum total cost.",
    c: "1 <= |a|, |b| <= 1000\n1 <= costs <= 1000",
    hints: ["This generalises edit distance with weights.", "The recurrence structure is unchanged.", "Only the constants added at each transition differ."],
    ap: "Weighted Levenshtein DP: each transition adds its own operation cost instead of one.",
    it: "Asymmetric costs matter — deleting from one string is not the same as inserting into the other once prices differ.",
    st: ["Initialise the first row with insertion costs and the first column with deletion costs.", "On a character match take the diagonal value.", "Otherwise take the cheapest weighted transition.", "Print the bottom-right cell."],
    tc: "O(|a| * |b|)", sc: "O(min(|a|, |b|))",
    solve: (input) => { const parts = input.trim().split("\n").map((l) => l.trim()); const a = parts[0], b = parts[1]; const [ci, cd, cr] = parts[2].split(/\s+/).map(Number); let prev = Array.from({ length: b.length + 1 }, (_, j) => j * ci); for (let i = 1; i <= a.length; i += 1) { const cur = new Array(b.length + 1).fill(0); cur[0] = i * cd; for (let j = 1; j <= b.length; j += 1) cur[j] = a[i - 1] === b[j - 1] ? prev[j - 1] : Math.min(prev[j] + cd, cur[j - 1] + ci, prev[j - 1] + cr); prev = cur; } return String(prev[b.length]); },
    samples: ["horse\nros\n1 1 1", "abc\nabd\n5 5 1"],
    why: ["Unit costs reproduce ordinary edit distance.", "One cheap substitution beats an insert plus a delete."],
    hidden: ["a\na\n1 1 1", "abc\nabc\n2 3 4", "ab\nba\n1 1 5", "abcd\n\n1 2 3"],
    edge: ["a\nb\n1 1 1000"],
  },
  {
    slug: "regex-matching",
    title: "Regular Expression Matching",
    difficulty: "HARD",
    topics: ["dp", "strings"],
    d: "Implement matching for a pattern where '.' matches any single character and '*' matches zero or more of the preceding element. The match must cover the entire string.",
    in: "Line 1: the text.\nLine 2: the pattern.",
    out: "YES if the pattern matches the whole text, otherwise NO.",
    c: "0 <= |text| <= 1000\n1 <= |pattern| <= 1000",
    hints: ["'*' applies to the character before it, not to the whole pattern.", "A '*' can consume zero characters or one more.", "That branch is the whole recurrence."],
    ap: "Two-dimensional DP over text and pattern prefixes. A '*' either drops its pair entirely or consumes one text character when the preceding pattern element matches.",
    it: "The zero-occurrence branch is what most naive implementations forget, and it is exactly what makes patterns like 'a*' match the empty string.",
    st: ["dp[0][0] is true.", "Handle patterns like 'a*b*' matching an empty text.", "On '*' take dp[i][j-2] or (match and dp[i-1][j]).", "Otherwise require a character match and take dp[i-1][j-1]."],
    tc: "O(|text| * |pattern|)", sc: "O(|text| * |pattern|)",
    solve: (input) => { const parts = input.split("\n"); const s = (parts[0] ?? "").trim(); const p = (parts[1] ?? "").trim(); const n = s.length, m = p.length; const dp = Array.from({ length: n + 1 }, () => new Array(m + 1).fill(false)); dp[0][0] = true; for (let j = 1; j <= m; j += 1) if (p[j - 1] === "*" && j >= 2) dp[0][j] = dp[0][j - 2]; for (let i = 1; i <= n; i += 1) for (let j = 1; j <= m; j += 1) { if (p[j - 1] === "*") { if (j >= 2) { dp[i][j] = dp[i][j - 2]; if (p[j - 2] === "." || p[j - 2] === s[i - 1]) dp[i][j] = dp[i][j] || dp[i - 1][j]; } } else if (p[j - 1] === "." || p[j - 1] === s[i - 1]) dp[i][j] = dp[i - 1][j - 1]; } return yesNo(dp[n][m]); },
    samples: ["aab\nc*a*b", "mississippi\nmis*is*p*."],
    why: ["'c*' matches zero c's and 'a*' matches two a's.", "The pattern cannot cover the whole string."],
    hidden: ["aa\na", "aa\na*", "ab\n.*", "abc\nabc"],
    edge: ["a\n.*"],
    companies: ["google", "meta", "amazon"],
  },
  {
    slug: "wildcard-matching",
    title: "Wildcard Matching",
    difficulty: "HARD",
    topics: ["dp", "greedy", "strings"],
    d: "Implement wildcard matching where '?' matches any single character and '*' matches any sequence including the empty one. The match must cover the entire string.",
    in: "Line 1: the text.\nLine 2: the pattern.",
    out: "YES if the pattern matches the whole text, otherwise NO.",
    c: "0 <= |text| <= 2000\n1 <= |pattern| <= 2000",
    hints: ["'*' here is independent of the preceding character, unlike regex.", "A '*' can absorb any number of characters.", "Either DP over prefixes, or a greedy two-pointer with backtracking."],
    ap: "Prefix DP where '*' either matches nothing or extends over one more character. A greedy two-pointer that remembers the last '*' achieves the same in linear time.",
    it: "Because '*' is unconstrained, backtracking only ever needs to revisit the most recent one.",
    st: ["dp[0][0] is true; leading '*'s match the empty text.", "On '*' take dp[i][j-1] or dp[i-1][j].", "On '?' or a matching character take dp[i-1][j-1].", "Return dp[n][m]."],
    tc: "O(|text| * |pattern|)", sc: "O(|pattern|)",
    solve: (input) => { const parts = input.split("\n"); const s = (parts[0] ?? "").trim(); const p = (parts[1] ?? "").trim(); const n = s.length, m = p.length; let prev = new Array(m + 1).fill(false); prev[0] = true; for (let j = 1; j <= m; j += 1) prev[j] = prev[j - 1] && p[j - 1] === "*"; for (let i = 1; i <= n; i += 1) { const cur = new Array(m + 1).fill(false); for (let j = 1; j <= m; j += 1) { if (p[j - 1] === "*") cur[j] = cur[j - 1] || prev[j]; else if (p[j - 1] === "?" || p[j - 1] === s[i - 1]) cur[j] = prev[j - 1]; } prev = cur; } return yesNo(prev[m]); },
    samples: ["adceb\n*a*b", "acdcb\na*c?b"],
    why: ["The stars absorb the surrounding characters.", "The pattern cannot align with the text."],
    hidden: ["aa\na", "aa\n*", "cb\n?a", "abc\na*c"],
    edge: ["a\n*"],
    companies: ["google", "amazon", "microsoft"],
  },
  {
    slug: "distinct-subsequences-count",
    title: "Distinct Subsequences",
    difficulty: "HARD",
    topics: ["dp", "strings"],
    d: "Count the distinct subsequences of s that equal t, modulo 1000000007.",
    in: "Line 1: string s.\nLine 2: string t.",
    out: "The count modulo 1000000007.",
    c: "1 <= |s|, |t| <= 1000",
    hints: ["Each character of s is either used or skipped.", "Skipping always carries the previous count forward.", "Using it only helps when the characters match."],
    ap: "Prefix DP where dp[i][j] counts ways to form t's first j characters from s's first i, adding the diagonal term only on a character match.",
    it: "Counting subsequences differs from matching them: you sum over choices rather than taking a maximum.",
    st: ["dp[i][0] is 1 for all i, since the empty target is always formed once.", "On a mismatch carry dp[i-1][j] forward.", "On a match add dp[i-1][j-1] as well.", "Print dp[|s|][|t|]."],
    tc: "O(|s| * |t|)", sc: "O(|t|)",
    solve: (input) => { const parts = input.trim().split("\n").map((l) => l.trim()); const s = parts[0], t = parts[1] ?? ""; const dp = new Array(t.length + 1).fill(0n); dp[0] = 1n; for (let i = 1; i <= s.length; i += 1) for (let j = t.length; j >= 1; j -= 1) if (s[i - 1] === t[j - 1]) dp[j] = (dp[j] + dp[j - 1]) % MOD; return dp[t.length].toString(); },
    samples: ["rabbbit\nrabbit", "babgbag\nbag"],
    why: ["Three distinct ways to pick 'rabbit'.", "Five distinct ways to pick 'bag'."],
    hidden: ["a\na", "aaa\na", "abc\nd", "aaaa\naa"],
    edge: ["a\nb"],
  },
  {
    slug: "burst-balloons",
    title: "Burst Balloons",
    difficulty: "HARD",
    topics: ["dp"],
    d: "Bursting balloon i earns left * i * right, where left and right are the nearest unburst neighbours. Maximise the total earned by bursting all balloons.",
    in: "First line: n.\nSecond line: n positive integers.",
    out: "The maximum total.",
    c: "1 <= n <= 300\n1 <= a[i] <= 100",
    hints: ["Thinking about which balloon to burst first leads nowhere.", "Think about which balloon is burst last in a range.", "That choice splits the range into two independent subproblems."],
    ap: "Interval DP over ranges, choosing which balloon in the range is burst last. That balloon's neighbours are the range boundaries, making the two sides independent.",
    it: "Reversing the question from first to last is what decouples the subproblems.",
    st: ["Pad the array with 1 at both ends.", "For each interval length, try every last-burst position.", "Combine the two sub-intervals plus the boundary product.", "Answer is the full range."],
    tc: "O(n^3)", sc: "O(n^2)",
    solve: (input) => { const a = [1, ...A(input), 1]; const n = a.length; const dp = Array.from({ length: n }, () => new Array(n).fill(0)); for (let len = 2; len < n; len += 1) for (let lo = 0; lo + len < n; lo += 1) { const hi = lo + len; for (let k = lo + 1; k < hi; k += 1) dp[lo][hi] = Math.max(dp[lo][hi], dp[lo][k] + dp[k][hi] + a[lo] * a[k] * a[hi]); } return String(dp[0][n - 1]); },
    samples: ["4\n3 1 5 8", "1\n5"],
    why: ["Bursting in the right order earns 167.", "A single balloon earns 5."],
    hidden: ["2\n1 5", "3\n1 1 1", "3\n5 5 5", "5\n1 2 3 4 5"],
    edge: ["2\n1 1"],
    companies: ["google", "amazon"],
  },
  {
    slug: "matrix-chain-multiplication",
    title: "Matrix Chain Multiplication",
    difficulty: "HARD",
    topics: ["dp"],
    d: "Given the dimensions of a chain of matrices, find the minimum number of scalar multiplications needed to multiply them all.",
    in: "First line: n, the number of matrices.\nSecond line: n+1 dimensions, where matrix i is dims[i] by dims[i+1].",
    out: "The minimum scalar multiplication count.",
    c: "1 <= n <= 200\n1 <= dimension <= 500",
    hints: ["Matrix multiplication is associative but the cost is not.", "Choose where to place the outermost split.", "Every split gives two independent subchains."],
    ap: "Interval DP over subchains, trying every split point and combining the two costs with the product of the three boundary dimensions.",
    it: "The last multiplication performed determines the split, which makes the subproblems independent.",
    st: ["For each chain length, consider every starting index.", "Try every split point inside the chain.", "Take the minimum of left + right + boundary product.", "Answer is the whole chain."],
    tc: "O(n^3)", sc: "O(n^2)",
    solve: (input) => { const r = reader(input); const n = r.int(); const d = r.ints(n + 1); const dp = Array.from({ length: n + 1 }, () => new Array(n + 1).fill(0)); for (let len = 2; len <= n; len += 1) for (let i = 1; i + len - 1 <= n; i += 1) { const j = i + len - 1; dp[i][j] = Infinity; for (let k = i; k < j; k += 1) dp[i][j] = Math.min(dp[i][j], dp[i][k] + dp[k + 1][j] + d[i - 1] * d[k] * d[j]); } return String(dp[1][n]); },
    samples: ["3\n10 30 5 60", "1\n5 10"],
    why: ["Multiplying the first two first costs 4500.", "A single matrix needs no multiplication."],
    hidden: ["2\n10 20 30", "4\n40 20 30 10 30", "3\n1 2 3 4", "5\n5 10 3 12 5 50"],
    edge: ["2\n1 1 1"],
  },
  {
    slug: "palindrome-partitioning-min-cuts",
    title: "Palindrome Partitioning II",
    difficulty: "HARD",
    topics: ["dp", "strings"],
    d: "Find the minimum number of cuts needed so that every piece of the string is a palindrome.",
    in: "A single line containing a string.",
    out: "The minimum number of cuts.",
    c: "1 <= |s| <= 2000",
    hints: ["Two DPs are involved: palindromicity and cut count.", "Precompute which substrings are palindromes.", "Then cuts[i] = 1 + min over palindromic suffixes ending at i."],
    ap: "Precompute a palindrome table by expanding around centres, then a linear DP over prefixes taking the best palindromic suffix.",
    it: "Separating the two questions keeps the total at O(n^2) instead of O(n^3).",
    st: ["Mark all palindromic substrings.", "Set cuts[0] = -1.", "For each i, minimise over j where s[j..i] is a palindrome.", "Print cuts[n]."],
    tc: "O(n^2)", sc: "O(n^2)",
    solve: (input) => { const s = input.trim(); const n = s.length; const pal = Array.from({ length: n }, () => new Array(n).fill(false)); for (let i = n - 1; i >= 0; i -= 1) for (let j = i; j < n; j += 1) if (s[i] === s[j] && (j - i < 2 || pal[i + 1][j - 1])) pal[i][j] = true; const cuts = new Array(n + 1).fill(0); cuts[0] = -1; for (let i = 1; i <= n; i += 1) { cuts[i] = Infinity; for (let j = 0; j < i; j += 1) if (pal[j][i - 1]) cuts[i] = Math.min(cuts[i], cuts[j] + 1); } return String(cuts[n]); },
    samples: ["aab", "a"],
    why: ["One cut gives 'aa' and 'b'.", "A single character needs no cut."],
    hidden: ["ab", "abcba", "aaaa", "abcd"],
    edge: ["aa"],
    companies: ["google", "amazon"],
  },
  {
    slug: "word-break-count-ways",
    title: "Word Break Combinations",
    difficulty: "HARD",
    topics: ["dp", "strings"],
    d: "Count the ways to segment a string into dictionary words, modulo 1000000007. Words may be reused.",
    in: "Line 1: the string.\nLine 2: k.\nLine 3: k space-separated dictionary words.",
    out: "The number of segmentations modulo 1000000007.",
    c: "1 <= |s| <= 2000\n1 <= k <= 1000",
    hints: ["This is the counting version of word break.", "Replace the boolean OR with a sum.", "Every split point that ends on a dictionary word contributes."],
    ap: "Prefix DP summing over every split point whose trailing segment is a dictionary word.",
    it: "Switching from feasibility to counting changes only the combining operator.",
    st: ["Set ways[0] = 1.", "For each i, sum ways[j] over all j where s[j..i) is in the dictionary.", "Reduce modulo 1000000007.", "Print ways[|s|]."],
    tc: "O(n^2)", sc: "O(n)",
    solve: (input) => { const parts = input.trim().split("\n").map((l) => l.trim()); const s = parts[0]; const k = Number(parts[1]); const dict = new Set((parts[2] ?? "").split(/\s+/).slice(0, k)); const ways = new Array(s.length + 1).fill(0n); ways[0] = 1n; for (let i = 1; i <= s.length; i += 1) for (let j = 0; j < i; j += 1) if (dict.has(s.slice(j, i))) ways[i] = (ways[i] + ways[j]) % MOD; return ways[s.length].toString(); },
    samples: ["catsanddog\n5\ncat cats and sand dog", "aaa\n2\na aa"],
    why: ["Two segmentations exist.", "Several combinations of 'a' and 'aa' cover the string."],
    hidden: ["a\n1\na", "abc\n2\na b", "aaaa\n1\na", "abcd\n2\nab cd"],
    edge: ["a\n1\nb"],
  },
  {
    slug: "longest-valid-parentheses",
    title: "Longest Valid Parentheses",
    difficulty: "HARD",
    topics: ["stack", "dp", "strings"],
    d: "Find the length of the longest well-formed substring of round brackets.",
    in: "A single line of round brackets.",
    out: "The length of the longest valid substring.",
    c: "0 <= |s| <= 100000",
    hints: ["Counting balance alone is not enough — you need positions.", "Push indices onto a stack rather than characters.", "Keep a sentinel index for the last unmatched closing bracket."],
    ap: "Stack of indices seeded with -1. On a closing bracket, pop; the distance to the new stack top is the length of the valid run ending here.",
    it: "The sentinel encodes 'where the current valid run could start', which is what turns balance counting into length measurement.",
    st: ["Push -1 as a base.", "Push the index of every '('.", "On ')' pop; if the stack empties push this index, otherwise update the best with i minus the new top.", "Print the best."],
    tc: "O(n)", sc: "O(n)",
    solve: (input) => { const s = input.replace(/\r?\n/g, "").trim(); const stack: number[] = [-1]; let best = 0; for (let i = 0; i < s.length; i += 1) { if (s[i] === "(") stack.push(i); else { stack.pop(); if (!stack.length) stack.push(i); else best = Math.max(best, i - stack[stack.length - 1]); } } return String(best); },
    samples: [")()())", "(()"],
    why: ["'()()' has length 4.", "'()' has length 2."],
    hidden: ["(", "()", "()(()", "((((("],
    edge: [")("],
    companies: ["google", "amazon", "meta"],
  },
  {
    slug: "basic-calculator",
    title: "Basic Calculator",
    difficulty: "HARD",
    topics: ["stack", "strings"],
    d: "Evaluate an arithmetic expression containing non-negative integers, +, -, and parentheses.",
    in: "A single line containing the expression, possibly with spaces.",
    out: "The value of the expression.",
    c: "1 <= |s| <= 100000\nThe expression is valid.",
    hints: ["Parentheses can flip the sign of everything inside.", "Track the current sign as you scan.", "Push the accumulated result and sign when a '(' is seen."],
    ap: "Single pass keeping a running result and sign. On '(' push the current state and reset; on ')' fold the inner result back with the saved sign.",
    it: "With only + and -, the sign is the entire state that parentheses affect.",
    st: ["Accumulate digits into a number.", "Apply the current sign when an operator or bracket ends the number.", "On '(' push the result and sign, then reset.", "On ')' pop and combine."],
    tc: "O(n)", sc: "O(n)",
    solve: (input) => { const s = input.replace(/\r?\n/g, ""); let result = 0, sign = 1, i = 0; const stack: number[] = []; while (i < s.length) { const ch = s[i]; if (ch >= "0" && ch <= "9") { let num = 0; while (i < s.length && s[i] >= "0" && s[i] <= "9") { num = num * 10 + Number(s[i]); i += 1; } result += sign * num; continue; } if (ch === "+") sign = 1; else if (ch === "-") sign = -1; else if (ch === "(") { stack.push(result, sign); result = 0; sign = 1; } else if (ch === ")") { const prevSign = stack.pop()!; const prevResult = stack.pop()!; result = prevResult + prevSign * result; } i += 1; } return String(result); },
    samples: ["(1+(4+5+2)-3)+(6+8)", "1 + 1"],
    why: ["The nested groups evaluate to 23.", "Simple addition."],
    hidden: ["0", "2-1+2", "(1)", "-(3+2)"],
    edge: ["1"],
    companies: ["google", "amazon", "microsoft"],
  },
  {
    slug: "expression-add-operators",
    title: "Expression Add Operators",
    difficulty: "HARD",
    topics: ["backtracking", "strings"],
    d: "Insert +, - or * between the digits of a string (or join digits into a multi-digit number) so the expression evaluates to a target. Count the distinct expressions. Numbers may not have leading zeroes.",
    in: "Line 1: a digit string.\nLine 2: the target.",
    out: "The number of valid expressions.",
    c: "1 <= |s| <= 10\n-10^9 <= target <= 10^9",
    hints: ["Multiplication breaks simple left-to-right evaluation.", "Carry the value of the last operand alongside the running total.", "To apply '*', undo the last addition and reapply it multiplied."],
    ap: "Backtracking over split points and operators, carrying both the running total and the last operand so multiplication can be applied with correct precedence.",
    it: "Tracking the previous operand is exactly what encodes precedence without building a parse tree.",
    st: ["Choose the next operand, rejecting leading zeroes.", "For '+' and '-' extend the total directly.", "For '*' subtract the previous operand and add previous * current.", "Count when the whole string is consumed and the total matches."],
    tc: "O(4^n)", sc: "O(n)",
    solve: (input) => { const parts = input.trim().split("\n").map((l) => l.trim()); const s = parts[0]; const target = BigInt(parts[1]); let count = 0; const go = (pos: number, total: bigint, prev: bigint) => { if (pos === s.length) { if (total === target) count += 1; return; } for (let len = 1; pos + len <= s.length; len += 1) { const part = s.slice(pos, pos + len); if (part.length > 1 && part[0] === "0") break; const value = BigInt(part); if (pos === 0) go(pos + len, value, value); else { go(pos + len, total + value, value); go(pos + len, total - value, -value); go(pos + len, total - prev + prev * value, prev * value); } } }; go(0, 0n, 0n); return String(count); },
    samples: ["123\n6", "232\n8"],
    why: ["1+2+3 and 1*2*3 both give 6.", "2*3+2 and 2+3*2 both give 8."],
    hidden: ["105\n5", "00\n0", "3456237490\n9191", "1\n1"],
    edge: ["1\n2"],
    companies: ["meta", "google"],
  },
  {
    slug: "n-queens-print",
    title: "N-Queens Solutions",
    difficulty: "HARD",
    topics: ["backtracking"],
    d: "Print every solution to the n-queens problem as the column index of the queen in each row, one solution per line, in lexicographic order. Print NONE if there are no solutions.",
    in: "A single integer n.",
    out: "One solution per line, or NONE.",
    c: "1 <= n <= 9",
    hints: ["Place queens row by row so rows never conflict.", "Track attacked columns and both diagonals.", "Trying columns in increasing order yields lexicographic output."],
    ap: "Row-by-row backtracking with column and diagonal occupancy sets, trying columns in increasing order so solutions emerge sorted.",
    it: "Generating in sorted order removes the need for any final sort.",
    st: ["For each row, try columns 0..n-1.", "Skip columns attacked by a column or diagonal.", "Recurse into the next row.", "Emit the placement when all rows are filled."],
    tc: "O(n!) with pruning", sc: "O(n)",
    solve: (input) => { const n = Number(input.trim()); const cols = new Set<number>(), d1 = new Set<number>(), d2 = new Set<number>(); const cur: number[] = []; const out: string[] = []; const go = (row: number) => { if (row === n) { out.push(join(cur)); return; } for (let c = 0; c < n; c += 1) { if (cols.has(c) || d1.has(row - c) || d2.has(row + c)) continue; cols.add(c); d1.add(row - c); d2.add(row + c); cur.push(c); go(row + 1); cur.pop(); cols.delete(c); d1.delete(row - c); d2.delete(row + c); } }; go(0); return out.length ? linesOut(out) : "NONE"; },
    samples: ["4", "2"],
    why: ["Two solutions exist for a 4x4 board.", "No arrangement works on a 2x2 board."],
    hidden: ["1", "3", "5", "6"],
    edge: ["7"],
    companies: ["amazon", "google"],
  },
  {
    slug: "sudoku-solver-check",
    title: "Sudoku Validity",
    difficulty: "HARD",
    topics: ["backtracking", "matrix"],
    d: "Decide whether a partially filled 9 by 9 Sudoku grid can be completed. Empty cells are 0.",
    in: "Nine lines of nine digits each, using 0 for empty cells.",
    out: "YES if the grid can be completed, otherwise NO.",
    c: "The grid is 9 by 9 and the digits are 0 to 9.",
    hints: ["First check that the given digits do not already conflict.", "Then try filling the empties by backtracking.", "Choosing the most constrained cell first prunes heavily."],
    ap: "Backtracking with row, column and box occupancy bitmasks, filling empty cells and undoing on failure.",
    it: "Constraint propagation via bitmasks makes each placement test O(1) rather than a scan.",
    st: ["Record the digits present in each row, column and 3x3 box.", "Reject immediately on a duplicate.", "Fill the next empty cell with each legal digit and recurse.", "Undo the placement on failure."],
    tc: "Exponential in the worst case, fast in practice", sc: "O(1)",
    solve: (input) => { const rows = input.trim().split("\n").map((l) => l.trim()); const g: number[][] = rows.slice(0, 9).map((line) => line.split("").map(Number)); const rowMask = new Array(9).fill(0), colMask = new Array(9).fill(0), boxMask = new Array(9).fill(0); const boxOf = (i: number, j: number) => Math.floor(i / 3) * 3 + Math.floor(j / 3); for (let i = 0; i < 9; i += 1) for (let j = 0; j < 9; j += 1) { const v = g[i][j]; if (!v) continue; const bit = 1 << v; if (rowMask[i] & bit || colMask[j] & bit || boxMask[boxOf(i, j)] & bit) return "NO"; rowMask[i] |= bit; colMask[j] |= bit; boxMask[boxOf(i, j)] |= bit; } const cells: Array<[number, number]> = []; for (let i = 0; i < 9; i += 1) for (let j = 0; j < 9; j += 1) if (!g[i][j]) cells.push([i, j]); const go = (k: number): boolean => { if (k === cells.length) return true; const [i, j] = cells[k]; const b = boxOf(i, j); for (let v = 1; v <= 9; v += 1) { const bit = 1 << v; if (rowMask[i] & bit || colMask[j] & bit || boxMask[b] & bit) continue; rowMask[i] |= bit; colMask[j] |= bit; boxMask[b] |= bit; if (go(k + 1)) { rowMask[i] ^= bit; colMask[j] ^= bit; boxMask[b] ^= bit; return true; } rowMask[i] ^= bit; colMask[j] ^= bit; boxMask[b] ^= bit; } return false; }; return yesNo(go(0)); },
    samples: [
      "530070000\n600195000\n098000060\n800060003\n400803001\n700020006\n060000280\n000419005\n000080079",
      "110000000\n000000000\n000000000\n000000000\n000000000\n000000000\n000000000\n000000000\n000000000",
    ],
    why: ["This classic puzzle has a solution.", "Two 1s in the same row make it invalid."],
    hidden: [
      "000000000\n000000000\n000000000\n000000000\n000000000\n000000000\n000000000\n000000000\n000000000",
      "123456789\n000000000\n000000000\n000000000\n000000000\n000000000\n000000000\n000000000\n000000000",
      "100000000\n000000000\n000000000\n000000000\n000000000\n000000000\n000000000\n000000000\n000000001",
      "111111111\n000000000\n000000000\n000000000\n000000000\n000000000\n000000000\n000000000\n000000000",
    ],
    edge: ["100000000\n100000000\n000000000\n000000000\n000000000\n000000000\n000000000\n000000000\n000000000"],
    companies: ["google", "amazon", "microsoft"],
  },
  {
    slug: "word-ladder-length",
    title: "Word Ladder",
    difficulty: "HARD",
    topics: ["graphs", "strings"],
    d: "Transform a start word into an end word by changing one letter at a time, where every intermediate word must be in the dictionary. Print the number of words in the shortest sequence, or 0 if impossible.",
    in: "Line 1: start and end.\nLine 2: k.\nLine 3: k space-separated dictionary words.",
    out: "The length of the shortest transformation sequence, or 0.",
    c: "1 <= k <= 5000\nAll words have the same length, at most 10.",
    hints: ["Words are vertices and single-letter changes are edges.", "Every edge costs the same, so BFS finds the shortest path.", "Generate neighbours by wildcarding each position rather than comparing all pairs."],
    ap: "BFS over the implicit word graph, generating neighbours by substituting each position with every letter and testing dictionary membership.",
    it: "Generating neighbours from the word rather than comparing all pairs turns O(k^2) into O(k * L * 26).",
    st: ["Put the dictionary in a hash set.", "BFS from the start word with distance 1.", "For each word, try every single-letter substitution.", "Return the distance on reaching the end word."],
    tc: "O(k * L * 26)", sc: "O(k * L)",
    solve: (input) => { const parts = input.trim().split("\n").map((l) => l.trim()); const [start, end] = parts[0].split(/\s+/); const k = Number(parts[1]); const dict = new Set((parts[2] ?? "").split(/\s+/).slice(0, k)); if (!dict.has(end)) return "0"; const queue: Array<[string, number]> = [[start, 1]]; const seen = new Set([start]); const letters = "abcdefghijklmnopqrstuvwxyz"; for (let head = 0; head < queue.length; head += 1) { const [word, dist] = queue[head]; if (word === end) return String(dist); for (let i = 0; i < word.length; i += 1) for (const ch of letters) { if (ch === word[i]) continue; const next = word.slice(0, i) + ch + word.slice(i + 1); if (dict.has(next) && !seen.has(next)) { seen.add(next); queue.push([next, dist + 1]); } } } return "0"; },
    samples: ["hit cog\n6\nhot dot dog lot log cog", "hit cog\n5\nhot dot dog lot log"],
    why: ["hit-hot-dot-dog-cog has five words.", "'cog' is not in the dictionary."],
    hidden: ["a c\n2\nb c", "ab ab\n1\nab", "abc abc\n1\nabc", "aa bb\n2\nab bb"],
    edge: ["ab cd\n1\nab"],
    companies: ["amazon", "google", "meta"],
  },
  {
    slug: "alien-dictionary-order",
    title: "Alien Dictionary",
    difficulty: "HARD",
    topics: ["graphs", "strings"],
    d: "Given words sorted by an unknown alphabet, deduce a valid letter order. Print IMPOSSIBLE if the input is contradictory. Break ties by preferring the smaller ordinary letter.",
    in: "First line: n.\nNext n lines: one word each.",
    out: "A valid letter order as a string, or IMPOSSIBLE.",
    c: "1 <= n <= 1000\nWords contain lowercase letters only.",
    hints: ["Each adjacent pair of words reveals at most one ordering constraint.", "The first differing character gives that constraint.", "Then it is a topological sort over the letters."],
    ap: "Build a precedence graph from the first differing character of each adjacent word pair, then topologically sort it, preferring smaller letters on ties.",
    it: "A prefix word appearing after its extension is contradictory, which is the case most implementations miss.",
    st: ["For each adjacent pair find the first differing character.", "Add an edge from the earlier letter to the later one.", "Detect the invalid prefix case.", "Topologically sort with a min-heap."],
    tc: "O(total characters + 26^2)", sc: "O(26^2)",
    solve: (input) => { const parts = input.trim().split("\n").map((l) => l.trim()); const n = Number(parts[0]); const words = parts.slice(1, 1 + n); const letters = new Set<string>(); for (const w of words) for (const ch of w) letters.add(ch); const adj = new Map<string, Set<string>>(); const indeg = new Map<string, number>(); for (const ch of letters) { adj.set(ch, new Set()); indeg.set(ch, 0); } for (let i = 0; i + 1 < words.length; i += 1) { const a = words[i], b = words[i + 1]; let found = false; for (let j = 0; j < Math.min(a.length, b.length); j += 1) { if (a[j] !== b[j]) { if (!adj.get(a[j])!.has(b[j])) { adj.get(a[j])!.add(b[j]); indeg.set(b[j], indeg.get(b[j])! + 1); } found = true; break; } } if (!found && a.length > b.length) return "IMPOSSIBLE"; } const available = [...letters].filter((ch) => indeg.get(ch) === 0).sort(); const out: string[] = []; while (available.length) { available.sort(); const ch = available.shift()!; out.push(ch); for (const next of adj.get(ch)!) { indeg.set(next, indeg.get(next)! - 1); if (indeg.get(next) === 0) available.push(next); } } return out.length === letters.size ? out.join("") : "IMPOSSIBLE"; },
    samples: ["5\nwrt\nwrf\ner\nett\nrftt", "2\nabc\nab"],
    why: ["The constraints force w before e before r before t before f.", "A word cannot precede its own prefix."],
    hidden: ["1\nz", "2\nz\nx", "3\nz\nx\nz", "2\nab\nac"],
    edge: ["2\na\nb"],
    companies: ["google", "amazon", "meta"],
  },
  {
    slug: "critical-connections-bridges",
    title: "Critical Connections",
    difficulty: "HARD",
    topics: ["graphs", "advanced"],
    d: "Find all bridges of an undirected graph, that is edges whose removal increases the number of connected components. Print them sorted, one per line, with the smaller endpoint first.",
    in: "First line: n and m.\nNext m lines: an edge u v.",
    out: "One bridge per line, or NONE.",
    c: "1 <= n <= 100000\n0 <= m <= 200000",
    hints: ["Removing each edge and retesting connectivity is O(m(n+m)).", "During DFS, track the earliest reachable ancestor from each subtree.", "An edge is a bridge when the child cannot reach above its parent."],
    ap: "Tarjan's bridge algorithm: DFS assigning discovery times and low-link values; edge (u,v) is a bridge when low[v] exceeds the discovery time of u.",
    it: "The low-link value summarises whether a back edge bypasses the tree edge, which is exactly the bridge condition.",
    st: ["Run DFS assigning discovery times.", "Compute low as the minimum over children and back edges.", "Report an edge as a bridge when low[child] > disc[parent].", "Skip the edge back to the parent."],
    tc: "O(n + m)", sc: "O(n + m)",
    solve: (input) => { const r = reader(input); const n = r.int(), m = r.int(); const adj: Array<Array<[number, number]>> = Array.from({ length: n }, () => []); for (let i = 0; i < m; i += 1) { const u = r.int(), v = r.int(); adj[u].push([v, i]); adj[v].push([u, i]); } const disc = new Array(n).fill(-1), low = new Array(n).fill(0); let timer = 0; const bridges: Array<[number, number]> = []; const dfs = (u: number, parentEdge: number) => { disc[u] = low[u] = timer++; for (const [v, id] of adj[u]) { if (id === parentEdge) continue; if (disc[v] === -1) { dfs(v, id); low[u] = Math.min(low[u], low[v]); if (low[v] > disc[u]) bridges.push([Math.min(u, v), Math.max(u, v)]); } else low[u] = Math.min(low[u], disc[v]); } }; for (let i = 0; i < n; i += 1) if (disc[i] === -1) dfs(i, -1); bridges.sort((a, b) => a[0] - b[0] || a[1] - b[1]); return bridges.length ? linesOut(bridges.map(([u, v]) => `${u} ${v}`)) : "NONE"; },
    samples: ["4 4\n0 1\n1 2\n2 0\n1 3", "3 3\n0 1\n1 2\n2 0"],
    why: ["Only edge 1-3 is a bridge; the triangle has none.", "Every edge lies on a cycle."],
    hidden: ["1 0", "2 1\n0 1", "4 3\n0 1\n1 2\n2 3", "5 4\n0 1\n1 2\n3 4\n2 3"],
    edge: ["2 0"],
    companies: ["amazon", "google"],
  },
  {
    slug: "strongly-connected-components",
    title: "Strongly Connected Components",
    difficulty: "HARD",
    topics: ["graphs", "advanced"],
    d: "Count the strongly connected components of a directed graph.",
    in: "First line: n and m.\nNext m lines: a directed edge u v.",
    out: "The number of strongly connected components.",
    c: "1 <= n <= 100000\n0 <= m <= 200000",
    hints: ["Undirected connectivity is not the same as strong connectivity.", "Order vertices by DFS finishing time.", "Then run DFS on the reversed graph in that order."],
    ap: "Kosaraju's algorithm: one DFS to order vertices by finishing time, then DFS the transpose graph in reverse finishing order, each traversal covering one component.",
    it: "Reversing the edges preserves components but breaks the paths between them, which is what isolates each one.",
    st: ["Run DFS on the original graph pushing vertices on finish.", "Build the transpose graph.", "Pop vertices in reverse finishing order.", "Each traversal on the transpose marks one component."],
    tc: "O(n + m)", sc: "O(n + m)",
    solve: (input) => { const r = reader(input); const n = r.int(), m = r.int(); const adj: number[][] = Array.from({ length: n }, () => []); const rev: number[][] = Array.from({ length: n }, () => []); for (let i = 0; i < m; i += 1) { const u = r.int(), v = r.int(); adj[u].push(v); rev[v].push(u); } const seen = new Uint8Array(n); const order: number[] = []; const dfs1 = (start: number) => { const stack: Array<[number, number]> = [[start, 0]]; seen[start] = 1; while (stack.length) { const top = stack[stack.length - 1]; if (top[1] < adj[top[0]].length) { const v = adj[top[0]][top[1]++]; if (!seen[v]) { seen[v] = 1; stack.push([v, 0]); } } else { order.push(top[0]); stack.pop(); } } }; for (let i = 0; i < n; i += 1) if (!seen[i]) dfs1(i); const seen2 = new Uint8Array(n); let count = 0; for (let i = order.length - 1; i >= 0; i -= 1) { const s = order[i]; if (seen2[s]) continue; count += 1; const stack = [s]; seen2[s] = 1; while (stack.length) { const u = stack.pop()!; for (const v of rev[u]) if (!seen2[v]) { seen2[v] = 1; stack.push(v); } } } return String(count); },
    samples: ["5 5\n0 1\n1 2\n2 0\n1 3\n3 4", "3 3\n0 1\n1 2\n2 0"],
    why: ["{0,1,2}, {3} and {4}.", "All three vertices reach each other."],
    hidden: ["1 0", "2 1\n0 1", "4 4\n0 1\n1 0\n2 3\n3 2", "3 2\n0 1\n1 2"],
    edge: ["2 2\n0 1\n1 0"],
    companies: ["google", "amazon"],
  },
  {
    slug: "shortest-path-negative-weights",
    title: "Shortest Path with Negative Edges",
    difficulty: "HARD",
    topics: ["graphs", "dp"],
    d: "Find shortest distances from vertex 0 in a directed graph that may contain negative edge weights. Print NEGATIVE CYCLE if a reachable negative cycle exists, and -1 for unreachable vertices.",
    in: "First line: n and m.\nNext m lines: u, v and w.",
    out: "n distances, space separated, or NEGATIVE CYCLE.",
    c: "1 <= n <= 2000\n0 <= m <= 10000\n-10^6 <= w <= 10^6",
    hints: ["Dijkstra's greedy choice is invalid with negative weights.", "Relax every edge repeatedly instead.", "After n-1 rounds, any further improvement means a negative cycle."],
    ap: "Bellman-Ford: relax all edges n-1 times, then run one more pass to detect a negative cycle.",
    it: "A shortest path uses at most n-1 edges, so n-1 rounds suffice unless a negative cycle exists.",
    st: ["Set all distances to infinity except the source.", "Relax every edge n-1 times.", "Run one more pass.", "Report a negative cycle if anything still improves."],
    tc: "O(nm)", sc: "O(n)",
    solve: (input) => { const r = reader(input); const n = r.int(), m = r.int(); const edges: Array<[number, number, number]> = []; for (let i = 0; i < m; i += 1) edges.push([r.int(), r.int(), r.int()]); const dist = new Array(n).fill(Infinity); dist[0] = 0; for (let round = 0; round < n - 1; round += 1) { let changed = false; for (const [u, v, w] of edges) if (dist[u] !== Infinity && dist[u] + w < dist[v]) { dist[v] = dist[u] + w; changed = true; } if (!changed) break; } for (const [u, v, w] of edges) if (dist[u] !== Infinity && dist[u] + w < dist[v]) return "NEGATIVE CYCLE"; return join(dist.map((d) => (d === Infinity ? -1 : d))); },
    samples: ["3 3\n0 1 4\n0 2 5\n1 2 -3", "2 2\n0 1 1\n1 0 -2"],
    why: ["Going through vertex 1 costs 1, beating the direct edge.", "The two edges form a negative cycle."],
    hidden: ["1 0", "3 2\n0 1 1\n1 2 1", "4 2\n0 1 1\n2 3 1", "2 1\n0 1 -5"],
    edge: ["2 0"],
    companies: ["google", "amazon"],
  },
  {
    slug: "all-pairs-shortest-path",
    title: "All Pairs Shortest Paths",
    difficulty: "HARD",
    topics: ["graphs", "dp"],
    d: "Compute the shortest distance between every pair of vertices in a directed weighted graph with non-negative weights. Print -1 for unreachable pairs.",
    in: "First line: n and m.\nNext m lines: u, v and w.",
    out: "n lines of n distances each.",
    c: "1 <= n <= 200\n0 <= m <= 10000\n1 <= w <= 10^6",
    hints: ["Running Dijkstra from every vertex works but is more code.", "Consider paths that may pass through the first k vertices.", "Adding one allowed intermediate vertex at a time gives a simple triple loop."],
    ap: "Floyd-Warshall: for every intermediate vertex k, relax every pair (i, j) through k.",
    it: "The outer loop must be the intermediate vertex — putting it anywhere else breaks correctness.",
    st: ["Initialise the matrix with edge weights and zero on the diagonal.", "For each k, i and j, take min(d[i][j], d[i][k] + d[k][j]).", "Print the matrix with -1 for infinity."],
    tc: "O(n^3)", sc: "O(n^2)",
    solve: (input) => { const r = reader(input); const n = r.int(), m = r.int(); const d = Array.from({ length: n }, (_, i) => Array.from({ length: n }, (_, j) => (i === j ? 0 : Infinity))); for (let i = 0; i < m; i += 1) { const u = r.int(), v = r.int(), w = r.int(); d[u][v] = Math.min(d[u][v], w); } for (let k = 0; k < n; k += 1) for (let i = 0; i < n; i += 1) for (let j = 0; j < n; j += 1) if (d[i][k] + d[k][j] < d[i][j]) d[i][j] = d[i][k] + d[k][j]; return linesOut(d.map((row) => join(row.map((v) => (v === Infinity ? -1 : v))))); },
    samples: ["3 3\n0 1 1\n1 2 2\n0 2 5", "2 0"],
    why: ["Going through vertex 1 beats the direct edge to 2.", "Only the diagonal is reachable."],
    hidden: ["1 0", "2 1\n0 1 3", "3 2\n0 1 1\n2 0 1", "4 4\n0 1 1\n1 2 1\n2 3 1\n3 0 1"],
    edge: ["1 1\n0 0 5"],
  },
  {
    slug: "network-delay-time",
    title: "Network Delay Time",
    difficulty: "HARD",
    topics: ["graphs", "heap"],
    d: "A signal is sent from a source vertex along directed weighted edges. Print the time for every vertex to receive it, or -1 if some vertex never does.",
    in: "First line: n, m and source.\nNext m lines: u, v and w.",
    out: "The total delay, or -1.",
    c: "1 <= n <= 100000\n0 <= m <= 200000\n1 <= w <= 10^9",
    hints: ["Each vertex receives the signal at its shortest distance from the source.", "The answer is the maximum of those distances.", "Dijkstra computes them all."],
    ap: "Dijkstra from the source; the answer is the maximum finalised distance, or -1 when some vertex stays unreachable.",
    it: "Propagation time is exactly the shortest-path distance, so no separate simulation is needed.",
    st: ["Run Dijkstra from the source.", "Take the maximum finalised distance.", "Report -1 if any vertex is unreachable."],
    tc: "O((n + m) log n)", sc: "O(n + m)",
    solve: (input) => { const r = reader(input); const n = r.int(), m = r.int(), src = r.int(); const adj: Array<Array<[number, number]>> = Array.from({ length: n }, () => []); for (let i = 0; i < m; i += 1) { const u = r.int(), v = r.int(), w = r.int(); adj[u].push([v, w]); } const dist = new Array(n).fill(Infinity); dist[src] = 0; const visited = new Array(n).fill(false); for (let step = 0; step < n; step += 1) { let best = -1; for (let i = 0; i < n; i += 1) if (!visited[i] && (best === -1 || dist[i] < dist[best])) best = i; if (best === -1 || dist[best] === Infinity) break; visited[best] = true; for (const [v, w] of adj[best]) if (dist[best] + w < dist[v]) dist[v] = dist[best] + w; } const worst = Math.max(...dist); return worst === Infinity ? "-1" : String(worst); },
    samples: ["4 3 0\n0 1 1\n0 2 1\n1 3 1", "2 0 0"],
    why: ["Vertex 3 receives the signal last, at time 2.", "Vertex 1 is unreachable."],
    hidden: ["1 0 0", "3 2 0\n0 1 5\n1 2 5", "3 3 1\n1 0 1\n1 2 2\n0 2 4", "2 1 0\n0 1 1000000000"],
    edge: ["2 1 1\n0 1 5"],
  },
  {
    slug: "cheapest-flights-k-stops",
    title: "Cheapest Flights Within K Stops",
    difficulty: "HARD",
    topics: ["graphs", "dp"],
    d: "Find the cheapest route from a source to a destination using at most k intermediate stops, or -1 if none exists.",
    in: "First line: n, m, src, dst and k.\nNext m lines: u, v and price.",
    out: "The cheapest price, or -1.",
    c: "1 <= n <= 1000\n0 <= m <= 10000\n0 <= k < n",
    hints: ["Plain Dijkstra ignores the stop limit.", "Add the number of edges used as a dimension.", "Relax all edges exactly k+1 times, using the previous round's values."],
    ap: "Bellman-Ford limited to k+1 rounds, relaxing from a snapshot of the previous round so each round adds exactly one edge.",
    it: "Copying the distance array each round is what enforces the hop limit; relaxing in place would allow longer paths.",
    st: ["Set the source distance to 0.", "Repeat k+1 times: relax all edges using the previous round's array.", "Copy the result into the working array.", "Report the destination distance."],
    tc: "O(k * m)", sc: "O(n)",
    solve: (input) => { const r = reader(input); const n = r.int(), m = r.int(), src = r.int(), dst = r.int(), k = r.int(); const edges: Array<[number, number, number]> = []; for (let i = 0; i < m; i += 1) edges.push([r.int(), r.int(), r.int()]); let dist = new Array(n).fill(Infinity); dist[src] = 0; for (let round = 0; round <= k; round += 1) { const next = [...dist]; for (const [u, v, w] of edges) if (dist[u] !== Infinity && dist[u] + w < next[v]) next[v] = dist[u] + w; dist = next; } return dist[dst] === Infinity ? "-1" : String(dist[dst]); },
    samples: ["3 3 0 2 1\n0 1 100\n1 2 100\n0 2 500", "3 3 0 2 0\n0 1 100\n1 2 100\n0 2 500"],
    why: ["One stop is allowed, so the 200 route wins.", "With no stops only the direct flight is usable."],
    hidden: ["2 1 0 1 0\n0 1 5", "2 0 0 1 0", "4 4 0 3 2\n0 1 1\n1 2 1\n2 3 1\n0 3 10", "3 2 0 2 5\n0 1 1\n1 2 1"],
    edge: ["1 0 0 0 0"],
    companies: ["amazon", "google"],
  },
  {
    slug: "lru-with-frequency",
    title: "LFU Cache",
    difficulty: "HARD",
    topics: ["hashing", "heap"],
    d: "Simulate a least-frequently-used cache. Operations are PUT key value and GET key. On eviction remove the least frequently used key, breaking ties by least recently used. GET prints the value or -1 and counts as a use.",
    in: "First line: capacity and q.\nNext q lines: one operation each.",
    out: "One line per GET.",
    c: "1 <= capacity <= 100000\n1 <= q <= 100000",
    hints: ["You need frequency ordering and recency ordering at once.", "Bucket keys by frequency.", "Within a bucket, keep insertion order for the recency tie-break."],
    ap: "Frequency buckets, each an ordered collection, plus a map from key to its frequency. Eviction takes the front of the lowest non-empty bucket.",
    it: "Keeping a pointer to the minimum frequency is what makes eviction O(1) rather than a search.",
    st: ["Track each key's frequency and its position in that bucket.", "On access, move the key to the next frequency bucket.", "Maintain the minimum frequency.", "Evict from the front of the minimum bucket."],
    tc: "O(1) amortised per operation", sc: "O(capacity)",
    solve: (input) => { const parts = input.trim().split("\n"); const [cap, q] = parts[0].trim().split(/\s+/).map(Number); const values = new Map<string, string>(); const freq = new Map<string, number>(); const order = new Map<string, number>(); let tick = 0; const out: string[] = []; const evict = () => { let worstKey = "", worstFreq = Infinity, worstTick = Infinity; for (const key of values.keys()) { const f = freq.get(key)!, t = order.get(key)!; if (f < worstFreq || (f === worstFreq && t < worstTick)) { worstKey = key; worstFreq = f; worstTick = t; } } values.delete(worstKey); freq.delete(worstKey); order.delete(worstKey); }; for (let i = 1; i <= q; i += 1) { const [op, k, v] = (parts[i] ?? "").trim().split(/\s+/); if (op === "PUT") { if (values.has(k)) { values.set(k, v); freq.set(k, freq.get(k)! + 1); order.set(k, tick++); } else { if (values.size >= cap) evict(); values.set(k, v); freq.set(k, 1); order.set(k, tick++); } } else if (op === "GET") { if (!values.has(k)) out.push("-1"); else { out.push(values.get(k)!); freq.set(k, freq.get(k)! + 1); order.set(k, tick++); } } } return linesOut(out); },
    samples: ["2 6\nPUT 1 1\nPUT 2 2\nGET 1\nPUT 3 3\nGET 2\nGET 3", "1 3\nPUT 1 1\nGET 1\nGET 2"],
    why: ["Key 2 is evicted because key 1 was used more often.", "Key 2 was never stored."],
    hidden: ["1 2\nPUT 1 1\nGET 1", "2 4\nPUT 1 1\nPUT 2 2\nGET 1\nGET 2", "1 3\nPUT 1 1\nPUT 2 2\nGET 1", "2 3\nGET 9\nPUT 9 9\nGET 9"],
    edge: ["1 1\nGET 1"],
    companies: ["amazon", "google"],
  },
  {
    slug: "range-sum-query-mutable",
    title: "Range Sum with Updates",
    difficulty: "HARD",
    topics: ["advanced", "arrays"],
    d: "Support two operations on an array: UPDATE i x sets a[i] to x, and QUERY l r prints the sum of a[l..r] inclusive.",
    in: "First line: n and q.\nSecond line: n integers.\nNext q lines: one operation each.",
    out: "One line per QUERY.",
    c: "1 <= n, q <= 100000\n-10^9 <= values <= 10^9",
    hints: ["A prefix-sum array answers queries fast but updates slowly.", "A plain array updates fast but queries slowly.", "A Fenwick tree or segment tree gives both in logarithmic time."],
    ap: "Fenwick (binary indexed) tree storing prefix sums, giving O(log n) point updates and O(log n) prefix queries.",
    it: "Both operations touch only O(log n) nodes because each index belongs to that many ranges.",
    st: ["Build the tree from the initial array.", "An update adds the delta along the index's ancestor chain.", "A prefix query sums along the complementary chain.", "A range query is the difference of two prefixes."],
    tc: "O((n + q) log n)", sc: "O(n)",
    solve: (input) => { const parts = input.trim().split("\n"); const [n, q] = parts[0].trim().split(/\s+/).map(Number); const a = parts[1].trim().split(/\s+/).map(Number).slice(0, n); const tree = new Array(n + 1).fill(0); const add = (i: number, delta: number) => { for (let k = i + 1; k <= n; k += k & -k) tree[k] += delta; }; const prefix = (i: number) => { let s = 0; for (let k = i; k > 0; k -= k & -k) s += tree[k]; return s; }; for (let i = 0; i < n; i += 1) add(i, a[i]); const out: number[] = []; for (let i = 2; i < 2 + q; i += 1) { const [op, x, y] = (parts[i] ?? "").trim().split(/\s+/); if (op === "UPDATE") { const idx = Number(x), value = Number(y); add(idx, value - a[idx]); a[idx] = value; } else if (op === "QUERY") out.push(prefix(Number(y) + 1) - prefix(Number(x))); } return linesOut(out); },
    samples: ["5 3\n1 2 3 4 5\nQUERY 0 2\nUPDATE 1 10\nQUERY 0 2", "1 1\n5\nQUERY 0 0"],
    why: ["6 before the update, 14 after.", "A single element."],
    hidden: ["3 2\n1 1 1\nQUERY 0 2\nQUERY 1 1", "4 3\n1 2 3 4\nUPDATE 0 0\nQUERY 0 3\nQUERY 2 2", "2 2\n-1 -1\nQUERY 0 1\nUPDATE 0 5", "3 1\n1 2 3\nQUERY 2 2"],
    edge: ["1 2\n0\nUPDATE 0 1\nQUERY 0 0"],
    companies: ["google", "amazon"],
  },
  {
    slug: "range-minimum-query",
    title: "Range Minimum Query",
    difficulty: "HARD",
    topics: ["advanced", "arrays"],
    d: "Answer q queries asking for the minimum of a[l..r] inclusive. The array does not change.",
    in: "First line: n and q.\nSecond line: n integers.\nNext q lines: l and r.",
    out: "One minimum per query.",
    c: "1 <= n, q <= 100000\n-10^9 <= a[i] <= 10^9",
    hints: ["Scanning each range is O(nq).", "The minimum operator is idempotent, so ranges may overlap.", "Precompute minima of every power-of-two length."],
    ap: "Sparse table: precompute the minimum of every interval whose length is a power of two, then answer any query with two overlapping intervals.",
    it: "Overlap is harmless because min(x, x) = x, which is what allows O(1) queries.",
    st: ["Build a table where table[k][i] covers 2^k elements from i.", "For a query compute k = floor(log2(r-l+1)).", "Answer min(table[k][l], table[k][r-2^k+1])."],
    tc: "O(n log n) build, O(1) per query", sc: "O(n log n)",
    solve: (input) => { const r = reader(input); const n = r.int(), q = r.int(); const a = r.ints(n); const LOG = Math.max(1, Math.floor(Math.log2(n)) + 1); const table: number[][] = [a.slice()]; for (let k = 1; k < LOG; k += 1) { const prev = table[k - 1]; const size = n - (1 << k) + 1; const row = new Array(Math.max(0, size)).fill(0); for (let i = 0; i < size; i += 1) row[i] = Math.min(prev[i], prev[i + (1 << (k - 1))]); table.push(row); } const out: number[] = []; for (let i = 0; i < q; i += 1) { const l = r.int(), rr = r.int(); const k = Math.floor(Math.log2(rr - l + 1)); out.push(Math.min(table[k][l], table[k][rr - (1 << k) + 1])); } return linesOut(out); },
    samples: ["5 2\n2 5 1 4 3\n0 2\n3 4", "1 1\n7\n0 0"],
    why: ["The minima are 1 and 3.", "A single element is its own minimum."],
    hidden: ["4 2\n1 2 3 4\n0 3\n1 2", "3 1\n-1 -2 -3\n0 2", "5 1\n5 5 5 5 5\n0 4", "2 2\n1 2\n0 0\n1 1"],
    edge: ["2 1\n-1000000000 1000000000\n0 1"],
  },
  {
    slug: "disjoint-set-queries",
    title: "Union Find Queries",
    difficulty: "HARD",
    topics: ["advanced", "graphs"],
    d: "Process operations on a disjoint-set structure: UNION a b merges two sets, FIND a b prints YES when a and b are in the same set and NO otherwise.",
    in: "First line: n and q.\nNext q lines: one operation each.",
    out: "One line per FIND.",
    c: "1 <= n, q <= 200000",
    hints: ["Naive merging can degrade to a long chain.", "Attach the smaller tree under the larger one.", "Compress paths during find so later queries are near constant."],
    ap: "Disjoint-set union with union by size and path compression, giving near-constant amortised time per operation.",
    it: "Either optimisation alone is decent; together they give the inverse-Ackermann bound.",
    st: ["Each element starts as its own root.", "FIND walks to the root, compressing the path.", "UNION attaches the smaller root under the larger.", "Two elements are connected when their roots match."],
    tc: "O(q * inverse Ackermann)", sc: "O(n)",
    solve: (input) => { const parts = input.trim().split("\n"); const [n, q] = parts[0].trim().split(/\s+/).map(Number); const parent = Array.from({ length: n }, (_, i) => i); const size = new Array(n).fill(1); const find = (x: number): number => (parent[x] === x ? x : (parent[x] = find(parent[x]))); const out: string[] = []; for (let i = 1; i <= q; i += 1) { const [op, x, y] = (parts[i] ?? "").trim().split(/\s+/); const a = find(Number(x)), b = find(Number(y)); if (op === "UNION") { if (a !== b) { if (size[a] < size[b]) { parent[a] = b; size[b] += size[a]; } else { parent[b] = a; size[a] += size[b]; } } } else if (op === "FIND") out.push(yesNo(a === b)); } return linesOut(out); },
    samples: ["4 4\nUNION 0 1\nFIND 0 1\nFIND 0 2\nUNION 1 2", "2 1\nFIND 0 1"],
    why: ["0 and 1 are merged; 2 is separate.", "Nothing has been merged yet."],
    hidden: ["3 3\nUNION 0 1\nUNION 1 2\nFIND 0 2", "2 2\nUNION 0 0\nFIND 0 0", "4 3\nUNION 0 1\nUNION 2 3\nFIND 1 2", "1 1\nFIND 0 0"],
    edge: ["2 1\nUNION 0 1"],
  },
  {
    slug: "kmp-pattern-search",
    title: "Pattern Search with KMP",
    difficulty: "HARD",
    topics: ["strings", "advanced"],
    d: "Find every starting index at which a pattern occurs in a text, counting overlapping occurrences.",
    in: "Line 1: the text.\nLine 2: the pattern.",
    out: "The 0-indexed occurrence positions, space separated, or NONE.",
    c: "1 <= |text| <= 200000\n1 <= |pattern| <= |text|",
    hints: ["Naive matching restarts the pattern after every mismatch.", "The pattern's own structure tells you how far you may safely skip.", "Precompute the longest proper prefix that is also a suffix at every position."],
    ap: "Knuth-Morris-Pratt: build the failure function of the pattern, then scan the text without ever moving the text pointer backwards.",
    it: "The failure function encodes what has already been matched, which is why no rescanning is needed.",
    st: ["Build the LPS array for the pattern.", "Scan the text with a pattern pointer.", "On a mismatch fall back via the LPS array.", "Record a match whenever the pattern pointer reaches its length."],
    tc: "O(|text| + |pattern|)", sc: "O(|pattern|)",
    solve: (input) => { const parts = input.trim().split("\n").map((l) => l.trim()); const text = parts[0], pattern = parts[1] ?? ""; const lps = new Array(pattern.length).fill(0); for (let i = 1, len = 0; i < pattern.length; ) { if (pattern[i] === pattern[len]) lps[i++] = ++len; else if (len) len = lps[len - 1]; else lps[i++] = 0; } const out: number[] = []; for (let i = 0, j = 0; i < text.length; ) { if (text[i] === pattern[j]) { i += 1; j += 1; if (j === pattern.length) { out.push(i - j); j = lps[j - 1]; } } else if (j) j = lps[j - 1]; else i += 1; } return out.length ? join(out) : "NONE"; },
    samples: ["ababcabab\nabab", "abcdef\nxyz"],
    why: ["Matches begin at indices 0 and 5.", "The pattern never occurs."],
    hidden: ["aaaa\naa", "a\na", "abcabcabc\nabc", "aaa\nb"],
    edge: ["ab\nab"],
    companies: ["google", "amazon"],
  },
  {
    slug: "z-algorithm-matching",
    title: "Z-Function Pattern Matching",
    difficulty: "HARD",
    topics: ["strings", "advanced"],
    d: "Count the occurrences of a pattern in a text, including overlaps, using the Z-function.",
    in: "Line 1: the text.\nLine 2: the pattern.",
    out: "The number of occurrences.",
    c: "1 <= |text| <= 200000\n1 <= |pattern| <= |text|",
    hints: ["Concatenate the pattern, a separator and the text.", "The Z-value at a position is the longest prefix match starting there.", "A Z-value equal to the pattern length marks an occurrence."],
    ap: "Build the string pattern + separator + text and compute its Z-array; every position whose Z-value equals the pattern length is a match.",
    it: "The separator prevents matches from spanning the boundary, which is what makes the reduction sound.",
    st: ["Form the concatenated string with a separator not present in either input.", "Compute the Z-array in linear time.", "Count positions in the text part whose Z-value equals the pattern length."],
    tc: "O(|text| + |pattern|)", sc: "O(|text| + |pattern|)",
    solve: (input) => { const parts = input.trim().split("\n").map((l) => l.trim()); const text = parts[0], pattern = parts[1] ?? ""; const s = `${pattern}${text}`; const n = s.length; const z = new Array(n).fill(0); for (let i = 1, l = 0, r = 0; i < n; i += 1) { if (i < r) z[i] = Math.min(r - i, z[i - l]); while (i + z[i] < n && s[z[i]] === s[i + z[i]]) z[i] += 1; if (i + z[i] > r) { l = i; r = i + z[i]; } } let count = 0; for (let i = pattern.length + 1; i < n; i += 1) if (z[i] === pattern.length) count += 1; return String(count); },
    samples: ["aaaa\naa", "abcabc\nabc"],
    why: ["Three overlapping matches.", "Two matches."],
    hidden: ["a\na", "abc\nd", "aaaaa\na", "ababab\nab"],
    edge: ["ab\nab"],
  },
  {
    slug: "longest-duplicate-substring",
    title: "Longest Duplicate Substring",
    difficulty: "HARD",
    topics: ["strings", "hashing", "searching"],
    d: "Find the length of the longest substring that occurs at least twice, allowing overlaps. Print 0 when none exists.",
    in: "A single line containing a lowercase string.",
    out: "The length of the longest duplicated substring.",
    c: "1 <= |s| <= 30000",
    hints: ["If a duplicate of length L exists, so does one of every shorter length.", "That monotonicity permits binary search on the length.", "Rolling hashes test a given length in linear time."],
    ap: "Binary search the answer length, testing each candidate with Rabin-Karp rolling hashes stored in a hash set.",
    it: "Monotonicity in the length is what makes binary search valid; the rolling hash is what makes each test linear.",
    st: ["Binary search L between 1 and n-1.", "Hash every substring of length L with a rolling hash.", "Report success on a repeated hash with a matching string.", "Keep the largest successful L."],
    tc: "O(n log n) expected", sc: "O(n)",
    solve: (input) => { const s = input.trim(); const n = s.length; const has = (len: number) => { if (len === 0) return true; const seen = new Set<string>(); for (let i = 0; i + len <= n; i += 1) { const sub = s.slice(i, i + len); if (seen.has(sub)) return true; seen.add(sub); } return false; }; let lo = 0, hi = n - 1, best = 0; while (lo <= hi) { const mid = (lo + hi) >> 1; if (has(mid)) { best = mid; lo = mid + 1; } else hi = mid - 1; } return String(best); },
    samples: ["banana", "abcd"],
    why: ["'ana' occurs twice, overlapping.", "Every substring is unique."],
    hidden: ["a", "aa", "aaaaa", "abcabc"],
    edge: ["ab"],
    companies: ["google", "amazon"],
  },
  {
    slug: "minimum-window-subsequence",
    title: "Minimum Window Subsequence",
    difficulty: "HARD",
    topics: ["dp", "strings"],
    d: "Find the length of the shortest substring of s that contains t as a subsequence, preserving order. Print 0 when none exists.",
    in: "Line 1: string s.\nLine 2: string t.",
    out: "The shortest window length, or 0.",
    c: "1 <= |s| <= 20000\n1 <= |t| <= 100",
    hints: ["This is a subsequence, not a substring, so characters may be spread out.", "Walk forward to match t, then walk backwards to tighten the window.", "Restart the forward walk from just after the tightened start."],
    ap: "Two-pointer forward-then-backward sweep: advance to complete a match of t, then contract from the right end backwards to find the tightest start.",
    it: "The backward pass is what turns any valid window into a minimal one ending at that position.",
    st: ["Scan forward matching characters of t in order.", "On completion, walk backwards matching t in reverse.", "Record the window length.", "Restart the forward scan just after the found start."],
    tc: "O(|s| * |t|)", sc: "O(1)",
    solve: (input) => { const parts = input.trim().split("\n").map((l) => l.trim()); const s = parts[0], t = parts[1] ?? ""; let best = Infinity; let i = 0; while (i < s.length) { let j = 0, k = i; while (k < s.length) { if (s[k] === t[j]) { j += 1; if (j === t.length) break; } k += 1; } if (j < t.length) break; const end = k; let back = t.length - 1; while (back >= 0) { if (s[k] === t[back]) back -= 1; k -= 1; } const start = k + 1; best = Math.min(best, end - start + 1); i = start + 1; } return String(best === Infinity ? 0 : best); },
    samples: ["abcdebdde\nbde", "abc\nd"],
    why: ["'bcde' is the shortest window containing 'bde' in order.", "'d' never appears."],
    hidden: ["a\na", "ab\nb", "aaa\naa", "cnhczmccqouqadqtmjjzl\nmm"],
    edge: ["a\nb"],
  },
  {
    slug: "count-smaller-after-self",
    title: "Count of Smaller Numbers After Self",
    difficulty: "HARD",
    topics: ["advanced", "sorting"],
    d: "For each index, count how many values to its right are strictly smaller.",
    in: "First line: n.\nSecond line: n integers.",
    out: "n counts, space separated.",
    c: "1 <= n <= 100000\n-10^9 <= a[i] <= 10^9",
    hints: ["The brute force is O(n^2).", "Process from the right, asking how many smaller values you have already seen.", "A Fenwick tree over compressed values answers that in log n."],
    ap: "Coordinate-compress the values, then scan right to left querying a Fenwick tree for the count of smaller values already inserted.",
    it: "This is the inversion-counting problem reported per index instead of in total.",
    st: ["Compress values to ranks.", "Scan from the right.", "Query the prefix count below the current rank.", "Insert the current rank."],
    tc: "O(n log n)", sc: "O(n)",
    solve: (input) => { const a = A(input); const n = a.length; const sorted = [...new Set(a)].sort((x, y) => x - y); const rank = new Map(sorted.map((v, i) => [v, i + 1])); const tree = new Array(sorted.length + 1).fill(0); const add = (i: number) => { for (let k = i; k <= sorted.length; k += k & -k) tree[k] += 1; }; const prefix = (i: number) => { let s = 0; for (let k = i; k > 0; k -= k & -k) s += tree[k]; return s; }; const out = new Array(n).fill(0); for (let i = n - 1; i >= 0; i -= 1) { const rk = rank.get(a[i])!; out[i] = prefix(rk - 1); add(rk); } return join(out); },
    samples: ["4\n5 2 6 1", "1\n5"],
    why: ["5 has two smaller values after it, 2 has one, 6 has one, 1 has none.", "A single element has nothing after it."],
    hidden: ["3\n1 2 3", "3\n3 2 1", "4\n2 2 2 2", "5\n-1 -2 -3 -4 -5"],
    edge: ["2\n1000000000 -1000000000"],
    companies: ["google", "amazon"],
  },
  {
    slug: "reverse-pairs-count",
    title: "Reverse Pairs",
    difficulty: "HARD",
    topics: ["sorting", "advanced"],
    d: "Count the pairs i < j with a[i] > 2 * a[j].",
    in: "First line: n.\nSecond line: n integers.",
    out: "The number of such pairs.",
    c: "1 <= n <= 50000\n-10^9 <= a[i] <= 10^9",
    hints: ["The quadratic scan is too slow at these limits.", "Modify merge sort to count across the split.", "Count with a separate two-pointer sweep before merging."],
    ap: "Modified merge sort: before merging two sorted halves, sweep two pointers to count pairs satisfying the condition across the halves.",
    it: "Doing the counting sweep before the merge keeps both halves sorted, which is what makes the sweep monotone.",
    st: ["Recursively sort and count both halves.", "Sweep to count pairs where left > 2 * right.", "Merge the halves.", "Return the total."],
    tc: "O(n log n)", sc: "O(n)",
    solve: (input) => { const a = A(input); let count = 0; const sortCount = (arr: number[]): number[] => { if (arr.length <= 1) return arr; const mid = arr.length >> 1; const left = sortCount(arr.slice(0, mid)); const right = sortCount(arr.slice(mid)); let j = 0; for (let i = 0; i < left.length; i += 1) { while (j < right.length && left[i] > 2 * right[j]) j += 1; count += j; } const out: number[] = []; let x = 0, y = 0; while (x < left.length && y < right.length) out.push(left[x] <= right[y] ? left[x++] : right[y++]); while (x < left.length) out.push(left[x++]); while (y < right.length) out.push(right[y++]); return out; }; sortCount(a); return String(count); },
    samples: ["5\n1 3 2 3 1", "4\n2 4 3 5"],
    why: ["Two pairs satisfy the condition.", "Three pairs satisfy it."],
    hidden: ["1\n1", "3\n1 2 3", "3\n5 2 1", "4\n-5 -4 -3 -2"],
    edge: ["2\n1000000000 -1000000000"],
  },
  {
    slug: "max-sum-rectangle-2d",
    title: "Maximum Sum Rectangle",
    difficulty: "HARD",
    topics: ["dp", "matrix"],
    d: "Find the largest sum obtainable from any non-empty rectangular submatrix.",
    in: "First line: n and m.\nNext n lines: m integers each.",
    out: "The maximum rectangle sum.",
    c: "1 <= n, m <= 200\n-10^6 <= values <= 10^6",
    hints: ["Enumerating all rectangles is O(n^2 m^2).", "Fix the top and bottom rows.", "Collapse the rows between them into one array and run Kadane."],
    ap: "Fix each pair of rows, compress the columns between them into a one-dimensional array, and apply Kadane's algorithm to find the best column range.",
    it: "Reducing two dimensions to one is what turns a quartic search into a cubic one.",
    st: ["For each top row, reset a column accumulator.", "For each bottom row, add that row into the accumulator.", "Run Kadane over the accumulator.", "Track the global maximum."],
    tc: "O(n^2 m)", sc: "O(m)",
    solve: (input) => { const r = reader(input); const n = r.int(), m = r.int(); const g: number[][] = []; for (let i = 0; i < n; i += 1) g.push(r.ints(m)); let best = -Infinity; for (let top = 0; top < n; top += 1) { const acc = new Array(m).fill(0); for (let bottom = top; bottom < n; bottom += 1) { for (let j = 0; j < m; j += 1) acc[j] += g[bottom][j]; let cur = acc[0], local = acc[0]; for (let j = 1; j < m; j += 1) { cur = Math.max(acc[j], cur + acc[j]); local = Math.max(local, cur); } best = Math.max(best, local); } } return String(best); },
    samples: ["4 5\n1 2 -1 -4 -20\n-8 -3 4 2 1\n3 8 10 1 3\n-4 -1 1 7 -6", "1 1\n-5"],
    why: ["The 2 by 3 block sums to 29.", "The only rectangle is the single negative cell."],
    hidden: ["1 1\n5", "2 2\n1 1\n1 1", "2 2\n-1 -2\n-3 -4", "3 3\n1 -1 1\n-1 1 -1\n1 -1 1"],
    edge: ["1 2\n-1 -2"],
    companies: ["google", "amazon"],
  },
  {
    slug: "russian-doll-envelopes",
    title: "Russian Doll Envelopes",
    difficulty: "HARD",
    topics: ["dp", "sorting", "searching"],
    d: "An envelope fits inside another when both its width and its height are strictly smaller. Find the longest chain of nested envelopes.",
    in: "First line: n.\nNext n lines: width and height.",
    out: "The maximum number of nested envelopes.",
    c: "1 <= n <= 100000\n1 <= width, height <= 10^9",
    hints: ["Sorting by width alone is not enough because ties break nesting.", "Sort by width ascending and by height descending on ties.", "Then the answer is the longest increasing subsequence of heights."],
    ap: "Sort by width ascending, height descending on equal widths, then compute the longest strictly increasing subsequence of the heights in O(n log n).",
    it: "The descending height tie-break prevents two envelopes of equal width from both entering the chain.",
    st: ["Sort with the described comparator.", "Run patience sorting over the heights.", "Print the resulting length."],
    tc: "O(n log n)", sc: "O(n)",
    solve: (input) => { const r = reader(input); const n = r.int(); const env: Array<[number, number]> = []; for (let i = 0; i < n; i += 1) env.push([r.int(), r.int()]); env.sort((a, b) => a[0] - b[0] || b[1] - a[1]); const tails: number[] = []; for (const [, h] of env) { let lo = 0, hi = tails.length; while (lo < hi) { const mid = (lo + hi) >> 1; if (tails[mid] < h) lo = mid + 1; else hi = mid; } tails[lo] = h; } return String(tails.length); },
    samples: ["4\n5 4\n6 4\n6 7\n2 3", "2\n1 1\n1 1"],
    why: ["2x3 fits in 5x4 fits in 6x7.", "Equal envelopes cannot nest."],
    hidden: ["1\n1 1", "3\n1 1\n2 2\n3 3", "3\n3 3\n2 2\n1 1", "4\n1 5\n2 4\n3 3\n4 2"],
    edge: ["2\n1 2\n2 1"],
    companies: ["google", "amazon"],
  },
  {
    slug: "job-scheduling-max-profit",
    title: "Weighted Job Scheduling",
    difficulty: "HARD",
    topics: ["dp", "searching", "sorting"],
    d: "Each job has a start time, an end time and a profit. Choose non-overlapping jobs maximising the total profit. A job may start exactly when another ends.",
    in: "First line: n.\nNext n lines: start, end and profit.",
    out: "The maximum total profit.",
    c: "1 <= n <= 100000\n0 <= start < end <= 10^9\n1 <= profit <= 10^6",
    hints: ["Greedy by profit or by end time both fail here.", "Sort by end time and define dp over jobs.", "Binary search for the last job that ends at or before the current start."],
    ap: "Sort by end time, then dp[i] = max(dp[i-1], profit[i] + dp[j]) where j is the last non-conflicting job found by binary search.",
    it: "Adding weights breaks the greedy argument that works for plain activity selection, so DP is required.",
    st: ["Sort jobs by end time.", "For each job binary search the latest compatible predecessor.", "Take the better of skipping or taking the job.", "Print the final value."],
    tc: "O(n log n)", sc: "O(n)",
    solve: (input) => { const r = reader(input); const n = r.int(); const jobs: Array<[number, number, number]> = []; for (let i = 0; i < n; i += 1) jobs.push([r.int(), r.int(), r.int()]); jobs.sort((a, b) => a[1] - b[1]); const ends = jobs.map((j) => j[1]); const dp = new Array(n + 1).fill(0); for (let i = 0; i < n; i += 1) { const [s, , p] = jobs[i]; let lo = 0, hi = i; while (lo < hi) { const mid = (lo + hi) >> 1; if (ends[mid] <= s) lo = mid + 1; else hi = mid; } dp[i + 1] = Math.max(dp[i], dp[lo] + p); } return String(dp[n]); },
    samples: ["4\n1 2 50\n3 5 20\n6 19 100\n2 100 200", "2\n1 2 10\n2 3 20"],
    why: ["Taking the first and last jobs gives 250.", "The two jobs chain end to end."],
    hidden: ["1\n0 1 5", "3\n1 3 20\n2 5 20\n3 10 100", "2\n1 10 1\n2 3 100", "3\n1 2 1\n2 3 1\n3 4 1"],
    edge: ["2\n0 1 1\n0 1 2"],
    companies: ["amazon", "google"],
  },
  {
    slug: "min-cost-connect-points",
    title: "Minimum Cost to Connect Points",
    difficulty: "HARD",
    topics: ["graphs", "greedy"],
    d: "Connect all points so that every pair is reachable, minimising the total Manhattan distance of the edges used.",
    in: "First line: n.\nNext n lines: x and y.",
    out: "The minimum total cost.",
    c: "1 <= n <= 1000\n-10^6 <= x, y <= 10^6",
    hints: ["This is a minimum spanning tree over a complete graph.", "With n up to 1000 the n^2 edges are affordable.", "Prim's algorithm avoids materialising all edges."],
    ap: "Prim's algorithm on the implicit complete graph, maintaining the cheapest known connection cost to the growing tree for every unvisited point.",
    it: "Prim suits dense graphs because it never needs the edge list to exist explicitly.",
    st: ["Start from point 0 with all costs at infinity.", "Repeatedly take the cheapest unvisited point.", "Add its cost to the total.", "Relax the costs of the remaining points against it."],
    tc: "O(n^2)", sc: "O(n)",
    solve: (input) => { const r = reader(input); const n = r.int(); const pts: Array<[number, number]> = []; for (let i = 0; i < n; i += 1) pts.push([r.int(), r.int()]); const cost = new Array(n).fill(Infinity); const used = new Array(n).fill(false); cost[0] = 0; let total = 0; for (let step = 0; step < n; step += 1) { let best = -1; for (let i = 0; i < n; i += 1) if (!used[i] && (best === -1 || cost[i] < cost[best])) best = i; used[best] = true; total += cost[best]; for (let i = 0; i < n; i += 1) if (!used[i]) { const d = Math.abs(pts[best][0] - pts[i][0]) + Math.abs(pts[best][1] - pts[i][1]); if (d < cost[i]) cost[i] = d; } } return String(total); },
    samples: ["5\n0 0\n2 2\n3 10\n5 2\n7 0", "1\n0 0"],
    why: ["The minimum spanning tree costs 20.", "A single point needs no edges."],
    hidden: ["2\n0 0\n1 1", "3\n0 0\n1 0\n2 0", "4\n0 0\n0 1\n1 0\n1 1", "2\n-1000000 -1000000\n1000000 1000000"],
    edge: ["2\n0 0\n0 0"],
    companies: ["amazon", "google"],
  },
  {
    slug: "maximum-profit-k-transactions",
    title: "Best Time to Buy and Sell Stock IV",
    difficulty: "HARD",
    topics: ["dp"],
    d: "With at most k buy-sell transactions and no overlapping trades, maximise the profit from a price series.",
    in: "First line: n and k.\nSecond line: n prices.",
    out: "The maximum profit.",
    c: "1 <= n <= 100000\n0 <= k <= 100\n0 <= price <= 10^9",
    hints: ["Track two states per transaction count: holding and not holding.", "Buying moves you into the holding state.", "When k is at least n/2 the limit is irrelevant."],
    ap: "DP over transaction count with holding and free states, plus a special case for unlimited transactions when k is large enough.",
    it: "The state machine per transaction is what keeps the complexity at O(nk) instead of exponential.",
    st: ["If 2k >= n, sum every positive daily gain.", "Otherwise keep buy[j] and sell[j] for each transaction index.", "Update both arrays for each price.", "Print sell[k]."],
    tc: "O(nk)", sc: "O(k)",
    solve: (input) => { const r = reader(input); const n = r.int(), k = r.int(); const prices = r.ints(n); if (k === 0 || n < 2) return "0"; if (2 * k >= n) { let total = 0; for (let i = 1; i < n; i += 1) if (prices[i] > prices[i - 1]) total += prices[i] - prices[i - 1]; return String(total); } const buy = new Array(k + 1).fill(-Infinity); const sell = new Array(k + 1).fill(0); for (const p of prices) for (let j = 1; j <= k; j += 1) { buy[j] = Math.max(buy[j], sell[j - 1] - p); sell[j] = Math.max(sell[j], buy[j] + p); } return String(sell[k]); },
    samples: ["6 2\n3 2 6 5 0 3", "4 2\n2 4 1 7"],
    why: ["Two trades give 7.", "Two trades give 8."],
    hidden: ["1 1\n5", "5 0\n1 2 3 4 5", "5 1\n5 4 3 2 1", "6 3\n1 2 3 4 5 6"],
    edge: ["2 1\n1 1"],
    companies: ["amazon", "google", "adobe"],
  },
  {
    slug: "stone-game-optimal",
    title: "Optimal Stone Game",
    difficulty: "HARD",
    topics: ["dp"],
    d: "Two players alternately take a pile from either end of a row of piles, both playing optimally. Print the maximum score the first player can guarantee.",
    in: "First line: n.\nSecond line: n pile sizes.",
    out: "The first player's optimal score.",
    c: "1 <= n <= 500\n1 <= pile <= 10^6",
    hints: ["Both players play optimally, so this is a minimax problem.", "Define the value of an interval for the player about to move.", "Taking one end leaves the opponent facing the remaining interval."],
    ap: "Interval DP storing the best score difference the mover can force, then converting that difference into an absolute score.",
    it: "Tracking the difference rather than two separate scores halves the state and removes the whose-turn bookkeeping.",
    st: ["dp[i][i] is the single pile.", "dp[i][j] = max(a[i] - dp[i+1][j], a[j] - dp[i][j-1]).", "The total plus the difference, halved, is the first player's score."],
    tc: "O(n^2)", sc: "O(n^2)",
    solve: (input) => { const a = A(input); const n = a.length; const dp = Array.from({ length: n }, () => new Array(n).fill(0)); for (let i = 0; i < n; i += 1) dp[i][i] = a[i]; for (let len = 2; len <= n; len += 1) for (let i = 0; i + len - 1 < n; i += 1) { const j = i + len - 1; dp[i][j] = Math.max(a[i] - dp[i + 1][j], a[j] - dp[i][j - 1]); } const total = a.reduce((s, v) => s + v, 0); return String((total + dp[0][n - 1]) / 2); },
    samples: ["4\n5 3 4 5", "2\n1 2"],
    why: ["Taking 5 first forces a win with 10.", "Taking 2 leaves 1."],
    hidden: ["1\n7", "3\n1 2 3", "4\n1 1 1 1", "5\n1 5 2 4 6"],
    edge: ["2\n1 1"],
  },
  {
    slug: "regular-bracket-sequences",
    title: "Count Balanced Bracket Sequences",
    difficulty: "HARD",
    topics: ["dp", "math"],
    d: "Count the balanced sequences of n pairs of round brackets, modulo 1000000007.",
    in: "A single integer n.",
    out: "The count modulo 1000000007.",
    c: "0 <= n <= 100000",
    hints: ["The answer is the nth Catalan number.", "Catalan numbers satisfy a simple product recurrence.", "Modular inverses handle the division."],
    ap: "Compute the nth Catalan number as C(2n, n) / (n+1) using modular factorials and Fermat inverses.",
    it: "The recursive decomposition of a balanced sequence into an inner and a following part is exactly the Catalan recurrence.",
    st: ["Precompute factorials modulo p.", "Compute C(2n, n) with modular inverses.", "Divide by n+1 using another inverse.", "Print the result."],
    tc: "O(n + log p)", sc: "O(n)",
    solve: (input) => { const n = Number(input.trim()); const p = MOD; const power = (b: bigint, e: bigint): bigint => { let result = 1n, base = b % p, exp = e; while (exp > 0n) { if (exp & 1n) result = (result * base) % p; base = (base * base) % p; exp >>= 1n; } return result; }; const size = 2 * n + 1; const fact = new Array(size + 1); fact[0] = 1n; for (let i = 1; i <= size; i += 1) fact[i] = (fact[i - 1] * BigInt(i)) % p; const inv = (x: bigint) => power(x, p - 2n); const catalan = (((fact[2 * n] * inv(fact[n])) % p) * inv(fact[n + 1])) % p; return catalan.toString(); },
    samples: ["3", "0"],
    why: ["The five balanced sequences of three pairs.", "The empty sequence is the only one."],
    hidden: ["1", "2", "10", "1000"],
    edge: ["4"],
  },
  {
    slug: "digit-dp-count-numbers",
    title: "Count Numbers Without a Digit",
    difficulty: "HARD",
    topics: ["dp", "math"],
    d: "Count the integers in [1, n] whose decimal representation does not contain a given digit d.",
    in: "One line: n and d.",
    out: "The count of such integers.",
    c: "1 <= n <= 10^18\n0 <= d <= 9",
    hints: ["Enumerating up to 10^18 is impossible.", "Build the number digit by digit from the most significant end.", "Track whether the prefix is already strictly below n's prefix."],
    ap: "Digit dynamic programming over the decimal representation, with a tight flag indicating whether the prefix still matches n, and a leading-zero flag.",
    it: "The tight flag is what lets you count whole blocks of numbers at once rather than one at a time.",
    st: ["Write n as a digit array.", "Recurse over positions with tight and started flags.", "Skip the forbidden digit.", "Memoise on (position, tight, started)."],
    tc: "O(digits * 10)", sc: "O(digits)",
    solve: (input) => { const [nStr, dStr] = input.trim().split(/\s+/); const digits = nStr.split("").map(Number); const d = Number(dStr); const memo = new Map<string, bigint>(); const go = (pos: number, tight: boolean, started: boolean): bigint => { if (pos === digits.length) return started ? 1n : 0n; const key = `${pos}|${tight ? 1 : 0}|${started ? 1 : 0}`; const cached = memo.get(key); if (cached !== undefined) return cached; const limit = tight ? digits[pos] : 9; let total = 0n; for (let digit = 0; digit <= limit; digit += 1) { const nextStarted = started || digit !== 0; if (nextStarted && digit === d) continue; total += go(pos + 1, tight && digit === limit, nextStarted); } memo.set(key, total); return total; }; return go(0, true, false).toString(); },
    samples: ["20 1", "9 0"],
    why: ["Numbers 1..20 without the digit 1.", "1..9 contain no zero."],
    hidden: ["100 5", "1000000000000000000 9", "10 0", "999 9"],
    edge: ["1 1"],
  },
  {
    slug: "count-subarrays-bounded-max",
    title: "Subarrays with Bounded Maximum",
    difficulty: "HARD",
    topics: ["arrays", "dp"],
    d: "Count the contiguous subarrays whose maximum element lies in the inclusive range [L, R].",
    in: "First line: n, L and R.\nSecond line: n integers.",
    out: "The number of such subarrays.",
    c: "1 <= n <= 100000\n0 <= L <= R <= 10^9",
    hints: ["Counting exactly is awkward; counting a bound is easy.", "Count subarrays whose maximum is at most X.", "Subtract the count for R from the count for L-1."],
    ap: "Count subarrays with maximum at most X by summing run lengths of elements below X, then subtract count(L-1) from count(R).",
    it: "Turning an interval constraint into the difference of two prefix constraints is the whole trick.",
    st: ["Write a helper counting subarrays with maximum at most X.", "It accumulates run lengths of qualifying elements.", "Answer is helper(R) minus helper(L-1)."],
    tc: "O(n)", sc: "O(1)",
    solve: (input) => { const r = reader(input); const n = r.int(), L = r.int(), R = r.int(); const a = r.ints(n); const atMost = (x: number) => { let total = 0, run = 0; for (const v of a) { if (v <= x) { run += 1; total += run; } else run = 0; } return total; }; return String(atMost(R) - atMost(L - 1)); },
    samples: ["3 2 3\n2 1 4 ", "4 1 2\n1 2 1 2"],
    why: ["Subarrays whose maximum is 2 or 3.", "Every subarray qualifies."],
    hidden: ["1 0 0\n0", "5 1 1\n1 1 1 1 1", "4 5 10\n1 2 3 4", "3 0 1000000000\n1 2 3"],
    edge: ["1 1 1\n2"],
  },
  {
    slug: "shortest-superstring-bitmask",
    title: "Shortest Common Supersequence Length",
    difficulty: "HARD",
    topics: ["dp", "strings"],
    d: "Find the length of the shortest string that contains both given strings as subsequences.",
    in: "Line 1: string a.\nLine 2: string b.",
    out: "The length of the shortest common supersequence.",
    c: "1 <= |a|, |b| <= 2000",
    hints: ["Shared characters need only appear once.", "That shared part is the longest common subsequence.", "The answer follows from an inclusion-exclusion count."],
    ap: "Compute the longest common subsequence, then the answer is |a| + |b| - LCS.",
    it: "Every character of the LCS is counted twice in the naive concatenation, and exactly once in the optimum.",
    st: ["Compute the LCS length with the standard DP.", "Add the two lengths and subtract the LCS.", "Print the result."],
    tc: "O(|a| * |b|)", sc: "O(min(|a|, |b|))",
    solve: (input) => { const parts = input.trim().split("\n").map((l) => l.trim()); const a = parts[0], b = parts[1] ?? ""; let prev = new Array(b.length + 1).fill(0); for (let i = 1; i <= a.length; i += 1) { const cur = new Array(b.length + 1).fill(0); for (let j = 1; j <= b.length; j += 1) cur[j] = a[i - 1] === b[j - 1] ? prev[j - 1] + 1 : Math.max(prev[j], cur[j - 1]); prev = cur; } return String(a.length + b.length - prev[b.length]); },
    samples: ["abac\ncab", "abc\nabc"],
    why: ["'cabac' has length 5.", "Identical strings need no extra characters."],
    hidden: ["a\na", "a\nb", "aaa\naa", "forge\nfrog"],
    edge: ["ab\nba"],
  },
  {
    slug: "maximum-xor-pair",
    title: "Maximum XOR of Two Numbers",
    difficulty: "HARD",
    topics: ["tries", "bit-manipulation"],
    d: "Find the maximum XOR obtainable from any two elements of an array.",
    in: "First line: n.\nSecond line: n non-negative integers.",
    out: "The maximum XOR value.",
    c: "2 <= n <= 200000\n0 <= a[i] <= 2^31 - 1",
    hints: ["Trying all pairs is O(n^2).", "Build the answer greedily from the highest bit down.", "A binary trie lets you always take the opposite bit when it exists."],
    ap: "Insert every value into a binary trie of its bits, then for each value walk the trie preferring the opposite bit at every level to maximise the XOR.",
    it: "The highest differing bit dominates the result, so greedy bit-by-bit choice is optimal.",
    st: ["Insert all numbers into a 32-level binary trie.", "For each number walk from the highest bit.", "Prefer the branch with the opposite bit when it exists.", "Track the best XOR found."],
    tc: "O(32n)", sc: "O(32n)",
    solve: (input) => { const a = A(input); let best = 0, mask = 0; for (let bit = 31; bit >= 0; bit -= 1) { mask |= 1 << bit; const prefixes = new Set(a.map((v) => v & mask)); const candidate = best | (1 << bit); for (const p of prefixes) { if (prefixes.has(p ^ candidate)) { best = candidate; break; } } } return String(best); },
    samples: ["6\n3 10 5 25 2 8", "2\n0 0"],
    why: ["5 XOR 25 gives 28.", "Both values are zero."],
    hidden: ["2\n1 2", "3\n8 10 2", "4\n0 1 2 3", "2\n2147483647 0"],
    edge: ["2\n1 1"],
    companies: ["google", "amazon"],
  },
  {
    slug: "count-bits-range",
    title: "Total Set Bits up to N",
    difficulty: "HARD",
    topics: ["bit-manipulation", "math"],
    d: "Count the total number of set bits across all integers from 1 to n.",
    in: "A single integer n.",
    out: "The total number of set bits.",
    c: "1 <= n <= 10^18",
    hints: ["Counting per number is impossible at this scale.", "Consider each bit position independently.", "In every block of 2^(k+1), bit k is set for exactly 2^k numbers."],
    ap: "Count each bit position separately: complete cycles contribute a fixed amount, and the partial cycle contributes the remainder above the half-point.",
    it: "Bits follow a strictly periodic pattern, which is what makes a closed-form count possible.",
    st: ["For each bit position k, compute the cycle length 2^(k+1).", "Add complete cycles times 2^k.", "Add the excess of the partial cycle beyond 2^k.", "Sum over all positions."],
    tc: "O(log n)", sc: "O(1)",
    solve: (input) => { const n = BigInt(input.trim()); let total = 0n; for (let bit = 0n; (1n << bit) <= n; bit += 1n) { const cycle = 1n << (bit + 1n); const full = (n + 1n) / cycle; const rest = (n + 1n) % cycle; total += full * (1n << bit) + (rest > (1n << bit) ? rest - (1n << bit) : 0n); } return total.toString(); },
    samples: ["3", "1"],
    why: ["1 has one bit, 2 has one, 3 has two.", "1 has a single set bit."],
    hidden: ["2", "10", "1000000", "1000000000000000000"],
    edge: ["4"],
  },
];

export const HARD_A = specs.map(build);
