import { build, join, linesOut, reader, yesNo, type QuestionSpec } from "./catalog";

const A = (input: string) => {
  const r = reader(input);
  return r.ints(r.int());
};

const MOD = 1000000007n;

const specs: QuestionSpec[] = [
  {
    slug: "three-sum-count",
    title: "Count Triplets with a Given Sum",
    difficulty: "MEDIUM",
    topics: ["arrays", "searching"],
    d: "Count the triples of distinct positions i < j < k whose values sum to a target.",
    in: "First line: n and target.\nSecond line: n integers.",
    out: "The number of such triples.",
    c: "3 <= n <= 2000\n-10^6 <= values, target <= 10^6",
    hints: ["The brute force is O(n^3).", "Fix one element and the problem becomes two-sum on the rest.", "Sort first, then use two pointers for the inner search."],
    ap: "Sort the array. Fix the first index, then sweep two pointers inwards over the suffix, counting matches and skipping equal blocks in bulk.",
    it: "Sorting turns the inner two-sum into a monotone sweep, dropping a whole factor of n.",
    st: ["Sort the array.", "For each i, set lo = i+1 and hi = n-1.", "Move the pointers based on the sum against the target.", "Count matches, handling runs of equal values."],
    tc: "O(n^2)", sc: "O(1)",
    solve: (input) => { const r = reader(input); const n = r.int(), t = r.int(); const a = r.ints(n).sort((x, y) => x - y); let count = 0; for (let i = 0; i < n - 2; i += 1) { let lo = i + 1, hi = n - 1; while (lo < hi) { const s = a[i] + a[lo] + a[hi]; if (s === t) { if (a[lo] === a[hi]) { const k = hi - lo + 1; count += (k * (k - 1)) / 2; break; } let l = 1; while (a[lo] === a[lo + l]) l += 1; let h = 1; while (a[hi] === a[hi - h]) h += 1; count += l * h; lo += l; hi -= h; } else if (s < t) lo += 1; else hi -= 1; } } return String(count); },
    samples: ["5 0\n-1 0 1 2 -1", "4 10\n1 2 3 4"],
    why: ["The triples (-1,0,1) appear twice and (-1,-1,2) once.", "No triple reaches 10."],
    hidden: ["3 6\n1 2 3", "6 0\n0 0 0 0 0 0", "5 3\n1 1 1 1 1", "4 -6\n-1 -2 -3 -4"],
    edge: ["3 0\n0 0 0"],
    companies: ["amazon", "meta", "adobe"],
  },
  {
    slug: "longest-substring-no-repeat",
    title: "Longest Substring Without Repeating Characters",
    difficulty: "MEDIUM",
    topics: ["strings", "hashing"],
    d: "Find the length of the longest contiguous substring in which no character repeats.",
    in: "A single line containing a string without spaces.",
    out: "The length of the longest such substring.",
    c: "1 <= |s| <= 100000",
    hints: ["Checking every substring is O(n^2) or worse.", "Grow a window to the right and shrink it from the left when a repeat appears.", "Store the last index of each character so the left edge can jump."],
    ap: "Sliding window with a map from character to its most recent index. When a repeat is found inside the window, jump the left edge past the previous occurrence.",
    it: "The window only ever moves right, so both pointers together traverse the string once.",
    st: ["Set left = 0 and best = 0.", "For each right, if s[right] was seen at or after left, move left past it.", "Record the last index of s[right].", "Update best with right - left + 1."],
    tc: "O(n)", sc: "O(min(n, alphabet))",
    solve: (input) => { const s = input.trim(); const last = new Map<string, number>(); let left = 0, best = 0; for (let right = 0; right < s.length; right += 1) { const seen = last.get(s[right]); if (seen !== undefined && seen >= left) left = seen + 1; last.set(s[right], right); best = Math.max(best, right - left + 1); } return String(best); },
    samples: ["abcabcbb", "bbbbb"],
    why: ["'abc' has length 3.", "Every character repeats, so the best is a single 'b'."],
    hidden: ["a", "pwwkew", "abcdef", "dvdf"],
    edge: ["aa"],
    companies: ["amazon", "google", "meta", "microsoft"],
    sol: { PYTHON: `import sys\ns=sys.stdin.readline().strip()\nlast={};left=best=0\nfor r,ch in enumerate(s):\n    if ch in last and last[ch]>=left: left=last[ch]+1\n    last[ch]=r; best=max(best,r-left+1)\nprint(best)\n` },
  },
  {
    slug: "group-anagrams-count",
    title: "Group Anagrams",
    difficulty: "MEDIUM",
    topics: ["hashing", "strings"],
    d: "Group words that are anagrams of each other. Print the size of each group in decreasing order of size, breaking ties by the lexicographically smallest word in the group.",
    in: "First line: n.\nSecond line: n space-separated lowercase words.",
    out: "The group sizes, space separated.",
    c: "1 <= n <= 100000\nEach word is at most 20 characters.",
    hints: ["Anagrams need a canonical form you can use as a key.", "Sorting a word's letters produces that key.", "A frequency signature works too and avoids the sort."],
    ap: "Map every word to a canonical key (its sorted letters), bucket words by that key, then order the buckets by size and representative word.",
    it: "Grouping by an equivalence relation is exactly hashing by a canonical representative.",
    st: ["For each word compute its sorted-letter key.", "Append the word to that key's bucket.", "Sort buckets by descending size, then by smallest member.", "Print the sizes."],
    tc: "O(n * k log k)", sc: "O(n * k)",
    solve: (input) => { const r = reader(input); const n = r.int(); const words = r.strs(n); const groups = new Map<string, string[]>(); for (const w of words) { const key = w.split("").sort().join(""); groups.set(key, [...(groups.get(key) ?? []), w]); } const list = [...groups.values()].map((g) => ({ size: g.length, min: [...g].sort()[0] })); list.sort((a, b) => b.size - a.size || (a.min < b.min ? -1 : 1)); return join(list.map((g) => g.size)); },
    samples: ["6\neat tea tan ate nat bat", "3\nabc def ghi"],
    why: ["{eat,tea,ate} has 3, {tan,nat} has 2, {bat} has 1.", "No two words are anagrams."],
    hidden: ["1\nsolo", "4\naa aa aa aa", "5\nab ba abc cba x", "3\nlisten silent enlist"],
    edge: ["2\na b"],
    companies: ["amazon", "adobe", "meta"],
  },
  {
    slug: "subarray-sum-equals-k",
    title: "Subarrays with Sum K",
    difficulty: "MEDIUM",
    topics: ["arrays", "hashing"],
    d: "Count the contiguous subarrays whose elements sum to exactly k. Values may be negative.",
    in: "First line: n and k.\nSecond line: n integers.",
    out: "The number of subarrays summing to k.",
    c: "1 <= n <= 100000\n-10^9 <= values, k <= 10^9",
    hints: ["Negative values break the sliding-window approach.", "Write the subarray sum as a difference of prefix sums.", "Count how often each prefix sum has occurred so far."],
    ap: "Maintain a running prefix sum and a hash map counting how many times each prefix value has occurred. For each position, the number of subarrays ending there is the count of prefix - k.",
    it: "sum(l..r) = prefix[r] - prefix[l-1], so counting subarrays becomes counting matching earlier prefixes.",
    st: ["Seed the map with prefix 0 occurring once.", "Accumulate the running prefix sum.", "Add the stored count of prefix - k to the answer.", "Increment the count for the current prefix."],
    tc: "O(n)", sc: "O(n)",
    solve: (input) => { const r = reader(input); const n = r.int(), k = r.int(); const a = r.ints(n); const seen = new Map<number, number>([[0, 1]]); let prefix = 0, count = 0; for (const v of a) { prefix += v; count += seen.get(prefix - k) ?? 0; seen.set(prefix, (seen.get(prefix) ?? 0) + 1); } return String(count); },
    samples: ["4 2\n1 1 1 1", "5 3\n1 2 3 -3 3"],
    why: ["Three adjacent pairs sum to 2.", "Several windows reach 3, including ones spanning the negative value."],
    hidden: ["1 5\n5", "5 0\n0 0 0 0 0", "4 -2\n-1 -1 -1 -1", "3 10\n1 2 3"],
    edge: ["1 0\n0"],
    companies: ["amazon", "google", "microsoft"],
  },
  {
    slug: "product-except-self",
    title: "Product of Array Except Self",
    difficulty: "MEDIUM",
    topics: ["arrays"],
    d: "For each index print the product of every other element. Solve it without division. Report each product modulo 1000000007.",
    in: "First line: n.\nSecond line: n integers.",
    out: "n products, space separated, each modulo 1000000007.",
    c: "2 <= n <= 100000\n-1000 <= a[i] <= 1000",
    hints: ["Division fails when the array contains a zero.", "Split the product into everything left of i and everything right of i.", "Two sweeps, one from each end, build both halves."],
    ap: "Build prefix products left to right and suffix products right to left; the answer at each index is the product of the two.",
    it: "Excluding one element means splitting the array at it, which two directional scans compute in linear time.",
    st: ["Compute prefix[i] = product of a[0..i-1].", "Compute suffix[i] = product of a[i+1..n-1].", "Multiply them per index under the modulus."],
    tc: "O(n)", sc: "O(n)",
    solve: (input) => { const a = A(input).map(BigInt); const n = a.length; const out = new Array<bigint>(n).fill(1n); let run = 1n; for (let i = 0; i < n; i += 1) { out[i] = run; run = ((run * a[i]) % MOD + MOD) % MOD; } run = 1n; for (let i = n - 1; i >= 0; i -= 1) { out[i] = ((out[i] * run) % MOD + MOD) % MOD; run = ((run * a[i]) % MOD + MOD) % MOD; } return join(out.map(String)); },
    samples: ["4\n1 2 3 4", "3\n1 0 2"],
    why: ["Each entry is the product of the other three.", "Only the position of the zero has a non-zero product."],
    hidden: ["2\n3 4", "5\n1 1 1 1 1", "4\n-1 2 -3 4", "3\n0 0 5"],
    edge: ["2\n0 0"],
    companies: ["amazon", "meta", "microsoft"],
  },
  {
    slug: "rotate-matrix-90",
    title: "Rotate a Matrix by 90 Degrees",
    difficulty: "MEDIUM",
    topics: ["matrix"],
    d: "Rotate an n by n matrix 90 degrees clockwise in place.",
    in: "First line: n.\nNext n lines: n integers each.",
    out: "The rotated matrix, one row per line.",
    c: "1 <= n <= 500\n-10^9 <= values <= 10^9",
    hints: ["An extra matrix makes it easy but uses O(n^2) memory.", "A clockwise rotation is a transpose followed by a row reversal.", "Both steps can be done in place."],
    ap: "Transpose the matrix across the main diagonal, then reverse each row. Both steps are in place, so no extra matrix is needed.",
    it: "Rotation is a composition of two reflections, each of which is cheap in place.",
    st: ["Swap a[i][j] with a[j][i] for all i < j.", "Reverse every row.", "Print the result."],
    tc: "O(n^2)", sc: "O(1)",
    solve: (input) => { const r = reader(input); const n = r.int(); const g: number[][] = []; for (let i = 0; i < n; i += 1) g.push(r.ints(n)); const out: string[] = []; for (let i = 0; i < n; i += 1) { const row: number[] = []; for (let j = 0; j < n; j += 1) row.push(g[n - 1 - j][i]); out.push(join(row)); } return linesOut(out); },
    samples: ["3\n1 2 3\n4 5 6\n7 8 9", "1\n5"],
    why: ["The first column becomes the first row, bottom to top.", "A single cell is unchanged."],
    hidden: ["2\n1 2\n3 4", "4\n1 2 3 4\n5 6 7 8\n9 10 11 12\n13 14 15 16", "2\n-1 -2\n-3 -4", "3\n1 1 1\n2 2 2\n3 3 3"],
    edge: ["2\n0 0\n0 0"],
    companies: ["amazon", "microsoft", "adobe"],
  },
  {
    slug: "set-matrix-zeroes",
    title: "Set Matrix Zeroes",
    difficulty: "MEDIUM",
    topics: ["matrix"],
    d: "If any cell is zero, set its entire row and column to zero. Use O(1) extra space beyond the matrix.",
    in: "First line: n and m.\nNext n lines: m integers each.",
    out: "The modified matrix, one row per line.",
    c: "1 <= n, m <= 500",
    hints: ["Zeroing as you scan cascades incorrectly.", "You need to record which rows and columns to clear before clearing anything.", "Use the first row and first column as the marker storage."],
    ap: "Use the first row and column as flags. Record whether they themselves contain a zero, mark the rest, then apply the marks inward-out.",
    it: "The matrix already has O(n+m) cells that can serve as scratch space, which is what removes the extra memory.",
    st: ["Record whether row 0 and column 0 contain a zero.", "For every inner zero, mark its row header and column header.", "Clear inner cells whose header is marked.", "Finally clear row 0 and column 0 if flagged."],
    tc: "O(nm)", sc: "O(1)",
    solve: (input) => { const r = reader(input); const n = r.int(), m = r.int(); const g: number[][] = []; for (let i = 0; i < n; i += 1) g.push(r.ints(m)); const rows = new Set<number>(), cols = new Set<number>(); for (let i = 0; i < n; i += 1) for (let j = 0; j < m; j += 1) if (g[i][j] === 0) { rows.add(i); cols.add(j); } const out: string[] = []; for (let i = 0; i < n; i += 1) out.push(join(g[i].map((v, j) => (rows.has(i) || cols.has(j) ? 0 : v)))); return linesOut(out); },
    samples: ["3 3\n1 1 1\n1 0 1\n1 1 1", "2 2\n1 2\n3 4"],
    why: ["The middle row and column are cleared.", "There is no zero, so nothing changes."],
    hidden: ["1 1\n0", "2 3\n0 1 2\n3 4 5", "3 3\n0 0 0\n0 0 0\n0 0 0", "2 2\n1 0\n0 1"],
    edge: ["1 1\n1"],
    companies: ["amazon", "microsoft"],
  },
  {
    slug: "search-2d-matrix",
    title: "Search a Sorted 2D Matrix",
    difficulty: "MEDIUM",
    topics: ["matrix", "searching"],
    d: "Each row is sorted left to right and each column is sorted top to bottom. Decide whether a target value is present.",
    in: "First line: n, m and target.\nNext n lines: m integers each.",
    out: "YES if the target is present, otherwise NO.",
    c: "1 <= n, m <= 1000",
    hints: ["A row-by-row binary search costs O(n log m).", "Look for a corner where the comparison decides an entire row or column.", "Start at the top-right cell."],
    ap: "Start at the top-right corner. A value larger than the target eliminates its column; a smaller value eliminates its row. Each step removes a full row or column.",
    it: "Only the top-right and bottom-left corners are simultaneously extreme in both dimensions, which is what makes the elimination unambiguous.",
    st: ["Set i = 0 and j = m-1.", "If the cell equals the target, answer YES.", "If it exceeds the target decrement j, otherwise increment i.", "Answer NO when the indices leave the matrix."],
    tc: "O(n + m)", sc: "O(1)",
    solve: (input) => { const r = reader(input); const n = r.int(), m = r.int(), t = r.int(); const g: number[][] = []; for (let i = 0; i < n; i += 1) g.push(r.ints(m)); let i = 0, j = m - 1; while (i < n && j >= 0) { if (g[i][j] === t) return "YES"; if (g[i][j] > t) j -= 1; else i += 1; } return "NO"; },
    samples: ["3 3 5\n1 4 7\n2 5 8\n3 6 9", "2 2 10\n1 2\n3 4"],
    why: ["5 sits in the middle of the matrix.", "10 exceeds every value."],
    hidden: ["1 1 1\n1", "3 3 1\n1 4 7\n2 5 8\n3 6 9", "3 3 9\n1 4 7\n2 5 8\n3 6 9", "2 3 4\n1 2 3\n4 5 6"],
    edge: ["1 1 2\n1"],
    companies: ["amazon", "google"],
  },
  {
    slug: "merge-intervals",
    title: "Merge Overlapping Intervals",
    difficulty: "MEDIUM",
    topics: ["sorting", "greedy"],
    d: "Merge all overlapping intervals and print the result sorted by start. Touching intervals such as [1,2] and [2,3] merge.",
    in: "First line: n.\nNext n lines: start and end.",
    out: "One merged interval per line as 'start end'.",
    c: "1 <= n <= 100000\n0 <= start <= end <= 10^9",
    hints: ["Unsorted intervals make overlap hard to detect.", "Sort by start time first.", "Then a new interval either extends the last merged one or begins a new one."],
    ap: "Sort by start, then sweep: extend the current interval while the next one starts at or before its end, otherwise emit and restart.",
    it: "After sorting by start, overlap is a purely local property between consecutive intervals.",
    st: ["Sort intervals by start.", "Hold the current merged interval.", "If the next start is within it, extend the end to the maximum.", "Otherwise emit and start a new interval."],
    tc: "O(n log n)", sc: "O(n)",
    solve: (input) => { const r = reader(input); const n = r.int(); const iv: Array<[number, number]> = []; for (let i = 0; i < n; i += 1) iv.push([r.int(), r.int()]); iv.sort((a, b) => a[0] - b[0] || a[1] - b[1]); const out: Array<[number, number]> = []; for (const [s, e] of iv) { const last = out[out.length - 1]; if (last && s <= last[1]) last[1] = Math.max(last[1], e); else out.push([s, e]); } return linesOut(out.map(([s, e]) => `${s} ${e}`)); },
    samples: ["4\n1 3\n2 6\n8 10\n15 18", "2\n1 4\n4 5"],
    why: ["[1,3] and [2,6] overlap into [1,6].", "Touching intervals merge."],
    hidden: ["1\n0 0", "3\n1 10\n2 3\n4 5", "3\n1 2\n3 4\n5 6", "4\n5 6\n1 2\n3 4\n2 3"],
    edge: ["2\n0 1000000000\n1 2"],
    companies: ["amazon", "google", "meta", "microsoft"],
  },
  {
    slug: "insert-interval",
    title: "Insert an Interval",
    difficulty: "MEDIUM",
    topics: ["sorting", "greedy"],
    d: "Insert a new interval into a sorted list of non-overlapping intervals, merging where necessary.",
    in: "First line: n.\nNext n lines: start and end, sorted and non-overlapping.\nLast line: the new interval's start and end.",
    out: "One interval per line after insertion.",
    c: "0 <= n <= 100000\n0 <= start <= end <= 10^9",
    hints: ["Existing intervals are already sorted and disjoint.", "Split them into three groups relative to the new interval.", "Everything strictly before, everything overlapping, everything strictly after."],
    ap: "Emit intervals ending before the new one, absorb every overlapping interval into an expanding merged interval, then emit the rest.",
    it: "Sortedness means the overlapping intervals form one contiguous block, so a single pass suffices.",
    st: ["Copy intervals whose end is below the new start.", "While the next interval starts at or before the new end, widen the new interval.", "Emit the widened interval.", "Copy the remaining intervals."],
    tc: "O(n)", sc: "O(n)",
    solve: (input) => { const r = reader(input); const n = r.int(); const iv: Array<[number, number]> = []; for (let i = 0; i < n; i += 1) iv.push([r.int(), r.int()]); let [ns, ne] = [r.int(), r.int()]; const out: Array<[number, number]> = []; let i = 0; while (i < n && iv[i][1] < ns) out.push(iv[i++]); while (i < n && iv[i][0] <= ne) { ns = Math.min(ns, iv[i][0]); ne = Math.max(ne, iv[i][1]); i += 1; } out.push([ns, ne]); while (i < n) out.push(iv[i++]); return linesOut(out.map(([s, e]) => `${s} ${e}`)); },
    samples: ["3\n1 3\n6 9\n12 15\n2 7", "0\n1 2"],
    why: ["[2,7] merges with [1,3] and [6,9].", "The list was empty, so the new interval stands alone."],
    hidden: ["2\n1 2\n5 6\n3 4", "2\n1 5\n10 20\n0 30", "1\n1 5\n6 7", "3\n1 2\n3 4\n5 6\n0 0"],
    edge: ["1\n1 1\n1 1"],
  },
  {
    slug: "non-overlapping-intervals",
    title: "Minimum Intervals to Remove",
    difficulty: "MEDIUM",
    topics: ["greedy", "sorting"],
    d: "Find the fewest intervals to remove so that the remaining ones do not overlap. Intervals that only touch at an endpoint do not overlap.",
    in: "First line: n.\nNext n lines: start and end.",
    out: "The minimum number of removals.",
    c: "1 <= n <= 100000\n0 <= start < end <= 10^9",
    hints: ["Removing the fewest is the same as keeping the most.", "That is the activity-selection problem.", "Sort by end time and take greedily."],
    ap: "Sort by end time and greedily keep every interval that starts at or after the last kept end. Removals are n minus the number kept.",
    it: "Keeping the earliest finisher leaves the most room for what follows, so greedy is optimal.",
    st: ["Sort intervals by end.", "Track the last kept end.", "Keep an interval when its start is not before that end.", "Print n minus the kept count."],
    tc: "O(n log n)", sc: "O(n)",
    solve: (input) => { const r = reader(input); const n = r.int(); const iv: Array<[number, number]> = []; for (let i = 0; i < n; i += 1) iv.push([r.int(), r.int()]); iv.sort((a, b) => a[1] - b[1]); let kept = 0, last = -Infinity; for (const [s, e] of iv) if (s >= last) { kept += 1; last = e; } return String(n - kept); },
    samples: ["4\n1 2\n2 3\n3 4\n1 3", "3\n1 2\n1 2\n1 2"],
    why: ["Removing [1,3] leaves a chain of three.", "Two of the three identical intervals must go."],
    hidden: ["1\n0 1", "3\n1 2\n2 3\n3 4", "4\n1 100\n2 3\n4 5\n6 7", "2\n1 5\n2 3"],
    edge: ["2\n0 1\n1 2"],
  },
  {
    slug: "meeting-rooms-min",
    title: "Minimum Meeting Rooms",
    difficulty: "MEDIUM",
    topics: ["heap", "sorting", "greedy"],
    d: "Given meeting start and end times, find the minimum number of rooms needed so that no two concurrent meetings share a room.",
    in: "First line: n.\nNext n lines: start and end.",
    out: "The minimum number of rooms.",
    c: "1 <= n <= 100000\n0 <= start < end <= 10^9",
    hints: ["The answer is the maximum number of meetings running at once.", "Think of starts as +1 events and ends as -1 events.", "Sort the events and sweep, or use a min-heap of end times."],
    ap: "Sweep line over sorted events: a start adds a room, an end frees one, and the answer is the peak concurrency. Process ends before starts at equal timestamps.",
    it: "The room count is exactly the maximum overlap depth, which a sweep computes directly.",
    st: ["Create +1 events at starts and -1 events at ends.", "Sort by time, ends before starts on ties.", "Sweep maintaining a running count.", "Print the maximum count observed."],
    tc: "O(n log n)", sc: "O(n)",
    solve: (input) => { const r = reader(input); const n = r.int(); const ev: Array<[number, number]> = []; for (let i = 0; i < n; i += 1) { const s = r.int(), e = r.int(); ev.push([s, 1], [e, -1]); } ev.sort((a, b) => a[0] - b[0] || a[1] - b[1]); let cur = 0, best = 0; for (const [, delta] of ev) { cur += delta; best = Math.max(best, cur); } return String(best); },
    samples: ["3\n0 30\n5 10\n15 20", "2\n7 10\n2 4"],
    why: ["The first meeting overlaps both others, but those two do not overlap each other.", "The meetings are disjoint."],
    hidden: ["1\n0 1", "3\n1 5\n2 6\n3 7", "4\n1 2\n2 3\n3 4\n4 5", "3\n0 10\n0 10\n0 10"],
    edge: ["2\n0 1\n1 2"],
    companies: ["google", "amazon", "meta"],
  },
  {
    slug: "kth-largest-element",
    title: "Kth Largest Element",
    difficulty: "MEDIUM",
    topics: ["heap", "sorting"],
    d: "Find the kth largest value in an array, counting duplicates as separate elements.",
    in: "First line: n and k.\nSecond line: n integers.",
    out: "The kth largest value.",
    c: "1 <= k <= n <= 100000\n-10^9 <= a[i] <= 10^9",
    hints: ["Full sorting costs O(n log n).", "A size-k min-heap keeps only the candidates that matter.", "Quickselect reaches O(n) on average."],
    ap: "Maintain a min-heap of the k largest values seen so far; its root is the answer. Quickselect gives the same result in expected linear time.",
    it: "You never need the relative order of the n-k elements you discard.",
    st: ["Push the first k elements into a min-heap.", "For each later value, if it exceeds the root, replace the root.", "The root is the kth largest."],
    tc: "O(n log k)", sc: "O(k)",
    solve: (input) => { const r = reader(input); const n = r.int(), k = r.int(); return String(r.ints(n).sort((x, y) => y - x)[k - 1]); },
    samples: ["6 2\n3 2 1 5 6 4", "5 1\n1 2 3 4 5"],
    why: ["Sorted descending the array starts 6, 5, so the 2nd largest is 5.", "The largest value is 5."],
    hidden: ["1 1\n7", "5 5\n1 2 3 4 5", "6 4\n3 2 3 1 2 4", "4 2\n-1 -2 -3 -4"],
    edge: ["2 2\n1000000000 -1000000000"],
    companies: ["amazon", "meta", "microsoft"],
  },
  {
    slug: "top-k-frequent",
    title: "Top K Frequent Elements",
    difficulty: "MEDIUM",
    topics: ["heap", "hashing"],
    d: "Print the k most frequent values. Break ties by preferring the smaller value, and print the result in decreasing order of frequency.",
    in: "First line: n and k.\nSecond line: n integers.",
    out: "The k values, space separated.",
    c: "1 <= k <= n <= 100000",
    hints: ["Counting comes first.", "Then you need the k largest counts.", "Bucket by frequency for a linear-time selection."],
    ap: "Count with a hash map, then select the k highest counts, breaking ties by the smaller value. Bucketing by frequency avoids the sort entirely.",
    it: "Frequencies are bounded by n, so they can be bucketed instead of compared.",
    st: ["Count occurrences of each value.", "Order the entries by descending count, then ascending value.", "Take the first k.", "Print them."],
    tc: "O(n log n)", sc: "O(n)",
    solve: (input) => { const r = reader(input); const n = r.int(), k = r.int(); const a = r.ints(n); const m = new Map<number, number>(); for (const v of a) m.set(v, (m.get(v) ?? 0) + 1); return join([...m.entries()].sort((x, y) => y[1] - x[1] || x[0] - y[0]).slice(0, k).map(([v]) => v)); },
    samples: ["6 2\n1 1 1 2 2 3", "4 1\n1 2 3 4"],
    why: ["1 occurs three times and 2 occurs twice.", "All counts tie, so the smallest value wins."],
    hidden: ["1 1\n5", "5 2\n4 4 3 3 2", "6 3\n1 2 3 1 2 1", "5 5\n1 2 3 4 5"],
    edge: ["2 2\n1 1"],
    companies: ["amazon", "meta", "adobe"],
  },
  {
    slug: "sort-by-frequency",
    title: "Sort by Frequency",
    difficulty: "MEDIUM",
    topics: ["hashing", "sorting"],
    d: "Sort an array so that values with higher frequency come first. Values with equal frequency are ordered by increasing value.",
    in: "First line: n.\nSecond line: n integers.",
    out: "The sorted array, space separated.",
    c: "1 <= n <= 100000",
    hints: ["The comparison key is the frequency, not the value.", "Count first, then sort.", "Break ties with the value itself so the output is deterministic."],
    ap: "Count occurrences, then sort the distinct values by descending count and ascending value, expanding each into its repetitions.",
    it: "Making the tie-break explicit is what turns an ambiguous ordering into a well-defined one.",
    st: ["Count every value.", "Sort distinct values by (-count, value).", "Emit each value count times."],
    tc: "O(n log n)", sc: "O(n)",
    solve: (input) => { const a = A(input); const m = new Map<number, number>(); for (const v of a) m.set(v, (m.get(v) ?? 0) + 1); const out: number[] = []; for (const [v, c] of [...m.entries()].sort((x, y) => y[1] - x[1] || x[0] - y[0])) for (let i = 0; i < c; i += 1) out.push(v); return join(out); },
    samples: ["6\n2 3 2 4 5 12", "5\n1 1 2 2 3"],
    why: ["2 appears twice, then the singletons in increasing order.", "Both pairs tie, so 1 precedes 2."],
    hidden: ["1\n5", "4\n4 4 4 4", "6\n1 2 3 4 5 6", "5\n-1 -1 0 0 1"],
    edge: ["2\n2 1"],
  },
  {
    slug: "longest-consecutive-sequence",
    title: "Longest Consecutive Sequence",
    difficulty: "MEDIUM",
    topics: ["hashing", "arrays"],
    d: "Find the length of the longest run of consecutive integers present in the array. The array is not sorted and the run need not be contiguous in it.",
    in: "First line: n.\nSecond line: n integers.",
    out: "The length of the longest consecutive run.",
    c: "1 <= n <= 100000\n-10^9 <= a[i] <= 10^9",
    hints: ["Sorting gives O(n log n); a hash set can do better.", "A run should only be counted from its smallest member.", "x starts a run exactly when x-1 is absent."],
    ap: "Insert every value into a hash set, then for each value that has no predecessor in the set, walk upwards counting the run.",
    it: "Only counting from run starts means every element is walked at most once overall, keeping the total linear.",
    st: ["Insert all values into a set.", "For each value x with x-1 absent, walk x+1, x+2, ... while present.", "Track the longest walk."],
    tc: "O(n)", sc: "O(n)",
    solve: (input) => { const s = new Set(A(input)); let best = 0; for (const v of s) { if (s.has(v - 1)) continue; let len = 1; while (s.has(v + len)) len += 1; best = Math.max(best, len); } return String(best); },
    samples: ["6\n100 4 200 1 3 2", "4\n1 1 1 1"],
    why: ["1, 2, 3, 4 form a run of length four.", "A single distinct value gives a run of one."],
    hidden: ["1\n5", "5\n1 2 3 4 5", "6\n9 1 4 7 3 2", "4\n-3 -2 -1 0"],
    edge: ["2\n1000000000 -1000000000"],
    companies: ["google", "amazon", "meta"],
  },
  {
    slug: "sort-merge-sort",
    title: "Merge Sort",
    difficulty: "MEDIUM",
    topics: ["sorting", "recursion"],
    d: "Sort an array using merge sort and print the result.",
    in: "First line: n.\nSecond line: n integers.",
    out: "The sorted array, space separated.",
    c: "1 <= n <= 200000\n-10^9 <= a[i] <= 10^9",
    hints: ["Divide the array in half and sort each half.", "The merge step assumes both halves are already sorted.", "Merging two sorted runs is a two-pointer sweep."],
    ap: "Divide and conquer: recursively sort both halves, then merge them with a two-pointer sweep into a scratch buffer.",
    it: "Merge sort is stable and has a guaranteed O(n log n) bound, which quicksort does not.",
    st: ["Split the range at the midpoint.", "Recursively sort both halves.", "Merge them by repeatedly taking the smaller head.", "Copy the merged run back."],
    tc: "O(n log n)", sc: "O(n)",
    solve: (input) => join(A(input).sort((x, y) => x - y)),
    samples: ["6\n38 27 43 3 9 82", "1\n5"],
    why: ["The halves are sorted and merged.", "A single element is already sorted."],
    hidden: ["4\n4 3 2 1", "5\n1 2 3 4 5", "6\n2 2 1 1 3 3", "5\n-1 -5 0 3 -2"],
    edge: ["2\n1000000000 -1000000000"],
  },
  {
    slug: "sort-quick-sort",
    title: "Quick Sort",
    difficulty: "MEDIUM",
    topics: ["sorting", "recursion"],
    d: "Sort an array using quicksort and print the result.",
    in: "First line: n.\nSecond line: n integers.",
    out: "The sorted array, space separated.",
    c: "1 <= n <= 200000\n-10^9 <= a[i] <= 10^9",
    hints: ["Partition around a pivot so smaller values end up left of it.", "After partitioning, the pivot is in its final position.", "Choose the pivot carefully or adversarial input degrades to O(n^2)."],
    ap: "Partition around a pivot, then recurse into both sides. Random or median-of-three pivot selection keeps the expected cost O(n log n).",
    it: "Quicksort's speed comes from partitioning in place; its risk is a bad pivot, which randomisation removes in expectation.",
    st: ["Choose a pivot.", "Partition so that smaller values precede it and larger follow.", "Recurse on both partitions.", "Print the array."],
    tc: "O(n log n) expected", sc: "O(log n) stack",
    solve: (input) => join(A(input).sort((x, y) => x - y)),
    samples: ["6\n10 7 8 9 1 5", "3\n3 1 2"],
    why: ["Partitioning places each pivot in its final slot.", "Three elements sort in one partition step."],
    hidden: ["1\n1", "5\n5 4 3 2 1", "6\n1 1 1 1 1 1", "4\n-2 -3 -1 0"],
    edge: ["2\n2 1"],
  },
  {
    slug: "count-inversions",
    title: "Count Inversions",
    difficulty: "MEDIUM",
    topics: ["sorting", "advanced"],
    d: "Count the pairs of positions i < j with a[i] > a[j].",
    in: "First line: n.\nSecond line: n integers.",
    out: "The number of inversions.",
    c: "1 <= n <= 100000\n-10^9 <= a[i] <= 10^9",
    hints: ["The brute force is O(n^2).", "Merge sort already compares elements across halves.", "During the merge, taking an element from the right half counts inversions in bulk."],
    ap: "Modified merge sort. When the merge takes an element from the right half, every remaining element of the left half forms an inversion with it, so add that count.",
    it: "Sorting has to examine every out-of-order pair anyway, so counting rides along at no asymptotic cost.",
    st: ["Recursively sort and count both halves.", "Merge the halves.", "When taking from the right, add the number of remaining left elements.", "Return the total."],
    tc: "O(n log n)", sc: "O(n)",
    solve: (input) => { const a = A(input); let count = 0; const sortCount = (arr: number[]): number[] => { if (arr.length <= 1) return arr; const mid = arr.length >> 1; const left = sortCount(arr.slice(0, mid)); const right = sortCount(arr.slice(mid)); const out: number[] = []; let i = 0, j = 0; while (i < left.length && j < right.length) { if (left[i] <= right[j]) out.push(left[i++]); else { count += left.length - i; out.push(right[j++]); } } while (i < left.length) out.push(left[i++]); while (j < right.length) out.push(right[j++]); return out; }; sortCount(a); return String(count); },
    samples: ["5\n2 4 1 3 5", "3\n3 2 1"],
    why: ["The inversions are (2,1), (4,1) and (4,3).", "Every pair is inverted."],
    hidden: ["1\n1", "4\n1 2 3 4", "5\n5 4 3 2 1", "4\n1 1 1 1"],
    edge: ["2\n2 1"],
    companies: ["amazon", "google"],
  },
  {
    slug: "search-rotated-sorted",
    title: "Search in a Rotated Sorted Array",
    difficulty: "MEDIUM",
    topics: ["searching"],
    d: "A sorted array of distinct values has been rotated at an unknown pivot. Find the index of a target, or -1.",
    in: "First line: n and target.\nSecond line: n integers.",
    out: "The index of the target, or -1.",
    c: "1 <= n <= 200000\nAll values are distinct.",
    hints: ["A plain binary search breaks because the array is not globally sorted.", "At least one half of any split is still sorted.", "Identify which half is sorted, then test whether the target lies inside it."],
    ap: "Binary search with an extra step: determine which half is sorted, and recurse into it when the target lies within its range, otherwise into the other half.",
    it: "A single rotation leaves at most one discontinuity, so one of the two halves is always ordinary.",
    st: ["Compute mid.", "If a[lo] <= a[mid], the left half is sorted.", "Check whether the target lies in that sorted range and move accordingly.", "Otherwise apply the same test to the right half."],
    tc: "O(log n)", sc: "O(1)",
    solve: (input) => { const r = reader(input); const n = r.int(), t = r.int(); const a = r.ints(n); let lo = 0, hi = n - 1; while (lo <= hi) { const mid = (lo + hi) >> 1; if (a[mid] === t) return String(mid); if (a[lo] <= a[mid]) { if (t >= a[lo] && t < a[mid]) hi = mid - 1; else lo = mid + 1; } else { if (t > a[mid] && t <= a[hi]) lo = mid + 1; else hi = mid - 1; } } return "-1"; },
    samples: ["7 0\n4 5 6 7 0 1 2", "7 3\n4 5 6 7 0 1 2"],
    why: ["0 sits at index 4.", "3 is absent."],
    hidden: ["1 1\n1", "5 5\n5 1 2 3 4", "5 4\n5 1 2 3 4", "3 2\n3 1 2"],
    edge: ["2 1\n2 1"],
    companies: ["amazon", "meta", "microsoft", "google"],
  },
  {
    slug: "find-peak-element",
    title: "Find a Peak Element",
    difficulty: "MEDIUM",
    topics: ["searching"],
    d: "A peak is an element strictly greater than its neighbours; out-of-range neighbours count as negative infinity. Return the index of any peak.",
    in: "First line: n.\nSecond line: n integers, no two adjacent values equal.",
    out: "The index of any peak.",
    c: "1 <= n <= 200000",
    hints: ["A linear scan works but does not use the structure.", "If a[mid] < a[mid+1], a peak must exist to the right.", "That gives a binary search even though the array is unsorted."],
    ap: "Binary search on the slope: move towards the higher neighbour, which guarantees a peak in that direction.",
    it: "Following an ascent must eventually stop, and where it stops is a peak — so the search never discards all the peaks.",
    st: ["Set lo = 0 and hi = n-1.", "While lo < hi, compute mid.", "If a[mid] < a[mid+1] set lo = mid+1, else hi = mid.", "Print lo."],
    tc: "O(log n)", sc: "O(1)",
    solve: (input) => { const a = A(input); let lo = 0, hi = a.length - 1; while (lo < hi) { const mid = (lo + hi) >> 1; if (a[mid] < a[mid + 1]) lo = mid + 1; else hi = mid; } return String(lo); },
    samples: ["4\n1 2 3 1", "5\n1 2 1 3 5"],
    why: ["Index 2 holds 3, greater than both neighbours.", "The search settles on index 4."],
    hidden: ["1\n1", "2\n1 2", "5\n5 4 3 2 1", "6\n1 3 2 4 3 5"],
    edge: ["2\n2 1"],
  },
  {
    slug: "koko-eating-bananas",
    title: "Minimum Eating Speed",
    difficulty: "MEDIUM",
    topics: ["searching", "greedy"],
    d: "There are n piles of bananas and h hours available. At a chosen integer speed k, each hour one pile is eaten from, consuming min(k, remaining) bananas. Find the smallest k that finishes every pile within h hours.",
    in: "First line: n and h.\nSecond line: n pile sizes.",
    out: "The minimum speed.",
    c: "1 <= n <= 100000\nn <= h <= 10^9\n1 <= pile <= 10^9",
    hints: ["Trying every speed is far too slow.", "The predicate 'speed k finishes in time' is monotone.", "Binary search on the answer, computing the hours needed for each candidate."],
    ap: "Binary search on the speed. For a candidate k, the hours needed are the sum of ceil(pile/k), and that total decreases as k grows.",
    it: "Binary search does not need a sorted array — only a monotone predicate over the answer space.",
    st: ["Search k over [1, max pile].", "For each candidate compute the total hours.", "Move the bound that keeps the total within h.", "Print the smallest feasible k."],
    tc: "O(n log(max pile))", sc: "O(1)",
    solve: (input) => { const r = reader(input); const n = r.int(), h = r.int(); const a = r.ints(n); let lo = 1, hi = Math.max(...a), best = hi; while (lo <= hi) { const k = Math.floor((lo + hi) / 2); let hours = 0; for (const p of a) hours += Math.ceil(p / k); if (hours <= h) { best = k; hi = k - 1; } else lo = k + 1; } return String(best); },
    samples: ["4 8\n3 6 7 11", "4 5\n30 11 23 4"],
    why: ["Speed 4 finishes in exactly 8 hours.", "Speed 30 is the smallest that fits five hours."],
    hidden: ["1 1\n1", "3 3\n1 1 1", "2 10\n1000000000 1", "5 5\n1 2 3 4 5"],
    edge: ["1 1\n1000000000"],
    companies: ["amazon", "google"],
  },
  {
    slug: "capacity-ship-packages",
    title: "Minimum Ship Capacity",
    difficulty: "MEDIUM",
    topics: ["searching", "greedy"],
    d: "Packages must be shipped in their given order within d days. Each day the ship carries a prefix of the remaining packages without exceeding its capacity. Find the smallest capacity that works.",
    in: "First line: n and d.\nSecond line: n package weights.",
    out: "The minimum capacity.",
    c: "1 <= n <= 100000\n1 <= d <= n\n1 <= weight <= 500",
    hints: ["Capacity must be at least the heaviest package.", "It never needs to exceed the total weight.", "Feasibility is monotone in the capacity, so binary search it."],
    ap: "Binary search the capacity between max(weight) and sum(weight), greedily filling days to test feasibility.",
    it: "The greedy packing is optimal for a fixed capacity, which makes the feasibility test exact.",
    st: ["Set lo = max weight and hi = total weight.", "For each candidate, simulate greedy day filling.", "If the days used fit within d, shrink hi; otherwise raise lo.", "Print the smallest feasible capacity."],
    tc: "O(n log(total))", sc: "O(1)",
    solve: (input) => { const r = reader(input); const n = r.int(), d = r.int(); const a = r.ints(n); let lo = Math.max(...a), hi = a.reduce((s, v) => s + v, 0), best = hi; while (lo <= hi) { const cap = Math.floor((lo + hi) / 2); let days = 1, load = 0; for (const w of a) { if (load + w > cap) { days += 1; load = 0; } load += w; } if (days <= d) { best = cap; hi = cap - 1; } else lo = cap + 1; } return String(best); },
    samples: ["10 5\n1 2 3 4 5 6 7 8 9 10", "5 5\n1 2 3 1 1"],
    why: ["Capacity 15 splits the packages into five days.", "Each package can take its own day."],
    hidden: ["1 1\n5", "3 1\n1 2 3", "4 4\n5 5 5 5", "5 2\n1 1 1 1 1"],
    edge: ["1 1\n1"],
  },
  {
    slug: "longest-palindromic-substring",
    title: "Longest Palindromic Substring",
    difficulty: "MEDIUM",
    topics: ["strings", "dp"],
    d: "Find the length of the longest contiguous palindromic substring.",
    in: "A single line containing a string without spaces.",
    out: "The length of the longest palindromic substring.",
    c: "1 <= |s| <= 3000",
    hints: ["Checking every substring for palindromicity is O(n^3).", "A palindrome is defined by its centre.", "Expand outwards from each of the 2n-1 possible centres."],
    ap: "Expand around every centre, handling odd and even lengths separately, and keep the longest expansion.",
    it: "Every palindrome has a unique centre, so enumerating centres enumerates all palindromes in O(n^2).",
    st: ["For each index, expand around it as an odd centre.", "Also expand around each gap as an even centre.", "Track the longest expansion."],
    tc: "O(n^2)", sc: "O(1)",
    solve: (input) => { const s = input.trim(); let best = 0; const expand = (l: number, r: number) => { while (l >= 0 && r < s.length && s[l] === s[r]) { best = Math.max(best, r - l + 1); l -= 1; r += 1; } }; for (let i = 0; i < s.length; i += 1) { expand(i, i); expand(i, i + 1); } return String(best); },
    samples: ["babad", "cbbd"],
    why: ["'bab' and 'aba' both have length 3.", "'bb' has length 2."],
    hidden: ["a", "aaaa", "abcde", "forgegrof"],
    edge: ["ab"],
    companies: ["amazon", "microsoft", "adobe"],
  },
  {
    slug: "string-permutations-count",
    title: "Distinct Permutations",
    difficulty: "MEDIUM",
    topics: ["backtracking", "math"],
    d: "Count the distinct permutations of a string, reported modulo 1000000007.",
    in: "A single line containing a lowercase string.",
    out: "The number of distinct permutations modulo 1000000007.",
    c: "1 <= |s| <= 1000",
    hints: ["Generating them all is impossible at this length.", "There is a closed form based on letter frequencies.", "n! divided by the product of each letter count's factorial."],
    ap: "Apply the multinomial formula n! / (c1! c2! ...), computing the modular inverse of each factorial via Fermat's little theorem.",
    it: "Identical letters are interchangeable, and dividing by their factorials removes exactly the duplicate orderings.",
    st: ["Count each letter's frequency.", "Compute n! modulo p.", "Divide by each count's factorial using modular inverses.", "Print the result."],
    tc: "O(n log p)", sc: "O(n)",
    solve: (input) => { const s = input.trim(); const p = MOD; const power = (b: bigint, e: bigint): bigint => { let result = 1n; let base = b % p; let exp = e; while (exp > 0n) { if (exp & 1n) result = (result * base) % p; base = (base * base) % p; exp >>= 1n; } return result; }; const fact: bigint[] = [1n]; for (let i = 1; i <= s.length; i += 1) fact.push((fact[i - 1] * BigInt(i)) % p); let answer = fact[s.length]; const count = new Map<string, number>(); for (const ch of s) count.set(ch, (count.get(ch) ?? 0) + 1); for (const c of count.values()) answer = (answer * power(fact[c], p - 2n)) % p; return answer.toString(); },
    samples: ["aab", "abc"],
    why: ["aab, aba and baa.", "All 3! = 6 orderings are distinct."],
    hidden: ["a", "aaaa", "abcd", "aabb"],
    edge: ["ab"],
  },
  {
    slug: "generate-subsets",
    title: "Generate All Subsets",
    difficulty: "MEDIUM",
    topics: ["backtracking", "recursion"],
    d: "Print every subset of a set of distinct integers. Sort each subset ascending, and print subsets in lexicographic order of their sorted contents. The empty subset is printed as the word EMPTY.",
    in: "First line: n.\nSecond line: n distinct integers.",
    out: "One subset per line.",
    c: "1 <= n <= 15",
    hints: ["Each element is either included or excluded.", "That is a binary decision per element, so 2^n subsets.", "Recurse, or iterate over bitmasks from 0 to 2^n - 1."],
    ap: "Enumerate bitmasks from 0 to 2^n - 1 over the sorted input, emitting the elements whose bit is set.",
    it: "A subset is exactly a binary string of inclusion decisions, so bitmask enumeration is the natural encoding.",
    st: ["Sort the input.", "For each mask, collect the elements whose bit is set.", "Sort the resulting list of subsets lexicographically.", "Print them."],
    tc: "O(2^n * n)", sc: "O(n)",
    solve: (input) => { const a = A(input).sort((x, y) => x - y); const n = a.length; const subsets: number[][] = []; for (let mask = 0; mask < 1 << n; mask += 1) { const sub: number[] = []; for (let i = 0; i < n; i += 1) if (mask & (1 << i)) sub.push(a[i]); subsets.push(sub); } subsets.sort((x, y) => { for (let i = 0; i < Math.min(x.length, y.length); i += 1) if (x[i] !== y[i]) return x[i] - y[i]; return x.length - y.length; }); return linesOut(subsets.map((s) => (s.length ? join(s) : "EMPTY"))); },
    samples: ["2\n1 2", "1\n5"],
    why: ["The four subsets of {1,2}.", "The empty set and {5}."],
    hidden: ["3\n1 2 3", "3\n3 1 2", "2\n-1 1", "4\n1 2 3 4"],
    edge: ["1\n0"],
    companies: ["amazon", "adobe"],
  },
  {
    slug: "combination-sum-count",
    title: "Combination Sum",
    difficulty: "MEDIUM",
    topics: ["backtracking"],
    d: "Given distinct positive candidates, count the multisets of candidates that sum to a target. Each candidate may be reused any number of times.",
    in: "First line: n and target.\nSecond line: n distinct positive integers.",
    out: "The number of distinct combinations.",
    c: "1 <= n <= 20\n1 <= target <= 500\n1 <= candidate <= 200",
    hints: ["Order must not matter, so avoid counting permutations.", "Fix an index and never look backwards.", "Recurse with the same index to allow reuse."],
    ap: "Backtracking that never revisits an earlier candidate index, which enforces non-decreasing selections and therefore counts each multiset once.",
    it: "The index bound is what turns permutation counting into combination counting.",
    st: ["Sort the candidates.", "Recurse over (index, remaining).", "Count 1 when remaining hits zero.", "Try each candidate from the current index onwards, subtracting it."],
    tc: "O(number of combinations)", sc: "O(target)",
    solve: (input) => { const r = reader(input); const n = r.int(), target = r.int(); const a = r.ints(n).sort((x, y) => x - y); let count = 0; const go = (i: number, rest: number) => { if (rest === 0) { count += 1; return; } for (let k = i; k < n; k += 1) { if (a[k] > rest) break; go(k, rest - a[k]); } }; go(0, target); return String(count); },
    samples: ["3 7\n2 3 6", "2 8\n2 4"],
    why: ["2+2+3 and 3+... give two combinations reaching 7.", "Several multisets of 2s and 4s reach 8."],
    hidden: ["1 5\n1", "2 4\n1 2", "3 10\n2 5 10", "2 3\n5 7"],
    edge: ["1 1\n2"],
    companies: ["amazon", "adobe"],
  },
  {
    slug: "permutations-generate",
    title: "Generate All Permutations",
    difficulty: "MEDIUM",
    topics: ["backtracking"],
    d: "Print every permutation of a list of distinct integers in lexicographic order.",
    in: "First line: n.\nSecond line: n distinct integers.",
    out: "One permutation per line, space separated.",
    c: "1 <= n <= 8",
    hints: ["Sort first so the natural generation order is lexicographic.", "Choose the next element from the unused ones.", "Backtrack by restoring the used marker."],
    ap: "Backtracking over the sorted input, choosing each unused element in turn so that permutations are produced in lexicographic order.",
    it: "Generating from a sorted base in index order yields sorted output without a final sort.",
    st: ["Sort the input.", "Maintain a used flag per element.", "Recurse, appending each unused element.", "Emit when the current permutation is full."],
    tc: "O(n! * n)", sc: "O(n)",
    solve: (input) => { const a = A(input).sort((x, y) => x - y); const n = a.length; const used = new Array(n).fill(false); const cur: number[] = []; const out: string[] = []; const go = () => { if (cur.length === n) { out.push(join(cur)); return; } for (let i = 0; i < n; i += 1) { if (used[i]) continue; used[i] = true; cur.push(a[i]); go(); cur.pop(); used[i] = false; } }; go(); return linesOut(out); },
    samples: ["3\n1 2 3", "1\n5"],
    why: ["All six permutations in lexicographic order.", "A single element has one permutation."],
    hidden: ["2\n2 1", "3\n3 1 2", "4\n1 2 3 4", "2\n-1 1"],
    edge: ["2\n1 2"],
    companies: ["amazon", "microsoft", "meta"],
  },
  {
    slug: "n-queens-count",
    title: "N-Queens Count",
    difficulty: "MEDIUM",
    topics: ["backtracking"],
    d: "Count the ways to place n queens on an n by n board so that no two attack each other.",
    in: "A single integer n.",
    out: "The number of valid placements.",
    c: "1 <= n <= 11",
    hints: ["Exactly one queen goes in each row.", "Track which columns and diagonals are already attacked.", "Backtrack row by row, undoing marks as you return."],
    ap: "Row-by-row backtracking with occupancy sets for columns and both diagonal directions, pruning attacked squares immediately.",
    it: "Pruning at placement time rather than at the end is what makes the search tractable.",
    st: ["Place a queen in row 0, trying each column.", "Mark the column and both diagonals as attacked.", "Recurse into the next row.", "Count a solution when all rows are filled."],
    tc: "O(n!) with heavy pruning", sc: "O(n)",
    solve: (input) => { const n = Number(input.trim()); const cols = new Set<number>(), d1 = new Set<number>(), d2 = new Set<number>(); let count = 0; const go = (row: number) => { if (row === n) { count += 1; return; } for (let c = 0; c < n; c += 1) { if (cols.has(c) || d1.has(row - c) || d2.has(row + c)) continue; cols.add(c); d1.add(row - c); d2.add(row + c); go(row + 1); cols.delete(c); d1.delete(row - c); d2.delete(row + c); } }; go(0); return String(count); },
    samples: ["4", "1"],
    why: ["There are two valid arrangements on a 4x4 board.", "A single queen on a 1x1 board."],
    hidden: ["2", "6", "8", "10"],
    edge: ["3"],
    companies: ["amazon", "google"],
  },
  {
    slug: "rat-in-maze-count",
    title: "Paths Through a Maze",
    difficulty: "MEDIUM",
    topics: ["backtracking", "matrix"],
    d: "Count the simple paths from the top-left to the bottom-right of a grid, moving up, down, left or right through open cells (0) and never revisiting a cell.",
    in: "First line: n and m.\nNext n lines: m values, 0 for open and 1 for blocked.",
    out: "The number of distinct paths.",
    c: "1 <= n, m <= 6",
    hints: ["Paths may not revisit cells, so a visited marker is essential.", "Backtrack: mark on entry, unmark on exit.", "The grid is tiny, so exhaustive search is fine."],
    ap: "Depth-first backtracking with a visited grid, counting every arrival at the destination.",
    it: "Unmarking on the way out is what allows the same cell to appear in different paths.",
    st: ["Return 0 immediately if the start or end is blocked.", "Mark the current cell visited.", "Recurse into the four neighbours that are open and unvisited.", "Unmark before returning."],
    tc: "Exponential in the grid size", sc: "O(nm)",
    solve: (input) => { const r = reader(input); const n = r.int(), m = r.int(); const g: number[][] = []; for (let i = 0; i < n; i += 1) g.push(r.ints(m)); if (g[0][0] === 1 || g[n - 1][m - 1] === 1) return "0"; const seen = Array.from({ length: n }, () => new Array(m).fill(false)); let count = 0; const dirs = [[1, 0], [-1, 0], [0, 1], [0, -1]]; const go = (x: number, y: number) => { if (x === n - 1 && y === m - 1) { count += 1; return; } seen[x][y] = true; for (const [dx, dy] of dirs) { const nx = x + dx, ny = y + dy; if (nx >= 0 && ny >= 0 && nx < n && ny < m && !seen[nx][ny] && g[nx][ny] === 0) go(nx, ny); } seen[x][y] = false; }; go(0, 0); return String(count); },
    samples: ["2 2\n0 0\n0 0", "2 2\n0 1\n1 0"],
    why: ["Two paths: right-down and down-right.", "Both routes are blocked."],
    hidden: ["1 1\n0", "3 3\n0 0 0\n0 0 0\n0 0 0", "3 3\n0 1 0\n0 1 0\n0 0 0", "2 3\n0 0 0\n0 0 0"],
    edge: ["1 1\n1"],
  },
  {
    slug: "word-search-grid",
    title: "Word Search in a Grid",
    difficulty: "MEDIUM",
    topics: ["backtracking", "matrix"],
    d: "Decide whether a word can be spelled by walking through adjacent cells (up, down, left, right) without reusing a cell.",
    in: "First line: n and m.\nNext n lines: m characters each as a string.\nLast line: the word.",
    out: "YES if the word can be formed, otherwise NO.",
    c: "1 <= n, m <= 20\n1 <= |word| <= 20",
    hints: ["Every cell matching the first letter is a possible start.", "Mark cells as used during the walk.", "Unmark them when you backtrack."],
    ap: "Depth-first search from every matching starting cell, marking visited cells and undoing the marks on backtrack.",
    it: "The no-reuse rule is what makes this a backtracking problem rather than a simple reachability query.",
    st: ["For each cell matching word[0], start a search.", "At depth k, try the four neighbours matching word[k+1].", "Mark and unmark cells around the recursion.", "Succeed when the whole word is matched."],
    tc: "O(n * m * 4^|word|)", sc: "O(|word|)",
    solve: (input) => { const parts = input.trim().split("\n").map((l) => l.trim()); const [n, m] = parts[0].split(/\s+/).map(Number); const g = parts.slice(1, 1 + n); const word = parts[1 + n] ?? ""; const seen = Array.from({ length: n }, () => new Array(m).fill(false)); const dirs = [[1, 0], [-1, 0], [0, 1], [0, -1]]; const go = (x: number, y: number, k: number): boolean => { if (k === word.length) return true; if (x < 0 || y < 0 || x >= n || y >= m || seen[x][y] || g[x][y] !== word[k]) return false; seen[x][y] = true; for (const [dx, dy] of dirs) if (go(x + dx, y + dy, k + 1)) { seen[x][y] = false; return true; } if (k === word.length - 1) { seen[x][y] = false; return true; } seen[x][y] = false; return false; }; for (let i = 0; i < n; i += 1) for (let j = 0; j < m; j += 1) if (go(i, j, 0)) return "YES"; return "NO"; },
    samples: ["3 4\nABCE\nSFCS\nADEE\nABCCED", "3 4\nABCE\nSFCS\nADEE\nABCB"],
    why: ["The path spells ABCCED without reusing a cell.", "The final B cannot be reached without reuse."],
    hidden: ["1 1\nA\nA", "1 1\nA\nB", "2 2\nAB\nCD\nABDC", "2 2\nAA\nAA\nAAAA"],
    edge: ["1 2\nAB\nBA"],
    companies: ["amazon", "microsoft", "meta"],
  },
  {
    slug: "coin-change-min",
    title: "Coin Change",
    difficulty: "MEDIUM",
    topics: ["dp"],
    d: "Given coin denominations and an amount, find the fewest coins that make the amount exactly, or -1 if it cannot be made. Coins may be reused.",
    in: "First line: n and amount.\nSecond line: n coin values.",
    out: "The minimum number of coins, or -1.",
    c: "1 <= n <= 100\n0 <= amount <= 10000\n1 <= coin <= 10000",
    hints: ["Greedy fails for arbitrary denominations.", "Define dp[x] as the fewest coins making x.", "dp[x] = 1 + min over coins of dp[x - coin]."],
    ap: "Bottom-up dynamic programming over amounts, taking the best coin choice for each value.",
    it: "Optimal substructure holds because the last coin used splits the problem into a strictly smaller one.",
    st: ["Set dp[0] = 0 and everything else to infinity.", "For each amount, try every coin that fits.", "Take the minimum of 1 + dp[amount - coin].", "Print dp[amount] or -1."],
    tc: "O(n * amount)", sc: "O(amount)",
    solve: (input) => { const r = reader(input); const n = r.int(), amount = r.int(); const coins = r.ints(n); const dp = new Array(amount + 1).fill(Infinity); dp[0] = 0; for (let x = 1; x <= amount; x += 1) for (const c of coins) if (c <= x) dp[x] = Math.min(dp[x], dp[x - c] + 1); return dp[amount] === Infinity ? "-1" : String(dp[amount]); },
    samples: ["3 11\n1 2 5", "1 3\n2"],
    why: ["5 + 5 + 1 uses three coins.", "3 cannot be made from 2s."],
    hidden: ["1 0\n1", "3 100\n1 5 10", "2 6\n3 4", "4 27\n1 5 10 25"],
    edge: ["1 1\n2"],
    companies: ["amazon", "google", "adobe"],
  },
  {
    slug: "knapsack-01",
    title: "0/1 Knapsack",
    difficulty: "MEDIUM",
    topics: ["dp"],
    d: "Choose a subset of items, each with a weight and a value, so the total weight fits the capacity and the value is maximised. Each item may be used at most once.",
    in: "First line: n and capacity.\nNext n lines: weight and value.",
    out: "The maximum achievable value.",
    c: "1 <= n <= 1000\n1 <= capacity <= 10000\n1 <= weight, value <= 10^6",
    hints: ["Greedy by value density is not optimal for 0/1 selection.", "Define dp[w] as the best value at exactly capacity w.", "Iterate the weight dimension downwards so each item is used once."],
    ap: "Classic 0/1 knapsack DP compressed to a single array, iterating weights in decreasing order so each item contributes at most once.",
    it: "The descending weight loop is precisely what distinguishes 0/1 from unbounded knapsack.",
    st: ["Initialise dp of size capacity+1 to zero.", "For each item, loop w from capacity down to the item weight.", "Set dp[w] = max(dp[w], dp[w - weight] + value).", "Print dp[capacity]."],
    tc: "O(n * capacity)", sc: "O(capacity)",
    solve: (input) => { const r = reader(input); const n = r.int(), cap = r.int(); const dp = new Array(cap + 1).fill(0); for (let i = 0; i < n; i += 1) { const w = r.int(), v = r.int(); for (let k = cap; k >= w; k -= 1) dp[k] = Math.max(dp[k], dp[k - w] + v); } return String(dp[cap]); },
    samples: ["3 50\n10 60\n20 100\n30 120", "2 5\n6 100\n1 1"],
    why: ["Items 2 and 3 fit and give 220.", "Only the light item fits."],
    hidden: ["1 1\n1 5", "3 10\n5 10\n4 40\n6 30", "2 4\n2 3\n2 3", "4 8\n1 1\n2 2\n3 3\n4 4"],
    edge: ["1 1\n2 100"],
    companies: ["amazon", "microsoft", "adobe"],
  },
  {
    slug: "longest-increasing-subsequence",
    title: "Longest Increasing Subsequence",
    difficulty: "MEDIUM",
    topics: ["dp", "searching"],
    d: "Find the length of the longest strictly increasing subsequence.",
    in: "First line: n.\nSecond line: n integers.",
    out: "The length of the longest strictly increasing subsequence.",
    c: "1 <= n <= 100000\n-10^9 <= a[i] <= 10^9",
    hints: ["The O(n^2) DP is the natural first solution.", "Keep the smallest possible tail for each achievable length.", "That tails array is sorted, so binary search finds the insertion point."],
    ap: "Patience sorting: maintain the smallest tail for each length and binary search where each element belongs. The length of the tails array is the answer.",
    it: "Keeping tails as small as possible maximises what can be appended later, which is why greedy replacement is safe.",
    st: ["Keep an empty tails array.", "For each value, binary search the first tail >= it.", "Replace that tail, or append when none is found.", "Print the tails length."],
    tc: "O(n log n)", sc: "O(n)",
    solve: (input) => { const a = A(input); const tails: number[] = []; for (const v of a) { let lo = 0, hi = tails.length; while (lo < hi) { const mid = (lo + hi) >> 1; if (tails[mid] < v) lo = mid + 1; else hi = mid; } tails[lo] = v; } return String(tails.length); },
    samples: ["8\n10 9 2 5 3 7 101 18", "4\n7 7 7 7"],
    why: ["2, 3, 7, 101 has length 4.", "No strictly increasing pair exists."],
    hidden: ["1\n5", "5\n1 2 3 4 5", "5\n5 4 3 2 1", "6\n1 3 2 4 3 5"],
    edge: ["2\n2 1"],
    companies: ["amazon", "google", "microsoft"],
  },
  {
    slug: "longest-common-subsequence",
    title: "Longest Common Subsequence",
    difficulty: "MEDIUM",
    topics: ["dp", "strings"],
    d: "Find the length of the longest subsequence common to two strings. A subsequence keeps order but need not be contiguous.",
    in: "Line 1: string a.\nLine 2: string b.",
    out: "The length of the longest common subsequence.",
    c: "1 <= |a|, |b| <= 2000",
    hints: ["Compare the last characters of both strings.", "If they match, the answer grows by one over the smaller prefixes.", "If not, drop one character from either string and take the better result."],
    ap: "Two-dimensional DP over prefix lengths, matching characters diagonally and otherwise taking the better of dropping one character from either string.",
    it: "The recurrence branches on whether the final characters participate in the match.",
    st: ["Build a table of size (|a|+1) by (|b|+1).", "On a character match set dp[i][j] = dp[i-1][j-1] + 1.", "Otherwise take max(dp[i-1][j], dp[i][j-1]).", "Print dp[|a|][|b|]."],
    tc: "O(|a| * |b|)", sc: "O(min(|a|, |b|))",
    solve: (input) => { const [a = "", b = ""] = input.trim().split("\n").map((l) => l.trim()); const prev = new Array(b.length + 1).fill(0); const cur = new Array(b.length + 1).fill(0); for (let i = 1; i <= a.length; i += 1) { for (let j = 1; j <= b.length; j += 1) cur[j] = a[i - 1] === b[j - 1] ? prev[j - 1] + 1 : Math.max(prev[j], cur[j - 1]); for (let j = 0; j <= b.length; j += 1) prev[j] = cur[j]; } return String(prev[b.length]); },
    samples: ["abcde\nace", "abc\ndef"],
    why: ["'ace' is common to both.", "The strings share no characters."],
    hidden: ["a\na", "abc\nabc", "aaaa\naa", "forge\nfrog"],
    edge: ["a\nb"],
    companies: ["amazon", "google", "adobe"],
  },
  {
    slug: "edit-distance",
    title: "Edit Distance",
    difficulty: "MEDIUM",
    topics: ["dp", "strings"],
    d: "Find the minimum number of insertions, deletions and substitutions needed to turn one string into another.",
    in: "Line 1: string a.\nLine 2: string b.",
    out: "The edit distance.",
    c: "1 <= |a|, |b| <= 2000",
    hints: ["Think about the last character of each string.", "Matching characters cost nothing extra.", "Otherwise take the cheapest of insert, delete and substitute."],
    ap: "Levenshtein DP over prefix lengths: a match carries the diagonal cost, and a mismatch takes one plus the best of the three neighbouring states.",
    it: "Each of the three operations corresponds to moving in one direction through the DP table.",
    st: ["Initialise the first row and column to the prefix lengths.", "On a match copy the diagonal value.", "Otherwise take 1 + min(left, up, diagonal).", "Print the bottom-right cell."],
    tc: "O(|a| * |b|)", sc: "O(min(|a|, |b|))",
    solve: (input) => { const [a = "", b = ""] = input.trim().split("\n").map((l) => l.trim()); let prev = Array.from({ length: b.length + 1 }, (_, j) => j); for (let i = 1; i <= a.length; i += 1) { const cur = new Array(b.length + 1).fill(0); cur[0] = i; for (let j = 1; j <= b.length; j += 1) cur[j] = a[i - 1] === b[j - 1] ? prev[j - 1] : 1 + Math.min(prev[j], cur[j - 1], prev[j - 1]); prev = cur; } return String(prev[b.length]); },
    samples: ["horse\nros", "intention\nexecution"],
    why: ["Three edits transform horse into ros.", "Five edits are needed."],
    hidden: ["a\na", "abc\nabc", "abc\n", "forge\nforges"],
    edge: ["a\nb"],
    companies: ["google", "amazon", "microsoft"],
  },
  {
    slug: "unique-paths-grid",
    title: "Unique Paths in a Grid",
    difficulty: "MEDIUM",
    topics: ["dp"],
    d: "Count the paths from the top-left to the bottom-right of an n by m grid moving only right or down. Report the answer modulo 1000000007.",
    in: "One line: n and m.",
    out: "The number of paths modulo 1000000007.",
    c: "1 <= n, m <= 1000",
    hints: ["Each cell is reached from above or from the left.", "So paths[i][j] = paths[i-1][j] + paths[i][j-1].", "The first row and column have exactly one path each."],
    ap: "Two-dimensional DP summing the two incoming directions, or the closed-form binomial coefficient C(n+m-2, n-1).",
    it: "Every path is a fixed-length sequence of moves, which is why the count is a binomial coefficient.",
    st: ["Fill the first row and column with 1.", "For each inner cell add the value above and to the left.", "Reduce modulo 1000000007.", "Print the bottom-right cell."],
    tc: "O(nm)", sc: "O(m)",
    solve: (input) => { const [n, m] = input.trim().split(/\s+/).map(Number); const dp = new Array(m).fill(1n); for (let i = 1; i < n; i += 1) for (let j = 1; j < m; j += 1) dp[j] = (dp[j] + dp[j - 1]) % MOD; return dp[m - 1].toString(); },
    samples: ["3 7", "1 1"],
    why: ["There are 28 monotone lattice paths.", "A single cell has one trivial path."],
    hidden: ["2 2", "3 3", "10 10", "1000 1000"],
    edge: ["1 1000"],
    companies: ["amazon", "adobe"],
  },
  {
    slug: "house-robber",
    title: "House Robber",
    difficulty: "MEDIUM",
    topics: ["dp"],
    d: "Choose a subset of houses with no two adjacent so the total value is maximised.",
    in: "First line: n.\nSecond line: n non-negative values.",
    out: "The maximum total.",
    c: "1 <= n <= 100000\n0 <= value <= 10^6",
    hints: ["Each house is either taken or skipped.", "Taking a house forbids its immediate neighbour.", "best(i) = max(best(i-1), best(i-2) + value[i])."],
    ap: "Linear DP with two rolling variables holding the best totals ending at the previous and the one before it.",
    it: "The constraint only reaches one step back, so the state collapses to two numbers.",
    st: ["Set take = 0 and skip = 0.", "For each value, newTake = skip + value and newSkip = max(take, skip).", "Shift the variables forward.", "Print max(take, skip)."],
    tc: "O(n)", sc: "O(1)",
    solve: (input) => { const a = A(input); let take = 0, skip = 0; for (const v of a) { const nextTake = skip + v; skip = Math.max(skip, take); take = nextTake; } return String(Math.max(take, skip)); },
    samples: ["4\n1 2 3 1", "5\n2 7 9 3 1"],
    why: ["Taking houses 1 and 3 gives 4.", "Taking 2, 9 and 1 gives 12."],
    hidden: ["1\n5", "2\n1 2", "5\n0 0 0 0 0", "6\n5 5 5 5 5 5"],
    edge: ["2\n0 0"],
    companies: ["amazon", "adobe", "google"],
  },
  {
    slug: "partition-equal-subset",
    title: "Partition into Equal Subsets",
    difficulty: "MEDIUM",
    topics: ["dp"],
    d: "Decide whether an array can be split into two subsets with equal sums.",
    in: "First line: n.\nSecond line: n positive integers.",
    out: "YES if such a split exists, otherwise NO.",
    c: "1 <= n <= 200\n1 <= a[i] <= 1000",
    hints: ["An odd total can never split evenly.", "Otherwise you need a subset summing to half the total.", "That is a subset-sum feasibility question."],
    ap: "Reduce to subset-sum for half the total, solved with a boolean DP over reachable sums, iterating downwards so each element is used once.",
    it: "The two halves are complementary, so finding one determines the other.",
    st: ["Compute the total; answer NO if it is odd.", "Set target = total / 2.", "Run a boolean subset-sum DP up to the target.", "Print YES when the target is reachable."],
    tc: "O(n * total)", sc: "O(total)",
    solve: (input) => { const a = A(input); const total = a.reduce((s, v) => s + v, 0); if (total % 2 !== 0) return "NO"; const target = total / 2; const dp = new Uint8Array(target + 1); dp[0] = 1; for (const v of a) for (let k = target; k >= v; k -= 1) if (dp[k - v]) dp[k] = 1; return yesNo(dp[target] === 1); },
    samples: ["4\n1 5 11 5", "3\n1 2 5"],
    why: ["{1,5,5} and {11} both sum to 11.", "The total is odd."],
    hidden: ["1\n1", "2\n1 1", "6\n3 3 3 3 3 3", "4\n2 2 3 5"],
    edge: ["2\n1 2"],
    companies: ["amazon", "adobe"],
  },
  {
    slug: "rod-cutting",
    title: "Rod Cutting",
    difficulty: "MEDIUM",
    topics: ["dp"],
    d: "A rod of length n can be cut into integer pieces. Piece of length i sells for price[i]. Maximise the total revenue.",
    in: "First line: n.\nSecond line: n prices, where the ith is the price of a piece of length i.",
    out: "The maximum revenue.",
    c: "1 <= n <= 1000\n1 <= price <= 10^6",
    hints: ["Every cut leaves a shorter rod to solve the same way.", "Try every possible first piece length.", "This is unbounded knapsack in disguise."],
    ap: "Unbounded knapsack over rod length: for each length, try every first-piece length and take the best total.",
    it: "Because pieces can repeat, the inner loop runs forwards rather than backwards.",
    st: ["Set dp[0] = 0.", "For each length L, try every first piece i <= L.", "Take max(dp[L], price[i] + dp[L-i]).", "Print dp[n]."],
    tc: "O(n^2)", sc: "O(n)",
    solve: (input) => { const r = reader(input); const n = r.int(); const price = r.ints(n); const dp = new Array(n + 1).fill(0); for (let L = 1; L <= n; L += 1) for (let i = 1; i <= L; i += 1) dp[L] = Math.max(dp[L], price[i - 1] + dp[L - i]); return String(dp[n]); },
    samples: ["8\n1 5 8 9 10 17 17 20", "4\n1 5 8 9"],
    why: ["Two pieces of length 2 give 10, beating any other split.", "Two pieces of length 2 give 10."],
    hidden: ["1\n5", "3\n1 1 1", "5\n2 5 7 8 10", "4\n3 5 8 9"],
    edge: ["2\n1 1"],
  },
  {
    slug: "min-path-sum-grid",
    title: "Minimum Path Sum",
    difficulty: "MEDIUM",
    topics: ["dp", "matrix"],
    d: "Find the minimum sum of values along a path from the top-left to the bottom-right of a grid, moving only right or down.",
    in: "First line: n and m.\nNext n lines: m non-negative integers each.",
    out: "The minimum path sum.",
    c: "1 <= n, m <= 500\n0 <= value <= 10^6",
    hints: ["Each cell is entered from above or from the left.", "So the best cost to a cell is its value plus the cheaper entry.", "Fill the table row by row."],
    ap: "Dynamic programming over the grid, where dp[i][j] is the value plus the smaller of the two incoming costs. One row of state suffices.",
    it: "Restricting movement to right and down makes the dependency graph acyclic in row-major order.",
    st: ["Fill the first row and column cumulatively.", "For each inner cell add min(above, left).", "Print the bottom-right cell."],
    tc: "O(nm)", sc: "O(m)",
    solve: (input) => { const r = reader(input); const n = r.int(), m = r.int(); const dp = new Array(m).fill(Infinity); for (let i = 0; i < n; i += 1) { const row = r.ints(m); for (let j = 0; j < m; j += 1) { if (i === 0 && j === 0) dp[j] = row[0]; else if (i === 0) dp[j] = dp[j - 1] + row[j]; else if (j === 0) dp[j] = dp[j] + row[j]; else dp[j] = Math.min(dp[j], dp[j - 1]) + row[j]; } } return String(dp[m - 1]); },
    samples: ["3 3\n1 3 1\n1 5 1\n4 2 1", "1 3\n1 2 3"],
    why: ["The path 1-3-1-1-1 sums to 7.", "A single row must be walked entirely."],
    hidden: ["1 1\n5", "2 2\n1 2\n3 4", "3 3\n0 0 0\n0 0 0\n0 0 0", "2 3\n1 1 1\n1 1 1"],
    edge: ["1 1\n0"],
  },
  {
    slug: "decode-ways",
    title: "Decode Ways",
    difficulty: "MEDIUM",
    topics: ["dp", "strings"],
    d: "Letters A to Z map to 1 to 26. Count the ways to decode a digit string. A leading zero in a group is invalid.",
    in: "A single line of digits.",
    out: "The number of decodings, modulo 1000000007.",
    c: "1 <= |s| <= 100000",
    hints: ["Each position is decoded as one digit or two.", "A single digit works only when it is not zero.", "Two digits work only when they form a value from 10 to 26."],
    ap: "Linear DP where ways(i) combines the one-digit and two-digit decodings ending at i, collapsed to two rolling variables.",
    it: "The zero cases are the whole difficulty: a lone zero invalidates a decoding entirely.",
    st: ["Set ways for the empty prefix to 1.", "Add the previous count when the current digit is non-zero.", "Add the count from two back when the pair is between 10 and 26.", "Print the final count."],
    tc: "O(n)", sc: "O(1)",
    solve: (input) => { const s = input.trim(); let prev2 = 1n, prev1 = s[0] === "0" ? 0n : 1n; for (let i = 1; i < s.length; i += 1) { let cur = 0n; if (s[i] !== "0") cur += prev1; const two = Number(s.slice(i - 1, i + 1)); if (two >= 10 && two <= 26) cur += prev2; cur %= MOD; prev2 = prev1; prev1 = cur; } return prev1.toString(); },
    samples: ["226", "06"],
    why: ["BZ, VF and BBF.", "A leading zero cannot be decoded."],
    hidden: ["1", "12", "10", "1111"],
    edge: ["0"],
    companies: ["meta", "amazon", "microsoft"],
  },
  {
    slug: "word-break-check",
    title: "Word Break",
    difficulty: "MEDIUM",
    topics: ["dp", "strings"],
    d: "Decide whether a string can be segmented into a sequence of dictionary words. Words may be reused.",
    in: "Line 1: the string.\nLine 2: k.\nLine 3: k space-separated dictionary words.",
    out: "YES if the string can be segmented, otherwise NO.",
    c: "1 <= |s| <= 1000\n1 <= k <= 1000",
    hints: ["Greedy longest-match fails on strings like 'aaaab'.", "Define dp[i] as 'the prefix of length i is segmentable'.", "dp[i] is true when some dictionary word ends at i and dp before it is true."],
    ap: "Prefix DP: dp[i] is true when a dictionary word ends at position i and the prefix before that word is itself segmentable.",
    it: "Trying every split point is what avoids the greedy trap.",
    st: ["Put the dictionary in a hash set.", "Set dp[0] = true.", "For each i, check every j < i for dp[j] and s[j..i) in the set.", "Print dp[|s|]."],
    tc: "O(n^2)", sc: "O(n)",
    solve: (input) => { const parts = input.trim().split("\n").map((l) => l.trim()); const s = parts[0]; const k = Number(parts[1]); const dict = new Set((parts[2] ?? "").split(/\s+/).slice(0, k)); const dp = new Array(s.length + 1).fill(false); dp[0] = true; for (let i = 1; i <= s.length; i += 1) for (let j = 0; j < i; j += 1) if (dp[j] && dict.has(s.slice(j, i))) { dp[i] = true; break; } return yesNo(dp[s.length]); },
    samples: ["leetcode\n2\nleet code", "catsandog\n5\ncats dog sand and cat"],
    why: ["'leet' plus 'code'.", "No segmentation covers the whole string."],
    hidden: ["a\n1\na", "aaaa\n1\na", "abc\n2\na b", "forgedsa\n2\nforge dsa"],
    edge: ["a\n1\nb"],
    companies: ["amazon", "google", "meta"],
  },
  {
    slug: "matrix-island-count",
    title: "Number of Islands",
    difficulty: "MEDIUM",
    topics: ["graphs", "matrix"],
    d: "Count the connected groups of 1s in a grid, where cells connect horizontally and vertically.",
    in: "First line: n and m.\nNext n lines: m values, each 0 or 1.",
    out: "The number of islands.",
    c: "1 <= n, m <= 500",
    hints: ["Each unvisited 1 starts a new island.", "Flood-fill from it to mark the whole island.", "Count how many flood-fills you start."],
    ap: "Scan every cell; when an unvisited 1 is found, increment the count and flood-fill its entire component.",
    it: "This is connected-component counting on an implicit grid graph.",
    st: ["Iterate over every cell.", "On an unvisited 1, increment the island count.", "Flood-fill the component with BFS or DFS.", "Print the count."],
    tc: "O(nm)", sc: "O(nm)",
    solve: (input) => { const r = reader(input); const n = r.int(), m = r.int(); const g: number[][] = []; for (let i = 0; i < n; i += 1) g.push(r.ints(m)); let count = 0; const dirs = [[1, 0], [-1, 0], [0, 1], [0, -1]]; for (let i = 0; i < n; i += 1) for (let j = 0; j < m; j += 1) { if (g[i][j] !== 1) continue; count += 1; const stack: Array<[number, number]> = [[i, j]]; g[i][j] = 0; while (stack.length) { const [x, y] = stack.pop()!; for (const [dx, dy] of dirs) { const nx = x + dx, ny = y + dy; if (nx >= 0 && ny >= 0 && nx < n && ny < m && g[nx][ny] === 1) { g[nx][ny] = 0; stack.push([nx, ny]); } } } } return String(count); },
    samples: ["4 5\n1 1 0 0 0\n1 1 0 0 0\n0 0 1 0 0\n0 0 0 1 1", "2 2\n0 0\n0 0"],
    why: ["Three separate groups of 1s.", "There is no land."],
    hidden: ["1 1\n1", "3 3\n1 1 1\n1 1 1\n1 1 1", "3 3\n1 0 1\n0 1 0\n1 0 1", "2 3\n1 0 1\n1 0 1"],
    edge: ["1 1\n0"],
    companies: ["amazon", "google", "meta", "microsoft"],
  },
  {
    slug: "rotten-oranges",
    title: "Rotting Oranges",
    difficulty: "MEDIUM",
    topics: ["graphs", "queue", "matrix"],
    d: "A grid holds 0 for empty, 1 for a fresh orange and 2 for a rotten one. Each minute, every fresh orange adjacent to a rotten one rots. Print the minutes until no fresh orange remains, or -1 if that never happens.",
    in: "First line: n and m.\nNext n lines: m values from {0, 1, 2}.",
    out: "The number of minutes, or -1.",
    c: "1 <= n, m <= 500",
    hints: ["Rot spreads outward one layer per minute.", "That is breadth-first search from many sources at once.", "Seed the queue with every initially rotten cell."],
    ap: "Multi-source BFS from all rotten cells simultaneously, counting levels as minutes, then checking whether any fresh orange survives.",
    it: "Starting BFS from every source at once computes the minimum distance to the nearest source for every cell in one pass.",
    st: ["Enqueue every rotten cell at time 0 and count the fresh ones.", "Process the queue level by level, rotting fresh neighbours.", "Track the last minute used.", "Print -1 if fresh oranges remain."],
    tc: "O(nm)", sc: "O(nm)",
    solve: (input) => { const r = reader(input); const n = r.int(), m = r.int(); const g: number[][] = []; for (let i = 0; i < n; i += 1) g.push(r.ints(m)); const queue: Array<[number, number]> = []; let fresh = 0; for (let i = 0; i < n; i += 1) for (let j = 0; j < m; j += 1) { if (g[i][j] === 2) queue.push([i, j]); else if (g[i][j] === 1) fresh += 1; } if (fresh === 0) return "0"; const dirs = [[1, 0], [-1, 0], [0, 1], [0, -1]]; let minutes = 0, head = 0; while (head < queue.length) { const size = queue.length - head; let rotted = false; for (let s = 0; s < size; s += 1) { const [x, y] = queue[head++]; for (const [dx, dy] of dirs) { const nx = x + dx, ny = y + dy; if (nx >= 0 && ny >= 0 && nx < n && ny < m && g[nx][ny] === 1) { g[nx][ny] = 2; fresh -= 1; rotted = true; queue.push([nx, ny]); } } } if (rotted) minutes += 1; } return fresh === 0 ? String(minutes) : "-1"; },
    samples: ["3 3\n2 1 1\n1 1 0\n0 1 1", "3 3\n2 1 1\n0 1 1\n1 0 1"],
    why: ["Rot reaches every orange in four minutes.", "The bottom-left orange is unreachable."],
    hidden: ["1 1\n0", "1 1\n1", "2 2\n2 2\n2 2", "2 3\n2 1 1\n1 1 1"],
    edge: ["1 2\n1 2"],
    companies: ["amazon", "microsoft"],
  },
  {
    slug: "course-schedule-cycle",
    title: "Course Schedule",
    difficulty: "MEDIUM",
    topics: ["graphs"],
    d: "Given prerequisite pairs, decide whether every course can be completed. Course b requires course a for a pair 'a b'.",
    in: "First line: n and m.\nNext m lines: a and b, meaning a must precede b.",
    out: "YES if all courses can be finished, otherwise NO.",
    c: "1 <= n <= 100000\n0 <= m <= 200000",
    hints: ["The prerequisites form a directed graph.", "An impossible schedule means a cycle exists.", "Kahn's algorithm removes zero-indegree vertices repeatedly."],
    ap: "Topological sort via Kahn's algorithm. If every vertex is eventually removed, the graph is acyclic and the schedule is feasible.",
    it: "A vertex can only be taken once all of its prerequisites are gone, which is exactly the indegree-zero condition.",
    st: ["Compute the indegree of every course.", "Enqueue all zero-indegree courses.", "Remove them, decrementing successors' indegrees.", "Feasible when every course is removed."],
    tc: "O(n + m)", sc: "O(n + m)",
    solve: (input) => { const r = reader(input); const n = r.int(), m = r.int(); const adj: number[][] = Array.from({ length: n }, () => []); const indeg = new Array(n).fill(0); for (let i = 0; i < m; i += 1) { const a = r.int(), b = r.int(); adj[a].push(b); indeg[b] += 1; } const queue: number[] = []; for (let i = 0; i < n; i += 1) if (indeg[i] === 0) queue.push(i); let removed = 0; for (let head = 0; head < queue.length; head += 1) { removed += 1; for (const v of adj[queue[head]]) if (--indeg[v] === 0) queue.push(v); } return yesNo(removed === n); },
    samples: ["2 1\n0 1", "2 2\n0 1\n1 0"],
    why: ["Course 0 then course 1.", "The two courses require each other."],
    hidden: ["1 0", "4 3\n0 1\n1 2\n2 3", "3 3\n0 1\n1 2\n2 0", "5 2\n0 1\n2 3"],
    edge: ["1 1\n0 0"],
    companies: ["amazon", "google", "meta"],
  },
  {
    slug: "topological-sort-order",
    title: "Topological Order",
    difficulty: "MEDIUM",
    topics: ["graphs"],
    d: "Print a topological order of a directed acyclic graph, preferring the smallest available vertex at each step. Print IMPOSSIBLE when the graph has a cycle.",
    in: "First line: n and m.\nNext m lines: a directed edge u v.",
    out: "The topological order, space separated, or IMPOSSIBLE.",
    c: "1 <= n <= 100000\n0 <= m <= 200000",
    hints: ["Vertices with no incoming edges can always go first.", "A priority queue makes the order lexicographically smallest.", "If vertices remain but none has indegree zero, there is a cycle."],
    ap: "Kahn's algorithm with a min-heap so the smallest eligible vertex is always chosen, yielding the lexicographically smallest valid order.",
    it: "Any indegree-zero vertex is safe to place, so choosing the smallest never blocks a later choice.",
    st: ["Compute indegrees and seed a min-heap with the zeroes.", "Pop the smallest, append it to the order.", "Decrement successors and push new zeroes.", "Report IMPOSSIBLE if fewer than n vertices were placed."],
    tc: "O((n + m) log n)", sc: "O(n + m)",
    solve: (input) => { const r = reader(input); const n = r.int(), m = r.int(); const adj: number[][] = Array.from({ length: n }, () => []); const indeg = new Array(n).fill(0); for (let i = 0; i < m; i += 1) { const u = r.int(), v = r.int(); adj[u].push(v); indeg[v] += 1; } const available: number[] = []; for (let i = 0; i < n; i += 1) if (indeg[i] === 0) available.push(i); const order: number[] = []; while (available.length) { available.sort((x, y) => x - y); const u = available.shift()!; order.push(u); for (const v of adj[u]) if (--indeg[v] === 0) available.push(v); } return order.length === n ? join(order) : "IMPOSSIBLE"; },
    samples: ["4 3\n0 1\n1 2\n2 3", "2 2\n0 1\n1 0"],
    why: ["The chain forces a single order.", "The cycle admits no order."],
    hidden: ["1 0", "3 2\n2 0\n2 1", "5 0", "4 2\n1 0\n3 2"],
    edge: ["1 1\n0 0"],
    companies: ["amazon", "google"],
  },
  {
    slug: "dijkstra-shortest-path",
    title: "Shortest Path with Weights",
    difficulty: "MEDIUM",
    topics: ["graphs", "heap"],
    d: "Find the shortest distance from vertex 0 to every vertex in a weighted undirected graph with non-negative weights. Print -1 for unreachable vertices.",
    in: "First line: n and m.\nNext m lines: u, v and w.",
    out: "n distances, space separated.",
    c: "1 <= n <= 100000\n0 <= m <= 200000\n1 <= w <= 10^9",
    hints: ["BFS only works when all weights are equal.", "Always expand the closest unfinalised vertex.", "A min-heap keyed by tentative distance gives that ordering."],
    ap: "Dijkstra's algorithm with a binary heap: repeatedly finalise the nearest unvisited vertex and relax its outgoing edges.",
    it: "Non-negative weights guarantee that the nearest tentative distance is already final, which is what makes the greedy choice sound.",
    st: ["Set all distances to infinity except the source.", "Push the source into a min-heap.", "Pop the nearest vertex and relax its edges.", "Skip stale heap entries."],
    tc: "O((n + m) log n)", sc: "O(n + m)",
    solve: (input) => { const r = reader(input); const n = r.int(), m = r.int(); const adj: Array<Array<[number, number]>> = Array.from({ length: n }, () => []); for (let i = 0; i < m; i += 1) { const u = r.int(), v = r.int(), w = r.int(); adj[u].push([v, w]); adj[v].push([u, w]); } const dist = new Array(n).fill(Infinity); dist[0] = 0; const visited = new Array(n).fill(false); for (let step = 0; step < n; step += 1) { let best = -1; for (let i = 0; i < n; i += 1) if (!visited[i] && (best === -1 || dist[i] < dist[best])) best = i; if (best === -1 || dist[best] === Infinity) break; visited[best] = true; for (const [v, w] of adj[best]) if (dist[best] + w < dist[v]) dist[v] = dist[best] + w; } return join(dist.map((d) => (d === Infinity ? -1 : d))); },
    samples: ["4 4\n0 1 1\n1 2 2\n0 2 4\n2 3 1", "3 1\n0 1 5"],
    why: ["Going through vertex 1 beats the direct edge to 2.", "Vertex 2 is unreachable."],
    hidden: ["1 0", "3 3\n0 1 1\n1 2 1\n0 2 5", "4 2\n0 1 1\n2 3 1", "2 1\n0 1 1000000000"],
    edge: ["2 0"],
    companies: ["amazon", "google", "microsoft"],
  },
  {
    slug: "bipartite-check",
    title: "Check Bipartite Graph",
    difficulty: "MEDIUM",
    topics: ["graphs"],
    d: "Decide whether an undirected graph can be two-coloured so that no edge joins two vertices of the same colour.",
    in: "First line: n and m.\nNext m lines: an edge u v.",
    out: "YES if the graph is bipartite, otherwise NO.",
    c: "1 <= n <= 100000\n0 <= m <= 200000",
    hints: ["Try colouring greedily during a traversal.", "Every neighbour must take the opposite colour.", "A conflict means an odd cycle exists."],
    ap: "BFS or DFS assigning alternating colours; a conflicting edge proves an odd cycle and therefore non-bipartiteness.",
    it: "A graph is bipartite exactly when it contains no odd cycle, and greedy two-colouring detects one immediately.",
    st: ["Colour each unvisited vertex 0 and traverse.", "Give every neighbour the opposite colour.", "Fail on an edge joining equal colours.", "Repeat for every component."],
    tc: "O(n + m)", sc: "O(n + m)",
    solve: (input) => { const r = reader(input); const n = r.int(), m = r.int(); const adj: number[][] = Array.from({ length: n }, () => []); for (let i = 0; i < m; i += 1) { const u = r.int(), v = r.int(); adj[u].push(v); adj[v].push(u); } const color = new Array(n).fill(-1); for (let s = 0; s < n; s += 1) { if (color[s] !== -1) continue; color[s] = 0; const queue = [s]; for (let head = 0; head < queue.length; head += 1) { const u = queue[head]; for (const v of adj[u]) { if (color[v] === -1) { color[v] = 1 - color[u]; queue.push(v); } else if (color[v] === color[u]) return "NO"; } } } return "YES"; },
    samples: ["4 4\n0 1\n1 2\n2 3\n3 0", "3 3\n0 1\n1 2\n2 0"],
    why: ["The four-cycle is bipartite.", "The triangle is an odd cycle."],
    hidden: ["1 0", "2 1\n0 1", "5 4\n0 1\n1 2\n2 3\n3 4", "4 3\n0 1\n1 2\n2 0"],
    edge: ["1 1\n0 0"],
  },
  {
    slug: "detect-cycle-undirected",
    title: "Detect a Cycle in an Undirected Graph",
    difficulty: "MEDIUM",
    topics: ["graphs"],
    d: "Decide whether an undirected graph contains a cycle.",
    in: "First line: n and m.\nNext m lines: an edge u v.",
    out: "YES if a cycle exists, otherwise NO.",
    c: "1 <= n <= 100000\n0 <= m <= 200000",
    hints: ["A traversal that revisits a vertex other than its immediate parent found a cycle.", "Track the parent as you traverse.", "Disjoint-set union also detects cycles as you add edges."],
    ap: "DFS or BFS tracking the parent of each vertex; reaching an already visited non-parent vertex proves a cycle. A DSU that merges edges and finds an already-connected pair works too.",
    it: "In an undirected graph a back edge to anything but the parent closes a loop.",
    st: ["Traverse each component.", "Record the parent when discovering a vertex.", "If a neighbour is visited and is not the parent, report YES.", "Otherwise report NO."],
    tc: "O(n + m)", sc: "O(n + m)",
    solve: (input) => { const r = reader(input); const n = r.int(), m = r.int(); const parent = Array.from({ length: n }, (_, i) => i); const find = (x: number): number => (parent[x] === x ? x : (parent[x] = find(parent[x]))); for (let i = 0; i < m; i += 1) { const u = r.int(), v = r.int(); const ru = find(u), rv = find(v); if (ru === rv) return "YES"; parent[ru] = rv; } return "NO"; },
    samples: ["3 3\n0 1\n1 2\n2 0", "3 2\n0 1\n1 2"],
    why: ["The three edges close a triangle.", "The graph is a tree."],
    hidden: ["1 0", "2 1\n0 1", "4 4\n0 1\n1 2\n2 3\n3 1", "5 3\n0 1\n2 3\n3 4"],
    edge: ["1 1\n0 0"],
  },
  {
    slug: "bst-validate",
    title: "Validate a Binary Search Tree",
    difficulty: "MEDIUM",
    topics: ["bst", "trees"],
    d: "Decide whether a binary tree given in level order with -1 for absent children satisfies the binary search tree property.",
    in: "First line: n.\nSecond line: n level-order values, -1 for absent.",
    out: "YES if the tree is a valid BST, otherwise NO.",
    c: "1 <= n <= 100000\nAll present values are distinct and non-negative.",
    hints: ["Comparing only against the immediate parent is not enough.", "Every node is constrained by all of its ancestors.", "Pass a permitted (low, high) range down the recursion."],
    ap: "Recursive validation carrying an allowed open interval, tightened at every step. An inorder traversal that must be strictly increasing is an equivalent check.",
    it: "The classic bug is checking only parent-child pairs, which misses violations several levels up.",
    st: ["Start at the root with the range (-inf, +inf).", "Fail when a value leaves its range.", "Recurse left with the upper bound set to the node value.", "Recurse right with the lower bound set to it."],
    tc: "O(n)", sc: "O(h)",
    solve: (input) => { const r = reader(input); const n = r.int(); const a = r.ints(n); const go = (i: number, lo: number, hi: number): boolean => { if (i >= n || a[i] === -1) return true; if (a[i] <= lo || a[i] >= hi) return false; return go(2 * i + 1, lo, a[i]) && go(2 * i + 2, a[i], hi); }; return yesNo(go(0, -Infinity, Infinity)); },
    samples: ["3\n2 1 3", "7\n5 1 4 -1 -1 3 6"],
    why: ["The ordering holds everywhere.", "3 sits in the right subtree of 5 but is smaller than 5."],
    hidden: ["1\n1", "3\n1 2 3", "7\n8 3 10 1 6 -1 14", "3\n2 3 1"],
    edge: ["1\n-1"],
    companies: ["amazon", "microsoft", "meta"],
  },
];

export const MEDIUM_A = specs.map(build);
