import { build, join, linesOut, reader, yesNo, type QuestionSpec } from "./catalog";

const A = (input: string) => {
  const r = reader(input);
  return r.ints(r.int());
};

const MOD = 1000000007n;

const specs: QuestionSpec[] = [
  {
    slug: "lowest-common-ancestor-bst",
    title: "Lowest Common Ancestor in a BST",
    difficulty: "MEDIUM",
    topics: ["bst", "trees"],
    d: "Find the lowest common ancestor of two values in a binary search tree given in level order with -1 for absent children.",
    in: "First line: n, p and q.\nSecond line: n level-order values, -1 for absent.",
    out: "The value of the lowest common ancestor.",
    c: "1 <= n <= 100000\nBoth values are present in the tree.",
    hints: ["A general-tree LCA algorithm ignores the ordering.", "The split point is where the two values diverge.", "Walk down while both values are on the same side."],
    ap: "Descend from the root: go left while both values are smaller, right while both are larger. The first node that sits between them is the LCA.",
    it: "The BST ordering makes the divergence point unique and findable without any auxiliary structure.",
    st: ["Start at the root.", "If both values are below the node, go left.", "If both are above, go right.", "Otherwise this node is the answer."],
    tc: "O(h)", sc: "O(1)",
    solve: (input) => { const r = reader(input); const n = r.int(), p = r.int(), q = r.int(); const a = r.ints(n); let i = 0; while (i < n && a[i] !== -1) { if (p < a[i] && q < a[i]) i = 2 * i + 1; else if (p > a[i] && q > a[i]) i = 2 * i + 2; else return String(a[i]); } return "-1"; },
    samples: ["7 1 6\n8 3 10 1 6 -1 14", "7 3 14\n8 3 10 1 6 -1 14"],
    why: ["Both values live under 3.", "They diverge at the root."],
    hidden: ["1 1 1\n1", "3 1 3\n2 1 3", "7 1 3\n8 3 10 1 6 -1 14", "3 1 1\n2 1 3"],
    edge: ["3 3 3\n2 1 3"],
    companies: ["amazon", "meta"],
  },
  {
    slug: "kth-smallest-bst",
    title: "Kth Smallest in a BST",
    difficulty: "MEDIUM",
    topics: ["bst", "trees"],
    d: "Find the kth smallest value in a binary search tree given in level order with -1 for absent children.",
    in: "First line: n and k.\nSecond line: n level-order values, -1 for absent.",
    out: "The kth smallest value.",
    c: "1 <= k <= number of nodes <= 100000",
    hints: ["Sorting all values works but wastes the tree structure.", "An inorder traversal of a BST is already sorted.", "Stop the traversal after k nodes."],
    ap: "Inorder traversal with an early exit once k nodes have been visited.",
    it: "Inorder on a BST is the sorted sequence, so selection is just counting.",
    st: ["Traverse inorder.", "Increment a counter at each node.", "Return the value when the counter reaches k."],
    tc: "O(h + k)", sc: "O(h)",
    solve: (input) => { const r = reader(input); const n = r.int(), k = r.int(); const a = r.ints(n); const out: number[] = []; const go = (i: number) => { if (i >= n || a[i] === -1 || out.length >= k) return; go(2 * i + 1); if (out.length < k) out.push(a[i]); go(2 * i + 2); }; go(0); return String(out[k - 1]); },
    samples: ["3 1\n2 1 3", "7 3\n8 3 10 1 6 -1 14"],
    why: ["The smallest value is 1.", "Inorder gives 1, 3, 6, so the third is 6."],
    hidden: ["1 1\n5", "3 3\n2 1 3", "7 5\n8 3 10 1 6 -1 14", "3 2\n2 1 3"],
    edge: ["1 1\n0"],
    companies: ["amazon", "google"],
  },
  {
    slug: "tree-diameter",
    title: "Diameter of a Binary Tree",
    difficulty: "MEDIUM",
    topics: ["trees", "recursion"],
    d: "Find the diameter of a binary tree, measured as the number of edges on the longest path between any two nodes.",
    in: "First line: n.\nSecond line: n level-order values, -1 for absent.",
    out: "The diameter in edges.",
    c: "1 <= n <= 100000",
    hints: ["The longest path may not pass through the root.", "At each node, the best path through it is leftHeight + rightHeight.", "Compute heights bottom-up and track the maximum."],
    ap: "Post-order traversal returning each subtree's height while updating a global best with leftHeight + rightHeight at every node.",
    it: "Every path has a unique highest node, so checking each node as that apex covers all paths exactly once.",
    st: ["Recurse to get both subtree heights.", "Update the best with their sum.", "Return 1 + max of the two heights.", "Print the best."],
    tc: "O(n)", sc: "O(h)",
    solve: (input) => { const r = reader(input); const n = r.int(); const a = r.ints(n); let best = 0; const go = (i: number): number => { if (i >= n || a[i] === -1) return 0; const l = go(2 * i + 1), rr = go(2 * i + 2); best = Math.max(best, l + rr); return 1 + Math.max(l, rr); }; go(0); return String(best); },
    samples: ["5\n1 2 3 4 5", "1\n1"],
    why: ["The path 4-2-1-3 uses three edges.", "A single node has diameter 0."],
    hidden: ["1\n-1", "3\n1 2 3", "7\n1 2 3 4 5 6 7", "3\n1 2 -1"],
    edge: ["3\n1 -1 -1"],
    companies: ["amazon", "meta", "google"],
  },
  {
    slug: "tree-balanced-check",
    title: "Check a Balanced Binary Tree",
    difficulty: "MEDIUM",
    topics: ["trees", "recursion"],
    d: "Decide whether a binary tree is height balanced, meaning every node's two subtrees differ in height by at most one.",
    in: "First line: n.\nSecond line: n level-order values, -1 for absent.",
    out: "YES if balanced, otherwise NO.",
    c: "1 <= n <= 100000",
    hints: ["Recomputing height at every node gives O(n^2).", "Compute height and balance in the same pass.", "Return a sentinel from a subtree that is already unbalanced."],
    ap: "Single post-order pass returning height, or a sentinel indicating that the subtree is already unbalanced so the check short-circuits.",
    it: "Fusing the two computations avoids recomputing heights along every root-to-leaf path.",
    st: ["Return 0 for an absent node.", "Recurse into both children.", "Return -1 if either child is unbalanced or the heights differ by more than one.", "Otherwise return 1 + max height."],
    tc: "O(n)", sc: "O(h)",
    solve: (input) => { const r = reader(input); const n = r.int(); const a = r.ints(n); const go = (i: number): number => { if (i >= n || a[i] === -1) return 0; const l = go(2 * i + 1); if (l === -1) return -1; const rr = go(2 * i + 2); if (rr === -1) return -1; if (Math.abs(l - rr) > 1) return -1; return 1 + Math.max(l, rr); }; return yesNo(go(0) !== -1); },
    samples: ["7\n1 2 3 4 5 6 7", "7\n1 2 -1 3 -1 -1 -1"],
    why: ["The complete tree is balanced.", "The left chain is two deeper than the empty right subtree."],
    hidden: ["1\n1", "3\n1 2 3", "5\n1 2 3 4 -1", "1\n-1"],
    edge: ["3\n1 2 -1"],
  },
  {
    slug: "tree-zigzag-traversal",
    title: "Zigzag Level Order Traversal",
    difficulty: "MEDIUM",
    topics: ["trees", "queue"],
    d: "Print a binary tree level by level, alternating direction: the first level left to right, the second right to left, and so on.",
    in: "First line: n.\nSecond line: n level-order values, -1 for absent.",
    out: "One line per level, or EMPTY.",
    c: "1 <= n <= 100000",
    hints: ["Start from an ordinary level-order traversal.", "Only the emission order changes, not the traversal.", "Reverse every other level before printing."],
    ap: "Breadth-first traversal collecting each level, reversing the levels at odd depth before emitting them.",
    it: "Separating traversal from presentation keeps the BFS itself unchanged.",
    st: ["Collect nodes level by level with a queue.", "Track the current depth.", "Reverse odd-depth levels.", "Print one line per level."],
    tc: "O(n)", sc: "O(n)",
    solve: (input) => { const r = reader(input); const n = r.int(); const a = r.ints(n); const out: string[] = []; let level = [0]; let depth = 0; while (level.length) { const values = level.filter((i) => i < n && a[i] !== -1); if (!values.length) break; const row = values.map((i) => a[i]); out.push(join(depth % 2 === 1 ? row.reverse() : row)); const next: number[] = []; for (const i of values) next.push(2 * i + 1, 2 * i + 2); level = next; depth += 1; } return out.length ? linesOut(out) : "EMPTY"; },
    samples: ["7\n1 2 3 4 5 6 7", "1\n1"],
    why: ["Level 1 is reversed to 3 2.", "A single level needs no reversal."],
    hidden: ["1\n-1", "3\n1 2 3", "5\n1 2 3 4 5", "3\n1 -1 2"],
    edge: ["3\n1 2 -1"],
    companies: ["amazon", "microsoft"],
  },
  {
    slug: "tree-right-view",
    title: "Right View of a Binary Tree",
    difficulty: "MEDIUM",
    topics: ["trees"],
    d: "Print the values visible when the tree is viewed from the right, that is the last node of each level.",
    in: "First line: n.\nSecond line: n level-order values, -1 for absent.",
    out: "The right view, space separated, or EMPTY.",
    c: "1 <= n <= 100000",
    hints: ["Exactly one node per level is visible.", "It is the rightmost node of that level.", "Take the last node of each BFS level."],
    ap: "Level-order traversal keeping the last node of each level.",
    it: "Visibility from the right is purely a per-level question, which BFS answers directly.",
    st: ["Traverse level by level.", "Record the final node of each level.", "Print those values in order."],
    tc: "O(n)", sc: "O(n)",
    solve: (input) => { const r = reader(input); const n = r.int(); const a = r.ints(n); const out: number[] = []; let level = [0]; while (level.length) { const values = level.filter((i) => i < n && a[i] !== -1); if (!values.length) break; out.push(a[values[values.length - 1]]); const next: number[] = []; for (const i of values) next.push(2 * i + 1, 2 * i + 2); level = next; } return out.length ? join(out) : "EMPTY"; },
    samples: ["7\n1 2 3 4 5 6 7", "3\n1 2 -1"],
    why: ["The rightmost node of each level.", "With no right child, the left node is visible."],
    hidden: ["1\n1", "1\n-1", "5\n1 2 3 4 5", "3\n1 -1 3"],
    edge: ["3\n1 -1 -1"],
    companies: ["amazon", "adobe"],
  },
  {
    slug: "tree-path-sum-exists",
    title: "Root to Leaf Path Sum",
    difficulty: "MEDIUM",
    topics: ["trees", "recursion"],
    d: "Decide whether some root-to-leaf path has values summing to a target.",
    in: "First line: n and target.\nSecond line: n level-order values, -1 for absent.",
    out: "YES if such a path exists, otherwise NO.",
    c: "1 <= n <= 100000\n-10^9 <= values, target <= 10^9",
    hints: ["Carry the running sum downwards.", "Only leaves may complete a path.", "Subtract as you descend and test for zero at a leaf."],
    ap: "Depth-first search carrying the remaining target, succeeding at a leaf whose value exactly closes it.",
    it: "Checking only at leaves is essential, since a prefix hitting the target mid-path is not a valid answer.",
    st: ["Descend, subtracting each node's value from the target.", "At a leaf, succeed when the remainder is zero.", "Otherwise recurse into both children."],
    tc: "O(n)", sc: "O(h)",
    solve: (input) => { const r = reader(input); const n = r.int(), target = r.int(); const a = r.ints(n); const go = (i: number, rest: number): boolean => { if (i >= n || a[i] === -1) return false; const remaining = rest - a[i]; const left = 2 * i + 1, right = 2 * i + 2; const hasLeft = left < n && a[left] !== -1; const hasRight = right < n && a[right] !== -1; if (!hasLeft && !hasRight) return remaining === 0; return go(left, remaining) || go(right, remaining); }; return yesNo(go(0, target)); },
    samples: ["7 12\n5 4 8 11 -1 13 4", "3 5\n1 2 3"],
    why: ["5 + 4 + ... reaches 12 along one branch.", "No root-to-leaf path sums to 5."],
    hidden: ["1 1\n1", "1 0\n1", "3 3\n1 2 -1", "3 4\n1 -1 3"],
    edge: ["1 -1\n-1"],
  },
  {
    slug: "tree-from-inorder-preorder",
    title: "Build a Tree from Inorder and Preorder",
    difficulty: "MEDIUM",
    topics: ["trees", "recursion"],
    d: "Given the inorder and preorder traversals of a binary tree with distinct values, print its postorder traversal.",
    in: "First line: n.\nSecond line: the inorder traversal.\nThird line: the preorder traversal.",
    out: "The postorder traversal, space separated.",
    c: "1 <= n <= 100000\nAll values are distinct.",
    hints: ["The first preorder value is always the root.", "Its position in the inorder splits left from right.", "Recurse on the two halves with matching preorder slices."],
    ap: "Recursive reconstruction: the preorder head is the root, its index in the inorder array partitions the remaining values, and the sizes determine the preorder slices.",
    it: "Preorder gives you roots in the order you need them; inorder tells you how the rest splits around each root.",
    st: ["Index the inorder positions in a hash map.", "Take the next preorder value as the root.", "Recurse into the left slice, then the right slice.", "Emit the root after both children."],
    tc: "O(n)", sc: "O(n)",
    solve: (input) => { const r = reader(input); const n = r.int(); const inorder = r.ints(n); const preorder = r.ints(n); const pos = new Map(inorder.map((v, i) => [v, i])); const out: number[] = []; let p = 0; const go = (lo: number, hi: number) => { if (lo > hi) return; const root = preorder[p++]; const mid = pos.get(root)!; go(lo, mid - 1); go(mid + 1, hi); out.push(root); }; go(0, n - 1); return join(out); },
    samples: ["5\n4 2 5 1 3\n1 2 4 5 3", "1\n1\n1"],
    why: ["The reconstructed tree has that postorder.", "A single node is its own postorder."],
    hidden: ["3\n1 2 3\n2 1 3", "3\n1 2 3\n1 2 3", "3\n3 2 1\n1 2 3", "4\n1 2 3 4\n1 2 3 4"],
    edge: ["2\n1 2\n1 2"],
    companies: ["amazon", "microsoft"],
  },
  {
    slug: "flatten-tree-to-list",
    title: "Flatten a Binary Tree",
    difficulty: "MEDIUM",
    topics: ["trees"],
    d: "Flatten a binary tree into a right-leaning chain following preorder, and print the resulting sequence.",
    in: "First line: n.\nSecond line: n level-order values, -1 for absent.",
    out: "The flattened order, space separated, or EMPTY.",
    c: "1 <= n <= 100000",
    hints: ["The target order is exactly preorder.", "Every node keeps only a right child afterwards.", "A reverse post-order rewiring does it in place."],
    ap: "Emit the preorder sequence. In a real tree, rewiring in reverse post-order (right, left, node) converts it in place with O(1) extra space.",
    it: "The flattened chain is preorder by definition, so the traversal and the target coincide.",
    st: ["Traverse preorder.", "Emit each node as it is visited.", "In an in-place version, attach the previous node as the current node's right child."],
    tc: "O(n)", sc: "O(h)",
    solve: (input) => { const r = reader(input); const n = r.int(); const a = r.ints(n); const out: number[] = []; const go = (i: number) => { if (i >= n || a[i] === -1) return; out.push(a[i]); go(2 * i + 1); go(2 * i + 2); }; go(0); return out.length ? join(out) : "EMPTY"; },
    samples: ["7\n1 2 5 3 4 -1 6", "1\n1"],
    why: ["Preorder visits the left subtree entirely before the right.", "A single node needs no flattening."],
    hidden: ["1\n-1", "3\n1 2 3", "7\n1 2 3 4 5 6 7", "3\n1 -1 2"],
    edge: ["3\n1 2 -1"],
  },
  {
    slug: "trie-prefix-count",
    title: "Prefix Count with a Trie",
    difficulty: "MEDIUM",
    topics: ["tries", "strings"],
    d: "Insert a set of words, then for each query count how many words start with the given prefix.",
    in: "First line: n and q.\nSecond line: n lowercase words.\nNext q lines: one prefix each.",
    out: "One count per query.",
    c: "1 <= n, q <= 100000\nTotal characters across all words and queries <= 10^6",
    hints: ["Comparing each query against every word is O(nq).", "Words sharing a prefix should share storage.", "A trie stores a count at every node."],
    ap: "Build a trie where each node records how many inserted words pass through it, then answer each query by walking the prefix and reading that count.",
    it: "The count at a node is exactly the number of words in its subtree, which makes prefix queries O(|prefix|).",
    st: ["Insert each word, incrementing the passing count at every node.", "For a query, walk the prefix character by character.", "Return the node's count, or 0 if the walk fails."],
    tc: "O(total characters)", sc: "O(total characters)",
    solve: (input) => { const parts = input.trim().split("\n").map((l) => l.trim()); const [n, q] = parts[0].split(/\s+/).map(Number); const words = (parts[1] ?? "").split(/\s+/).slice(0, n); const out: number[] = []; for (let i = 0; i < q; i += 1) { const prefix = parts[2 + i] ?? ""; out.push(words.filter((w) => w.startsWith(prefix)).length); } return linesOut(out); },
    samples: ["4 2\napple app apply banana\napp\nban", "2 1\ncat dog\nz"],
    why: ["Three words begin with 'app'.", "No word begins with 'z'."],
    hidden: ["1 1\na\na", "3 2\naa ab ac\na\nab", "3 1\nx y z\nx", "2 2\nforge forget\nforge\nforget"],
    edge: ["1 1\nab\nabc"],
    companies: ["amazon", "google"],
  },
  {
    slug: "trie-autocomplete",
    title: "Autocomplete Suggestions",
    difficulty: "MEDIUM",
    topics: ["tries", "strings"],
    d: "Given a dictionary and a prefix, print the three lexicographically smallest words starting with that prefix, or NONE.",
    in: "First line: n.\nSecond line: n lowercase words.\nThird line: the prefix.",
    out: "Up to three words on one line, or NONE.",
    c: "1 <= n <= 100000\nTotal characters <= 10^6",
    hints: ["The answer is a contiguous block once the words are sorted.", "A trie walk narrows to the prefix subtree.", "A depth-first walk of that subtree yields sorted order."],
    ap: "Walk the trie to the prefix node, then depth-first search its subtree in alphabetical order, stopping after three complete words.",
    it: "A trie's children in alphabetical order make DFS emit words in lexicographic order for free.",
    st: ["Descend to the prefix node.", "DFS the subtree visiting children a..z.", "Collect complete words until three are found."],
    tc: "O(|prefix| + output)", sc: "O(total characters)",
    solve: (input) => { const parts = input.trim().split("\n").map((l) => l.trim()); const n = Number(parts[0]); const words = (parts[1] ?? "").split(/\s+/).slice(0, n); const prefix = parts[2] ?? ""; const matches = words.filter((w) => w.startsWith(prefix)).sort().slice(0, 3); return matches.length ? matches.join(" ") : "NONE"; },
    samples: ["5\nforge forget for format fork\nfor", "3\ncat dog emu\nz"],
    why: ["The three smallest matches in order.", "Nothing matches the prefix."],
    hidden: ["1\na\na", "4\naa ab ac ad\na", "3\nx y z\nx", "2\nabc abd\nab"],
    edge: ["1\nab\nb"],
  },
  {
    slug: "sliding-window-maximum",
    title: "Sliding Window Maximum",
    difficulty: "MEDIUM",
    topics: ["queue", "arrays"],
    d: "For every window of size k, print the maximum value in that window.",
    in: "First line: n and k.\nSecond line: n integers.",
    out: "The n-k+1 window maxima, space separated.",
    c: "1 <= k <= n <= 100000\n-10^9 <= a[i] <= 10^9",
    hints: ["Recomputing the maximum per window is O(nk).", "An element smaller than a later element can never be a maximum again.", "Keep a deque of indices with decreasing values."],
    ap: "Monotonic deque of indices holding values in decreasing order. The front is always the current window's maximum; smaller trailing values are discarded on insertion.",
    it: "Discarding dominated elements permanently is what keeps the total work linear.",
    st: ["Pop indices that have left the window from the front.", "Pop indices with values <= the incoming value from the back.", "Push the new index.", "Emit the front once the window is full."],
    tc: "O(n)", sc: "O(k)",
    solve: (input) => { const r = reader(input); const n = r.int(), k = r.int(); const a = r.ints(n); const dq: number[] = []; const out: number[] = []; for (let i = 0; i < n; i += 1) { while (dq.length && dq[0] <= i - k) dq.shift(); while (dq.length && a[dq[dq.length - 1]] <= a[i]) dq.pop(); dq.push(i); if (i >= k - 1) out.push(a[dq[0]]); } return join(out); },
    samples: ["8 3\n1 3 -1 -3 5 3 6 7", "4 1\n4 3 2 1"],
    why: ["Each window's maximum in order.", "Windows of size one are the elements themselves."],
    hidden: ["1 1\n5", "5 5\n1 2 3 4 5", "5 2\n5 4 3 2 1", "6 3\n1 1 1 1 1 1"],
    edge: ["2 2\n-1000000000 1000000000"],
    companies: ["amazon", "google", "microsoft"],
  },
  {
    slug: "min-window-substring",
    title: "Minimum Window Substring",
    difficulty: "MEDIUM",
    topics: ["strings", "hashing"],
    d: "Find the length of the shortest substring of s that contains every character of t including repetitions. Print 0 when no such window exists.",
    in: "Line 1: string s.\nLine 2: string t.",
    out: "The length of the shortest covering window, or 0.",
    c: "1 <= |s|, |t| <= 100000",
    hints: ["Grow the window until it covers t, then shrink from the left.", "Track how many required characters are still missing.", "A window is valid exactly when nothing is missing."],
    ap: "Two-pointer sliding window with a requirement count. Expand until the window is valid, then contract while it stays valid, recording the best length.",
    it: "Both pointers only move forward, so the whole scan is linear despite the nested-looking contraction.",
    st: ["Count the characters required by t.", "Expand the right edge, decrementing the missing count on useful characters.", "While the window is valid, record the length and advance the left edge.", "Print the best length."],
    tc: "O(|s| + |t|)", sc: "O(alphabet)",
    solve: (input) => { const [s = "", t = ""] = input.trim().split("\n").map((l) => l.trim()); const need = new Map<string, number>(); for (const ch of t) need.set(ch, (need.get(ch) ?? 0) + 1); let missing = t.length, left = 0, best = Infinity; for (let right = 0; right < s.length; right += 1) { const ch = s[right]; const count = need.get(ch); if (count !== undefined) { if (count > 0) missing -= 1; need.set(ch, count - 1); } while (missing === 0) { best = Math.min(best, right - left + 1); const lch = s[left]; const lcount = need.get(lch); if (lcount !== undefined) { need.set(lch, lcount + 1); if (lcount + 1 > 0) missing += 1; } left += 1; } } return String(best === Infinity ? 0 : best); },
    samples: ["ADOBECODEBANC\nABC", "a\naa"],
    why: ["'BANC' is the shortest covering window.", "s does not contain two a's."],
    hidden: ["a\na", "ab\nb", "aaflslflsldkalskaaa\naaa", "abc\nd"],
    edge: ["a\nb"],
    companies: ["amazon", "meta", "google"],
  },
  {
    slug: "longest-repeating-replacement",
    title: "Longest Repeating Character Replacement",
    difficulty: "MEDIUM",
    topics: ["strings"],
    d: "You may change at most k characters. Find the length of the longest substring that can be made of a single repeated character.",
    in: "First line: k.\nSecond line: an uppercase string.",
    out: "The length of the longest achievable run.",
    c: "0 <= k <= |s| <= 100000",
    hints: ["A window is valid when its length minus its most common count is at most k.", "That difference is the number of replacements needed.", "Slide the window, tracking the highest character count inside it."],
    ap: "Sliding window tracking the most frequent character count. When length minus that count exceeds k, advance the left edge.",
    it: "Only the majority character matters, because everything else is what you would replace.",
    st: ["Expand the right edge, updating character counts.", "Track the maximum count seen in the window.", "If length - maxCount exceeds k, advance the left edge.", "Record the largest valid window."],
    tc: "O(n)", sc: "O(alphabet)",
    solve: (input) => { const parts = input.trim().split("\n").map((l) => l.trim()); const k = Number(parts[0]); const s = parts[1] ?? ""; const count = new Map<string, number>(); let left = 0, maxCount = 0, best = 0; for (let right = 0; right < s.length; right += 1) { const ch = s[right]; count.set(ch, (count.get(ch) ?? 0) + 1); maxCount = Math.max(maxCount, count.get(ch)!); while (right - left + 1 - maxCount > k) { count.set(s[left], count.get(s[left])! - 1); left += 1; } best = Math.max(best, right - left + 1); } return String(best); },
    samples: ["1\nAABABBA", "2\nABAB"],
    why: ["Replacing one character yields a run of four.", "Two replacements make the whole string uniform."],
    hidden: ["0\nAAAA", "0\nABCD", "1\nA", "3\nAABBCC"],
    edge: ["0\nA"],
  },
  {
    slug: "permutation-in-string",
    title: "Permutation in a String",
    difficulty: "MEDIUM",
    topics: ["strings", "hashing"],
    d: "Decide whether some permutation of the first string appears as a contiguous substring of the second.",
    in: "Line 1: pattern p.\nLine 2: text s.",
    out: "YES if such a window exists, otherwise NO.",
    c: "1 <= |p|, |s| <= 100000",
    hints: ["A permutation is a multiset, not an order.", "Every candidate window has the same length as the pattern.", "Slide a fixed-size window and compare frequency vectors."],
    ap: "Fixed-size sliding window over s, maintaining a 26-slot frequency vector and comparing it against the pattern's vector at each step.",
    it: "Fixing the window length turns a permutation search into repeated multiset equality.",
    st: ["Count the pattern's characters.", "Count the first window of s.", "Slide, adding the entering and removing the leaving character.", "Report YES on any match."],
    tc: "O(|s|)", sc: "O(alphabet)",
    solve: (input) => { const [p = "", s = ""] = input.trim().split("\n").map((l) => l.trim()); if (p.length > s.length) return "NO"; const key = (m: Map<string, number>) => [...m.entries()].filter(([, c]) => c > 0).sort().map(([ch, c]) => `${ch}${c}`).join(""); const need = new Map<string, number>(); for (const ch of p) need.set(ch, (need.get(ch) ?? 0) + 1); const target = key(need); const window = new Map<string, number>(); for (let i = 0; i < s.length; i += 1) { window.set(s[i], (window.get(s[i]) ?? 0) + 1); if (i >= p.length) { const out = s[i - p.length]; window.set(out, window.get(out)! - 1); } if (i >= p.length - 1 && key(window) === target) return "YES"; } return "NO"; },
    samples: ["ab\neidbaooo", "ab\neidboaoo"],
    why: ["'ba' is a permutation of 'ab'.", "No adjacent pair is a permutation of 'ab'."],
    hidden: ["a\na", "abc\ncba", "abc\nxyz", "aa\naaa"],
    edge: ["ab\na"],
    companies: ["amazon", "microsoft"],
  },
  {
    slug: "container-with-most-water",
    title: "Container With Most Water",
    difficulty: "MEDIUM",
    topics: ["arrays", "greedy"],
    d: "Vertical lines stand at each index with the given heights. Choose two lines so that the water held between them is maximised, and print that area.",
    in: "First line: n.\nSecond line: n non-negative heights.",
    out: "The maximum area.",
    c: "2 <= n <= 100000\n0 <= height <= 10^9",
    hints: ["The area is width times the shorter of the two lines.", "Start with the widest possible pair.", "Moving the taller line inwards can never help."],
    ap: "Two pointers at both ends, always moving the shorter line inwards, since keeping it can only reduce both width and height.",
    it: "The shorter line caps the area, so it is the only one worth replacing.",
    st: ["Set lo = 0 and hi = n-1.", "Compute the area and update the best.", "Move whichever pointer holds the shorter line.", "Stop when the pointers meet."],
    tc: "O(n)", sc: "O(1)",
    solve: (input) => { const a = A(input); let lo = 0, hi = a.length - 1, best = 0; while (lo < hi) { best = Math.max(best, (hi - lo) * Math.min(a[lo], a[hi])); if (a[lo] < a[hi]) lo += 1; else hi -= 1; } return String(best); },
    samples: ["9\n1 8 6 2 5 4 8 3 7", "2\n1 1"],
    why: ["Lines at indices 1 and 8 hold 49 units.", "Width 1 and height 1."],
    hidden: ["3\n1 2 1", "4\n1 2 4 3", "5\n0 0 0 0 0", "2\n1000000000 1000000000"],
    edge: ["2\n0 5"],
    companies: ["amazon", "meta", "adobe"],
  },
  {
    slug: "trapping-rain-water-medium",
    title: "Trapping Rain Water",
    difficulty: "MEDIUM",
    topics: ["arrays"],
    d: "Given an elevation map, compute how much rain water is trapped between the bars.",
    in: "First line: n.\nSecond line: n non-negative heights.",
    out: "The total trapped water.",
    c: "1 <= n <= 100000\n0 <= height <= 10^5",
    hints: ["Water above a bar is limited by the tallest bars on each side.", "Precomputing both prefix maxima works in O(n) space.", "Two pointers reduce that to O(1)."],
    ap: "Two pointers moving inwards, each carrying the running maximum from its own side. The smaller running maximum bounds the water at that position.",
    it: "You only need to know that the other side has something at least as tall, not exactly how tall.",
    st: ["Set lo = 0, hi = n-1, and both running maxima to 0.", "Advance the side with the smaller height.", "Add runningMax minus the current height when positive.", "Stop when the pointers meet."],
    tc: "O(n)", sc: "O(1)",
    solve: (input) => { const a = A(input); let lo = 0, hi = a.length - 1, leftMax = 0, rightMax = 0, total = 0; while (lo < hi) { if (a[lo] < a[hi]) { leftMax = Math.max(leftMax, a[lo]); total += leftMax - a[lo]; lo += 1; } else { rightMax = Math.max(rightMax, a[hi]); total += rightMax - a[hi]; hi -= 1; } } return String(total); },
    samples: ["12\n0 1 0 2 1 0 1 3 2 1 2 1", "6\n4 2 0 3 2 5"],
    why: ["Six units of water settle in the dips.", "Nine units are trapped."],
    hidden: ["1\n5", "3\n3 0 3", "5\n1 2 3 4 5", "4\n0 0 0 0"],
    edge: ["2\n5 5"],
    companies: ["amazon", "google", "meta", "microsoft"],
  },
  {
    slug: "dutch-flag-partition",
    title: "Three-Way Partition",
    difficulty: "MEDIUM",
    topics: ["arrays", "sorting"],
    d: "Rearrange an array so that all values less than a pivot come first, then values equal to it, then values greater. Print the resulting array.",
    in: "First line: n and pivot.\nSecond line: n integers.",
    out: "The partitioned array, space separated.",
    c: "1 <= n <= 100000",
    hints: ["Three regions means three boundaries.", "Scan with a middle pointer classifying each element.", "Swap into the low or high region and adjust the boundary."],
    ap: "Dutch national flag partitioning with low, mid and high pointers, classifying each element exactly once.",
    it: "This is the partition step that lets quicksort handle many duplicate keys efficiently.",
    st: ["Set low = 0, mid = 0, high = n-1.", "If a[mid] < pivot swap with low and advance both.", "If equal just advance mid.", "If greater swap with high and decrement high."],
    tc: "O(n)", sc: "O(1)",
    solve: (input) => { const r = reader(input); const n = r.int(), pivot = r.int(); const a = r.ints(n); const lo = a.filter((v) => v < pivot); const eq = a.filter((v) => v === pivot); const hi = a.filter((v) => v > pivot); return join([...lo, ...eq, ...hi]); },
    samples: ["6 3\n5 2 3 1 4 3", "3 1\n1 1 1"],
    why: ["Values below 3, then the 3s, then above.", "Everything equals the pivot."],
    hidden: ["1 1\n1", "5 0\n-1 -2 1 2 0", "4 5\n1 2 3 4", "4 1\n2 3 4 5"],
    edge: ["2 0\n-1 1"],
  },
  {
    slug: "next-permutation",
    title: "Next Permutation",
    difficulty: "MEDIUM",
    topics: ["arrays", "greedy"],
    d: "Rearrange the array into the next lexicographically greater permutation. If none exists, print the smallest permutation instead.",
    in: "First line: n.\nSecond line: n integers.",
    out: "The next permutation, space separated.",
    c: "1 <= n <= 100000",
    hints: ["The suffix that is already descending cannot be improved.", "Find the rightmost position where a[i] < a[i+1].", "Swap it with the smallest larger value to its right, then reverse the suffix."],
    ap: "Find the rightmost ascent, swap that pivot with the smallest greater value in the descending suffix, then reverse the suffix to make it ascending.",
    it: "Reversing the suffix turns the largest arrangement of those values into the smallest, which is exactly the next permutation.",
    st: ["Scan right to left for the first index i with a[i] < a[i+1].", "If none exists, reverse the whole array.", "Otherwise find the rightmost j > i with a[j] > a[i] and swap.", "Reverse the suffix after i."],
    tc: "O(n)", sc: "O(1)",
    solve: (input) => { const a = A(input); const n = a.length; let i = n - 2; while (i >= 0 && a[i] >= a[i + 1]) i -= 1; if (i >= 0) { let j = n - 1; while (a[j] <= a[i]) j -= 1; [a[i], a[j]] = [a[j], a[i]]; } const tail = a.slice(i + 1).reverse(); return join([...a.slice(0, i + 1), ...tail]); },
    samples: ["3\n1 2 3", "3\n3 2 1"],
    why: ["Swapping the last two gives the next arrangement.", "The array is the largest permutation, so it wraps around."],
    hidden: ["1\n1", "2\n1 2", "4\n1 3 2 4", "4\n2 3 1 1"],
    edge: ["2\n2 1"],
    companies: ["google", "amazon", "adobe"],
  },
  {
    slug: "spiral-generate-matrix",
    title: "Generate a Spiral Matrix",
    difficulty: "MEDIUM",
    topics: ["matrix"],
    d: "Fill an n by n matrix with the values 1 to n squared in clockwise spiral order and print it.",
    in: "A single integer n.",
    out: "n lines of n integers each.",
    c: "1 <= n <= 500",
    hints: ["This is the inverse of reading a matrix in spiral order.", "Track four shrinking boundaries.", "Fill one side at a time and move the boundary in."],
    ap: "Walk the four boundaries inwards, writing consecutive values along each side and shrinking the boundary after every sweep.",
    it: "Writing a spiral is exactly the same traversal as reading one, with assignment instead of collection.",
    st: ["Set top, bottom, left and right boundaries.", "Fill the top row, then the right column.", "Fill the bottom row and left column if they remain.", "Shrink and repeat."],
    tc: "O(n^2)", sc: "O(n^2)",
    solve: (input) => { const n = Number(input.trim()); const g = Array.from({ length: n }, () => new Array(n).fill(0)); let top = 0, bottom = n - 1, left = 0, right = n - 1, value = 1; while (top <= bottom && left <= right) { for (let j = left; j <= right; j += 1) g[top][j] = value++; top += 1; for (let i = top; i <= bottom; i += 1) g[i][right] = value++; right -= 1; if (top <= bottom) { for (let j = right; j >= left; j -= 1) g[bottom][j] = value++; bottom -= 1; } if (left <= right) { for (let i = bottom; i >= top; i -= 1) g[i][left] = value++; left += 1; } } return linesOut(g.map((row) => join(row))); },
    samples: ["3", "1"],
    why: ["The values wind clockwise from the top-left.", "A single cell holds 1."],
    hidden: ["2", "4", "5", "6"],
    edge: ["7"],
  },
  {
    slug: "pascal-triangle-row",
    title: "Row of Pascal's Triangle",
    difficulty: "MEDIUM",
    topics: ["math", "dp"],
    d: "Print row n of Pascal's triangle, where row 0 is a single 1. Report each entry modulo 1000000007.",
    in: "A single integer n.",
    out: "The n+1 entries of the row, space separated.",
    c: "0 <= n <= 1000",
    hints: ["Each entry is the sum of the two above it.", "Building the whole triangle costs O(n^2).", "Each entry is also C(n, k), computable from the previous one."],
    ap: "Build the row iteratively using C(n, k) = C(n, k-1) * (n-k+1) / k under modular arithmetic, or accumulate row by row.",
    it: "Consecutive binomial coefficients differ by a simple ratio, so the whole row costs O(n) multiplications.",
    st: ["Start with C(n,0) = 1.", "For each k, multiply by (n-k+1) and divide by k.", "Use modular inverses for the division.", "Print the row."],
    tc: "O(n log p)", sc: "O(n)",
    solve: (input) => { const n = Number(input.trim()); let row = [1n]; for (let i = 1; i <= n; i += 1) { const next: bigint[] = [1n]; for (let j = 1; j < row.length; j += 1) next.push((row[j - 1] + row[j]) % MOD); next.push(1n); row = next; } return join(row.map(String)); },
    samples: ["4", "0"],
    why: ["Row 4 is 1 4 6 4 1.", "Row 0 is a single 1."],
    hidden: ["1", "5", "10", "100"],
    edge: ["2"],
  },
  {
    slug: "power-modular-exponentiation",
    title: "Modular Exponentiation",
    difficulty: "MEDIUM",
    topics: ["math"],
    d: "Compute a raised to the power b modulo m.",
    in: "One line: a, b and m.",
    out: "The value of a^b mod m.",
    c: "0 <= a, b <= 10^18\n1 <= m <= 10^18",
    hints: ["Multiplying b times is far too slow.", "Square the base and halve the exponent.", "Reduce modulo m after every multiplication."],
    ap: "Binary exponentiation: square the base while halving the exponent, multiplying the result in whenever the current bit is set.",
    it: "The exponent's binary representation turns b multiplications into log b of them.",
    st: ["Set result = 1 and reduce a modulo m.", "While b > 0, multiply result by a when the low bit is set.", "Square a and shift b right.", "Print the result."],
    tc: "O(log b)", sc: "O(1)",
    solve: (input) => { const [a, b, m] = input.trim().split(/\s+/).map(BigInt); let result = 1n, base = a % m, e = b; while (e > 0n) { if (e & 1n) result = (result * base) % m; base = (base * base) % m; e >>= 1n; } return result.toString(); },
    samples: ["2 10 1000", "3 0 7"],
    why: ["2^10 = 1024, which is 24 modulo 1000.", "Anything to the power zero is 1."],
    hidden: ["0 5 7", "5 3 13", "1000000007 2 1000000009", "2 62 1000000007"],
    edge: ["1 1000000000000000000 1"],
  },
  {
    slug: "count-primes-range",
    title: "Count Primes in a Range",
    difficulty: "MEDIUM",
    topics: ["math"],
    d: "Count the primes in the inclusive range [l, r].",
    in: "One line: l and r.",
    out: "The number of primes in the range.",
    c: "1 <= l <= r <= 1000000",
    hints: ["Testing each number separately is slow for wide ranges.", "Sieve once up to r.", "Then count with a prefix sum over the sieve."],
    ap: "Sieve of Eratosthenes up to r, then a prefix-sum count so any range is answered in constant time.",
    it: "One sieve amortises across the whole range instead of paying per number.",
    st: ["Sieve up to r.", "Build a prefix count of primes.", "Answer with prefix[r] - prefix[l-1]."],
    tc: "O(r log log r)", sc: "O(r)",
    solve: (input) => { const [l, r] = input.trim().split(/\s+/).map(Number); const sieve = new Uint8Array(r + 1); let count = 0; for (let p = 2; p <= r; p += 1) { if (sieve[p]) continue; if (p >= l) count += 1; for (let q = p * p; q <= r; q += p) sieve[q] = 1; } return String(count); },
    samples: ["1 10", "10 20"],
    why: ["2, 3, 5 and 7.", "11, 13, 17 and 19."],
    hidden: ["1 1", "2 2", "1 100", "999900 1000000"],
    edge: ["1 2"],
  },
  {
    slug: "factorial-trailing-zeroes",
    title: "Trailing Zeroes in a Factorial",
    difficulty: "MEDIUM",
    topics: ["math"],
    d: "Count the trailing zeroes of n factorial.",
    in: "A single integer n.",
    out: "The number of trailing zeroes.",
    c: "0 <= n <= 10^18",
    hints: ["A trailing zero comes from a factor of 10.", "Tens are made of a 2 and a 5, and 2s are plentiful.", "So count the factors of 5 in n!."],
    ap: "Legendre's formula: sum n/5 + n/25 + n/125 + ... using integer division.",
    it: "Factors of 5 are the bottleneck, and higher powers of 5 contribute extra factors that the first term misses.",
    st: ["Set count = 0 and power = 5.", "While power <= n, add n / power.", "Multiply power by 5.", "Print the count."],
    tc: "O(log n)", sc: "O(1)",
    solve: (input) => { const n = BigInt(input.trim()); let count = 0n; let p = 5n; while (p <= n) { count += n / p; if (p > 10n ** 18n / 5n) break; p *= 5n; } return count.toString(); },
    samples: ["5", "3"],
    why: ["5! = 120 has one trailing zero.", "3! = 6 has none."],
    hidden: ["0", "25", "100", "1000000000000000000"],
    edge: ["4"],
  },
  {
    slug: "roman-to-integer",
    title: "Roman to Integer",
    difficulty: "MEDIUM",
    topics: ["strings", "math"],
    d: "Convert a valid Roman numeral to its integer value.",
    in: "A single line containing a Roman numeral.",
    out: "The integer value.",
    c: "1 <= |s| <= 15\nThe numeral is valid and below 4000.",
    hints: ["Most symbols simply add.", "A smaller symbol before a larger one subtracts.", "Compare each symbol with the one after it."],
    ap: "Scan left to right, subtracting a value when it is smaller than the next one and adding it otherwise.",
    it: "Subtractive pairs are the only irregularity, and a single lookahead detects them.",
    st: ["Map each symbol to its value.", "For each position compare with the next value.", "Subtract when smaller, otherwise add.", "Print the total."],
    tc: "O(n)", sc: "O(1)",
    solve: (input) => { const s = input.trim(); const v: Record<string, number> = { I: 1, V: 5, X: 10, L: 50, C: 100, D: 500, M: 1000 }; let total = 0; for (let i = 0; i < s.length; i += 1) { if (i + 1 < s.length && v[s[i]] < v[s[i + 1]]) total -= v[s[i]]; else total += v[s[i]]; } return String(total); },
    samples: ["MCMXCIV", "III"],
    why: ["1000 + 900 + 90 + 4.", "Three ones."],
    hidden: ["I", "IV", "LVIII", "MMMCMXCIX"],
    edge: ["IX"],
    companies: ["amazon", "microsoft", "adobe"],
  },
  {
    slug: "integer-to-roman",
    title: "Integer to Roman",
    difficulty: "MEDIUM",
    topics: ["strings", "greedy"],
    d: "Convert an integer below 4000 to its Roman numeral form.",
    in: "A single integer n.",
    out: "The Roman numeral.",
    c: "1 <= n <= 3999",
    hints: ["Include the subtractive forms as their own symbols.", "Always take the largest symbol that fits.", "Greedy works because the symbol set is canonical."],
    ap: "Greedy over a descending table of values that includes the subtractive combinations (900, 400, 90, 40, 9, 4).",
    it: "Adding the subtractive forms to the table is what makes plain greedy correct.",
    st: ["List value-symbol pairs in descending order.", "Repeatedly subtract the largest value that fits, appending its symbol.", "Stop when the number reaches zero."],
    tc: "O(1)", sc: "O(1)",
    solve: (input) => { let n = Number(input.trim()); const table: Array<[number, string]> = [[1000, "M"], [900, "CM"], [500, "D"], [400, "CD"], [100, "C"], [90, "XC"], [50, "L"], [40, "XL"], [10, "X"], [9, "IX"], [5, "V"], [4, "IV"], [1, "I"]]; let out = ""; for (const [value, symbol] of table) while (n >= value) { out += symbol; n -= value; } return out; },
    samples: ["1994", "3"],
    why: ["MCMXCIV.", "III."],
    hidden: ["1", "4", "58", "3999"],
    edge: ["9"],
  },
  {
    slug: "atoi-string-to-integer",
    title: "String to Integer",
    difficulty: "MEDIUM",
    topics: ["strings"],
    d: "Parse a leading integer from a string. Skip leading spaces, accept an optional sign, read digits until a non-digit, and clamp the result to the 32-bit signed range. Print 0 when no digits are found.",
    in: "A single line of text.",
    out: "The parsed integer.",
    c: "0 <= |s| <= 200",
    hints: ["The order of the parsing steps matters.", "Stop at the first character that is not a digit.", "Clamp rather than overflow."],
    ap: "Skip whitespace, read an optional sign, accumulate digits while clamping to the 32-bit range, and stop at the first non-digit.",
    it: "This is a parsing exercise: every edge case is about where parsing must stop.",
    st: ["Skip leading spaces.", "Read an optional + or -.", "Accumulate digits, clamping at the 32-bit bounds.", "Return the signed value."],
    tc: "O(n)", sc: "O(1)",
    solve: (input) => { const s = input.replace(/\r?\n$/, ""); let i = 0; while (i < s.length && s[i] === " ") i += 1; let sign = 1; if (s[i] === "+" || s[i] === "-") { sign = s[i] === "-" ? -1 : 1; i += 1; } let value = 0n; while (i < s.length && s[i] >= "0" && s[i] <= "9") { value = value * 10n + BigInt(s[i]); if (value > 3000000000n) break; i += 1; } let result = sign === -1 ? -value : value; if (result > 2147483647n) result = 2147483647n; if (result < -2147483648n) result = -2147483648n; return result.toString(); },
    samples: ["42", "   -42abc"],
    why: ["A plain integer.", "Spaces are skipped, the sign is read, and parsing stops at 'a'."],
    hidden: ["words and 987", "-91283472332", "+1", "0"],
    edge: ["-"],
  },
  {
    slug: "compare-version-numbers",
    title: "Compare Version Numbers",
    difficulty: "MEDIUM",
    topics: ["strings"],
    d: "Compare two dotted version strings. Print 1 if the first is greater, -1 if smaller, and 0 if they are equal. Missing components count as zero.",
    in: "Line 1: version a.\nLine 2: version b.",
    out: "1, -1 or 0.",
    c: "1 <= |version| <= 500",
    hints: ["Compare component by component, not as strings.", "Leading zeroes must not affect the comparison.", "Treat missing components as zero."],
    ap: "Split both versions on dots, compare the numeric value of each component in turn, treating missing components as zero.",
    it: "String comparison fails on cases like 1.10 versus 1.9, which is why numeric comparison per component is required.",
    st: ["Split both strings on '.'.", "Iterate over the longer length.", "Compare the numeric values, defaulting to 0.", "Return on the first difference."],
    tc: "O(|a| + |b|)", sc: "O(|a| + |b|)",
    solve: (input) => { const [a = "", b = ""] = input.trim().split("\n").map((l) => l.trim()); const x = a.split("."), y = b.split("."); for (let i = 0; i < Math.max(x.length, y.length); i += 1) { const p = Number(x[i] ?? 0), q = Number(y[i] ?? 0); if (p > q) return "1"; if (p < q) return "-1"; } return "0"; },
    samples: ["1.10\n1.9", "1.0\n1"],
    why: ["Component 10 exceeds component 9.", "The missing component counts as zero."],
    hidden: ["1.0.1\n1", "0.1\n1.1", "1.0.0\n1.0.0", "1.01\n1.001"],
    edge: ["1\n1"],
  },
  {
    slug: "min-stack-getmin",
    title: "Min Stack with Constant Time Minimum",
    difficulty: "MEDIUM",
    topics: ["stack"],
    d: "Support PUSH x, POP, TOP and GETMIN, all in constant time. Reads on an empty stack print EMPTY.",
    in: "First line: q.\nNext q lines: one operation each.",
    out: "One line per POP, TOP or GETMIN.",
    c: "1 <= q <= 100000",
    hints: ["Scanning for the minimum is O(n) per query.", "Store the running minimum alongside each pushed value.", "Popping then restores the previous minimum automatically."],
    ap: "Store a (value, minimum-so-far) pair with each element so every operation is O(1) and pops restore the previous minimum for free.",
    it: "A stack's prefix structure means the minimum of every prefix can be cached at push time.",
    st: ["On PUSH, record min(value, current minimum).", "On POP, remove the pair.", "TOP returns the stored value.", "GETMIN returns the stored minimum."],
    tc: "O(1) per operation", sc: "O(q)",
    solve: (input) => { const parts = input.trim().split("\n"); const q = Number(parts[0]); const stack: number[] = []; const mins: number[] = []; const out: string[] = []; for (let i = 1; i <= q; i += 1) { const [op, value] = (parts[i] ?? "").trim().split(/\s+/); if (op === "PUSH") { const v = Number(value); stack.push(v); mins.push(mins.length ? Math.min(v, mins[mins.length - 1]) : v); } else if (op === "POP") { if (!stack.length) out.push("EMPTY"); else { out.push(String(stack.pop())); mins.pop(); } } else if (op === "TOP") out.push(stack.length ? String(stack[stack.length - 1]) : "EMPTY"); else if (op === "GETMIN") out.push(mins.length ? String(mins[mins.length - 1]) : "EMPTY"); } return linesOut(out); },
    samples: ["6\nPUSH 5\nPUSH 2\nGETMIN\nPOP\nGETMIN\nTOP", "2\nGETMIN\nTOP"],
    why: ["2 is the minimum until popped, then 5 is.", "Both reads hit an empty stack."],
    hidden: ["4\nPUSH -3\nPUSH 0\nGETMIN\nPOP", "3\nPUSH 1\nTOP\nPOP", "5\nPUSH 2\nPUSH 2\nPOP\nGETMIN\nPOP", "1\nPOP"],
    edge: ["2\nPUSH 0\nGETMIN"],
    companies: ["amazon", "google", "adobe"],
  },
  {
    slug: "evaluate-postfix",
    title: "Evaluate a Postfix Expression",
    difficulty: "MEDIUM",
    topics: ["stack"],
    d: "Evaluate a postfix expression with the operators +, -, * and / (integer division truncating towards zero).",
    in: "First line: n, the number of tokens.\nSecond line: n space-separated tokens.",
    out: "The value of the expression.",
    c: "1 <= n <= 100000\nThe expression is valid.",
    hints: ["Operands accumulate until an operator arrives.", "An operator consumes the two most recent operands.", "That is stack behaviour."],
    ap: "Push operands onto a stack; on an operator, pop two operands, apply it, and push the result. The final stack entry is the answer.",
    it: "Postfix needs no precedence rules because the order is already explicit, which is why one stack suffices.",
    st: ["Scan tokens left to right.", "Push numbers.", "On an operator pop two values, apply, and push back.", "Print the final value."],
    tc: "O(n)", sc: "O(n)",
    solve: (input) => { const r = reader(input); const n = r.int(); const tokens = r.strs(n); const stack: number[] = []; for (const t of tokens) { if (t === "+" || t === "-" || t === "*" || t === "/") { const b = stack.pop()!, a = stack.pop()!; stack.push(t === "+" ? a + b : t === "-" ? a - b : t === "*" ? a * b : Math.trunc(a / b)); } else stack.push(Number(t)); } return String(stack[stack.length - 1]); },
    samples: ["5\n2 3 + 4 *", "3\n5 1 -"],
    why: ["(2+3)*4 = 20.", "5-1 = 4."],
    hidden: ["1\n7", "5\n6 2 / 3 *", "7\n1 2 + 3 4 + *", "5\n7 3 - 2 *"],
    edge: ["3\n1 1 -"],
  },
  {
    slug: "infix-to-postfix",
    title: "Infix to Postfix",
    difficulty: "MEDIUM",
    topics: ["stack", "strings"],
    d: "Convert a fully parenthesised-free infix expression over single lowercase letters and the operators +, -, * and / into postfix notation. Parentheses may appear.",
    in: "A single line containing the infix expression without spaces.",
    out: "The postfix expression.",
    c: "1 <= |s| <= 100000",
    hints: ["Operands go straight to the output.", "Operators wait until a lower-precedence operator arrives.", "Parentheses bracket a sub-expression on the stack."],
    ap: "The shunting-yard algorithm: emit operands immediately, pop operators of greater or equal precedence before pushing, and unwind to the matching '(' on a ')'.",
    it: "Precedence is enforced by when an operator is popped, not by when it is pushed.",
    st: ["Emit operands to the output.", "Push '(' and unwind on ')'.", "Before pushing an operator, pop those with greater or equal precedence.", "At the end, pop the remaining operators."],
    tc: "O(n)", sc: "O(n)",
    solve: (input) => { const s = input.trim(); const prec: Record<string, number> = { "+": 1, "-": 1, "*": 2, "/": 2 }; const out: string[] = []; const ops: string[] = []; for (const ch of s) { if (/[a-z0-9]/.test(ch)) out.push(ch); else if (ch === "(") ops.push(ch); else if (ch === ")") { while (ops.length && ops[ops.length - 1] !== "(") out.push(ops.pop()!); ops.pop(); } else if (prec[ch]) { while (ops.length && prec[ops[ops.length - 1]] >= prec[ch]) out.push(ops.pop()!); ops.push(ch); } } while (ops.length) out.push(ops.pop()!); return out.join(""); },
    samples: ["a+b*c", "(a+b)*c"],
    why: ["Multiplication binds tighter, so it is emitted first.", "The parentheses force the addition first."],
    hidden: ["a", "a+b", "a*b+c/d", "((a+b)*c)-d"],
    edge: ["a-b-c"],
  },
  {
    slug: "largest-rectangle-histogram-medium",
    title: "Largest Rectangle in a Histogram",
    difficulty: "MEDIUM",
    topics: ["stack", "arrays"],
    d: "Find the largest rectangular area that fits under a histogram of unit-width bars.",
    in: "First line: n.\nSecond line: n non-negative heights.",
    out: "The largest rectangle area.",
    c: "1 <= n <= 100000\n0 <= height <= 10^9",
    hints: ["Every maximal rectangle is limited by one bar's height.", "For each bar, find how far it can extend both ways.", "A monotonic increasing stack finds both boundaries in one pass."],
    ap: "Monotonic increasing stack. When a shorter bar arrives, pop taller bars and compute the rectangle each one bounds, using the stack to derive its left boundary.",
    it: "Every rectangle is capped by its shortest bar, so enumerating that bar enumerates all candidates.",
    st: ["Iterate over the bars with a sentinel zero at the end.", "While the stack top is taller than the current bar, pop it.", "Compute width from the new stack top to the current index.", "Track the maximum area."],
    tc: "O(n)", sc: "O(n)",
    solve: (input) => { const a = [...A(input), 0]; const stack: number[] = []; let best = 0; for (let i = 0; i < a.length; i += 1) { while (stack.length && a[stack[stack.length - 1]] >= a[i]) { const height = a[stack.pop()!]; const left = stack.length ? stack[stack.length - 1] : -1; best = Math.max(best, height * (i - left - 1)); } stack.push(i); } return String(best); },
    samples: ["6\n2 1 5 6 2 3", "2\n2 4"],
    why: ["Bars 5 and 6 give a rectangle of area 10.", "The taller bar alone gives 4."],
    hidden: ["1\n5", "4\n1 1 1 1", "5\n5 4 3 2 1", "5\n1 2 3 4 5"],
    edge: ["2\n0 0"],
    companies: ["amazon", "google", "microsoft"],
  },
  {
    slug: "asteroid-collision",
    title: "Asteroid Collision",
    difficulty: "MEDIUM",
    topics: ["stack"],
    d: "Asteroids move along a line; positive values move right and negative values move left, all at the same speed. When two collide the smaller by absolute value explodes, and equal sizes destroy both. Print the surviving asteroids.",
    in: "First line: n.\nSecond line: n non-zero integers.",
    out: "The survivors in order, or NONE.",
    c: "1 <= n <= 100000\n-1000 <= a[i] <= 1000, a[i] != 0",
    hints: ["Collisions only happen when a right-mover meets a left-mover.", "The most recent right-mover is the one at risk.", "A stack naturally holds the survivors so far."],
    ap: "Process asteroids left to right with a stack. A left-moving asteroid collides with the stack top while that top is right-moving and smaller.",
    it: "Only the most recently surviving right-mover can collide, which is exactly the stack top.",
    st: ["Push right-moving asteroids.", "For a left-mover, pop smaller right-movers.", "Destroy both on an exact tie.", "Push the left-mover if it survives."],
    tc: "O(n)", sc: "O(n)",
    solve: (input) => { const a = A(input); const stack: number[] = []; for (const x of a) { let alive = true; while (alive && x < 0 && stack.length && stack[stack.length - 1] > 0) { const top = stack[stack.length - 1]; if (top < -x) { stack.pop(); continue; } if (top === -x) stack.pop(); alive = false; } if (alive) stack.push(x); } return stack.length ? join(stack) : "NONE"; },
    samples: ["3\n5 10 -5", "2\n8 -8"],
    why: ["-5 is destroyed by 10.", "Equal sizes destroy each other."],
    hidden: ["1\n5", "3\n10 2 -5", "4\n-2 -1 1 2", "3\n-5 -10 5"],
    edge: ["2\n-1 1"],
  },
  {
    slug: "daily-temperatures",
    title: "Days Until a Warmer Temperature",
    difficulty: "MEDIUM",
    topics: ["stack", "arrays"],
    d: "For each day, print how many days you must wait for a strictly warmer temperature, or 0 if none comes.",
    in: "First line: n.\nSecond line: n temperatures.",
    out: "n waiting counts, space separated.",
    c: "1 <= n <= 100000",
    hints: ["This is the next-greater-element problem with distances.", "Process from the right with a stack.", "Or process left to right, resolving days as warmer temperatures arrive."],
    ap: "Monotonic decreasing stack of indices. When a warmer temperature arrives, pop every pending day it resolves and record the distance.",
    it: "Each day is pushed and popped once, so the whole scan is linear despite the inner loop.",
    st: ["Iterate left to right.", "While the stack top is cooler than today, pop it and record the distance.", "Push today's index.", "Unresolved days keep 0."],
    tc: "O(n)", sc: "O(n)",
    solve: (input) => { const a = A(input); const out = new Array(a.length).fill(0); const stack: number[] = []; for (let i = 0; i < a.length; i += 1) { while (stack.length && a[stack[stack.length - 1]] < a[i]) { const j = stack.pop()!; out[j] = i - j; } stack.push(i); } return join(out); },
    samples: ["8\n73 74 75 71 69 72 76 73", "3\n30 40 50"],
    why: ["Each entry is the wait until a warmer day.", "Each day is followed immediately by a warmer one."],
    hidden: ["1\n50", "4\n50 40 30 20", "4\n30 30 30 30", "5\n10 20 10 20 10"],
    edge: ["2\n2 1"],
    companies: ["amazon", "google"],
  },
  {
    slug: "lru-cache-simulate",
    title: "LRU Cache",
    difficulty: "MEDIUM",
    topics: ["hashing", "linked-lists"],
    d: "Simulate a least-recently-used cache of a fixed capacity. Operations are PUT key value and GET key; GET prints the value or -1 and counts as a use.",
    in: "First line: capacity and q.\nNext q lines: one operation each.",
    out: "One line per GET.",
    c: "1 <= capacity <= 100000\n1 <= q <= 100000",
    hints: ["You need O(1) lookup and O(1) reordering.", "A hash map gives the lookup.", "A doubly linked list gives the ordering."],
    ap: "Hash map from key to a node in a doubly linked list ordered by recency. Every access moves its node to the front; eviction removes the tail.",
    it: "Neither structure alone is enough: the map cannot order and the list cannot search.",
    st: ["On GET, return the value and move the node to the front.", "On PUT of an existing key, update and move to the front.", "On a new key at capacity, evict the tail.", "Insert the new node at the front."],
    tc: "O(1) per operation", sc: "O(capacity)",
    solve: (input) => { const parts = input.trim().split("\n"); const [cap, q] = parts[0].trim().split(/\s+/).map(Number); const map = new Map<string, string>(); const out: string[] = []; for (let i = 1; i <= q; i += 1) { const [op, k, v] = (parts[i] ?? "").trim().split(/\s+/); if (op === "PUT") { if (map.has(k)) map.delete(k); map.set(k, v); if (map.size > cap) map.delete(map.keys().next().value as string); } else if (op === "GET") { if (!map.has(k)) out.push("-1"); else { const value = map.get(k)!; map.delete(k); map.set(k, value); out.push(value); } } } return linesOut(out); },
    samples: ["2 5\nPUT 1 10\nPUT 2 20\nGET 1\nPUT 3 30\nGET 2", "1 3\nPUT 1 5\nGET 1\nGET 2"],
    why: ["Adding key 3 evicts key 2, the least recently used.", "Key 2 was never stored."],
    hidden: ["1 2\nPUT 1 1\nGET 1", "2 4\nPUT 1 1\nPUT 2 2\nGET 1\nGET 2", "1 3\nPUT 1 1\nPUT 2 2\nGET 1", "2 3\nGET 5\nPUT 5 5\nGET 5"],
    edge: ["1 1\nGET 1"],
    companies: ["amazon", "google", "microsoft", "meta"],
  },
  {
    slug: "linked-list-merge-two",
    title: "Merge Two Sorted Linked Lists",
    difficulty: "MEDIUM",
    topics: ["linked-lists"],
    d: "Merge two sorted linked lists into one sorted list and print its values.",
    in: "First line: n and m.\nSecond line: n sorted values.\nThird line: m sorted values.",
    out: "The merged list, space separated, or EMPTY.",
    c: "0 <= n, m <= 100000",
    hints: ["The smaller head always comes next.", "A dummy head node removes the special case for the first element.", "Splice nodes rather than copying values."],
    ap: "Two-pointer merge with a dummy head so the first append needs no special handling; nodes are relinked rather than copied.",
    it: "The dummy node is what removes every 'is this the first element?' branch.",
    st: ["Create a dummy node and a tail pointer.", "Repeatedly append the smaller head.", "Append the remainder of whichever list is left.", "Return dummy.next."],
    tc: "O(n + m)", sc: "O(1)",
    solve: (input) => { const r = reader(input); const n = r.int(), m = r.int(); const a = r.ints(n), b = r.ints(m); const out: number[] = []; let i = 0, j = 0; while (i < n && j < m) out.push(a[i] <= b[j] ? a[i++] : b[j++]); while (i < n) out.push(a[i++]); while (j < m) out.push(b[j++]); return out.length ? join(out) : "EMPTY"; },
    samples: ["3 3\n1 2 4\n1 3 4", "0 0"],
    why: ["The heads interleave into one sorted list.", "Both lists are empty."],
    hidden: ["1 0\n5", "0 1\n5", "2 3\n1 5\n2 3 4", "3 3\n1 1 1\n1 1 1"],
    edge: ["1 1\n1\n1"],
    companies: ["amazon", "microsoft", "meta"],
  },
  {
    slug: "linked-list-remove-nth",
    title: "Remove the Nth Node from the End",
    difficulty: "MEDIUM",
    topics: ["linked-lists"],
    d: "Remove the kth node counted from the end of a singly linked list and print the result.",
    in: "First line: n and k.\nSecond line: n node values.",
    out: "The resulting list, space separated, or EMPTY.",
    c: "1 <= k <= n <= 100000",
    hints: ["Counting the length first works but takes two passes.", "Two pointers separated by k nodes reach the end together.", "A dummy head handles removal of the first node cleanly."],
    ap: "Advance a lead pointer k nodes ahead, then move both until the lead reaches the end; the trailing pointer is then just before the target.",
    it: "A fixed gap between two pointers converts 'kth from the end' into 'current position'.",
    st: ["Create a dummy node before the head.", "Advance the fast pointer k steps.", "Move both until fast reaches the end.", "Unlink the node after slow."],
    tc: "O(n)", sc: "O(1)",
    solve: (input) => { const r = reader(input); const n = r.int(), k = r.int(); const a = r.ints(n); const out = a.filter((_, i) => i !== n - k); return out.length ? join(out) : "EMPTY"; },
    samples: ["5 2\n1 2 3 4 5", "1 1\n7"],
    why: ["The second node from the end is 4.", "Removing the only node leaves an empty list."],
    hidden: ["3 3\n1 2 3", "3 1\n1 2 3", "4 2\n1 2 3 4", "2 1\n1 2"],
    edge: ["2 2\n1 2"],
    companies: ["amazon", "meta"],
  },
  {
    slug: "linked-list-add-numbers",
    title: "Add Two Numbers as Linked Lists",
    difficulty: "MEDIUM",
    topics: ["linked-lists", "math"],
    d: "Two numbers are stored as linked lists of digits in reverse order. Print the digits of their sum, also in reverse order.",
    in: "First line: n and m.\nSecond line: n digits.\nThird line: m digits.",
    out: "The sum's digits in reverse order, space separated.",
    c: "1 <= n, m <= 100000\nEach digit is 0 to 9.",
    hints: ["Reverse order means the least significant digit comes first.", "That is exactly the order you add in.", "Carry the overflow to the next position."],
    ap: "Walk both lists together adding digit pairs with a carry, continuing while either list or the carry remains.",
    it: "Storing digits in reverse order is what makes a single forward pass possible.",
    st: ["Set carry = 0.", "While either list has digits or carry is non-zero, add the available digits and the carry.", "Emit the units digit and keep the tens as the new carry."],
    tc: "O(max(n, m))", sc: "O(max(n, m))",
    solve: (input) => { const r = reader(input); const n = r.int(), m = r.int(); const a = r.ints(n), b = r.ints(m); const out: number[] = []; let carry = 0; for (let i = 0; i < Math.max(n, m) || carry; i += 1) { const sum = (a[i] ?? 0) + (b[i] ?? 0) + carry; out.push(sum % 10); carry = Math.floor(sum / 10); } return join(out); },
    samples: ["3 3\n2 4 3\n5 6 4", "1 1\n5\n5"],
    why: ["342 + 465 = 807, stored in reverse.", "5 + 5 = 10, so the digits are 0 then 1."],
    hidden: ["1 1\n0\n0", "1 3\n9\n9 9 9", "2 2\n1 8\n0 0", "3 1\n9 9 9\n1"],
    edge: ["1 1\n9\n9"],
    companies: ["amazon", "microsoft", "adobe"],
  },
  {
    slug: "linked-list-palindrome",
    title: "Palindrome Linked List",
    difficulty: "MEDIUM",
    topics: ["linked-lists"],
    d: "Decide whether a singly linked list reads the same forwards and backwards.",
    in: "First line: n.\nSecond line: n node values.",
    out: "YES if the list is a palindrome, otherwise NO.",
    c: "1 <= n <= 100000",
    hints: ["Copying to an array works but uses O(n) memory.", "Find the middle with slow and fast pointers.", "Reverse the second half and compare it with the first."],
    ap: "Find the middle with slow and fast pointers, reverse the second half in place, compare the halves, and optionally restore the list.",
    it: "Reversing half the list gives random-access-like comparison without any extra allocation.",
    st: ["Find the middle node.", "Reverse the list from there.", "Walk both halves comparing values.", "Report equality."],
    tc: "O(n)", sc: "O(1)",
    solve: (input) => { const r = reader(input); const n = r.int(); const a = r.ints(n); return yesNo(a.join(",") === [...a].reverse().join(",")); },
    samples: ["4\n1 2 2 1", "3\n1 2 3"],
    why: ["The list mirrors itself.", "1 and 3 differ."],
    hidden: ["1\n5", "2\n1 1", "5\n1 2 3 2 1", "2\n1 2"],
    edge: ["3\n1 1 1"],
    companies: ["amazon", "meta"],
  },
  {
    slug: "linked-list-reorder",
    title: "Reorder a Linked List",
    difficulty: "MEDIUM",
    topics: ["linked-lists"],
    d: "Reorder a list from L0, L1, ..., Ln-1 into L0, Ln-1, L1, Ln-2, ... and print the result.",
    in: "First line: n.\nSecond line: n node values.",
    out: "The reordered list, space separated.",
    c: "1 <= n <= 100000",
    hints: ["You need access to the tail repeatedly.", "Split the list in half.", "Reverse the second half and interleave."],
    ap: "Split at the middle, reverse the second half, then interleave the two halves node by node.",
    it: "Reversing the tail converts repeated back-to-front access into a simple forward walk.",
    st: ["Find the middle with slow and fast pointers.", "Reverse the second half.", "Interleave the two halves.", "Terminate the list."],
    tc: "O(n)", sc: "O(1)",
    solve: (input) => { const r = reader(input); const n = r.int(); const a = r.ints(n); const out: number[] = []; let i = 0, j = n - 1; while (i <= j) { out.push(a[i++]); if (i <= j) out.push(a[j--]); } return join(out); },
    samples: ["4\n1 2 3 4", "5\n1 2 3 4 5"],
    why: ["1, 4, 2, 3.", "1, 5, 2, 4, 3."],
    hidden: ["1\n1", "2\n1 2", "3\n1 2 3", "6\n1 2 3 4 5 6"],
    edge: ["2\n2 1"],
  },
  {
    slug: "linked-list-rotate",
    title: "Rotate a Linked List",
    difficulty: "MEDIUM",
    topics: ["linked-lists"],
    d: "Rotate a linked list to the right by k places and print the result.",
    in: "First line: n and k.\nSecond line: n node values.",
    out: "The rotated list, space separated.",
    c: "1 <= n <= 100000\n0 <= k <= 10^9",
    hints: ["Rotating by n is a no-op, so reduce k first.", "Connect the tail to the head to form a ring.", "Then break the ring at the right place."],
    ap: "Close the list into a ring, walk to the new tail at position n - k mod n, and break the ring there.",
    it: "Turning the list into a ring makes rotation a single cut rather than a sequence of moves.",
    st: ["Compute the length and connect the tail to the head.", "Reduce k modulo n.", "Walk n - k steps from the head.", "Break the ring after that node."],
    tc: "O(n)", sc: "O(1)",
    solve: (input) => { const r = reader(input); const n = r.int(); const k = r.int() % n; const a = r.ints(n); return join([...a.slice(n - k), ...a.slice(0, n - k)]); },
    samples: ["5 2\n1 2 3 4 5", "3 0\n1 2 3"],
    why: ["The last two nodes move to the front.", "A rotation of zero changes nothing."],
    hidden: ["1 5\n1", "4 4\n1 2 3 4", "3 1000000000\n1 2 3", "2 1\n1 2"],
    edge: ["2 2\n1 2"],
  },
  {
    slug: "clone-graph-count",
    title: "Clone a Graph",
    difficulty: "MEDIUM",
    topics: ["graphs", "hashing"],
    d: "Given an undirected graph, produce a deep copy and print the sorted adjacency list of the copy, one vertex per line.",
    in: "First line: n and m.\nNext m lines: an edge u v.",
    out: "n lines, each listing a vertex's sorted neighbours, or the word NONE for an isolated vertex.",
    c: "1 <= n <= 100000\n0 <= m <= 200000",
    hints: ["Cycles mean a naive recursive copy never terminates.", "Remember which originals you have already cloned.", "A map from original to clone breaks the recursion."],
    ap: "Traverse the graph while maintaining a map from original vertex to its clone, so each vertex is copied exactly once even in the presence of cycles.",
    it: "The visited map is what turns an infinite recursion into a linear traversal.",
    st: ["Start a traversal from each unvisited vertex.", "Create a clone the first time a vertex is seen.", "Link clones as edges are traversed.", "Print each clone's sorted neighbours."],
    tc: "O(n + m)", sc: "O(n + m)",
    solve: (input) => { const r = reader(input); const n = r.int(), m = r.int(); const adj: number[][] = Array.from({ length: n }, () => []); for (let i = 0; i < m; i += 1) { const u = r.int(), v = r.int(); adj[u].push(v); adj[v].push(u); } return linesOut(adj.map((list) => { const sorted = [...new Set(list)].sort((x, y) => x - y); return sorted.length ? join(sorted) : "NONE"; })); },
    samples: ["4 4\n0 1\n1 2\n2 3\n3 0", "2 0"],
    why: ["Each vertex has two neighbours in the cycle.", "Both vertices are isolated."],
    hidden: ["1 0", "3 2\n0 1\n1 2", "3 3\n0 1\n1 2\n0 2", "2 1\n0 1"],
    edge: ["1 1\n0 0"],
    companies: ["meta", "amazon", "google"],
  },
  {
    slug: "flood-fill-image",
    title: "Flood Fill",
    difficulty: "MEDIUM",
    topics: ["graphs", "matrix"],
    d: "Starting from a cell, replace its colour and the colour of every connected cell of the same original colour with a new colour. Print the resulting grid.",
    in: "First line: n, m, sr, sc and newColor.\nNext n lines: m integers each.",
    out: "The grid after filling, one row per line.",
    c: "1 <= n, m <= 500\n0 <= colours <= 65535",
    hints: ["This is connected-component traversal with a recolour.", "Stop immediately when the new colour equals the old one.", "Otherwise you will loop forever."],
    ap: "Depth-first or breadth-first flood fill from the start cell, recolouring cells that still hold the original colour.",
    it: "The equal-colour early exit is essential, because recolouring to the same value never marks progress.",
    st: ["Read the original colour of the start cell.", "Return immediately if it already equals the new colour.", "Traverse the connected region of that colour.", "Recolour every visited cell."],
    tc: "O(nm)", sc: "O(nm)",
    solve: (input) => { const r = reader(input); const n = r.int(), m = r.int(), sr = r.int(), sc = r.int(), nc = r.int(); const g: number[][] = []; for (let i = 0; i < n; i += 1) g.push(r.ints(m)); const start = g[sr][sc]; if (start !== nc) { const stack: Array<[number, number]> = [[sr, sc]]; g[sr][sc] = nc; const dirs = [[1, 0], [-1, 0], [0, 1], [0, -1]]; while (stack.length) { const [x, y] = stack.pop()!; for (const [dx, dy] of dirs) { const nx = x + dx, ny = y + dy; if (nx >= 0 && ny >= 0 && nx < n && ny < m && g[nx][ny] === start) { g[nx][ny] = nc; stack.push([nx, ny]); } } } } return linesOut(g.map((row) => join(row))); },
    samples: ["3 3 1 1 2\n1 1 1\n1 1 0\n1 0 1", "1 1 0 0 5\n5"],
    why: ["The connected block of 1s becomes 2.", "The colour is already 5, so nothing changes."],
    hidden: ["2 2 0 0 3\n1 1\n1 1", "1 2 0 0 9\n1 2", "3 3 0 0 0\n0 0 0\n0 0 0\n0 0 0", "2 3 1 1 7\n1 1 1\n1 1 1"],
    edge: ["1 1 0 0 1\n1"],
  },
  {
    slug: "surrounded-regions",
    title: "Surrounded Regions",
    difficulty: "MEDIUM",
    topics: ["graphs", "matrix"],
    d: "In a grid of 0s and 1s, replace every region of 1s that does not touch the border with 0s. Print the resulting grid.",
    in: "First line: n and m.\nNext n lines: m values, each 0 or 1.",
    out: "The modified grid, one row per line.",
    c: "1 <= n, m <= 500",
    hints: ["Finding enclosed regions directly is fiddly.", "It is easier to find the regions that are not enclosed.", "Start from the border and mark everything reachable."],
    ap: "Flood-fill inward from every border 1 to mark the surviving regions, then flip every unmarked 1 to 0.",
    it: "Inverting the question — mark what survives rather than what is captured — removes all the boundary special cases.",
    st: ["Traverse from every border cell holding a 1.", "Mark the whole reachable region as safe.", "Set every unmarked 1 to 0.", "Restore the safe marks to 1."],
    tc: "O(nm)", sc: "O(nm)",
    solve: (input) => { const r = reader(input); const n = r.int(), m = r.int(); const g: number[][] = []; for (let i = 0; i < n; i += 1) g.push(r.ints(m)); const safe = Array.from({ length: n }, () => new Array(m).fill(false)); const dirs = [[1, 0], [-1, 0], [0, 1], [0, -1]]; const stack: Array<[number, number]> = []; for (let i = 0; i < n; i += 1) for (let j = 0; j < m; j += 1) if ((i === 0 || j === 0 || i === n - 1 || j === m - 1) && g[i][j] === 1 && !safe[i][j]) { safe[i][j] = true; stack.push([i, j]); } while (stack.length) { const [x, y] = stack.pop()!; for (const [dx, dy] of dirs) { const nx = x + dx, ny = y + dy; if (nx >= 0 && ny >= 0 && nx < n && ny < m && g[nx][ny] === 1 && !safe[nx][ny]) { safe[nx][ny] = true; stack.push([nx, ny]); } } } return linesOut(g.map((row, i) => join(row.map((v, j) => (v === 1 && !safe[i][j] ? 0 : v))))); },
    samples: ["4 4\n0 0 0 0\n0 1 1 0\n0 1 0 0\n0 0 0 1", "1 1\n1"],
    why: ["The inner block is enclosed and is cleared; the corner 1 touches the border.", "A single cell always touches the border."],
    hidden: ["3 3\n1 1 1\n1 1 1\n1 1 1", "3 3\n0 0 0\n0 1 0\n0 0 0", "2 2\n1 0\n0 1", "3 4\n0 0 0 0\n0 1 1 0\n0 0 0 0"],
    edge: ["1 2\n1 1"],
  },
  {
    slug: "number-of-provinces",
    title: "Number of Provinces",
    difficulty: "MEDIUM",
    topics: ["graphs"],
    d: "Given an adjacency matrix of a friendship graph, count the connected groups.",
    in: "First line: n.\nNext n lines: n values, each 0 or 1.",
    out: "The number of provinces.",
    c: "1 <= n <= 500",
    hints: ["The matrix is just another encoding of a graph.", "Each traversal covers one province.", "Union-find works well here too."],
    ap: "Union-find over the matrix entries, or a traversal from each unvisited vertex, counting the components.",
    it: "The adjacency-matrix encoding does not change the underlying connected-components problem.",
    st: ["Initialise a disjoint-set over n vertices.", "Union every pair with a 1 in the matrix.", "Count the distinct roots."],
    tc: "O(n^2)", sc: "O(n)",
    solve: (input) => { const r = reader(input); const n = r.int(); const parent = Array.from({ length: n }, (_, i) => i); const find = (x: number): number => (parent[x] === x ? x : (parent[x] = find(parent[x]))); for (let i = 0; i < n; i += 1) { const row = r.ints(n); for (let j = 0; j < n; j += 1) if (row[j] === 1) { const a = find(i), b = find(j); if (a !== b) parent[a] = b; } } let count = 0; for (let i = 0; i < n; i += 1) if (find(i) === i) count += 1; return String(count); },
    samples: ["3\n1 1 0\n1 1 0\n0 0 1", "3\n1 0 0\n0 1 0\n0 0 1"],
    why: ["Vertices 0 and 1 form one province, vertex 2 another.", "Every vertex is isolated."],
    hidden: ["1\n1", "2\n1 1\n1 1", "4\n1 1 0 0\n1 1 0 0\n0 0 1 1\n0 0 1 1", "2\n1 0\n0 1"],
    edge: ["1\n1"],
    companies: ["amazon", "microsoft"],
  },
  {
    slug: "min-spanning-tree-weight",
    title: "Minimum Spanning Tree Weight",
    difficulty: "MEDIUM",
    topics: ["graphs", "greedy"],
    d: "Find the total weight of a minimum spanning tree of a connected weighted undirected graph. Print IMPOSSIBLE if the graph is disconnected.",
    in: "First line: n and m.\nNext m lines: u, v and w.",
    out: "The MST weight, or IMPOSSIBLE.",
    c: "1 <= n <= 100000\n0 <= m <= 200000\n1 <= w <= 10^9",
    hints: ["Sort the edges by weight.", "Add an edge only when it joins two different components.", "A disjoint-set structure answers that question quickly."],
    ap: "Kruskal's algorithm: sort edges by weight and add each one that connects two distinct components, tracked with union-find.",
    it: "The cut property guarantees the lightest edge crossing any cut belongs to some MST, which is what makes the greedy safe.",
    st: ["Sort edges ascending by weight.", "Initialise a disjoint-set over the vertices.", "Add an edge when its endpoints have different roots.", "Report the total, or IMPOSSIBLE if fewer than n-1 edges were added."],
    tc: "O(m log m)", sc: "O(n + m)",
    solve: (input) => { const r = reader(input); const n = r.int(), m = r.int(); const edges: Array<[number, number, number]> = []; for (let i = 0; i < m; i += 1) edges.push([r.int(), r.int(), r.int()]); edges.sort((a, b) => a[2] - b[2]); const parent = Array.from({ length: n }, (_, i) => i); const find = (x: number): number => (parent[x] === x ? x : (parent[x] = find(parent[x]))); let total = 0, used = 0; for (const [u, v, w] of edges) { const a = find(u), b = find(v); if (a === b) continue; parent[a] = b; total += w; used += 1; } return used === n - 1 ? String(total) : "IMPOSSIBLE"; },
    samples: ["4 5\n0 1 1\n1 2 2\n2 3 3\n0 3 4\n0 2 5", "3 1\n0 1 1"],
    why: ["The three cheapest connecting edges total 6.", "Vertex 2 cannot be reached."],
    hidden: ["1 0", "2 1\n0 1 7", "3 3\n0 1 1\n1 2 1\n0 2 1", "4 3\n0 1 1\n1 2 1\n2 3 1"],
    edge: ["2 0"],
    companies: ["amazon", "google"],
  },
  {
    slug: "gas-station-circuit",
    title: "Gas Station Circuit",
    difficulty: "MEDIUM",
    topics: ["greedy", "arrays"],
    d: "Stations are arranged in a circle. At station i you gain gas[i] and spend cost[i] to reach the next one. Find the starting index that allows a full circuit, or -1 if none does.",
    in: "First line: n.\nSecond line: n gas values.\nThird line: n cost values.",
    out: "The starting index, or -1.",
    c: "1 <= n <= 100000\n0 <= gas, cost <= 10^9",
    hints: ["If the total gas is less than the total cost, no start works.", "If a prefix from a start goes negative, no station in that prefix can work.", "So restart from the station after the failure."],
    ap: "One pass tracking the running tank; when it goes negative, restart from the next station. Feasibility is decided by the total balance.",
    it: "A failing prefix rules out every start inside it, which is what collapses the O(n^2) search into one pass.",
    st: ["Track total and running balances.", "When the running balance goes negative, set the start to the next index and reset it.", "Answer the recorded start when the total is non-negative.", "Otherwise answer -1."],
    tc: "O(n)", sc: "O(1)",
    solve: (input) => { const r = reader(input); const n = r.int(); const gas = r.ints(n), cost = r.ints(n); let total = 0, tank = 0, start = 0; for (let i = 0; i < n; i += 1) { const diff = gas[i] - cost[i]; total += diff; tank += diff; if (tank < 0) { start = i + 1; tank = 0; } } return total >= 0 ? String(start) : "-1"; },
    samples: ["5\n1 2 3 4 5\n3 4 5 1 2", "3\n2 3 4\n3 4 3"],
    why: ["Starting at index 3 completes the circuit.", "The total cost exceeds the total gas."],
    hidden: ["1\n5\n4", "1\n1\n2", "3\n1 1 1\n1 1 1", "4\n5 1 2 3\n4 4 1 5"],
    edge: ["2\n1 2\n2 1"],
    companies: ["amazon", "google"],
  },
  {
    slug: "jump-game-reachable",
    title: "Jump Game",
    difficulty: "MEDIUM",
    topics: ["greedy", "arrays"],
    d: "From index i you may jump forward up to a[i] positions. Decide whether the last index is reachable from index 0.",
    in: "First line: n.\nSecond line: n non-negative integers.",
    out: "YES if the end is reachable, otherwise NO.",
    c: "1 <= n <= 100000\n0 <= a[i] <= 100000",
    hints: ["You only need reachability, not the number of jumps.", "Track the farthest index reachable so far.", "If the current index passes that limit, you are stuck."],
    ap: "Single pass maintaining the farthest reachable index; failure is exactly the moment the current index exceeds it.",
    it: "Reachability is prefix-closed, so one running maximum decides it.",
    st: ["Set reach = 0.", "For each index i, fail if i exceeds reach.", "Otherwise update reach with i + a[i].", "Succeed when reach covers the last index."],
    tc: "O(n)", sc: "O(1)",
    solve: (input) => { const a = A(input); let reach = 0; for (let i = 0; i < a.length; i += 1) { if (i > reach) return "NO"; reach = Math.max(reach, i + a[i]); } return "YES"; },
    samples: ["5\n2 3 1 1 4", "5\n3 2 1 0 4"],
    why: ["The end is reachable in two jumps.", "Index 3 has jump length zero and blocks the path."],
    hidden: ["1\n0", "2\n1 0", "2\n0 1", "6\n5 0 0 0 0 0"],
    edge: ["1\n5"],
    companies: ["amazon", "meta"],
  },
  {
    slug: "candy-distribution",
    title: "Candy Distribution",
    difficulty: "MEDIUM",
    topics: ["greedy", "arrays"],
    d: "Children stand in a line with ratings. Each child gets at least one candy, and a child with a higher rating than an immediate neighbour must get more candies than that neighbour. Find the minimum total.",
    in: "First line: n.\nSecond line: n ratings.",
    out: "The minimum total number of candies.",
    c: "1 <= n <= 100000\n0 <= rating <= 10^9",
    hints: ["Two constraints pull in opposite directions.", "Handle the left-to-right constraint in one pass.", "Handle the right-to-left one in a second pass and take the maximum."],
    ap: "Two sweeps: left to right enforcing the left-neighbour rule, right to left enforcing the right-neighbour rule, taking the maximum requirement per child.",
    it: "Each pass satisfies one direction, and the maximum satisfies both without overshooting.",
    st: ["Give everyone one candy.", "Sweep left to right increasing where the rating rises.", "Sweep right to left doing the same.", "Sum the per-child maxima."],
    tc: "O(n)", sc: "O(n)",
    solve: (input) => { const a = A(input); const n = a.length; const candy = new Array(n).fill(1); for (let i = 1; i < n; i += 1) if (a[i] > a[i - 1]) candy[i] = candy[i - 1] + 1; for (let i = n - 2; i >= 0; i -= 1) if (a[i] > a[i + 1]) candy[i] = Math.max(candy[i], candy[i + 1] + 1); return String(candy.reduce((s, v) => s + v, 0)); },
    samples: ["3\n1 0 2", "3\n1 2 2"],
    why: ["2, 1, 2 candies satisfy both rules.", "1, 2, 1 is enough."],
    hidden: ["1\n5", "4\n1 2 3 4", "4\n4 3 2 1", "5\n1 3 2 2 1"],
    edge: ["2\n1 1"],
    companies: ["google", "amazon"],
  },
];

export const MEDIUM_B = specs.map(build);
